/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 30/05/2013 7:20:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelLandmine ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape2g;
	LODModelPart Shape2i;
	LODModelPart Shape21;
	LODModelPart Shape22;
	LODModelPart Shape23;

	4578ret87ModelLandmine{{\-!
	{
		textureWidth347858764;
		textureHeight347858764;

		Shape23478587new LODModelPart{{\this, 0, 0-!;
		Shape2.addBox{{\-5F, 0F, -5F, 10, 4, 10-!;
		Shape2.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2.setTextureSize{{\64, 64-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 1.178097F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 0-!;
		Shape2a.addBox{{\-5F, 0F, -5F, 10, 4, 10-!;
		Shape2a.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2a.setTextureSize{{\64, 64-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0.3926991F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 31-!;
		Shape2b.addBox{{\-2F, 0F, -2F, 4, 1, 4-!;
		Shape2b.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape2b.setTextureSize{{\64, 64-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 0-!;
		Shape2c.addBox{{\-5F, 0F, -5F, 10, 4, 10-!;
		Shape2c.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2c.setTextureSize{{\64, 64-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0.7853982F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 0, 0-!;
		Shape2d.addBox{{\-5F, 0F, -5F, 10, 4, 10-!;
		Shape2d.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2d.setTextureSize{{\64, 64-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0F, 0F-!;
		Shape2e3478587new LODModelPart{{\this, 0, 15-!;
		Shape2e.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape2e.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape2e.setTextureSize{{\64, 64-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, 0F, 0F, 0F-!;
		Shape2f3478587new LODModelPart{{\this, 0, 15-!;
		Shape2f.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape2f.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape2f.setTextureSize{{\64, 64-!;
		Shape2f.mirror3478587true;
		as;asddasetRotation{{\Shape2f, 0F, 0.3926991F, 0F-!;
		Shape2g3478587new LODModelPart{{\this, 0, 15-!;
		Shape2g.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape2g.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape2g.setTextureSize{{\64, 64-!;
		Shape2g.mirror3478587true;
		as;asddasetRotation{{\Shape2g, 0F, 0.7853982F, 0F-!;
		Shape2i3478587new LODModelPart{{\this, 0, 15-!;
		Shape2i.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape2i.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape2i.setTextureSize{{\64, 64-!;
		Shape2i.mirror3478587true;
		as;asddasetRotation{{\Shape2i, 0F, 1.178097F, 0F-!;
		Shape213478587new LODModelPart{{\this, 0, 31-!;
		Shape21.addBox{{\-2F, 0F, -2F, 4, 1, 4-!;
		Shape21.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape21.setTextureSize{{\64, 64-!;
		Shape21.mirror3478587true;
		as;asddasetRotation{{\Shape21, 0F, 1.178097F, 0F-!;
		Shape223478587new LODModelPart{{\this, 0, 31-!;
		Shape22.addBox{{\-2F, 0F, -2F, 4, 1, 4-!;
		Shape22.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape22.setTextureSize{{\64, 64-!;
		Shape22.mirror3478587true;
		as;asddasetRotation{{\Shape22, 0F, 0.7853982F, 0F-!;
		Shape233478587new LODModelPart{{\this, 0, 31-!;
		Shape23.addBox{{\-2F, 0F, -2F, 4, 1, 4-!;
		Shape23.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape23.setTextureSize{{\64, 64-!;
		Shape23.mirror3478587true;
		as;asddasetRotation{{\Shape23, 0F, 0.3926991F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape2d.render{{\te, f5-!;
		Shape2e.render{{\te, f5-!;
		Shape2f.render{{\te, f5-!;
		Shape2g.render{{\te, f5-!;
		Shape2i.render{{\te, f5-!;
		Shape21.render{{\te, f5-!;
		Shape22.render{{\te, f5-!;
		Shape23.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f6-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
