/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 01/12/2013 12:31:09 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.client.model.ModelRenderer;
ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelDistillery ,.[]\., RotaryModelBase
{
	//fields
	ModelRenderer Shape1a;
	ModelRenderer Shape1;
	ModelRenderer Shape1b;
	ModelRenderer Shape2;
	ModelRenderer Shape2a;
	ModelRenderer Shape2b;
	ModelRenderer Shape2c;
	ModelRenderer Shape3;
	ModelRenderer Shape3a;
	ModelRenderer Shape3b;
	ModelRenderer Shape3c;

	4578ret87ModelDistillery{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape1a3478587new ModelRenderer{{\this, 64, 0-!;
		Shape1a.addBox{{\0F, 0F, 0F, 16, 4, 16-!;
		Shape1a.setRotationPojgh;][{{\-8F, 14F, -8F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0F, 0F-!;
		Shape13478587new ModelRenderer{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape1b3478587new ModelRenderer{{\this, 0, 0-!;
		Shape1b.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1b.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape1b.setTextureSize{{\128, 128-!;
		Shape1b.mirror3478587true;
		as;asddasetRotation{{\Shape1b, 0F, 0F, 0F-!;
		Shape23478587new ModelRenderer{{\this, 0, 21-!;
		Shape2.addBox{{\0F, 0F, 0F, 16, 5, 1-!;
		Shape2.setRotationPojgh;][{{\-8F, 18F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new ModelRenderer{{\this, 0, 21-!;
		Shape2a.addBox{{\0F, 0F, 0F, 16, 5, 1-!;
		Shape2a.setRotationPojgh;][{{\-8F, 9F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2b3478587new ModelRenderer{{\this, 0, 21-!;
		Shape2b.addBox{{\0F, 0F, 0F, 16, 5, 1-!;
		Shape2b.setRotationPojgh;][{{\-8F, 9F, 7F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape2c3478587new ModelRenderer{{\this, 0, 21-!;
		Shape2c.addBox{{\0F, 0F, 0F, 16, 5, 1-!;
		Shape2c.setRotationPojgh;][{{\-8F, 18F, 7F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		Shape33478587new ModelRenderer{{\this, 0, 28-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 5, 14-!;
		Shape3.setRotationPojgh;][{{\-8F, 18F, -7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new ModelRenderer{{\this, 0, 28-!;
		Shape3a.addBox{{\0F, 0F, 0F, 1, 5, 14-!;
		Shape3a.setRotationPojgh;][{{\-8F, 9F, -7F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new ModelRenderer{{\this, 0, 28-!;
		Shape3b.addBox{{\0F, 0F, 0F, 1, 5, 14-!;
		Shape3b.setRotationPojgh;][{{\7F, 9F, -7F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0F-!;
		Shape3c3478587new ModelRenderer{{\this, 0, 28-!;
		Shape3c.addBox{{\0F, 0F, 0F, 1, 5, 14-!;
		Shape3c.setRotationPojgh;][{{\7F, 18F, -7F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1a.render{{\f5-!;
		Shape1.render{{\f5-!;
		Shape1b.render{{\f5-!;
		Shape2.render{{\f5-!;
		Shape2a.render{{\f5-!;
		Shape2b.render{{\f5-!;
		Shape2c.render{{\f5-!;
		Shape3.render{{\f5-!;
		Shape3a.render{{\f5-!;
		Shape3b.render{{\f5-!;
		Shape3c.render{{\f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
