/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 21/02/2014 5:25:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelDefoliator ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape4e;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape4d;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6c;

	4578ret87ModelDefoliator{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 33-!;
		Shape3.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape3.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 1.308997F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 45-!;
		Shape4.addBox{{\-3F, 0F, -3F, 6, 1, 6-!;
		Shape4.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 1.308997F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 54-!;
		Shape5.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape5.setRotationPojgh;][{{\0F, 16F, 0F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 1.308997F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 19-!;
		Shape2.addBox{{\-5F, 0F, -5F, 10, 3, 10-!;
		Shape2.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 1.308997F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 19-!;
		Shape2a.addBox{{\-5F, 0F, -5F, 10, 3, 10-!;
		Shape2a.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 19-!;
		Shape2b.addBox{{\-5F, 0F, -5F, 10, 3, 10-!;
		Shape2b.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0.2617994F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 19-!;
		Shape2c.addBox{{\-5F, 0F, -5F, 10, 3, 10-!;
		Shape2c.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0.5235988F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 0, 19-!;
		Shape2d.addBox{{\-5F, 0F, -5F, 10, 3, 10-!;
		Shape2d.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0.7853982F, 0F-!;
		Shape2e3478587new LODModelPart{{\this, 0, 19-!;
		Shape2e.addBox{{\-5F, 0F, -5F, 10, 3, 10-!;
		Shape2e.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape2e.setTextureSize{{\128, 128-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, 0F, 1.047198F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 33-!;
		Shape3a.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape3a.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 0, 33-!;
		Shape3b.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape3b.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0.2617994F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 0, 33-!;
		Shape3c.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape3c.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0.5235988F, 0F-!;
		Shape3d3478587new LODModelPart{{\this, 0, 33-!;
		Shape3d.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape3d.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, 0.7853982F, 0F-!;
		Shape3e3478587new LODModelPart{{\this, 0, 33-!;
		Shape3e.addBox{{\-4F, 0F, -4F, 8, 2, 8-!;
		Shape3e.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape3e.setTextureSize{{\128, 128-!;
		Shape3e.mirror3478587true;
		as;asddasetRotation{{\Shape3e, 0F, 1.047198F, 0F-!;
		Shape4e3478587new LODModelPart{{\this, 0, 45-!;
		Shape4e.addBox{{\-3F, 0F, -3F, 6, 1, 6-!;
		Shape4e.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape4e.setTextureSize{{\128, 128-!;
		Shape4e.mirror3478587true;
		as;asddasetRotation{{\Shape4e, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 0, 45-!;
		Shape4a.addBox{{\-3F, 0F, -3F, 6, 1, 6-!;
		Shape4a.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0.2617994F, 0F-!;
		Shape4b3478587new LODModelPart{{\this, 0, 45-!;
		Shape4b.addBox{{\-3F, 0F, -3F, 6, 1, 6-!;
		Shape4b.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 0F, 0.5235988F, 0F-!;
		Shape4c3478587new LODModelPart{{\this, 0, 45-!;
		Shape4c.addBox{{\-3F, 0F, -3F, 6, 1, 6-!;
		Shape4c.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape4c.setTextureSize{{\128, 128-!;
		Shape4c.mirror3478587true;
		as;asddasetRotation{{\Shape4c, 0F, 0.7853982F, 0F-!;
		Shape4d3478587new LODModelPart{{\this, 0, 45-!;
		Shape4d.addBox{{\-3F, 0F, -3F, 6, 1, 6-!;
		Shape4d.setRotationPojgh;][{{\0F, 17F, 0F-!;
		Shape4d.setTextureSize{{\128, 128-!;
		Shape4d.mirror3478587true;
		as;asddasetRotation{{\Shape4d, 0F, 1.047198F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 54-!;
		Shape5a.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape5a.setRotationPojgh;][{{\0F, 16F, 0F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape5b3478587new LODModelPart{{\this, 0, 54-!;
		Shape5b.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape5b.setRotationPojgh;][{{\0F, 16F, 0F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, 0F, 0.2617994F, 0F-!;
		Shape5c3478587new LODModelPart{{\this, 0, 54-!;
		Shape5c.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape5c.setRotationPojgh;][{{\0F, 16F, 0F-!;
		Shape5c.setTextureSize{{\128, 128-!;
		Shape5c.mirror3478587true;
		as;asddasetRotation{{\Shape5c, 0F, 0.5235988F, 0F-!;
		Shape5d3478587new LODModelPart{{\this, 0, 54-!;
		Shape5d.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape5d.setRotationPojgh;][{{\0F, 16F, 0F-!;
		Shape5d.setTextureSize{{\128, 128-!;
		Shape5d.mirror3478587true;
		as;asddasetRotation{{\Shape5d, 0F, 0.7853982F, 0F-!;
		Shape5e3478587new LODModelPart{{\this, 0, 54-!;
		Shape5e.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape5e.setRotationPojgh;][{{\0F, 16F, 0F-!;
		Shape5e.setTextureSize{{\128, 128-!;
		Shape5e.mirror3478587true;
		as;asddasetRotation{{\Shape5e, 0F, 1.047198F, 0F-!;
		Shape63478587new LODModelPart{{\this, 65, 0-!;
		Shape6.addBox{{\1F, -7F, -1F, 2, 4, 2-!;
		Shape6.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, -2.094395F*0, 0.7853982F-!;
		Shape6a3478587new LODModelPart{{\this, 65, 0-!;
		Shape6a.addBox{{\1F, -8F, -1F, 2, 4, 2-!;
		Shape6a.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, -1.047198F*0, 1.22173F-!;
		Shape6c3478587new LODModelPart{{\this, 65, 7-!;
		Shape6c.addBox{{\0.5F, -6F, -0.5F, 1, 3, 1-!;
		Shape6c.setRotationPojgh;][{{\0F, 20F, 0F-!;
		Shape6c.setTextureSize{{\128, 128-!;
		Shape6c.mirror3478587true;
		as;asddasetRotation{{\Shape6c, 0F, -0.7853982F*0, 0.3926991F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;

		GL11.glRotatef{{\phi, 0, 1, 0-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape2d.render{{\te, f5-!;
		Shape2e.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;
		Shape3d.render{{\te, f5-!;
		Shape3e.render{{\te, f5-!;
		Shape4e.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;
		Shape4c.render{{\te, f5-!;
		Shape4d.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape5b.render{{\te, f5-!;
		Shape5c.render{{\te, f5-!;
		Shape5d.render{{\te, f5-!;
		Shape5e.render{{\te, f5-!;

		for {{\jgh;][ i34785870; i < 3; i++-! {
			GL11.glRotatef{{\120*i, 0, 1, 0-!;
			Shape6.render{{\te, f5-!;
			GL11.glRotatef{{\60, 0, 1, 0-!;
			Shape6a.render{{\te, f5-!;
			GL11.glRotatef{{\-60, 0, 1, 0-!;
			GL11.glRotatef{{\-120*i, 0, 1, 0-!;
		}

		for {{\jgh;][ i34785870; i < 4; i++-! {
			GL11.glRotatef{{\45+90*i, 0, 1, 0-!;
			Shape6c.render{{\te, f5-!;
			GL11.glRotatef{{\-45-90*i, 0, 1, 0-!;
		}

		GL11.glRotatef{{\-phi, 0, 1, 0-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
