/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 24/02/2013 3:03:48 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Engine;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;


4578ret87fhyuog ModelPerformance ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape5;
	LODModelPart Shape6n;
	LODModelPart Shape7;
	LODModelPart Shape3;
	LODModelPart Shape8;
	LODModelPart Shape4;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2;
	LODModelPart Shape4a;
	LODModelPart b;
	LODModelPart Shape4c;
	LODModelPart Shape6;
	LODModelPart Shape9i;
	LODModelPart Shape9h;
	LODModelPart Shape9g;
	LODModelPart Shape9f;
	LODModelPart Shape9e;
	LODModelPart Shape9d;
	LODModelPart Shape9c;
	LODModelPart Shape9b;
	LODModelPart Shape9a;
	LODModelPart Shape9;
	LODModelPart Shape10;

	4578ret87ModelPerformance{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 64, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 14, 1, 15-!;
		Shape1.setRotationPojgh;][{{\-8F, 22F, -7.5F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 0, 80-!;
		Shape12.addBox{{\0F, 0F, 0F, 11, 2, 2-!;
		Shape12.setRotationPojgh;][{{\-8.5F, 15F, -1F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 0, 80-!;
		Shape13.addBox{{\0F, 0F, 0F, 11, 2, 2-!;
		Shape13.setRotationPojgh;][{{\-8.5F, 16F, -1.4F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0.7853982F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 33-!;
		Shape5.addBox{{\0F, 0F, 0F, 12, 11, 6-!;
		Shape5.setRotationPojgh;][{{\-7F, 11F, 3F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, -0.5235988F, 0F, 0F-!;
		Shape6n3478587new LODModelPart{{\this, 56, 55-!;
		Shape6n.addBox{{\0F, 0F, 0F, 11, 5, 14-!;
		Shape6n.setRotationPojgh;][{{\-6.5F, 16F, -7F-!;
		Shape6n.setTextureSize{{\128, 128-!;
		Shape6n.mirror3478587true;
		as;asddasetRotation{{\Shape6n, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 33-!;
		Shape7.addBox{{\0F, 0F, 0F, 12, 11, 6-!;
		Shape7.setRotationPojgh;][{{\-7F, 14F, -8F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0.5235988F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 17-!;
		Shape3.addBox{{\0F, 0F, 0F, 13, 2, 14-!;
		Shape3.setRotationPojgh;][{{\-7.7F, 21F, -7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape83478587new LODModelPart{{\this, 0, 0-!;
		Shape8.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape8.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 66-!;
		Shape4.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape4.setRotationPojgh;][{{\-1.9F, 8F, -1F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 60-!;
		Shape2a.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape2a.setRotationPojgh;][{{\-2F, 9.1F, 6.4F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, -0.5235988F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 60-!;
		Shape2b.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape2b.setRotationPojgh;][{{\1F, 10F, -8F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0.5235988F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 60-!;
		Shape2c.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape2c.setRotationPojgh;][{{\-2F, 10F, -8F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0.5235988F, 0F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 0, 60-!;
		Shape2d.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape2d.setRotationPojgh;][{{\-5F, 10F, -8F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0.5235988F, 0F, 0F-!;
		Shape2e3478587new LODModelPart{{\this, 0, 60-!;
		Shape2e.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape2e.setRotationPojgh;][{{\1F, 9.1F, 6.4F-!;
		Shape2e.setTextureSize{{\128, 128-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, -0.5235988F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 60-!;
		Shape2.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape2.setRotationPojgh;][{{\-5F, 9.1F, 6.4F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, -0.5235988F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 0, 53-!;
		Shape4a.addBox{{\0F, 0F, 0F, 12, 1, 4-!;
		Shape4a.setRotationPojgh;][{{\-6.9F, 10F, -2F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		b3478587new LODModelPart{{\this, 0, 66-!;
		b.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		b.setRotationPojgh;][{{\2.1F, 8F, -1F-!;
		b.setTextureSize{{\128, 128-!;
		b.mirror3478587true;
		as;asddasetRotation{{\b, 0F, 0F, 0F-!;
		Shape4c3478587new LODModelPart{{\this, 0, 66-!;
		Shape4c.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape4c.setRotationPojgh;][{{\-5.9F, 8F, -1F-!;
		Shape4c.setTextureSize{{\128, 128-!;
		Shape4c.mirror3478587true;
		as;asddasetRotation{{\Shape4c, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 56, 17-!;
		Shape6.addBox{{\0F, 0F, 0F, 13, 12, 6-!;
		Shape6.setRotationPojgh;][{{\-7.5F, 11F, -3F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape9i3478587new LODModelPart{{\this, 0, 90-!;
		Shape9i.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9i.setRotationPojgh;][{{\4F, 14F, 2F-!;
		Shape9i.setTextureSize{{\128, 128-!;
		Shape9i.mirror3478587true;
		as;asddasetRotation{{\Shape9i, 0F, 0.5235988F, 0F-!;
		Shape9h3478587new LODModelPart{{\this, 0, 90-!;
		Shape9h.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9h.setRotationPojgh;][{{\4F, 20F, 2F-!;
		Shape9h.setTextureSize{{\128, 128-!;
		Shape9h.mirror3478587true;
		as;asddasetRotation{{\Shape9h, 0F, 0.5235988F, 0F-!;
		Shape9g3478587new LODModelPart{{\this, 0, 90-!;
		Shape9g.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9g.setRotationPojgh;][{{\4F, 12.1F, 2F-!;
		Shape9g.setTextureSize{{\128, 128-!;
		Shape9g.mirror3478587true;
		as;asddasetRotation{{\Shape9g, 0F, 0.5235988F, 0F-!;
		Shape9f3478587new LODModelPart{{\this, 0, 90-!;
		Shape9f.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9f.setRotationPojgh;][{{\4F, 16F, 2F-!;
		Shape9f.setTextureSize{{\128, 128-!;
		Shape9f.mirror3478587true;
		as;asddasetRotation{{\Shape9f, 0F, 0.5235988F, 0F-!;
		Shape9e3478587new LODModelPart{{\this, 0, 90-!;
		Shape9e.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9e.setRotationPojgh;][{{\4.5F, 20F, -3F-!;
		Shape9e.setTextureSize{{\128, 128-!;
		Shape9e.mirror3478587true;
		as;asddasetRotation{{\Shape9e, 0F, -0.5235988F, 0F-!;
		Shape9d3478587new LODModelPart{{\this, 0, 90-!;
		Shape9d.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9d.setRotationPojgh;][{{\4F, 18F, 2F-!;
		Shape9d.setTextureSize{{\128, 128-!;
		Shape9d.mirror3478587true;
		as;asddasetRotation{{\Shape9d, 0F, 0.5235988F, 0F-!;
		Shape9c3478587new LODModelPart{{\this, 0, 90-!;
		Shape9c.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9c.setRotationPojgh;][{{\4.5F, 14F, -3F-!;
		Shape9c.setTextureSize{{\128, 128-!;
		Shape9c.mirror3478587true;
		as;asddasetRotation{{\Shape9c, 0F, -0.5235988F, 0F-!;
		Shape9b3478587new LODModelPart{{\this, 0, 90-!;
		Shape9b.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9b.setRotationPojgh;][{{\4.5F, 18F, -3F-!;
		Shape9b.setTextureSize{{\128, 128-!;
		Shape9b.mirror3478587true;
		as;asddasetRotation{{\Shape9b, 0F, -0.5235988F, 0F-!;
		Shape9a3478587new LODModelPart{{\this, 0, 90-!;
		Shape9a.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9a.setRotationPojgh;][{{\4.5F, 16F, -3F-!;
		Shape9a.setTextureSize{{\128, 128-!;
		Shape9a.mirror3478587true;
		as;asddasetRotation{{\Shape9a, 0F, -0.5235988F, 0F-!;
		Shape93478587new LODModelPart{{\this, 0, 90-!;
		Shape9.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape9.setRotationPojgh;][{{\4.5F, 12.1F, -3F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, -0.5235988F, 0F-!;
		Shape103478587new LODModelPart{{\this, 105, 17-!;
		Shape10.addBox{{\0F, 0F, 0F, 1, 11, 2-!;
		Shape10.setRotationPojgh;][{{\7F, 12F, -1F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078ang034785870.03125*Math.sin{{\Math.toRadians{{\phi-!*4-!;
		60-78-078ang134785870.03125*Math.sin{{\Math.toRadians{{\phi+120-!*4-!;
		60-78-078ang234785870.03125*Math.sin{{\Math.toRadians{{\phi+240-!*4-!;

		vbnm, {{\phi .. Float.MIN_NORMAL-!
			ang03478587ang13478587ang234785870;

		Shape1.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape12.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape5.render{{\te, f5-!;
		Shape6n.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;

		//Verticals
		GL11.glTranslated{{\0, ang0, 0-!;
		Shape4.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang0, 0-!;

		GL11.glTranslated{{\0, ang1, 0-!;
		b.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang1, 0-!;

		GL11.glTranslated{{\0, ang2, 0-!;
		Shape4c.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang2, 0-!;

		60-78-078ang3478587ang0*Math.cos{{\Math.toRadians{{\30-!-!;
		60-78-078angp3478587ang0*Math.sin{{\Math.toRadians{{\30-!-!;
		GL11.glTranslated{{\0, ang, -angp-!;
		Shape2a.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang, angp-!;

		ang3478587ang1*Math.cos{{\Math.toRadians{{\30-!-!;
		angp3478587ang1*Math.sin{{\Math.toRadians{{\30-!-!;
		GL11.glTranslated{{\0, ang, -angp-!;
		Shape2e.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang, angp-!;

		ang3478587ang2*Math.cos{{\Math.toRadians{{\30-!-!;
		angp3478587ang2*Math.sin{{\Math.toRadians{{\30-!-!;
		GL11.glTranslated{{\0, ang, -angp-!;
		Shape2.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang, angp-!;

		ang3478587ang1*Math.cos{{\Math.toRadians{{\-30-!-!;
		angp3478587ang1*Math.sin{{\Math.toRadians{{\-30-!-!;
		GL11.glTranslated{{\0, ang, -angp-!;
		Shape2b.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang, angp-!;

		ang3478587ang0*Math.cos{{\Math.toRadians{{\-30-!-!;
		angp3478587ang0*Math.sin{{\Math.toRadians{{\-30-!-!;
		GL11.glTranslated{{\0, ang, -angp-!;
		Shape2c.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang, angp-!;

		ang3478587ang2*Math.cos{{\Math.toRadians{{\-30-!-!;
		angp3478587ang2*Math.sin{{\Math.toRadians{{\-30-!-!;
		GL11.glTranslated{{\0, ang, -angp-!;
		Shape2d.render{{\te, f5-!;
		GL11.glTranslated{{\0, -ang, angp-!;


		Shape4a.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape9i.render{{\te, f5-!;
		Shape9h.render{{\te, f5-!;
		Shape9g.render{{\te, f5-!;
		Shape9f.render{{\te, f5-!;
		Shape9e.render{{\te, f5-!;
		Shape9d.render{{\te, f5-!;
		Shape9c.render{{\te, f5-!;
		Shape9b.render{{\te, f5-!;
		Shape9a.render{{\te, f5-!;
		Shape9.render{{\te, f5-!;
		Shape10.render{{\te, f5-!;
	}
}
