/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 17/05/2013 1:11:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelMagnetizer ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2c;
	LODModelPart Shape2b;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape2g;
	LODModelPart Shape2j;
	LODModelPart Shape2h;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape2k;
	LODModelPart Shape2l;
	LODModelPart Shape2m;
	LODModelPart Shape2n;
	LODModelPart Shape2o;
	LODModelPart Shape2p;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;

	4578ret87ModelMagnetizer{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 38-!;
		Shape2.addBox{{\0F, 0F, 0F, 5, 1, 16-!;
		Shape2.setRotationPojgh;][{{\3F, 22F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 20-!;
		Shape2a.addBox{{\0F, 0F, 0F, 5, 1, 16-!;
		Shape2a.setRotationPojgh;][{{\-8F, 22F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 82, 94-!;
		Shape2c.addBox{{\0F, 0F, 0F, 4, 1, 16-!;
		Shape2c.setRotationPojgh;][{{\4F, 9F, -8F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 82, 57-!;
		Shape2b.addBox{{\0F, 0F, 0F, 3, 2, 16-!;
		Shape2b.setRotationPojgh;][{{\5F, 10F, -8F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 43, 98-!;
		Shape2d.addBox{{\0F, 0F, 0F, 1, 2, 16-!;
		Shape2d.setRotationPojgh;][{{\7F, 14F, -8F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0F, 0F-!;
		Shape2e3478587new LODModelPart{{\this, 82, 19-!;
		Shape2e.addBox{{\0F, 0F, 0F, 2, 2, 16-!;
		Shape2e.setRotationPojgh;][{{\6F, 12F, -8F-!;
		Shape2e.setTextureSize{{\128, 128-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, 0F, 0F, 0F-!;
		Shape2f3478587new LODModelPart{{\this, 82, 76-!;
		Shape2f.addBox{{\0F, 0F, 0F, 4, 1, 16-!;
		Shape2f.setRotationPojgh;][{{\-8F, 9F, -8F-!;
		Shape2f.setTextureSize{{\128, 128-!;
		Shape2f.mirror3478587true;
		as;asddasetRotation{{\Shape2f, 0F, 0F, 0F-!;
		Shape2g3478587new LODModelPart{{\this, 82, 38-!;
		Shape2g.addBox{{\0F, 0F, 0F, 3, 2, 16-!;
		Shape2g.setRotationPojgh;][{{\-8F, 10F, -8F-!;
		Shape2g.setTextureSize{{\128, 128-!;
		Shape2g.mirror3478587true;
		as;asddasetRotation{{\Shape2g, 0F, 0F, 0F-!;
		Shape2j3478587new LODModelPart{{\this, 79, 0-!;
		Shape2j.addBox{{\0F, 0F, 0F, 2, 2, 16-!;
		Shape2j.setRotationPojgh;][{{\-8F, 12F, -8F-!;
		Shape2j.setTextureSize{{\128, 128-!;
		Shape2j.mirror3478587true;
		as;asddasetRotation{{\Shape2j, 0F, 0F, 0F-!;
		Shape2h3478587new LODModelPart{{\this, 43, 79-!;
		Shape2h.addBox{{\0F, 0F, 0F, 1, 2, 16-!;
		Shape2h.setRotationPojgh;][{{\-8F, 14F, -8F-!;
		Shape2h.setTextureSize{{\128, 128-!;
		Shape2h.mirror3478587true;
		as;asddasetRotation{{\Shape2h, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 111-!;
		Shape3.addBox{{\-1F, -1F, 0F, 2, 2, 15-!;
		Shape3.setRotationPojgh;][{{\0F, 15F, -6.5F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0.7853982F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 111-!;
		Shape3a.addBox{{\-1F, -1F, 0F, 2, 2, 15-!;
		Shape3a.setRotationPojgh;][{{\0F, 15F, -6.5F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 66, 0-!;
		Shape4.addBox{{\0F, 0F, 0F, 4, 10, 2-!;
		Shape4.setRotationPojgh;][{{\-2F, 13F, 6F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 66, 0-!;
		Shape4a.addBox{{\0F, 0F, 0F, 4, 10, 2-!;
		Shape4a.setRotationPojgh;][{{\-2F, 13F, -6F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		Shape2k3478587new LODModelPart{{\this, 43, 39-!;
		Shape2k.addBox{{\0F, 0F, 0F, 2, 3, 16-!;
		Shape2k.setRotationPojgh;][{{\-8F, 16F, -8F-!;
		Shape2k.setTextureSize{{\128, 128-!;
		Shape2k.mirror3478587true;
		as;asddasetRotation{{\Shape2k, 0F, 0F, 0F-!;
		Shape2l3478587new LODModelPart{{\this, 43, 59-!;
		Shape2l.addBox{{\0F, 0F, 0F, 2, 3, 16-!;
		Shape2l.setRotationPojgh;][{{\6F, 16F, -8F-!;
		Shape2l.setTextureSize{{\128, 128-!;
		Shape2l.mirror3478587true;
		as;asddasetRotation{{\Shape2l, 0F, 0F, 0F-!;
		Shape2m3478587new LODModelPart{{\this, 0, 92-!;
		Shape2m.addBox{{\0F, 0F, 0F, 3, 2, 16-!;
		Shape2m.setRotationPojgh;][{{\-8F, 19F, -8F-!;
		Shape2m.setTextureSize{{\128, 128-!;
		Shape2m.mirror3478587true;
		as;asddasetRotation{{\Shape2m, 0F, 0F, 0F-!;
		Shape2n3478587new LODModelPart{{\this, 43, 20-!;
		Shape2n.addBox{{\0F, 0F, 0F, 3, 2, 16-!;
		Shape2n.setRotationPojgh;][{{\5F, 19F, -8F-!;
		Shape2n.setTextureSize{{\128, 128-!;
		Shape2n.mirror3478587true;
		as;asddasetRotation{{\Shape2n, 0F, 0F, 0F-!;
		Shape2o3478587new LODModelPart{{\this, 0, 56-!;
		Shape2o.addBox{{\0F, 0F, 0F, 4, 1, 16-!;
		Shape2o.setRotationPojgh;][{{\-8F, 21F, -8F-!;
		Shape2o.setTextureSize{{\128, 128-!;
		Shape2o.mirror3478587true;
		as;asddasetRotation{{\Shape2o, 0F, 0F, 0F-!;
		Shape2p3478587new LODModelPart{{\this, 0, 74-!;
		Shape2p.addBox{{\0F, 0F, 0F, 4, 1, 16-!;
		Shape2p.setRotationPojgh;][{{\4F, 21F, -8F-!;
		Shape2p.setTextureSize{{\128, 128-!;
		Shape2p.mirror3478587true;
		as;asddasetRotation{{\Shape2p, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 79, 113-!;
		Shape5.addBox{{\-2F, -2F, 0F, 4, 4, 6-!;
		Shape5.setRotationPojgh;][{{\0F, 15F, -2F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0.7853982F-!;
		Shape5a3478587new LODModelPart{{\this, 79, 113-!;
		Shape5a.addBox{{\-2F, -2F, 0F, 4, 4, 6-!;
		Shape5a.setRotationPojgh;][{{\0F, 15F, -2F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0.3926991F-!;
		Shape5b3478587new LODModelPart{{\this, 79, 113-!;
		Shape5b.addBox{{\-2F, -2F, 0F, 4, 4, 6-!;
		Shape5b.setRotationPojgh;][{{\0F, 15F, -2F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, 0F, 0F, 1.178097F-!;
		Shape5c3478587new LODModelPart{{\this, 79, 113-!;
		Shape5c.addBox{{\-2F, -2F, 0F, 4, 4, 6-!;
		Shape5c.setRotationPojgh;][{{\0F, 15F, -2F-!;
		Shape5c.setTextureSize{{\128, 128-!;
		Shape5c.mirror3478587true;
		as;asddasetRotation{{\Shape5c, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2d.render{{\te, f5-!;
		Shape2e.render{{\te, f5-!;
		Shape2f.render{{\te, f5-!;
		Shape2g.render{{\te, f5-!;
		Shape2j.render{{\te, f5-!;
		Shape2h.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape2k.render{{\te, f5-!;
		Shape2l.render{{\te, f5-!;
		Shape2m.render{{\te, f5-!;
		Shape2n.render{{\te, f5-!;
		Shape2o.render{{\te, f5-!;
		Shape2p.render{{\te, f5-!;
		60-78-078has3478587{{\Boolean-!li.get{{\0-!;
		vbnm, {{\!has-!
			return;
		GL11.glTranslated{{\0, 0.9375, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -0.9375, 0-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape5b.render{{\te, f5-!;
		Shape5c.render{{\te, f5-!;
		GL11.glTranslated{{\0, 0.9375, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -0.9375, 0-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f6-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
