/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 11/02/2013 9:16:18 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated.ShaftOnly;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;


4578ret87fhyuog ModelShaft ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape12;
	LODModelPart Shape13;

	4578ret87ModelShaft{{\-!
	{
		textureWidth3478587128;
		textureHeight347858732;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 32-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 64, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 12, 16-!;
		Shape2.setRotationPojgh;][{{\7F, 11F, -8F-!;
		Shape2.setTextureSize{{\128, 32-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2.mirror3478587false;
		Shape33478587new LODModelPart{{\this, 64, 0-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 12, 16-!;
		Shape3.setRotationPojgh;][{{\-8F, 11F, -8F-!;
		Shape3.setTextureSize{{\128, 32-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3.mirror3478587false;
		Shape43478587new LODModelPart{{\this, 0, 17-!;
		Shape4.addBox{{\0F, 0F, 0F, 14, 6, 1-!;
		Shape4.setRotationPojgh;][{{\-7F, 17F, 7F-!;
		Shape4.setTextureSize{{\128, 32-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape4.mirror3478587false;
		Shape53478587new LODModelPart{{\this, 0, 17-!;
		Shape5.addBox{{\0F, 0F, 0F, 14, 6, 1-!;
		Shape5.setRotationPojgh;][{{\-7F, 17F, -8F-!;
		Shape5.setTextureSize{{\128, 32-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5.mirror3478587false;
		Shape63478587new LODModelPart{{\this, 30, 17-!;
		Shape6.addBox{{\0F, 0F, 0F, 1, 3, 1-!;
		Shape6.setRotationPojgh;][{{\6F, 14F, 7F-!;
		Shape6.setTextureSize{{\128, 32-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6.mirror3478587false;
		Shape73478587new LODModelPart{{\this, 30, 17-!;
		Shape7.addBox{{\0F, 0F, 0F, 1, 3, 1-!;
		Shape7.setRotationPojgh;][{{\6F, 14F, -8F-!;
		Shape7.setTextureSize{{\128, 32-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape7.mirror3478587false;
		Shape83478587new LODModelPart{{\this, 30, 17-!;
		Shape8.addBox{{\0F, 0F, 0F, 1, 3, 1-!;
		Shape8.setRotationPojgh;][{{\-7F, 14F, 7F-!;
		Shape8.setTextureSize{{\128, 32-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape8.mirror3478587false;
		Shape93478587new LODModelPart{{\this, 30, 17-!;
		Shape9.addBox{{\0F, 0F, 0F, 1, 3, 1-!;
		Shape9.setRotationPojgh;][{{\-7F, 14F, -8F-!;
		Shape9.setTextureSize{{\128, 32-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape9.mirror3478587false;
		Shape103478587new LODModelPart{{\this, 42, 17-!;
		Shape10.addBox{{\0F, 0F, 0F, 1, 3, 10-!;
		Shape10.setRotationPojgh;][{{\7F, 8F, -5F-!;
		Shape10.setTextureSize{{\128, 32-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
		Shape10.mirror3478587false;
		Shape113478587new LODModelPart{{\this, 42, 17-!;
		Shape11.addBox{{\0F, 0F, 0F, 1, 3, 10-!;
		Shape11.setRotationPojgh;][{{\-8F, 8F, -5F-!;
		Shape11.setTextureSize{{\128, 32-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
		Shape11.mirror3478587false;
		Shape123478587new LODModelPart{{\this, 0, 27-!;
		Shape12.addBox{{\0F, 0F, 0F, 17, 2, 2-!;
		Shape12.setRotationPojgh;][{{\-8.5F, 15F, -1F-!;
		Shape12.setTextureSize{{\128, 32-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape12.mirror3478587false;
		Shape133478587new LODModelPart{{\this, 0, 27-!;
		Shape13.addBox{{\0F, 0F, 0F, 17, 2, 2-!;
		Shape13.setRotationPojgh;][{{\-8.5F, 16F, -1.4F-!;
		Shape13.setTextureSize{{\128, 32-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0.7853982F, 0F, 0F-!;
		Shape13.mirror3478587false;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078fail3478587{{\Boolean-!li.get{{\0-!;
		as;asddarenderMount{{\te-!;
		vbnm, {{\!fail-!
			as;asddarenderShaft{{\te, phi-!;
	}

	4578ret87void renderShaft{{\60-78-078 te, float phi-! {
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape12.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
	}

	4578ret87void renderMount{{\60-78-078 te-! {
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
		Shape9.render{{\te, f5-!;
		Shape10.render{{\te, f5-!;
		Shape11.render{{\te, f5-!;
	}

}
