/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 21/05/2013 1:15:04 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelScreen ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape7;
	LODModelPart Shape8a;
	LODModelPart Shape8b;
	LODModelPart Shape8c;
	LODModelPart Shape8d;
	LODModelPart Shape8;

	4578ret87ModelScreen{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 91, 14-!;
		Shape2.addBox{{\0F, 0F, 0F, 8, 1, 8-!;
		Shape2.setRotationPojgh;][{{\-4F, 20F, -4F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 65, 14-!;
		Shape3.addBox{{\0F, 0F, 0F, 6, 1, 6-!;
		Shape3.setRotationPojgh;][{{\-3F, 21F, -3F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 65, 0-!;
		Shape4.addBox{{\0F, 0F, 0F, 12, 1, 12-!;
		Shape4.setRotationPojgh;][{{\-6F, 22F, -6F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 7, 26-!;
		Shape5.addBox{{\0F, 0F, 0F, 2, 12, 1-!;
		Shape5.setRotationPojgh;][{{\6F, 8F, -8F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 26-!;
		Shape5a.addBox{{\0F, 0F, 0F, 2, 12, 1-!;
		Shape5a.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 22-!;
		Shape6.addBox{{\0F, 0F, 0F, 12, 2, 1-!;
		Shape6.setRotationPojgh;][{{\-6F, 8F, -8F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 18-!;
		Shape6a.addBox{{\0F, 0F, 0F, 12, 2, 1-!;
		Shape6a.setRotationPojgh;][{{\-6F, 18F, -8F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 40-!;
		Shape7.addBox{{\0F, 0F, 0F, 12, 8, 1-!;
		Shape7.setRotationPojgh;][{{\-6F, 10F, -7.5F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape8a3478587new LODModelPart{{\this, 0, 110-!;
		Shape8a.addBox{{\0F, 0F, 0F, 12, 7, 2-!;
		Shape8a.setRotationPojgh;][{{\-6F, 12F, 6F-!;
		Shape8a.setTextureSize{{\128, 128-!;
		Shape8a.mirror3478587true;
		as;asddasetRotation{{\Shape8a, 0F, 0F, 0F-!;
		Shape8b3478587new LODModelPart{{\this, 0, 50-!;
		Shape8b.addBox{{\0F, 0F, 0F, 16, 12, 5-!;
		Shape8b.setRotationPojgh;][{{\-8F, 8F, -7F-!;
		Shape8b.setTextureSize{{\128, 128-!;
		Shape8b.mirror3478587true;
		as;asddasetRotation{{\Shape8b, 0F, 0F, 0F-!;
		Shape8c3478587new LODModelPart{{\this, 0, 68-!;
		Shape8c.addBox{{\0F, 0F, 0F, 16, 11, 3-!;
		Shape8c.setRotationPojgh;][{{\-8F, 9F, -2F-!;
		Shape8c.setTextureSize{{\128, 128-!;
		Shape8c.mirror3478587true;
		as;asddasetRotation{{\Shape8c, 0F, 0F, 0F-!;
		Shape8d3478587new LODModelPart{{\this, 0, 83-!;
		Shape8d.addBox{{\0F, 0F, 0F, 15, 10, 3-!;
		Shape8d.setRotationPojgh;][{{\-7.5F, 10F, 1F-!;
		Shape8d.setTextureSize{{\128, 128-!;
		Shape8d.mirror3478587true;
		as;asddasetRotation{{\Shape8d, 0F, 0F, 0F-!;
		Shape83478587new LODModelPart{{\this, 0, 98-!;
		Shape8.addBox{{\0F, 0F, 0F, 14, 9, 2-!;
		Shape8.setRotationPojgh;][{{\-7F, 11F, 4F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape8a.render{{\te, f5-!;
		Shape8b.render{{\te, f5-!;
		Shape8c.render{{\te, f5-!;
		Shape8d.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f6-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
