/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 14/03/2013 9:51:16 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelMonitor ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape4a;
	LODModelPart Shape7;
	LODModelPart Shape1a;
	LODModelPart Shape4b;
	LODModelPart Shape7a;
	LODModelPart Shape4c;
	LODModelPart Shape6b;
	LODModelPart Shape6c;

	4578ret87ModelMonitor{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 64, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 14, 16-!;
		Shape2.setRotationPojgh;][{{\7F, 9F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 64, 0-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 14, 16-!;
		Shape3.setRotationPojgh;][{{\-8F, 9F, -8F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 32-!;
		Shape4.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape4.setRotationPojgh;][{{\-7F, 9F, -8F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 0, 27-!;
		Shape12.addBox{{\0F, 0F, 0F, 17, 2, 2-!;
		Shape12.setRotationPojgh;][{{\-8.5F, 15F, -1F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 0, 27-!;
		Shape13.addBox{{\0F, 0F, 0F, 17, 2, 2-!;
		Shape13.setRotationPojgh;][{{\-8.5F, 16F, -1.4F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0.7853982F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 34-!;
		Shape6.addBox{{\0F, 0F, 0F, 1, 12, 1-!;
		Shape6.setRotationPojgh;][{{\-7F, 10F, -8F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 34-!;
		Shape6a.addBox{{\0F, 0F, 0F, 1, 12, 1-!;
		Shape6a.setRotationPojgh;][{{\6F, 10F, -8F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 0, 32-!;
		Shape4a.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape4a.setRotationPojgh;][{{\-7F, 22F, -8F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 4, 34-!;
		Shape7.addBox{{\0F, 0F, 0F, 14, 14, 1-!;
		Shape7.setRotationPojgh;][{{\-7F, 9F, -7F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 0, 0-!;
		Shape1a.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1a.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0F, 0F-!;
		Shape4b3478587new LODModelPart{{\this, 0, 32-!;
		Shape4b.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape4b.setRotationPojgh;][{{\-7F, 22F, 7F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 0F, 0F, 0F-!;
		Shape7a3478587new LODModelPart{{\this, 4, 34-!;
		Shape7a.addBox{{\0F, 0F, 0F, 14, 14, 1-!;
		Shape7a.setRotationPojgh;][{{\-7F, 9F, 6F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, 0F, 0F-!;
		Shape4c3478587new LODModelPart{{\this, 0, 32-!;
		Shape4c.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape4c.setRotationPojgh;][{{\-7F, 9F, 7F-!;
		Shape4c.setTextureSize{{\128, 128-!;
		Shape4c.mirror3478587true;
		as;asddasetRotation{{\Shape4c, 0F, 0F, 0F-!;
		Shape6b3478587new LODModelPart{{\this, 0, 34-!;
		Shape6b.addBox{{\0F, 0F, 0F, 1, 12, 1-!;
		Shape6b.setRotationPojgh;][{{\6F, 10F, 7F-!;
		Shape6b.setTextureSize{{\128, 128-!;
		Shape6b.mirror3478587true;
		as;asddasetRotation{{\Shape6b, 0F, 0F, 0F-!;
		Shape6c3478587new LODModelPart{{\this, 0, 34-!;
		Shape6c.addBox{{\0F, 0F, 0F, 1, 12, 1-!;
		Shape6c.setRotationPojgh;][{{\-7F, 10F, 7F-!;
		Shape6c.setTextureSize{{\128, 128-!;
		Shape6c.mirror3478587true;
		as;asddasetRotation{{\Shape6c, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;
		Shape7a.render{{\te, f5-!;
		Shape4c.render{{\te, f5-!;
		Shape6b.render{{\te, f5-!;
		Shape6c.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape12.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
	}
}
