/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 13/06/2013 11:18:12 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelMirror ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape3d;
	LODModelPart Shape3as;
	LODModelPart Shape5af;
	LODModelPart Shape5as;

	4578ret87ModelMirror{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 71-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 0-!;
		Shape3.addBox{{\-5F, 0F, -5F, 10, 1, 10-!;
		Shape3.setRotationPojgh;][{{\0F, 22F, 0F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0.5235988F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 19-!;
		Shape4.addBox{{\-1F, -4.1F, -4F, 2, 9, 1-!;
		Shape4.setRotationPojgh;][{{\0F, 23F, 0F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, -1.047198F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 66, 0-!;
		Shape5.addBox{{\-8F, 6.1F, 5.3F, 16, 3, 1-!;
		Shape5.setRotationPojgh;][{{\0F, 9F, 0F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, -0.7853982F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 57-!;
		Shape5a.addBox{{\4F, 3F, 1.5F, 2, 11, 1-!;
		Shape5a.setRotationPojgh;][{{\0F, 9F, 0F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape5b3478587new LODModelPart{{\this, 66, 11-!;
		Shape5b.addBox{{\-8F, 3F, 2.1F, 16, 3, 1-!;
		Shape5b.setRotationPojgh;][{{\0F, 9F, 0F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, -0.2617994F, 0F, 0F-!;
		Shape5c3478587new LODModelPart{{\this, 66, 5-!;
		Shape5c.addBox{{\-8F, 4.7F, 3.5F, 16, 3, 1-!;
		Shape5c.setRotationPojgh;][{{\0F, 9F, 0F-!;
		Shape5c.setTextureSize{{\128, 128-!;
		Shape5c.mirror3478587true;
		as;asddasetRotation{{\Shape5c, -0.5235988F, 0F, 0F-!;
		Shape5d3478587new LODModelPart{{\this, 66, 17-!;
		Shape5d.addBox{{\-8F, 0.6F, 1.3F, 16, 3, 1-!;
		Shape5d.setRotationPojgh;][{{\0F, 9F, 0F-!;
		Shape5d.setTextureSize{{\128, 128-!;
		Shape5d.mirror3478587true;
		as;asddasetRotation{{\Shape5d, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 0-!;
		Shape3a.addBox{{\-5F, 0F, -5F, 10, 1, 10-!;
		Shape3a.setRotationPojgh;][{{\0F, 22F, 0F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 0, 0-!;
		Shape3b.addBox{{\-5F, 0F, -5F, 10, 1, 10-!;
		Shape3b.setRotationPojgh;][{{\0F, 22F, 0F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 1.047198F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 0, 0-!;
		Shape3c.addBox{{\-5F, 0F, -5F, 10, 1, 10-!;
		Shape3c.setRotationPojgh;][{{\0F, 22F, 0F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0.7853982F, 0F-!;
		Shape3d3478587new LODModelPart{{\this, 0, 0-!;
		Shape3d.addBox{{\-5F, 0F, -5F, 10, 1, 10-!;
		Shape3d.setRotationPojgh;][{{\0F, 22F, 0F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, 1.308997F, 0F-!;
		Shape3as3478587new LODModelPart{{\this, 0, 0-!;
		Shape3as.addBox{{\-5F, 0F, -5F, 10, 1, 10-!;
		Shape3as.setRotationPojgh;][{{\0F, 22F, 0F-!;
		Shape3as.setTextureSize{{\128, 128-!;
		Shape3as.mirror3478587true;
		as;asddasetRotation{{\Shape3as, 0F, 0.2617994F, 0F-!;
		Shape5af3478587new LODModelPart{{\this, 0, 31-!;
		Shape5af.addBox{{\-6F, 3F, 1.5F, 2, 11, 1-!;
		Shape5af.setRotationPojgh;][{{\0F, 9F, 0F-!;
		Shape5af.setTextureSize{{\128, 128-!;
		Shape5af.mirror3478587true;
		as;asddasetRotation{{\Shape5af, 0F, 0F, 0F-!;
		Shape5as3478587new LODModelPart{{\this, 0, 44-!;
		Shape5as.addBox{{\-1F, 3F, 1.5F, 2, 11, 1-!;
		Shape5as.setRotationPojgh;][{{\0F, 9F, 0F-!;
		Shape5as.setTextureSize{{\128, 128-!;
		Shape5as.mirror3478587true;
		as;asddasetRotation{{\Shape5as, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078broken3478587{{\Boolean-!li.get{{\0-!;
		Shape1.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 0, 1, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;

		vbnm, {{\!broken-! {
			GL11.glTranslated{{\0, 1, 0-!;
			GL11.glRotatef{{\theta, 1, 0, 0-!;
			GL11.glTranslated{{\0, -1, 0-!;
			Shape5.render{{\te, f5-!;
			Shape5b.render{{\te, f5-!;
			Shape5c.render{{\te, f5-!;
			Shape5d.render{{\te, f5-!;
			GL11.glTranslated{{\0, 1, 0-!;
			GL11.glRotatef{{\-theta, 1, 0, 0-!;
			GL11.glTranslated{{\0, -1, 0-!;
		}

		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;
		Shape3d.render{{\te, f5-!;
		Shape3as.render{{\te, f5-!;

		60-78-078sc34785871-0.725*Math.cos{{\Math.toRadians{{\theta-!-!*Math.sin{{\Math.toRadians{{\-theta-!-!;
		60-78-078d34785871.5;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glScaled{{\1, sc, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
		Shape5a.render{{\te, f5-!;
		Shape5af.render{{\te, f5-!;
		Shape5as.render{{\te, f5-!;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glScaled{{\1, 1D/sc, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;


		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 0, 1, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
	}

}
