/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 30/10/2013 6:13:43 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelAggregator ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape3f;
	LODModelPart Shape3g;
	LODModelPart Shape1a;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape1d;
	LODModelPart Shape1e;
	LODModelPart Shape1f;
	LODModelPart Shape1g;
	LODModelPart Shape2a;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;

	4578ret87ModelAggregator{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\2.5F, 0F, -3.2F, 3, 12, 1-!;
		Shape1.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 1.570796F, 0F-!;
		Shape23478587new LODModelPart{{\this, 44, 0-!;
		Shape2.addBox{{\-1F, 0F, -1F, 2, 16, 2-!;
		Shape2.setRotationPojgh;][{{\0F, 8.5F, 0F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0.7853982F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 0-!;
		Shape3.addBox{{\1F, 0F, -0.5F, 3, 12, 1-!;
		Shape3.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, -2.356194F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 0-!;
		Shape3a.addBox{{\1F, 0F, -0.5F, 3, 12, 1-!;
		Shape3a.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 0, 0-!;
		Shape3b.addBox{{\1F, 0F, -0.5F, 3, 12, 1-!;
		Shape3b.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0.7853982F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 0, 0-!;
		Shape3c.addBox{{\1F, 0F, -0.5F, 3, 12, 1-!;
		Shape3c.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 1.570796F, 0F-!;
		Shape3d3478587new LODModelPart{{\this, 0, 0-!;
		Shape3d.addBox{{\1F, 0F, -0.5F, 3, 12, 1-!;
		Shape3d.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, 2.356194F, 0F-!;
		Shape3e3478587new LODModelPart{{\this, 0, 0-!;
		Shape3e.addBox{{\1F, 0F, -0.5F, 3, 12, 1-!;
		Shape3e.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape3e.setTextureSize{{\128, 128-!;
		Shape3e.mirror3478587true;
		as;asddasetRotation{{\Shape3e, 0F, 3.141593F, 0F-!;
		Shape3f3478587new LODModelPart{{\this, 0, 0-!;
		Shape3f.addBox{{\1F, 0F, -0.5F, 3, 12, 1-!;
		Shape3f.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape3f.setTextureSize{{\128, 128-!;
		Shape3f.mirror3478587true;
		as;asddasetRotation{{\Shape3f, 0F, -0.7853982F, 0F-!;
		Shape3g3478587new LODModelPart{{\this, 0, 0-!;
		Shape3g.addBox{{\1F, 0F, -0.5F, 3, 12, 1-!;
		Shape3g.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape3g.setTextureSize{{\128, 128-!;
		Shape3g.mirror3478587true;
		as;asddasetRotation{{\Shape3g, 0F, -1.570796F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 0, 0-!;
		Shape1a.addBox{{\2.5F, 0F, -3.2F, 3, 12, 1-!;
		Shape1a.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0.7853982F, 0F-!;
		Shape1b3478587new LODModelPart{{\this, 0, 0-!;
		Shape1b.addBox{{\2.5F, 0F, -3.2F, 3, 12, 1-!;
		Shape1b.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape1b.setTextureSize{{\128, 128-!;
		Shape1b.mirror3478587true;
		as;asddasetRotation{{\Shape1b, 0F, 0F, 0F-!;
		Shape1c3478587new LODModelPart{{\this, 0, 0-!;
		Shape1c.addBox{{\2.5F, 0F, -3.2F, 3, 12, 1-!;
		Shape1c.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape1c.setTextureSize{{\128, 128-!;
		Shape1c.mirror3478587true;
		as;asddasetRotation{{\Shape1c, 0F, -0.7853982F, 0F-!;
		Shape1d3478587new LODModelPart{{\this, 0, 0-!;
		Shape1d.addBox{{\2.5F, 0F, -3.2F, 3, 12, 1-!;
		Shape1d.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape1d.setTextureSize{{\128, 128-!;
		Shape1d.mirror3478587true;
		as;asddasetRotation{{\Shape1d, 0F, -1.570796F, 0F-!;
		Shape1e3478587new LODModelPart{{\this, 0, 0-!;
		Shape1e.addBox{{\2.5F, 0F, -3.2F, 3, 12, 1-!;
		Shape1e.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape1e.setTextureSize{{\128, 128-!;
		Shape1e.mirror3478587true;
		as;asddasetRotation{{\Shape1e, 0F, -2.356194F, 0F-!;
		Shape1f3478587new LODModelPart{{\this, 0, 0-!;
		Shape1f.addBox{{\2.5F, 0F, -3.2F, 3, 12, 1-!;
		Shape1f.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape1f.setTextureSize{{\128, 128-!;
		Shape1f.mirror3478587true;
		as;asddasetRotation{{\Shape1f, 0F, 3.141593F, 0F-!;
		Shape1g3478587new LODModelPart{{\this, 0, 0-!;
		Shape1g.addBox{{\2.5F, 0F, -3.2F, 3, 12, 1-!;
		Shape1g.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape1g.setTextureSize{{\128, 128-!;
		Shape1g.mirror3478587true;
		as;asddasetRotation{{\Shape1g, 0F, 2.356194F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 44, 0-!;
		Shape2a.addBox{{\-1F, 0F, -1F, 2, 16, 2-!;
		Shape2a.setRotationPojgh;][{{\0F, 8.5F, 0F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 59, 19-!;
		Shape4.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape4.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 59, 0-!;
		Shape5.addBox{{\-1F, 0F, -8F, 2, 1, 16-!;
		Shape5.setRotationPojgh;][{{\6F, 8F, 0F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 47-!;
		Shape6.addBox{{\0F, 0F, 0F, 16, 14, 1-!;
		Shape6.setRotationPojgh;][{{\-8F, 9F, 7F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 30-!;
		Shape6a.addBox{{\0F, 0F, 0F, 16, 14, 1-!;
		Shape6a.setRotationPojgh;][{{\-8F, 9F, -8F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 64-!;
		Shape7.addBox{{\0F, 0F, 0F, 1, 14, 14-!;
		Shape7.setRotationPojgh;][{{\7F, 9F, -7F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape7a3478587new LODModelPart{{\this, 10, 0-!;
		Shape7a.addBox{{\0F, 0F, 0F, 1, 14, 14-!;
		Shape7a.setRotationPojgh;][{{\-8F, 9F, -7F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 59, 91-!;
		Shape5a.addBox{{\-1F, 0F, -8F, 2, 1, 16-!;
		Shape5a.setRotationPojgh;][{{\-6F, 8F, 0F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape5b3478587new LODModelPart{{\this, 59, 37-!;
		Shape5b.addBox{{\-1F, 0F, -8F, 2, 1, 16-!;
		Shape5b.setRotationPojgh;][{{\3F, 8F, 0F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, 0F, 0F, 0F-!;
		Shape5c3478587new LODModelPart{{\this, 59, 109-!;
		Shape5c.addBox{{\-7.5F, 0F, -1F, 15, 1, 2-!;
		Shape5c.setRotationPojgh;][{{\0F, 8.4F, 0F-!;
		Shape5c.setTextureSize{{\128, 128-!;
		Shape5c.mirror3478587true;
		as;asddasetRotation{{\Shape5c, 0F, 0F, 0F-!;
		Shape5d3478587new LODModelPart{{\this, 59, 73-!;
		Shape5d.addBox{{\-1F, 0F, -8F, 2, 1, 16-!;
		Shape5d.setRotationPojgh;][{{\-3F, 8F, 0F-!;
		Shape5d.setTextureSize{{\128, 128-!;
		Shape5d.mirror3478587true;
		as;asddasetRotation{{\Shape5d, 0F, 0F, 0F-!;
		Shape5e3478587new LODModelPart{{\this, 59, 55-!;
		Shape5e.addBox{{\-1F, 0F, -8F, 2, 1, 16-!;
		Shape5e.setRotationPojgh;][{{\0F, 8F, 0F-!;
		Shape5e.setTextureSize{{\128, 128-!;
		Shape5e.mirror3478587true;
		as;asddasetRotation{{\Shape5e, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		GL11.glRotatef{{\phi, 0, 1, 0-!;
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;
		Shape3d.render{{\te, f5-!;
		Shape3e.render{{\te, f5-!;
		Shape3f.render{{\te, f5-!;
		Shape3g.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;
		Shape1b.render{{\te, f5-!;
		Shape1c.render{{\te, f5-!;
		Shape1d.render{{\te, f5-!;
		Shape1e.render{{\te, f5-!;
		Shape1f.render{{\te, f5-!;
		Shape1g.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		GL11.glRotatef{{\-phi, 0, 1, 0-!;

		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape7a.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape5b.render{{\te, f5-!;
		Shape5c.render{{\te, f5-!;
		Shape5d.render{{\te, f5-!;
		Shape5e.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
