/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 26-03-2014 13:45:49
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelHighGear ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape24;
	LODModelPart Shape25;
	LODModelPart Shape42;
	LODModelPart Shape43;
	LODModelPart Shape12a;
	LODModelPart Shape12;
	LODModelPart Shape12c;
	LODModelPart Shape12b;
	LODModelPart Shape13;
	LODModelPart Shape13a;
	LODModelPart Shape12d;
	LODModelPart Shape12e;
	LODModelPart Shape12f;
	LODModelPart Shape12g;
	LODModelPart Shape13b;
	LODModelPart Shape13c;

	4578ret87ModelHighGear{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 64, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 12, 16-!;
		Shape2.setRotationPojgh;][{{\7F, 11F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2.mirror3478587false;
		Shape33478587new LODModelPart{{\this, 64, 0-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 12, 16-!;
		Shape3.setRotationPojgh;][{{\-8F, 11F, -8F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3.mirror3478587false;
		Shape43478587new LODModelPart{{\this, 0, 17-!;
		Shape4.addBox{{\0F, 0F, 0F, 14, 4, 1-!;
		Shape4.setRotationPojgh;][{{\-7F, 19F, 7F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape4.mirror3478587false;
		Shape53478587new LODModelPart{{\this, 0, 17-!;
		Shape5.addBox{{\0F, 0F, 0F, 14, 4, 1-!;
		Shape5.setRotationPojgh;][{{\-7F, 19F, -8F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5.mirror3478587false;
		Shape63478587new LODModelPart{{\this, 30, 17-!;
		Shape6.addBox{{\0F, 0F, 0F, 1, 3, 1-!;
		Shape6.setRotationPojgh;][{{\6F, 16F, 7F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6.mirror3478587false;
		Shape73478587new LODModelPart{{\this, 30, 17-!;
		Shape7.addBox{{\0F, 0F, 0F, 1, 3, 1-!;
		Shape7.setRotationPojgh;][{{\6F, 16F, -8F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape7.mirror3478587false;
		Shape83478587new LODModelPart{{\this, 30, 17-!;
		Shape8.addBox{{\0F, 0F, 0F, 1, 3, 1-!;
		Shape8.setRotationPojgh;][{{\-7F, 16F, 7F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape8.mirror3478587false;
		Shape93478587new LODModelPart{{\this, 30, 17-!;
		Shape9.addBox{{\0F, 0F, 0F, 1, 3, 1-!;
		Shape9.setRotationPojgh;][{{\-7F, 16F, -8F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape9.mirror3478587false;
		Shape103478587new LODModelPart{{\this, 42, 17-!;
		Shape10.addBox{{\0F, 0F, 0F, 1, 3, 10-!;
		Shape10.setRotationPojgh;][{{\7F, 8F, -5F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
		Shape10.mirror3478587false;
		Shape113478587new LODModelPart{{\this, 42, 17-!;
		Shape11.addBox{{\0F, 0F, 0F, 1, 3, 10-!;
		Shape11.setRotationPojgh;][{{\-8F, 8F, -5F-!;
		Shape11.setTextureSize{{\128, 128-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
		Shape11.mirror3478587false;
		Shape243478587new LODModelPart{{\this, 0, 27-!;
		Shape24.addBox{{\0F, -1F, -1F, 3, 2, 2-!;
		Shape24.setRotationPojgh;][{{\5.5F, 16F, 0F-!;
		Shape24.setTextureSize{{\128, 128-!;
		Shape24.mirror3478587true;
		as;asddasetRotation{{\Shape24, 0F, 0F, 0F-!;
		Shape253478587new LODModelPart{{\this, 0, 27-!;
		Shape25.addBox{{\0F, -1F, -1F, 3, 2, 2-!;
		Shape25.setRotationPojgh;][{{\5.5F, 16F, 0F-!;
		Shape25.setTextureSize{{\128, 128-!;
		Shape25.mirror3478587true;
		as;asddasetRotation{{\Shape25, 0.7853982F, 0F, 0.0174533F-!;
		Shape423478587new LODModelPart{{\this, 0, 27-!;
		Shape42.addBox{{\0F, -1F, -1F, 3, 2, 2-!;
		Shape42.setRotationPojgh;][{{\-8.5F, 16F, 0F-!;
		Shape42.setTextureSize{{\128, 128-!;
		Shape42.mirror3478587true;
		as;asddasetRotation{{\Shape42, 0F, 0F, 0F-!;
		Shape433478587new LODModelPart{{\this, 0, 27-!;
		Shape43.addBox{{\0F, -1F, -1F, 3, 2, 2-!;
		Shape43.setRotationPojgh;][{{\-8.5F, 16F, 0F-!;
		Shape43.setTextureSize{{\128, 128-!;
		Shape43.mirror3478587true;
		as;asddasetRotation{{\Shape43, 0.7853982F, 0F, 0F-!;
		Shape12a3478587new LODModelPart{{\this, 0, 32-!;
		Shape12a.addBox{{\0F, -4F, -4F, 1, 8, 8-!;
		Shape12a.setRotationPojgh;][{{\-6F, 15F, -2F-!;
		Shape12a.setTextureSize{{\128, 128-!;
		Shape12a.mirror3478587true;
		as;asddasetRotation{{\Shape12a, 1.178097F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 0, 32-!;
		Shape12.addBox{{\0F, -4F, -4F, 1, 8, 8-!;
		Shape12.setRotationPojgh;][{{\-6F, 15F, -2F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape12c3478587new LODModelPart{{\this, 0, 32-!;
		Shape12c.addBox{{\0F, -4F, -4F, 1, 8, 8-!;
		Shape12c.setRotationPojgh;][{{\-5F, 15F, 2F-!;
		Shape12c.setTextureSize{{\128, 128-!;
		Shape12c.mirror3478587true;
		as;asddasetRotation{{\Shape12c, 1.178097F, 0F, 0F-!;
		Shape12b3478587new LODModelPart{{\this, 0, 32-!;
		Shape12b.addBox{{\0F, -4F, -4F, 1, 8, 8-!;
		Shape12b.setRotationPojgh;][{{\-6F, 15F, -2F-!;
		Shape12b.setTextureSize{{\128, 128-!;
		Shape12b.mirror3478587true;
		as;asddasetRotation{{\Shape12b, 0.3926991F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 20, 32-!;
		Shape13.addBox{{\0F, -1.5F, -1.5F, 1, 3, 3-!;
		Shape13.setRotationPojgh;][{{\-5F, 15F, -4.5F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0F, 0F, 0F-!;
		Shape13a3478587new LODModelPart{{\this, 20, 32-!;
		Shape13a.addBox{{\0F, -1.5F, -1.5F, 1, 3, 3-!;
		Shape13a.setRotationPojgh;][{{\-6F, 15F, 4.5F-!;
		Shape13a.setTextureSize{{\128, 128-!;
		Shape13a.mirror3478587true;
		as;asddasetRotation{{\Shape13a, 0F, 0F, 0F-!;
		Shape12d3478587new LODModelPart{{\this, 0, 32-!;
		Shape12d.addBox{{\0F, -4F, -4F, 1, 8, 8-!;
		Shape12d.setRotationPojgh;][{{\-6F, 15F, -2F-!;
		Shape12d.setTextureSize{{\128, 128-!;
		Shape12d.mirror3478587true;
		as;asddasetRotation{{\Shape12d, 0.7853982F, 0F, 0F-!;
		Shape12e3478587new LODModelPart{{\this, 0, 32-!;
		Shape12e.addBox{{\0F, -4F, -4F, 1, 8, 8-!;
		Shape12e.setRotationPojgh;][{{\-5F, 15F, 2F-!;
		Shape12e.setTextureSize{{\128, 128-!;
		Shape12e.mirror3478587true;
		as;asddasetRotation{{\Shape12e, 0.7853982F, 0F, 0F-!;
		Shape12f3478587new LODModelPart{{\this, 0, 32-!;
		Shape12f.addBox{{\0F, -4F, -4F, 1, 8, 8-!;
		Shape12f.setRotationPojgh;][{{\-5F, 15F, 2F-!;
		Shape12f.setTextureSize{{\128, 128-!;
		Shape12f.mirror3478587true;
		as;asddasetRotation{{\Shape12f, 0F, 0F, 0F-!;
		Shape12g3478587new LODModelPart{{\this, 0, 32-!;
		Shape12g.addBox{{\0F, -4F, -4F, 1, 8, 8-!;
		Shape12g.setRotationPojgh;][{{\-5F, 15F, 2F-!;
		Shape12g.setTextureSize{{\128, 128-!;
		Shape12g.mirror3478587true;
		as;asddasetRotation{{\Shape12g, 0.3926991F, 0F, 0F-!;
		Shape13b3478587new LODModelPart{{\this, 20, 32-!;
		Shape13b.addBox{{\0F, -1.5F, -1.5F, 1, 3, 3-!;
		Shape13b.setRotationPojgh;][{{\-6F, 15F, 4.5F-!;
		Shape13b.setTextureSize{{\128, 128-!;
		Shape13b.mirror3478587true;
		as;asddasetRotation{{\Shape13b, 0.7853982F, 0F, 0F-!;
		Shape13c3478587new LODModelPart{{\this, 20, 32-!;
		Shape13c.addBox{{\0F, -1.5F, -1.5F, 1, 3, 3-!;
		Shape13c.setRotationPojgh;][{{\-5F, 15F, -4.5F-!;
		Shape13c.setTextureSize{{\128, 128-!;
		Shape13c.mirror3478587true;
		as;asddasetRotation{{\Shape13c, 0.7853982F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-! {
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
		Shape9.render{{\te, f5-!;
		Shape10.render{{\te, f5-!;
		Shape11.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape24.render{{\te, f5-!;
		Shape25.render{{\te, f5-!;
		Shape42.render{{\te, f5-!;
		Shape43.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		for {{\60-78-078f34785870; f < 0.75; f +. 0.125-! {
			GL11.glTranslated{{\f, 0, 0-!;

			60-78-078d34785870.125;
			GL11.glTranslated{{\0, 0.9375, d-!;
			GL11.glRotatef{{\phi, 1, 0, 0-!;
			GL11.glTranslated{{\0, -0.9375, -d-!;
			Shape12c.render{{\te, f5-!;
			Shape12e.render{{\te, f5-!;
			Shape12f.render{{\te, f5-!;
			Shape12g.render{{\te, f5-!;
			GL11.glTranslated{{\0, 0.9375, d-!;
			GL11.glRotatef{{\-phi, 1, 0, 0-!;
			GL11.glTranslated{{\0, -0.9375, -d-!;

			GL11.glTranslated{{\0, 0.9375, -d-!;
			GL11.glRotatef{{\-phi, 1, 0, 0-!;
			GL11.glTranslated{{\0, -0.9375, d-!;
			Shape12a.render{{\te, f5-!;
			Shape12.render{{\te, f5-!;
			Shape12b.render{{\te, f5-!;
			Shape12d.render{{\te, f5-!;
			GL11.glTranslated{{\0, 0.9375, -d-!;
			GL11.glRotatef{{\phi, 1, 0, 0-!;
			GL11.glTranslated{{\0, -0.9375, d-!;

			d34785870.2875;
			GL11.glTranslated{{\0, 0.9375, -d-!;
			GL11.glRotatef{{\-phi, 1, 0, 0-!;
			GL11.glTranslated{{\0, -0.9375, d-!;
			Shape13.render{{\te, f5-!;
			Shape13c.render{{\te, f5-!;
			GL11.glTranslated{{\0, 0.9375, -d-!;
			GL11.glRotatef{{\phi, 1, 0, 0-!;
			GL11.glTranslated{{\0, -0.9375, d-!;

			GL11.glTranslated{{\0, 0.9375, d-!;
			GL11.glRotatef{{\phi, 1, 0, 0-!;
			GL11.glTranslated{{\0, -0.9375, -d-!;
			Shape13a.render{{\te, f5-!;
			Shape13b.render{{\te, f5-!;
			GL11.glTranslated{{\0, 0.9375, d-!;
			GL11.glRotatef{{\-phi, 1, 0, 0-!;
			GL11.glTranslated{{\0, -0.9375, -d-!;

			GL11.glTranslated{{\-f, 0, 0-!;
		}
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
