/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 16/02/2013 12:10:02 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelAerosolizer ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape10;
	LODModelPart Shape11;

	4578ret87ModelAerosolizer{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 12, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 12F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 28-!;
		Shape2.addBox{{\0F, 0F, 0F, 14, 2, 1-!;
		Shape2.setRotationPojgh;][{{\-7F, 10F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 28-!;
		Shape3.addBox{{\0F, 0F, 0F, 14, 2, 1-!;
		Shape3.setRotationPojgh;][{{\-7F, 10F, 7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 28-!;
		Shape4.addBox{{\0F, 0F, 0F, 14, 2, 1-!;
		Shape4.setRotationPojgh;][{{\-7F, 10F, 2F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 28-!;
		Shape5.addBox{{\0F, 0F, 0F, 14, 2, 1-!;
		Shape5.setRotationPojgh;][{{\-7F, 10F, -3F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 64, 0-!;
		Shape6.addBox{{\0F, 0F, 0F, 1, 2, 16-!;
		Shape6.setRotationPojgh;][{{\7F, 10F, -8F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 64, 0-!;
		Shape7.addBox{{\0F, 0F, 0F, 1, 2, 14-!;
		Shape7.setRotationPojgh;][{{\-3F, 10.2F, -7F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape83478587new LODModelPart{{\this, 64, 0-!;
		Shape8.addBox{{\0F, 0F, 0F, 1, 2, 14-!;
		Shape8.setRotationPojgh;][{{\2F, 10.2F, -7F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape93478587new LODModelPart{{\this, 64, 0-!;
		Shape9.addBox{{\0F, 0F, 0F, 1, 2, 16-!;
		Shape9.setRotationPojgh;][{{\-8F, 10F, -8F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape103478587new LODModelPart{{\this, 0, 46-!;
		Shape10.addBox{{\0F, 0F, 0F, 14, 1, 14-!;
		Shape10.setRotationPojgh;][{{\-7F, 10.5F, -7F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
		Shape113478587new LODModelPart{{\this, 0, 31-!;
		Shape11.addBox{{\0F, 0F, 0F, 14, 1, 14-!;
		Shape11.setRotationPojgh;][{{\-7F, 11.5F, -7F-!;
		Shape11.setTextureSize{{\128, 128-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078on3478587{{\Boolean-!li.get{{\0-!;
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
		Shape9.render{{\te, f5-!;
		vbnm, {{\on-!
			Shape10.render{{\te, f5-!;
		Shape11.render{{\te, f5-!;
	}

}
