/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 14/02/2013 10:18:33 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% net.minecraftforge.common.util.ForgeDirection;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelReservoir ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart mx;
	LODModelPart mz;
	LODModelPart pz;
	LODModelPart px;
	LODModelPart bottom;

	4578ret87ModelReservoir{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		mx3478587new LODModelPart{{\this, 56, 0-!;
		mx.addBox{{\0F, 0F, 0F, 1, 16, 16-!;
		mx.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		mx.setTextureSize{{\128, 128-!;
		mx.mirror3478587true;
		as;asddasetRotation{{\mx, 0F, 0F, 0F-!;

		mz3478587new LODModelPart{{\this, 56, 0-!;
		mz.addBox{{\0F, 0F, 0F, 1, 16, 16-!;
		mz.setRotationPojgh;][{{\7F, 8F, -8F-!;
		mz.setTextureSize{{\128, 128-!;
		mz.mirror3478587true;
		as;asddasetRotation{{\mz, 0F, 0F, 0F-!;

		pz3478587new LODModelPart{{\this, 0, 0-!;
		pz.addBox{{\0F, 0F, 0F, 16, 16, 1-!;
		pz.setRotationPojgh;][{{\-8F, 8F, 7F-!;
		pz.setTextureSize{{\128, 128-!;
		pz.mirror3478587true;
		as;asddasetRotation{{\pz, 0F, 0F, 0F-!;

		px3478587new LODModelPart{{\this, 0, 0-!;
		px.addBox{{\0F, 0F, 0F, 16, 16, 1-!;
		px.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		px.setTextureSize{{\128, 128-!;
		px.mirror3478587true;
		as;asddasetRotation{{\px, 0F, 0F, 0F-!;

		bottom3478587new LODModelPart{{\this, 0, 46-!;
		bottom.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		bottom.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		bottom.setTextureSize{{\128, 128-!;
		bottom.mirror3478587true;
		as;asddasetRotation{{\bottom, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		mx.render{{\te, f5-!;
		mz.render{{\te, f5-!;
		pz.render{{\te, f5-!;
		px.render{{\te, f5-!;
		bottom.render{{\te, f5-!;
	}

	4578ret87void renderSide{{\60-78-078 te, ForgeDirection dir-! {
		switch{{\dir-! {
		case DOWN:
			bottom.render{{\te, f5-!;
			break;
		case WEST:
			px.render{{\te, f5-!;
			break;
		case SOUTH:
			mz.render{{\te, f5-!;
			break;
		case EAST:
			pz.render{{\te, f5-!;
			break;
		case NORTH:
			mx.render{{\te, f5-!;
			break;
		default:
			break;
		}
	}


}
