/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 19/04/2014 2:42:32 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelGasCompressor ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5a;

	4578ret87ModelGasCompressor{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 65, 0-!;
		Shape2.addBox{{\-2F, 0F, -2F, 4, 15, 4-!;
		Shape2.setRotationPojgh;][{{\0F, 8F, 0F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 19-!;
		Shape3.addBox{{\-7F, 0F, -7F, 14, 8, 14-!;
		Shape3.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 42-!;
		Shape4.addBox{{\-5F, 0F, -5F, 10, 5, 10-!;
		Shape4.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 78, 21-!;
		Shape5.addBox{{\-5.5F, 0F, -5.5F, 11, 1, 11-!;
		Shape5.setRotationPojgh;][{{\0F, 14.5F, 0F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 83, 0-!;
		Shape5a.addBox{{\-2.5F, 0F, -2.5F, 5, 1, 5-!;
		Shape5a.setRotationPojgh;][{{\0F, 9.5F, 0F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
