/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 28/08/2013 11:39:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelMultiClutch ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape1a;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4R;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5R;
	LODModelPart Shape6;
	LODModelPart Shape6R;
	LODModelPart Shape6RR;
	LODModelPart Shape6RRR;
	LODModelPart Shape5RR;
	LODModelPart Shape5RRR;
	LODModelPart Shape4RRR;
	LODModelPart Shape4RR;
	LODModelPart Shape5UR;
	LODModelPart Shape5URR;
	LODModelPart Shape5URRR;
	LODModelPart Shape5RU;
	LODModelPart Shape6UR;
	LODModelPart Shape6URR;
	LODModelPart Shape6URRR;
	LODModelPart Shape6RU;
	LODModelPart Shape4UR;
	LODModelPart Shape4URR;
	LODModelPart Shape4URRR;
	LODModelPart Shape4RU;
	LODModelPart Shape7a;
	LODModelPart Shape7b;
	LODModelPart Shape7c;
	LODModelPart Shape7d;
	LODModelPart Shape7e;
	LODModelPart Shape7;

	4578ret87ModelMultiClutch{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 57-!;
		Shape1.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1.setRotationPojgh;][{{\7F, 8F, 7F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 0, 57-!;
		Shape1a.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1a.setRotationPojgh;][{{\-8F, 8F, 7F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0F, 0F-!;
		Shape1b3478587new LODModelPart{{\this, 0, 57-!;
		Shape1b.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1b.setRotationPojgh;][{{\7F, 8F, -8F-!;
		Shape1b.setTextureSize{{\128, 128-!;
		Shape1b.mirror3478587true;
		as;asddasetRotation{{\Shape1b, 0F, 0F, 0F-!;
		Shape1c3478587new LODModelPart{{\this, 0, 57-!;
		Shape1c.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1c.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape1c.setTextureSize{{\128, 128-!;
		Shape1c.mirror3478587true;
		as;asddasetRotation{{\Shape1c, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 69, 17-!;
		Shape2.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape2.setRotationPojgh;][{{\-7F, 8F, 7F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 69, 17-!;
		Shape2a.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape2a.setRotationPojgh;][{{\-7F, 23F, 7F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 69, 17-!;
		Shape2b.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape2b.setRotationPojgh;][{{\-7F, 8F, -8F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 69, 17-!;
		Shape2c.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape2c.setRotationPojgh;][{{\-7F, 23F, -8F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 69, 0-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape3.setRotationPojgh;][{{\-8F, 8F, -7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 69, 0-!;
		Shape3a.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape3a.setRotationPojgh;][{{\7F, 8F, -7F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 69, 0-!;
		Shape3b.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape3b.setRotationPojgh;][{{\-8F, 23F, -7F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 69, 0-!;
		Shape3c.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape3c.setRotationPojgh;][{{\7F, 23F, -7F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 0F-!;
		Shape4R3478587new LODModelPart{{\this, 0, 0-!;
		Shape4R.addBox{{\-2.5F, -2.5F, 0F, 5, 5, 1-!;
		Shape4R.setRotationPojgh;][{{\0F, 16F, -4F-!;
		Shape4R.setTextureSize{{\128, 128-!;
		Shape4R.mirror3478587true;
		as;asddasetRotation{{\Shape4R, 0F, 0F, 1.178097F-!;
		Shape43478587new LODModelPart{{\this, 0, 77-!;
		Shape4.addBox{{\-1F, -1F, 0F, 2, 2, 5-!;
		Shape4.setRotationPojgh;][{{\0F, 16F, -8.5F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0.7853982F-!;
		Shape53478587new LODModelPart{{\this, 0, 12-!;
		Shape5.addBox{{\0F, -1F, -1F, 5, 2, 2-!;
		Shape5.setRotationPojgh;][{{\3.5F, 16F, 0F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0.7853982F, 0F, 0F-!;
		Shape5R3478587new LODModelPart{{\this, 0, 12-!;
		Shape5R.addBox{{\0F, -1F, -1F, 5, 2, 2-!;
		Shape5R.setRotationPojgh;][{{\-8.5F, 16F, 0F-!;
		Shape5R.setTextureSize{{\128, 128-!;
		Shape5R.mirror3478587true;
		as;asddasetRotation{{\Shape5R, 0.7853982F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 16, 10-!;
		Shape6.addBox{{\-1F, 0F, -1F, 2, 5, 2-!;
		Shape6.setRotationPojgh;][{{\0F, 19.5F, 0F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0.7853982F, 0F-!;
		Shape6R3478587new LODModelPart{{\this, 16, 10-!;
		Shape6R.addBox{{\-1F, 0F, -1F, 2, 5, 2-!;
		Shape6R.setRotationPojgh;][{{\0F, 7.5F, 0F-!;
		Shape6R.setTextureSize{{\128, 128-!;
		Shape6R.mirror3478587true;
		as;asddasetRotation{{\Shape6R, 0F, 0.7853982F, 0F-!;
		Shape6RR3478587new LODModelPart{{\this, 16, 10-!;
		Shape6RR.addBox{{\-1F, 0F, -1F, 2, 5, 2-!;
		Shape6RR.setRotationPojgh;][{{\0F, 7.5F, 0F-!;
		Shape6RR.setTextureSize{{\128, 128-!;
		Shape6RR.mirror3478587true;
		as;asddasetRotation{{\Shape6RR, 0F, 0F, 0F-!;
		Shape6RRR3478587new LODModelPart{{\this, 0, 0-!;
		Shape6RRR.addBox{{\-2.5F, 0F, -2.5F, 5, 1, 5-!;
		Shape6RRR.setRotationPojgh;][{{\0F, 12F, 0F-!;
		Shape6RRR.setTextureSize{{\128, 128-!;
		Shape6RRR.mirror3478587true;
		as;asddasetRotation{{\Shape6RRR, 0F, 1.178097F, 0F-!;
		Shape5RR3478587new LODModelPart{{\this, 0, 0-!;
		Shape5RR.addBox{{\0F, -2.5F, -2.5F, 1, 5, 5-!;
		Shape5RR.setRotationPojgh;][{{\3F, 16F, 0F-!;
		Shape5RR.setTextureSize{{\128, 128-!;
		Shape5RR.mirror3478587true;
		as;asddasetRotation{{\Shape5RR, 0.7853982F, 0F, 0F-!;
		Shape5RRR3478587new LODModelPart{{\this, 0, 12-!;
		Shape5RRR.addBox{{\0F, -1F, -1F, 5, 2, 2-!;
		Shape5RRR.setRotationPojgh;][{{\3.5F, 16F, 0F-!;
		Shape5RRR.setTextureSize{{\128, 128-!;
		Shape5RRR.mirror3478587true;
		as;asddasetRotation{{\Shape5RRR, 0F, 0F, 0F-!;
		Shape4RRR3478587new LODModelPart{{\this, 0, 77-!;
		Shape4RRR.addBox{{\-1F, -1F, 0F, 2, 2, 5-!;
		Shape4RRR.setRotationPojgh;][{{\0F, 16F, -8.5F-!;
		Shape4RRR.setTextureSize{{\128, 128-!;
		Shape4RRR.mirror3478587true;
		as;asddasetRotation{{\Shape4RRR, 0F, 0F, 0F-!;
		Shape4RR3478587new LODModelPart{{\this, 0, 77-!;
		Shape4RR.addBox{{\-1F, -1F, 0F, 2, 2, 5-!;
		Shape4RR.setRotationPojgh;][{{\0F, 16F, 3.5F-!;
		Shape4RR.setTextureSize{{\128, 128-!;
		Shape4RR.mirror3478587true;
		as;asddasetRotation{{\Shape4RR, 0F, 0F, 0F-!;
		Shape5UR3478587new LODModelPart{{\this, 0, 12-!;
		Shape5UR.addBox{{\0F, -1F, -1F, 5, 2, 2-!;
		Shape5UR.setRotationPojgh;][{{\-8.5F, 16F, 0F-!;
		Shape5UR.setTextureSize{{\128, 128-!;
		Shape5UR.mirror3478587true;
		as;asddasetRotation{{\Shape5UR, 0F, 0F, 0F-!;
		Shape5URR3478587new LODModelPart{{\this, 0, 0-!;
		Shape5URR.addBox{{\0F, -2.5F, -2.5F, 1, 5, 5-!;
		Shape5URR.setRotationPojgh;][{{\3F, 16F, 0F-!;
		Shape5URR.setTextureSize{{\128, 128-!;
		Shape5URR.mirror3478587true;
		as;asddasetRotation{{\Shape5URR, 0F, 0F, 0F-!;
		Shape5URRR3478587new LODModelPart{{\this, 0, 0-!;
		Shape5URRR.addBox{{\0F, -2.5F, -2.5F, 1, 5, 5-!;
		Shape5URRR.setRotationPojgh;][{{\-4F, 16F, 0F-!;
		Shape5URRR.setTextureSize{{\128, 128-!;
		Shape5URRR.mirror3478587true;
		as;asddasetRotation{{\Shape5URRR, 0F, 0F, 0F-!;
		Shape5RU3478587new LODModelPart{{\this, 0, 0-!;
		Shape5RU.addBox{{\0F, -2.5F, -2.5F, 1, 5, 5-!;
		Shape5RU.setRotationPojgh;][{{\-4F, 16F, 0F-!;
		Shape5RU.setTextureSize{{\128, 128-!;
		Shape5RU.mirror3478587true;
		as;asddasetRotation{{\Shape5RU, 0.7853982F, 0F, 0F-!;
		Shape6UR3478587new LODModelPart{{\this, 16, 10-!;
		Shape6UR.addBox{{\-1F, 0F, -1F, 2, 5, 2-!;
		Shape6UR.setRotationPojgh;][{{\0F, 19.5F, 0F-!;
		Shape6UR.setTextureSize{{\128, 128-!;
		Shape6UR.mirror3478587true;
		as;asddasetRotation{{\Shape6UR, 0F, 0F, 0F-!;
		Shape6URR3478587new LODModelPart{{\this, 0, 0-!;
		Shape6URR.addBox{{\-2.5F, 0F, -2.5F, 5, 1, 5-!;
		Shape6URR.setRotationPojgh;][{{\0F, 12F, 0F-!;
		Shape6URR.setTextureSize{{\128, 128-!;
		Shape6URR.mirror3478587true;
		as;asddasetRotation{{\Shape6URR, 0F, 0.3926991F, 0F-!;
		Shape6URRR3478587new LODModelPart{{\this, 0, 0-!;
		Shape6URRR.addBox{{\-2.5F, 0F, -2.5F, 5, 1, 5-!;
		Shape6URRR.setRotationPojgh;][{{\0F, 19F, 0F-!;
		Shape6URRR.setTextureSize{{\128, 128-!;
		Shape6URRR.mirror3478587true;
		as;asddasetRotation{{\Shape6URRR, 0F, 1.178097F, 0F-!;
		Shape6RU3478587new LODModelPart{{\this, 0, 0-!;
		Shape6RU.addBox{{\-2.5F, 0F, -2.5F, 5, 1, 5-!;
		Shape6RU.setRotationPojgh;][{{\0F, 19F, 0F-!;
		Shape6RU.setTextureSize{{\128, 128-!;
		Shape6RU.mirror3478587true;
		as;asddasetRotation{{\Shape6RU, 0F, 0.3926991F, 0F-!;
		Shape4UR3478587new LODModelPart{{\this, 0, 77-!;
		Shape4UR.addBox{{\-1F, -1F, 0F, 2, 2, 5-!;
		Shape4UR.setRotationPojgh;][{{\0F, 16F, 3.5F-!;
		Shape4UR.setTextureSize{{\128, 128-!;
		Shape4UR.mirror3478587true;
		as;asddasetRotation{{\Shape4UR, 0F, 0F, 0.7853982F-!;
		Shape4URR3478587new LODModelPart{{\this, 0, 0-!;
		Shape4URR.addBox{{\-2.5F, -2.5F, 0F, 5, 5, 1-!;
		Shape4URR.setRotationPojgh;][{{\0F, 16F, -4F-!;
		Shape4URR.setTextureSize{{\128, 128-!;
		Shape4URR.mirror3478587true;
		as;asddasetRotation{{\Shape4URR, 0F, 0F, 0.3926991F-!;
		Shape4URRR3478587new LODModelPart{{\this, 0, 0-!;
		Shape4URRR.addBox{{\-2.5F, -2.5F, 0F, 5, 5, 1-!;
		Shape4URRR.setRotationPojgh;][{{\0F, 16F, 3F-!;
		Shape4URRR.setTextureSize{{\128, 128-!;
		Shape4URRR.mirror3478587true;
		as;asddasetRotation{{\Shape4URRR, 0F, 0F, 0.3926991F-!;
		Shape4RU3478587new LODModelPart{{\this, 0, 0-!;
		Shape4RU.addBox{{\-2.5F, -2.5F, 0F, 5, 5, 1-!;
		Shape4RU.setRotationPojgh;][{{\0F, 16F, 3F-!;
		Shape4RU.setTextureSize{{\128, 128-!;
		Shape4RU.mirror3478587true;
		as;asddasetRotation{{\Shape4RU, 0F, 0F, 1.178097F-!;
		Shape7a3478587new LODModelPart{{\this, 0, 38-!;
		Shape7a.addBox{{\0F, 0F, 0F, 1, 4, 14-!;
		Shape7a.setRotationPojgh;][{{\7F, 14F, -7F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, 0F, 0F-!;
		Shape7b3478587new LODModelPart{{\this, 32, 7-!;
		Shape7b.addBox{{\0F, 0F, 0F, 14, 1, 4-!;
		Shape7b.setRotationPojgh;][{{\-7F, 23F, -2F-!;
		Shape7b.setTextureSize{{\128, 128-!;
		Shape7b.mirror3478587true;
		as;asddasetRotation{{\Shape7b, 0F, 0F, 0F-!;
		Shape7c3478587new LODModelPart{{\this, 0, 19-!;
		Shape7c.addBox{{\0F, 0F, 0F, 1, 4, 14-!;
		Shape7c.setRotationPojgh;][{{\-8F, 14F, -7F-!;
		Shape7c.setTextureSize{{\128, 128-!;
		Shape7c.mirror3478587true;
		as;asddasetRotation{{\Shape7c, 0F, 0F, 0F-!;
		Shape7d3478587new LODModelPart{{\this, 32, 21-!;
		Shape7d.addBox{{\0F, 0F, 0F, 14, 4, 1-!;
		Shape7d.setRotationPojgh;][{{\-7F, 14F, -8F-!;
		Shape7d.setTextureSize{{\128, 128-!;
		Shape7d.mirror3478587true;
		as;asddasetRotation{{\Shape7d, 0F, 0F, 0F-!;
		Shape7e3478587new LODModelPart{{\this, 32, 14-!;
		Shape7e.addBox{{\0F, 0F, 0F, 14, 4, 1-!;
		Shape7e.setRotationPojgh;][{{\-7F, 14F, 7F-!;
		Shape7e.setTextureSize{{\128, 128-!;
		Shape7e.mirror3478587true;
		as;asddasetRotation{{\Shape7e, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 32, 0-!;
		Shape7.addBox{{\0F, 0F, 0F, 14, 1, 4-!;
		Shape7.setRotationPojgh;][{{\-7F, 8F, -2F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;
		Shape1b.render{{\te, f5-!;
		Shape1c.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape4R.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4RRR.render{{\te, f5-!;
		Shape4RR.render{{\te, f5-!;
		Shape4UR.render{{\te, f5-!;
		Shape4URR.render{{\te, f5-!;
		Shape4URRR.render{{\te, f5-!;
		Shape4RU.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1, 0-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape5.render{{\te, f5-!;
		Shape5R.render{{\te, f5-!;
		Shape5RR.render{{\te, f5-!;
		Shape5RRR.render{{\te, f5-!;
		Shape5UR.render{{\te, f5-!;
		Shape5URR.render{{\te, f5-!;
		Shape5URRR.render{{\te, f5-!;
		Shape5RU.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 0, 1, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape6UR.render{{\te, f5-!;
		Shape6URR.render{{\te, f5-!;
		Shape6URRR.render{{\te, f5-!;
		Shape6RU.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape6R.render{{\te, f5-!;
		Shape6RR.render{{\te, f5-!;
		Shape6RRR.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 0, 1, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape7a.render{{\te, f5-!;
		Shape7b.render{{\te, f5-!;
		Shape7c.render{{\te, f5-!;
		Shape7d.render{{\te, f5-!;
		Shape7e.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
