/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 13/05/2013 11:58:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Engine;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelHydro ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape1a;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape3;
	LODModelPart Shape3d;

	4578ret87ModelHydro{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, -1F, -1F, 17, 2, 2-!;
		Shape1.setRotationPojgh;][{{\-8.5F, 16F, 0F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0.7853982F, 0F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 0, 0-!;
		Shape1a.addBox{{\0F, -1F, -1F, 17, 2, 2-!;
		Shape1a.setRotationPojgh;][{{\-8.5F, 16F, 0F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 34-!;
		Shape2.addBox{{\0F, -0.5F, -16F, 14, 1, 32-!;
		Shape2.setRotationPojgh;][{{\-7F, 16F, 0F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 1.570796F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 34-!;
		Shape2a.addBox{{\0F, -0.5F, -16F, 14, 1, 32-!;
		Shape2a.setRotationPojgh;][{{\-7F, 16F, 0F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 2.356194F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 34-!;
		Shape2b.addBox{{\0F, -0.5F, -16F, 14, 1, 32-!;
		Shape2b.setRotationPojgh;][{{\-7F, 16F, 0F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0.7853982F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 34-!;
		Shape2c.addBox{{\0F, -0.5F, -16F, 14, 1, 32-!;
		Shape2c.setRotationPojgh;][{{\-7F, 16F, 0F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 75, 0-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 16, 16-!;
		Shape3.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3d3478587new LODModelPart{{\this, 40, 0-!;
		Shape3d.addBox{{\0F, 0F, 0F, 1, 16, 16-!;
		Shape3d.setRotationPojgh;][{{\7F, 8F, -8F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078fail3478587{{\Boolean-!li.get{{\0-!;
		60-78-078bedrock3478587{{\Boolean-!li.get{{\1-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape1.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;

		60-78-078d34785870.1875;
		vbnm, {{\fail-!
			GL11.glTranslated{{\0, d, 0-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		vbnm, {{\fail-!
			GL11.glTranslated{{\0, -d, 0-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape3.render{{\te, f5-!;
		Shape3d.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f6-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
