/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 29/06/2015 6:15:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelChunkLoader ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape21;
	LODModelPart Shape3d;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape32d;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4d;
	LODModelPart Shape2d;
	LODModelPart Shape2c;
	LODModelPart Shape2b;
	LODModelPart Shape21d;
	LODModelPart Shape21c;
	LODModelPart Shape21b;
	LODModelPart Shape3;
	LODModelPart Shape31d;
	LODModelPart Shape32;
	LODModelPart Shape32b;
	LODModelPart Shape32c;
	LODModelPart Shape31;
	LODModelPart Shape31b;
	LODModelPart Shape31c;

	4578ret87ModelChunkLoader{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 3, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 21F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 20-!;
		Shape2.addBox{{\-1F, 0F, -1F, 2, 2, 2-!;
		Shape2.setRotationPojgh;][{{\0F, 19F, 0F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0.7853982F, 0F-!;
		Shape213478587new LODModelPart{{\this, 0, 20-!;
		Shape21.addBox{{\-1F, 0F, -1F, 2, 2, 2-!;
		Shape21.setRotationPojgh;][{{\0F, 19F, 0F-!;
		Shape21.setTextureSize{{\128, 128-!;
		Shape21.mirror3478587true;
		as;asddasetRotation{{\Shape21, 0F, 0F, 0F-!;
		Shape3d3478587new LODModelPart{{\this, 0, 26-!;
		Shape3d.addBox{{\-3F, 0F, -1F, 6, 1, 2-!;
		Shape3d.setRotationPojgh;][{{\0F, 10.5F, 0F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 65, 0-!;
		Shape4.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape4.setRotationPojgh;][{{\0F, 9F, 0F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 65, 0-!;
		Shape4a.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape4a.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		Shape4b3478587new LODModelPart{{\this, 65, 0-!;
		Shape4b.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape4b.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 0F, 0F, 0F-!;
		Shape32d3478587new LODModelPart{{\this, 24, 26-!;
		Shape32d.addBox{{\1F, 0F, -2F, 2, 1, 1-!;
		Shape32d.setRotationPojgh;][{{\0F, 10.5F, 0F-!;
		Shape32d.setTextureSize{{\128, 128-!;
		Shape32d.mirror3478587true;
		as;asddasetRotation{{\Shape32d, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 0, 34-!;
		Shape3b.addBox{{\-5F, 0F, -1F, 10, 1, 2-!;
		Shape3b.setRotationPojgh;][{{\0F, 16.5F, 0F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 0, 30-!;
		Shape3c.addBox{{\-4F, 0F, -1F, 8, 1, 2-!;
		Shape3c.setRotationPojgh;][{{\0F, 13.5F, 0F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 0F-!;
		Shape4d3478587new LODModelPart{{\this, 65, 0-!;
		Shape4d.addBox{{\-1.5F, 0F, -1.5F, 3, 1, 3-!;
		Shape4d.setRotationPojgh;][{{\0F, 12F, 0F-!;
		Shape4d.setTextureSize{{\128, 128-!;
		Shape4d.mirror3478587true;
		as;asddasetRotation{{\Shape4d, 0F, 0F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 0, 20-!;
		Shape2d.addBox{{\-1F, 0F, -1F, 2, 2, 2-!;
		Shape2d.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0.7853982F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 20-!;
		Shape2c.addBox{{\-1F, 0F, -1F, 2, 2, 2-!;
		Shape2c.setRotationPojgh;][{{\0F, 13F, 0F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0.7853982F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 20-!;
		Shape2b.addBox{{\-1F, 0F, -1F, 2, 2, 2-!;
		Shape2b.setRotationPojgh;][{{\0F, 16F, 0F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0.7853982F, 0F-!;
		Shape21d3478587new LODModelPart{{\this, 0, 20-!;
		Shape21d.addBox{{\-1F, 0F, -1F, 2, 2, 2-!;
		Shape21d.setRotationPojgh;][{{\0F, 10F, 0F-!;
		Shape21d.setTextureSize{{\128, 128-!;
		Shape21d.mirror3478587true;
		as;asddasetRotation{{\Shape21d, 0F, 0F, 0F-!;
		Shape21c3478587new LODModelPart{{\this, 0, 20-!;
		Shape21c.addBox{{\-1F, 0F, -1F, 2, 2, 2-!;
		Shape21c.setRotationPojgh;][{{\0F, 13F, 0F-!;
		Shape21c.setTextureSize{{\128, 128-!;
		Shape21c.mirror3478587true;
		as;asddasetRotation{{\Shape21c, 0F, 0F, 0F-!;
		Shape21b3478587new LODModelPart{{\this, 0, 20-!;
		Shape21b.addBox{{\-1F, 0F, -1F, 2, 2, 2-!;
		Shape21b.setRotationPojgh;][{{\0F, 16F, 0F-!;
		Shape21b.setTextureSize{{\128, 128-!;
		Shape21b.mirror3478587true;
		as;asddasetRotation{{\Shape21b, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 40-!;
		Shape3.addBox{{\-6F, 0F, -1F, 12, 1, 2-!;
		Shape3.setRotationPojgh;][{{\0F, 19.5F, 0F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape31d3478587new LODModelPart{{\this, 17, 26-!;
		Shape31d.addBox{{\-3F, 0F, 1F, 2, 1, 1-!;
		Shape31d.setRotationPojgh;][{{\0F, 10.5F, 0F-!;
		Shape31d.setTextureSize{{\128, 128-!;
		Shape31d.mirror3478587true;
		as;asddasetRotation{{\Shape31d, 0F, 0F, 0F-!;
		Shape323478587new LODModelPart{{\this, 42, 40-!;
		Shape32.addBox{{\4F, 0F, -5F, 2, 1, 4-!;
		Shape32.setRotationPojgh;][{{\0F, 19.5F, 0F-!;
		Shape32.setTextureSize{{\128, 128-!;
		Shape32.mirror3478587true;
		as;asddasetRotation{{\Shape32, 0F, 0F, 0F-!;
		Shape32b3478587new LODModelPart{{\this, 36, 34-!;
		Shape32b.addBox{{\3F, 0F, -4F, 2, 1, 3-!;
		Shape32b.setRotationPojgh;][{{\0F, 16.5F, 0F-!;
		Shape32b.setTextureSize{{\128, 128-!;
		Shape32b.mirror3478587true;
		as;asddasetRotation{{\Shape32b, 0F, 0F, 0F-!;
		Shape32c3478587new LODModelPart{{\this, 30, 30-!;
		Shape32c.addBox{{\2F, 0F, -3F, 2, 1, 2-!;
		Shape32c.setRotationPojgh;][{{\0F, 13.5F, 0F-!;
		Shape32c.setTextureSize{{\128, 128-!;
		Shape32c.mirror3478587true;
		as;asddasetRotation{{\Shape32c, 0F, 0F, 0F-!;
		Shape313478587new LODModelPart{{\this, 29, 40-!;
		Shape31.addBox{{\-6F, 0F, 1F, 2, 1, 4-!;
		Shape31.setRotationPojgh;][{{\0F, 19.5F, 0F-!;
		Shape31.setTextureSize{{\128, 128-!;
		Shape31.mirror3478587true;
		as;asddasetRotation{{\Shape31, 0F, 0F, 0F-!;
		Shape31b3478587new LODModelPart{{\this, 25, 34-!;
		Shape31b.addBox{{\-5F, 0F, 1F, 2, 1, 3-!;
		Shape31b.setRotationPojgh;][{{\0F, 16.5F, 0F-!;
		Shape31b.setTextureSize{{\128, 128-!;
		Shape31b.mirror3478587true;
		as;asddasetRotation{{\Shape31b, 0F, 0F, 0F-!;
		Shape31c3478587new LODModelPart{{\this, 21, 30-!;
		Shape31c.addBox{{\-4F, 0F, 1F, 2, 1, 2-!;
		Shape31c.setRotationPojgh;][{{\0F, 13.5F, 0F-!;
		Shape31c.setTextureSize{{\128, 128-!;
		Shape31c.mirror3478587true;
		as;asddasetRotation{{\Shape31c, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape21.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;
		Shape4d.render{{\te, f5-!;
		Shape2d.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape21d.render{{\te, f5-!;
		Shape21c.render{{\te, f5-!;
		Shape21b.render{{\te, f5-!;

		GL11.glPushMatrix{{\-!;
		GL11.glRotated{{\phi, 0, 1, 0-!;
		Shape3d.render{{\te, f5-!;
		Shape31d.render{{\te, f5-!;
		Shape32d.render{{\te, f5-!;

		GL11.glRotated{{\phi, 0, 1, 0-!;
		Shape3c.render{{\te, f5-!;
		Shape31c.render{{\te, f5-!;
		Shape32c.render{{\te, f5-!;

		GL11.glRotated{{\phi, 0, 1, 0-!;
		Shape3b.render{{\te, f5-!;
		Shape31b.render{{\te, f5-!;
		Shape32b.render{{\te, f5-!;

		GL11.glRotated{{\phi, 0, 1, 0-!;

		Shape3.render{{\te, f5-!;
		Shape31.render{{\te, f5-!;
		Shape32.render{{\te, f5-!;

		GL11.glPopMatrix{{\-!;
	}

	4578ret87void setRotation{{\LODModelPart model, float x, float y, float z-!
	{
		model.rotateAngleX3478587x;
		model.rotateAngleY3478587y;
		model.rotateAngleZ3478587z;
	}

}
