/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 20/02/2013 1:48:42 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;


4578ret87fhyuog ModelCompactor ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape3;
	LODModelPart Shape20;
	LODModelPart Shape21;
	LODModelPart Shape22;
	LODModelPart Shape23;
	LODModelPart Shape24;
	LODModelPart Shape25;
	LODModelPart Shape4;

	4578ret87ModelCompactor{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 100, 12-!;
		Shape2.addBox{{\0F, 0F, 0F, 5, 3, 1-!;
		Shape2.setRotationPojgh;][{{\-2.5F, 14.5F, -4F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 88-!;
		Shape5.addBox{{\0F, 0F, 0F, 4, 1, 2-!;
		Shape5.setRotationPojgh;][{{\-2F, 18F, -1F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 100, 16-!;
		Shape6.addBox{{\0F, 0F, 0F, 4, 2, 1-!;
		Shape6.setRotationPojgh;][{{\-2F, 15F, -3F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 84-!;
		Shape7.addBox{{\0F, 0F, 0F, 5, 1, 3-!;
		Shape7.setRotationPojgh;][{{\-2.5F, 19F, -1.5F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape83478587new LODModelPart{{\this, 100, 0-!;
		Shape8.addBox{{\0F, 0F, 0F, 8, 6, 1-!;
		Shape8.setRotationPojgh;][{{\-4F, 13F, -6F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape93478587new LODModelPart{{\this, 100, 16-!;
		Shape9.addBox{{\0F, 0F, 0F, 5, 2, 1-!;
		Shape9.setRotationPojgh;][{{\-3F, 15F, 2F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape103478587new LODModelPart{{\this, 100, 7-!;
		Shape10.addBox{{\0F, 0F, 0F, 6, 4, 1-!;
		Shape10.setRotationPojgh;][{{\-3F, 14F, -5F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
		Shape113478587new LODModelPart{{\this, 100, 12-!;
		Shape11.addBox{{\0F, 0F, 0F, 6, 3, 1-!;
		Shape11.setRotationPojgh;][{{\-3.5F, 14.5F, 3F-!;
		Shape11.setTextureSize{{\128, 128-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 100, 7-!;
		Shape12.addBox{{\0F, 0F, 0F, 6, 4, 1-!;
		Shape12.setRotationPojgh;][{{\-3F, 14F, 4F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 100, 0-!;
		Shape13.addBox{{\0F, 0F, 0F, 8, 6, 1-!;
		Shape13.setRotationPojgh;][{{\-4F, 13F, 5F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0F, 0F, 0F-!;
		Shape143478587new LODModelPart{{\this, 0, 72-!;
		Shape14.addBox{{\0F, 0F, 0F, 8, 1, 6-!;
		Shape14.setRotationPojgh;][{{\-4F, 21F, -3F-!;
		Shape14.setTextureSize{{\128, 128-!;
		Shape14.mirror3478587true;
		as;asddasetRotation{{\Shape14, 0F, 0F, 0F-!;
		Shape153478587new LODModelPart{{\this, 0, 88-!;
		Shape15.addBox{{\0F, 0F, 0F, 4, 1, 2-!;
		Shape15.setRotationPojgh;][{{\-2F, 13F, -1F-!;
		Shape15.setTextureSize{{\128, 128-!;
		Shape15.mirror3478587true;
		as;asddasetRotation{{\Shape15, 0F, 0F, 0F-!;
		Shape163478587new LODModelPart{{\this, 0, 79-!;
		Shape16.addBox{{\0F, 0F, 0F, 6, 1, 4-!;
		Shape16.setRotationPojgh;][{{\-3F, 20F, -2F-!;
		Shape16.setTextureSize{{\128, 128-!;
		Shape16.mirror3478587true;
		as;asddasetRotation{{\Shape16, 0F, 0F, 0F-!;
		Shape173478587new LODModelPart{{\this, 0, 84-!;
		Shape17.addBox{{\0F, 0F, 0F, 5, 1, 3-!;
		Shape17.setRotationPojgh;][{{\-2.5F, 12F, -1.5F-!;
		Shape17.setTextureSize{{\128, 128-!;
		Shape17.mirror3478587true;
		as;asddasetRotation{{\Shape17, 0F, 0F, 0F-!;
		Shape183478587new LODModelPart{{\this, 0, 79-!;
		Shape18.addBox{{\0F, 0F, 0F, 6, 1, 4-!;
		Shape18.setRotationPojgh;][{{\-3F, 11F, -2F-!;
		Shape18.setTextureSize{{\128, 128-!;
		Shape18.mirror3478587true;
		as;asddasetRotation{{\Shape18, 0F, 0F, 0F-!;
		Shape193478587new LODModelPart{{\this, 0, 72-!;
		Shape19.addBox{{\0F, 0F, 0F, 8, 1, 6-!;
		Shape19.setRotationPojgh;][{{\-4F, 10F, -3F-!;
		Shape19.setTextureSize{{\128, 128-!;
		Shape19.mirror3478587true;
		as;asddasetRotation{{\Shape19, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 46-!;
		Shape3.addBox{{\0F, 0F, 0F, 10, 12, 1-!;
		Shape3.setRotationPojgh;][{{\-5F, 11F, 7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape203478587new LODModelPart{{\this, 0, 18-!;
		Shape20.addBox{{\0F, 0F, 0F, 12, 1, 14-!;
		Shape20.setRotationPojgh;][{{\-6F, 22F, -7F-!;
		Shape20.setTextureSize{{\128, 128-!;
		Shape20.mirror3478587true;
		as;asddasetRotation{{\Shape20, 0F, 0F, 0F-!;
		Shape213478587new LODModelPart{{\this, 0, 59-!;
		Shape21.addBox{{\0F, 0F, 0F, 11, 1, 12-!;
		Shape21.setRotationPojgh;][{{\-5.5F, 8F, -6F-!;
		Shape21.setTextureSize{{\128, 128-!;
		Shape21.mirror3478587true;
		as;asddasetRotation{{\Shape21, 0F, 0F, 0F-!;
		Shape223478587new LODModelPart{{\this, 0, 46-!;
		Shape22.addBox{{\0F, 0F, 0F, 10, 12, 1-!;
		Shape22.setRotationPojgh;][{{\-5F, 11F, -8F-!;
		Shape22.setTextureSize{{\128, 128-!;
		Shape22.mirror3478587true;
		as;asddasetRotation{{\Shape22, 0F, 0F, 0F-!;
		Shape233478587new LODModelPart{{\this, 0, 33-!;
		Shape23.addBox{{\0F, 0F, 0F, 12, 12, 1-!;
		Shape23.setRotationPojgh;][{{\-6F, 10F, -7F-!;
		Shape23.setTextureSize{{\128, 128-!;
		Shape23.mirror3478587true;
		as;asddasetRotation{{\Shape23, 0F, 0F, 0F-!;
		Shape243478587new LODModelPart{{\this, 0, 33-!;
		Shape24.addBox{{\0F, 0F, 0F, 12, 12, 1-!;
		Shape24.setRotationPojgh;][{{\-6F, 10F, 6F-!;
		Shape24.setTextureSize{{\128, 128-!;
		Shape24.mirror3478587true;
		as;asddasetRotation{{\Shape24, 0F, 0F, 0F-!;
		Shape253478587new LODModelPart{{\this, 0, 18-!;
		Shape25.addBox{{\0F, 0F, 0F, 12, 1, 14-!;
		Shape25.setRotationPojgh;][{{\-6F, 9F, -7F-!;
		Shape25.setTextureSize{{\128, 128-!;
		Shape25.mirror3478587true;
		as;asddasetRotation{{\Shape25, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 64, 0-!;
		Shape4.addBox{{\0F, 0F, 0F, 2, 15, 16-!;
		Shape4.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		60-78-078d3478587phi/3D-0.36;
		GL11.glTranslated{{\0, 0, d-!;
		GL11.glScalef{{\1, 1, phi-!;
		Shape2.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
		Shape10.render{{\te, f5-!;
		GL11.glScalef{{\1, 1, 1F/phi-!;
		GL11.glTranslated{{\0, 0, -d-!;

		GL11.glTranslated{{\0, 0, -d-!;
		GL11.glScalef{{\1, 1, phi-!;
		Shape9.render{{\te, f5-!;
		Shape11.render{{\te, f5-!;
		Shape12.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;
		GL11.glScalef{{\1, 1, 1F/phi-!;
		GL11.glTranslated{{\0, 0, d-!;

		d34785871.38;

		GL11.glTranslated{{\0, d, 0-!;
		GL11.glScalef{{\1, phi, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
		Shape5.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape14.render{{\te, f5-!;
		Shape16.render{{\te, f5-!;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glScalef{{\1, 1F/phi, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;

		d34785870.62;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glScalef{{\1, phi, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
		Shape15.render{{\te, f5-!;
		Shape17.render{{\te, f5-!;
		Shape18.render{{\te, f5-!;
		Shape19.render{{\te, f5-!;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glScalef{{\1, 1F/phi, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;

		Shape20.render{{\te, f5-!;
		Shape21.render{{\te, f5-!;
		Shape22.render{{\te, f5-!;
		Shape23.render{{\te, f5-!;
		Shape24.render{{\te, f5-!;
		Shape25.render{{\te, f5-!;
	}

}
