/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 17/03/2013 12:30:05 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelBreeder ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;
	LODModelPart Shape5f;
	LODModelPart Shape5g;
	LODModelPart Shape5h;
	LODModelPart Shape5i;
	LODModelPart Shape6a;
	LODModelPart Shape6b;
	LODModelPart Shape6c;
	LODModelPart Shape6d;
	LODModelPart Shape6e;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape7b;
	LODModelPart Shape8;
	LODModelPart Shape8a;
	LODModelPart Shape8b;
	LODModelPart Shape8c;
	LODModelPart Shape4;

	4578ret87ModelBreeder{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 41-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 31, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 7, 16-!;
		Shape2.setRotationPojgh;][{{\-8F, 16F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 31, 0-!;
		Shape2a.addBox{{\0F, 0F, 0F, 1, 7, 16-!;
		Shape2a.setRotationPojgh;][{{\7F, 16F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 18-!;
		Shape3.addBox{{\0F, 0F, 0F, 14, 7, 1-!;
		Shape3.setRotationPojgh;][{{\-7F, 16F, 7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 18-!;
		Shape3a.addBox{{\0F, 0F, 0F, 14, 7, 1-!;
		Shape3a.setRotationPojgh;][{{\-7F, 16F, -8F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 0-!;
		Shape5.addBox{{\0F, 0F, 0F, 1, 1, 1-!;
		Shape5.setRotationPojgh;][{{\4F, 17F, 0F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 0-!;
		Shape5a.addBox{{\0F, 0F, 0F, 3, 1, 3-!;
		Shape5a.setRotationPojgh;][{{\-7F, 17F, 2F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, -0.1570796F, 0F, 0F-!;
		Shape5b3478587new LODModelPart{{\this, 0, 0-!;
		Shape5b.addBox{{\0F, 0F, 0F, 1, 1, 1-!;
		Shape5b.setRotationPojgh;][{{\-3F, 17F, -1F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, 0F, 0F, 0F-!;
		Shape5c3478587new LODModelPart{{\this, 0, 0-!;
		Shape5c.addBox{{\0F, 0F, 0F, 3, 1, 3-!;
		Shape5c.setRotationPojgh;][{{\-1F, 17F, -6F-!;
		Shape5c.setTextureSize{{\128, 128-!;
		Shape5c.mirror3478587true;
		as;asddasetRotation{{\Shape5c, 0F, 0.1396263F, 0.1570796F-!;
		Shape5d3478587new LODModelPart{{\this, 0, 0-!;
		Shape5d.addBox{{\0F, 0F, 0F, 1, 1, 1-!;
		Shape5d.setRotationPojgh;][{{\0F, 17F, 5F-!;
		Shape5d.setTextureSize{{\128, 128-!;
		Shape5d.mirror3478587true;
		as;asddasetRotation{{\Shape5d, -0.2617994F, 0F, 0.1745329F-!;
		Shape5e3478587new LODModelPart{{\this, 0, 0-!;
		Shape5e.addBox{{\0F, 0F, 0F, 1, 2, 1-!;
		Shape5e.setRotationPojgh;][{{\5F, 17F, -4F-!;
		Shape5e.setTextureSize{{\128, 128-!;
		Shape5e.mirror3478587true;
		as;asddasetRotation{{\Shape5e, -0.1489348F, -0.4363323F, -0.296706F-!;
		Shape5f3478587new LODModelPart{{\this, 0, 0-!;
		Shape5f.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape5f.setRotationPojgh;][{{\4F, 17F, 5F-!;
		Shape5f.setTextureSize{{\128, 128-!;
		Shape5f.mirror3478587true;
		as;asddasetRotation{{\Shape5f, 0F, 1.204277F, 0.3141593F-!;
		Shape5g3478587new LODModelPart{{\this, 0, 0-!;
		Shape5g.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape5g.setRotationPojgh;][{{\-5F, 17F, -5F-!;
		Shape5g.setTextureSize{{\128, 128-!;
		Shape5g.mirror3478587true;
		as;asddasetRotation{{\Shape5g, -0.2268928F, -0.2792527F, -0.1570796F-!;
		Shape5h3478587new LODModelPart{{\this, 0, 0-!;
		Shape5h.addBox{{\0F, 0F, 0F, 1, 1, 1-!;
		Shape5h.setRotationPojgh;][{{\-7F, 17F, -2F-!;
		Shape5h.setTextureSize{{\128, 128-!;
		Shape5h.mirror3478587true;
		as;asddasetRotation{{\Shape5h, 0F, 0F, 0F-!;
		Shape5i3478587new LODModelPart{{\this, 0, 0-!;
		Shape5i.addBox{{\0F, 0F, 0F, 2, 1, 2-!;
		Shape5i.setRotationPojgh;][{{\-1F, 17F, 0F-!;
		Shape5i.setTextureSize{{\128, 128-!;
		Shape5i.mirror3478587true;
		as;asddasetRotation{{\Shape5i, 0F, 0.3141593F, 0F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 4-!;
		Shape6a.addBox{{\0F, 0F, 0F, 3, 1, 1-!;
		Shape6a.setRotationPojgh;][{{\-4F, 17F, 5F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0.3839724F, 0.1570796F-!;
		Shape6b3478587new LODModelPart{{\this, 0, 4-!;
		Shape6b.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape6b.setRotationPojgh;][{{\3F, 17F, -3F-!;
		Shape6b.setTextureSize{{\128, 128-!;
		Shape6b.mirror3478587true;
		as;asddasetRotation{{\Shape6b, 0F, 1.169371F, 0.1919862F-!;
		Shape6c3478587new LODModelPart{{\this, 0, 4-!;
		Shape6c.addBox{{\0F, 0F, 0F, 9, 1, 1-!;
		Shape6c.setRotationPojgh;][{{\-2F, 17.2F, 4F-!;
		Shape6c.setTextureSize{{\128, 128-!;
		Shape6c.mirror3478587true;
		as;asddasetRotation{{\Shape6c, 0F, 1.745329F, 0F-!;
		Shape6d3478587new LODModelPart{{\this, 0, 4-!;
		Shape6d.addBox{{\0F, 0F, 0F, 7, 1, 1-!;
		Shape6d.setRotationPojgh;][{{\-2F, 17F, 1F-!;
		Shape6d.setTextureSize{{\128, 128-!;
		Shape6d.mirror3478587true;
		as;asddasetRotation{{\Shape6d, 0F, -0.6108652F, 0F-!;
		Shape6e3478587new LODModelPart{{\this, 0, 4-!;
		Shape6e.addBox{{\0F, 0F, 0F, 11, 2, 1-!;
		Shape6e.setRotationPojgh;][{{\-5F, 17F, -2F-!;
		Shape6e.setTextureSize{{\128, 128-!;
		Shape6e.mirror3478587true;
		as;asddasetRotation{{\Shape6e, 0.122173F, 0F, 0.0349066F-!;
		Shape73478587new LODModelPart{{\this, 0, 6-!;
		Shape7.addBox{{\0F, 0F, 0F, 3, 1, 4-!;
		Shape7.setRotationPojgh;][{{\-4F, 17.5F, -7F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, -0.2617994F, 0F-!;
		Shape7a3478587new LODModelPart{{\this, 0, 6-!;
		Shape7a.addBox{{\0F, 0F, 0F, 3, 1, 4-!;
		Shape7a.setRotationPojgh;][{{\-2F, 17.5F, 1F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, -1.343904F, 0F-!;
		Shape7b3478587new LODModelPart{{\this, 0, 6-!;
		Shape7b.addBox{{\0F, 0F, 0F, 3, 1, 4-!;
		Shape7b.setRotationPojgh;][{{\0F, 17.5F, 0F-!;
		Shape7b.setTextureSize{{\128, 128-!;
		Shape7b.mirror3478587true;
		as;asddasetRotation{{\Shape7b, 0F, 0.4886922F, 0F-!;
		Shape83478587new LODModelPart{{\this, 0, 11-!;
		Shape8.addBox{{\0F, 0F, 0F, 1, 2, 3-!;
		Shape8.setRotationPojgh;][{{\5F, 16.5F, 1F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, -0.0872665F, -0.7853982F, 0.3316126F-!;
		Shape8a3478587new LODModelPart{{\this, 0, 11-!;
		Shape8a.addBox{{\0F, 0F, 0F, 1, 2, 3-!;
		Shape8a.setRotationPojgh;][{{\1F, 16.5F, -4F-!;
		Shape8a.setTextureSize{{\128, 128-!;
		Shape8a.mirror3478587true;
		as;asddasetRotation{{\Shape8a, -0.0349066F, -1.099557F, -0.2792527F-!;
		Shape8b3478587new LODModelPart{{\this, 0, 11-!;
		Shape8b.addBox{{\0F, 0F, 0F, 1, 2, 3-!;
		Shape8b.setRotationPojgh;][{{\-5F, 16.8F, 6F-!;
		Shape8b.setTextureSize{{\128, 128-!;
		Shape8b.mirror3478587true;
		as;asddasetRotation{{\Shape8b, 0F, 1.43117F, 0F-!;
		Shape8c3478587new LODModelPart{{\this, 0, 11-!;
		Shape8c.addBox{{\0F, 0F, 0F, 1, 2, 3-!;
		Shape8c.setRotationPojgh;][{{\-6F, 16.5F, -2F-!;
		Shape8c.setTextureSize{{\128, 128-!;
		Shape8c.mirror3478587true;
		as;asddasetRotation{{\Shape8c, 0F, 0.3490659F, -0.2094395F-!;
		Shape43478587new LODModelPart{{\this, 0, 26-!;
		Shape4.addBox{{\0F, 0F, 0F, 14, 1, 14-!;
		Shape4.setRotationPojgh;][{{\-7F, 18F, -7F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078wheat3478587{{\Boolean-!li.get{{\0-!;
		60-78-078carrots3478587{{\Boolean-!li.get{{\1-!;
		60-78-078meat3478587{{\Boolean-!li.get{{\2-!;
		60-78-078fish3478587{{\Boolean-!li.get{{\3-!;
		60-78-078greens3478587{{\Boolean-!li.get{{\4-!;
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		vbnm, {{\carrots-! {
			Shape5.render{{\te, f5-!;
			Shape5a.render{{\te, f5-!;
			Shape5b.render{{\te, f5-!;
			Shape5c	.render{{\te, f5-!;
			Shape5d.render{{\te, f5-!;
			Shape5e.render{{\te, f5-!;
			Shape5f.render{{\te, f5-!;
			Shape5g.render{{\te, f5-!;
			Shape5h.render{{\te, f5-!;
			Shape5i.render{{\te, f5-!;
		}
		vbnm, {{\greens-! {
			Shape6a.render{{\te, f5-!;
			Shape6b.render{{\te, f5-!;
			Shape6c.render{{\te, f5-!;
			Shape6d.render{{\te, f5-!;
			Shape6e.render{{\te, f5-!;
		}
		vbnm, {{\meat-! {
			Shape7.render{{\te, f5-!;
			Shape7a.render{{\te, f5-!;
			Shape7b.render{{\te, f5-!;
		}
		vbnm, {{\fish-! {
			Shape8.render{{\te, f5-!;
			Shape8a.render{{\te, f5-!;
			Shape8b.render{{\te, f5-!;
			Shape8c.render{{\te, f5-!;
		}
		vbnm, {{\wheat-!
			Shape4.render{{\te, f5-!;
	}
}
