/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 14/11/2013 4:02:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelBelt ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shaape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart s1;
	LODModelPart s2;
	LODModelPart w;
	LODModelPart w4;
	LODModelPart w1;
	LODModelPart w2;
	LODModelPart w3;
	LODModelPart w5;
	LODModelPart w6;
	LODModelPart w7;
	LODModelPart c;
	LODModelPart w8;
	LODModelPart w9;
	LODModelPart w10;
	LODModelPart w11;
	LODModelPart w12;
	LODModelPart w13;
	LODModelPart w14;
	LODModelPart w15;
	LODModelPart c1;
	LODModelPart c2;
	LODModelPart c3;

	4578ret87ModelBelt{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 8-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 14, 5-!;
		Shape1.setRotationPojgh;][{{\-8F, 9F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shaape13478587new LODModelPart{{\this, 0, 8-!;
		Shaape1.addBox{{\0F, 0F, 0F, 16, 14, 5-!;
		Shaape1.setRotationPojgh;][{{\-8F, 9F, 3F-!;
		Shaape1.setTextureSize{{\128, 128-!;
		Shaape1.mirror3478587true;
		as;asddasetRotation{{\Shaape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 14, 1, 5-!;
		Shape2.setRotationPojgh;][{{\-7F, 8F, 3F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 0-!;
		Shape2a.addBox{{\0F, 0F, 0F, 14, 1, 5-!;
		Shape2a.setRotationPojgh;][{{\-7F, 8F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 0-!;
		Shape2b.addBox{{\0F, 0F, 0F, 14, 1, 5-!;
		Shape2b.setRotationPojgh;][{{\-7F, 23F, -8F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 0-!;
		Shape2c.addBox{{\0F, 0F, 0F, 14, 1, 5-!;
		Shape2c.setRotationPojgh;][{{\-7F, 23F, 3F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		s13478587new LODModelPart{{\this, 43, 0-!;
		s1.addBox{{\-1F, -1F, 0F, 2, 2, 17-!;
		s1.setRotationPojgh;][{{\0F, 16F, -8.5F-!;
		s1.setTextureSize{{\128, 128-!;
		s1.mirror3478587true;
		as;asddasetRotation{{\s1, 0F, 0F, 0.7853982F-!;
		s23478587new LODModelPart{{\this, 43, 0-!;
		s2.addBox{{\-1F, -1F, 0F, 2, 2, 17-!;
		s2.setRotationPojgh;][{{\0F, 16F, -8.5F-!;
		s2.setTextureSize{{\128, 128-!;
		s2.mirror3478587true;
		as;asddasetRotation{{\s2, 0F, 0F, 0F-!;
		w3478587new LODModelPart{{\this, 0, 28-!;
		w.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w.setRotationPojgh;][{{\0F, 16F, 2F-!;
		w.setTextureSize{{\128, 128-!;
		w.mirror3478587true;
		as;asddasetRotation{{\w, 0F, 0F, 0F-!;
		w43478587new LODModelPart{{\this, 0, 28-!;
		w4.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w4.setRotationPojgh;][{{\0F, 16F, 2F-!;
		w4.setTextureSize{{\128, 128-!;
		w4.mirror3478587true;
		as;asddasetRotation{{\w4, 0F, 0F, 0.7853982F-!;
		w13478587new LODModelPart{{\this, 0, 28-!;
		w1.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w1.setRotationPojgh;][{{\0F, 16F, 2F-!;
		w1.setTextureSize{{\128, 128-!;
		w1.mirror3478587true;
		as;asddasetRotation{{\w1, 0F, 0F, 1.178097F-!;
		w23478587new LODModelPart{{\this, 0, 28-!;
		w2.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w2.setRotationPojgh;][{{\0F, 16F, 2F-!;
		w2.setTextureSize{{\128, 128-!;
		w2.mirror3478587true;
		as;asddasetRotation{{\w2, 0F, 0F, 1.374447F-!;
		w33478587new LODModelPart{{\this, 0, 28-!;
		w3.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w3.setRotationPojgh;][{{\0F, 16F, 2F-!;
		w3.setTextureSize{{\128, 128-!;
		w3.mirror3478587true;
		as;asddasetRotation{{\w3, 0F, 0F, 0.3926991F-!;
		w53478587new LODModelPart{{\this, 0, 28-!;
		w5.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w5.setRotationPojgh;][{{\0F, 16F, 2F-!;
		w5.setTextureSize{{\128, 128-!;
		w5.mirror3478587true;
		as;asddasetRotation{{\w5, 0F, 0F, 0.1963495F-!;
		w63478587new LODModelPart{{\this, 0, 28-!;
		w6.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w6.setRotationPojgh;][{{\0F, 16F, 2F-!;
		w6.setTextureSize{{\128, 128-!;
		w6.mirror3478587true;
		as;asddasetRotation{{\w6, 0F, 0F, 0.5890486F-!;
		w73478587new LODModelPart{{\this, 0, 28-!;
		w7.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w7.setRotationPojgh;][{{\0F, 16F, 2F-!;
		w7.setTextureSize{{\128, 128-!;
		w7.mirror3478587true;
		as;asddasetRotation{{\w7, 0F, 0F, 0.9817477F-!;
		c3478587new LODModelPart{{\this, 0, 43-!;
		c.addBox{{\-4F, -4F, 0F, 8, 8, 4-!;
		c.setRotationPojgh;][{{\0F, 16F, -2F-!;
		c.setTextureSize{{\128, 128-!;
		c.mirror3478587true;
		as;asddasetRotation{{\c, 0F, 0F, 0.7853982F-!;
		w83478587new LODModelPart{{\this, 0, 28-!;
		w8.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w8.setRotationPojgh;][{{\0F, 16F, -3F-!;
		w8.setTextureSize{{\128, 128-!;
		w8.mirror3478587true;
		as;asddasetRotation{{\w8, 0F, 0F, 1.374447F-!;
		w93478587new LODModelPart{{\this, 0, 28-!;
		w9.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w9.setRotationPojgh;][{{\0F, 16F, -3F-!;
		w9.setTextureSize{{\128, 128-!;
		w9.mirror3478587true;
		as;asddasetRotation{{\w9, 0F, 0F, 1.178097F-!;
		w103478587new LODModelPart{{\this, 0, 28-!;
		w10.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w10.setRotationPojgh;][{{\0F, 16F, -3F-!;
		w10.setTextureSize{{\128, 128-!;
		w10.mirror3478587true;
		as;asddasetRotation{{\w10, 0F, 0F, 0.9817477F-!;
		w113478587new LODModelPart{{\this, 0, 28-!;
		w11.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w11.setRotationPojgh;][{{\0F, 16F, -3F-!;
		w11.setTextureSize{{\128, 128-!;
		w11.mirror3478587true;
		as;asddasetRotation{{\w11, 0F, 0F, 0.7853982F-!;
		w123478587new LODModelPart{{\this, 0, 28-!;
		w12.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w12.setRotationPojgh;][{{\0F, 16F, -3F-!;
		w12.setTextureSize{{\128, 128-!;
		w12.mirror3478587true;
		as;asddasetRotation{{\w12, 0F, 0F, 0.5890486F-!;
		w133478587new LODModelPart{{\this, 0, 28-!;
		w13.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w13.setRotationPojgh;][{{\0F, 16F, -3F-!;
		w13.setTextureSize{{\128, 128-!;
		w13.mirror3478587true;
		as;asddasetRotation{{\w13, 0F, 0F, 0.3926991F-!;
		w143478587new LODModelPart{{\this, 0, 28-!;
		w14.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w14.setRotationPojgh;][{{\0F, 16F, -3F-!;
		w14.setTextureSize{{\128, 128-!;
		w14.mirror3478587true;
		as;asddasetRotation{{\w14, 0F, 0F, 0.1963495F-!;
		w153478587new LODModelPart{{\this, 0, 28-!;
		w15.addBox{{\-6F, -6F, 0F, 12, 12, 1-!;
		w15.setRotationPojgh;][{{\0F, 16F, -3F-!;
		w15.setTextureSize{{\128, 128-!;
		w15.mirror3478587true;
		as;asddasetRotation{{\w15, 0F, 0F, 0F-!;
		c13478587new LODModelPart{{\this, 0, 43-!;
		c1.addBox{{\-4F, -4F, 0F, 8, 8, 4-!;
		c1.setRotationPojgh;][{{\0F, 16F, -2F-!;
		c1.setTextureSize{{\128, 128-!;
		c1.mirror3478587true;
		as;asddasetRotation{{\c1, 0F, 0F, 0F-!;
		c23478587new LODModelPart{{\this, 0, 43-!;
		c2.addBox{{\-4F, -4F, 0F, 8, 8, 4-!;
		c2.setRotationPojgh;][{{\0F, 16F, -2F-!;
		c2.setTextureSize{{\128, 128-!;
		c2.mirror3478587true;
		as;asddasetRotation{{\c2, 0F, 0F, 0.3926991F-!;
		c33478587new LODModelPart{{\this, 0, 43-!;
		c3.addBox{{\-4F, -4F, 0F, 8, 8, 4-!;
		c3.setRotationPojgh;][{{\0F, 16F, -2F-!;
		c3.setTextureSize{{\128, 128-!;
		c3.mirror3478587true;
		as;asddasetRotation{{\c3, 0F, 0F, 1.178097F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shaape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;

		60-78-078d34785871;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;

		s1.render{{\te, f5-!;
		s2.render{{\te, f5-!;
		w.render{{\te, f5-!;
		w4.render{{\te, f5-!;
		w1.render{{\te, f5-!;
		w2.render{{\te, f5-!;
		w3.render{{\te, f5-!;
		w5.render{{\te, f5-!;
		w6.render{{\te, f5-!;
		w7.render{{\te, f5-!;
		c.render{{\te, f5-!;
		w8.render{{\te, f5-!;
		w9.render{{\te, f5-!;
		w10.render{{\te, f5-!;
		w11.render{{\te, f5-!;
		w12.render{{\te, f5-!;
		w13.render{{\te, f5-!;
		w14.render{{\te, f5-!;
		w15.render{{\te, f5-!;
		c1.render{{\te, f5-!;
		c2.render{{\te, f5-!;
		c3.render{{\te, f5-!;

		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
