/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 15/03/2013 12:54:13 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelHeater ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;
	LODModelPart Shape5f;
	LODModelPart Shape5g;
	LODModelPart Shape5h;
	LODModelPart Shape5i;
	LODModelPart Shape5j;
	LODModelPart Shape5k;
	LODModelPart Shape5l;
	LODModelPart Shape5m;
	LODModelPart Shape5n;
	LODModelPart Shape5o;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape7b;
	LODModelPart Shape7c;
	LODModelPart Shape7d;
	LODModelPart Shape7e;
	LODModelPart Shape7f;
	LODModelPart Shape7g;
	LODModelPart Shape7h;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6b;

	4578ret87ModelHeater{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 30, 25-!;
		Shape2.addBox{{\0F, 0F, 0F, 16, 7, 1-!;
		Shape2.setRotationPojgh;][{{\-8F, 16F, 7F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 30, 17-!;
		Shape2a.addBox{{\0F, 0F, 0F, 16, 7, 1-!;
		Shape2a.setRotationPojgh;][{{\-8F, 16F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 17-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 7, 14-!;
		Shape3.setRotationPojgh;][{{\-8F, 16F, -7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 38-!;
		Shape3a.addBox{{\0F, 0F, 0F, 1, 7, 14-!;
		Shape3a.setRotationPojgh;][{{\7F, 16F, -7F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 64, 0-!;
		Shape4.addBox{{\0F, 0F, 0F, 14, 1, 14-!;
		Shape4.setRotationPojgh;][{{\-7F, 22F, -7F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 59-!;
		Shape5.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5.setRotationPojgh;][{{\-5.5F, 18F, -2.5F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 59-!;
		Shape5a.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5a.setRotationPojgh;][{{\-5.5F, 18F, 3.5F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape5b3478587new LODModelPart{{\this, 0, 59-!;
		Shape5b.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5b.setRotationPojgh;][{{\-2.5F, 18F, -2.5F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, 0F, 0F, 0F-!;
		Shape5c3478587new LODModelPart{{\this, 0, 59-!;
		Shape5c.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5c.setRotationPojgh;][{{\-5.5F, 18F, 0.5F-!;
		Shape5c.setTextureSize{{\128, 128-!;
		Shape5c.mirror3478587true;
		as;asddasetRotation{{\Shape5c, 0F, 0F, 0F-!;
		Shape5d3478587new LODModelPart{{\this, 0, 59-!;
		Shape5d.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5d.setRotationPojgh;][{{\3.5F, 18F, -2.5F-!;
		Shape5d.setTextureSize{{\128, 128-!;
		Shape5d.mirror3478587true;
		as;asddasetRotation{{\Shape5d, 0F, 0F, 0F-!;
		Shape5e3478587new LODModelPart{{\this, 0, 59-!;
		Shape5e.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5e.setRotationPojgh;][{{\0.5F, 18F, -2.5F-!;
		Shape5e.setTextureSize{{\128, 128-!;
		Shape5e.mirror3478587true;
		as;asddasetRotation{{\Shape5e, 0F, 0F, 0F-!;
		Shape5f3478587new LODModelPart{{\this, 0, 59-!;
		Shape5f.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5f.setRotationPojgh;][{{\-5.5F, 18F, -5.5F-!;
		Shape5f.setTextureSize{{\128, 128-!;
		Shape5f.mirror3478587true;
		as;asddasetRotation{{\Shape5f, 0F, 0F, 0F-!;
		Shape5g3478587new LODModelPart{{\this, 0, 59-!;
		Shape5g.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5g.setRotationPojgh;][{{\3.5F, 18F, 3.5F-!;
		Shape5g.setTextureSize{{\128, 128-!;
		Shape5g.mirror3478587true;
		as;asddasetRotation{{\Shape5g, 0F, 0F, 0F-!;
		Shape5h3478587new LODModelPart{{\this, 0, 59-!;
		Shape5h.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5h.setRotationPojgh;][{{\3.5F, 18F, 0.5F-!;
		Shape5h.setTextureSize{{\128, 128-!;
		Shape5h.mirror3478587true;
		as;asddasetRotation{{\Shape5h, 0F, 0F, 0F-!;
		Shape5i3478587new LODModelPart{{\this, 0, 59-!;
		Shape5i.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5i.setRotationPojgh;][{{\3.5F, 18F, -5.5F-!;
		Shape5i.setTextureSize{{\128, 128-!;
		Shape5i.mirror3478587true;
		as;asddasetRotation{{\Shape5i, 0F, 0F, 0F-!;
		Shape5j3478587new LODModelPart{{\this, 0, 59-!;
		Shape5j.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5j.setRotationPojgh;][{{\0.5F, 18F, 3.5F-!;
		Shape5j.setTextureSize{{\128, 128-!;
		Shape5j.mirror3478587true;
		as;asddasetRotation{{\Shape5j, 0F, 0F, 0F-!;
		Shape5k3478587new LODModelPart{{\this, 0, 59-!;
		Shape5k.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5k.setRotationPojgh;][{{\0.5F, 18F, 0.5F-!;
		Shape5k.setTextureSize{{\128, 128-!;
		Shape5k.mirror3478587true;
		as;asddasetRotation{{\Shape5k, 0F, 0F, 0F-!;
		Shape5l3478587new LODModelPart{{\this, 0, 59-!;
		Shape5l.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5l.setRotationPojgh;][{{\0.5F, 18F, -5.5F-!;
		Shape5l.setTextureSize{{\128, 128-!;
		Shape5l.mirror3478587true;
		as;asddasetRotation{{\Shape5l, 0F, 0F, 0F-!;
		Shape5m3478587new LODModelPart{{\this, 0, 59-!;
		Shape5m.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5m.setRotationPojgh;][{{\-2.5F, 18F, 3.5F-!;
		Shape5m.setTextureSize{{\128, 128-!;
		Shape5m.mirror3478587true;
		as;asddasetRotation{{\Shape5m, 0F, 0F, 0F-!;
		Shape5n3478587new LODModelPart{{\this, 0, 59-!;
		Shape5n.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5n.setRotationPojgh;][{{\-2.5F, 18F, 0.5F-!;
		Shape5n.setTextureSize{{\128, 128-!;
		Shape5n.mirror3478587true;
		as;asddasetRotation{{\Shape5n, 0F, 0F, 0F-!;
		Shape5o3478587new LODModelPart{{\this, 0, 59-!;
		Shape5o.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape5o.setRotationPojgh;][{{\-2.5F, 18F, -5.5F-!;
		Shape5o.setTextureSize{{\128, 128-!;
		Shape5o.mirror3478587true;
		as;asddasetRotation{{\Shape5o, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 65-!;
		Shape7.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7.setRotationPojgh;][{{\4F, 16.2F, -7F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape7a3478587new LODModelPart{{\this, 0, 65-!;
		Shape7a.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7a.setRotationPojgh;][{{\-3.5F, 16.2F, -7F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, 0F, 0F-!;
		Shape7b3478587new LODModelPart{{\this, 0, 65-!;
		Shape7b.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7b.setRotationPojgh;][{{\1F, 16.2F, -7F-!;
		Shape7b.setTextureSize{{\128, 128-!;
		Shape7b.mirror3478587true;
		as;asddasetRotation{{\Shape7b, 0F, 0F, 0F-!;
		Shape7c3478587new LODModelPart{{\this, 0, 65-!;
		Shape7c.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7c.setRotationPojgh;][{{\-5F, 16.2F, -7F-!;
		Shape7c.setTextureSize{{\128, 128-!;
		Shape7c.mirror3478587true;
		as;asddasetRotation{{\Shape7c, 0F, 0F, 0F-!;
		Shape7d3478587new LODModelPart{{\this, 0, 65-!;
		Shape7d.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7d.setRotationPojgh;][{{\-6.5F, 16.2F, -7F-!;
		Shape7d.setTextureSize{{\128, 128-!;
		Shape7d.mirror3478587true;
		as;asddasetRotation{{\Shape7d, 0F, 0F, 0F-!;
		Shape7e3478587new LODModelPart{{\this, 0, 65-!;
		Shape7e.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7e.setRotationPojgh;][{{\5.5F, 16.2F, -7F-!;
		Shape7e.setTextureSize{{\128, 128-!;
		Shape7e.mirror3478587true;
		as;asddasetRotation{{\Shape7e, 0F, 0F, 0F-!;
		Shape7f3478587new LODModelPart{{\this, 0, 65-!;
		Shape7f.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7f.setRotationPojgh;][{{\2.5F, 16.2F, -7F-!;
		Shape7f.setTextureSize{{\128, 128-!;
		Shape7f.mirror3478587true;
		as;asddasetRotation{{\Shape7f, 0F, 0F, 0F-!;
		Shape7g3478587new LODModelPart{{\this, 0, 65-!;
		Shape7g.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7g.setRotationPojgh;][{{\-2F, 16.2F, -7F-!;
		Shape7g.setTextureSize{{\128, 128-!;
		Shape7g.mirror3478587true;
		as;asddasetRotation{{\Shape7g, 0F, 0F, 0F-!;
		Shape7h3478587new LODModelPart{{\this, 0, 65-!;
		Shape7h.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape7h.setRotationPojgh;][{{\-0.5F, 16.2F, -7F-!;
		Shape7h.setTextureSize{{\128, 128-!;
		Shape7h.mirror3478587true;
		as;asddasetRotation{{\Shape7h, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 80-!;
		Shape6.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape6.setRotationPojgh;][{{\-7F, 16.3F, -4F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 80-!;
		Shape6a.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape6a.setRotationPojgh;][{{\-7F, 16.3F, -0.5F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0F-!;
		Shape6b3478587new LODModelPart{{\this, 0, 80-!;
		Shape6b.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape6b.setRotationPojgh;][{{\-7F, 16.3F, 3F-!;
		Shape6b.setTextureSize{{\128, 128-!;
		Shape6b.mirror3478587true;
		as;asddasetRotation{{\Shape6b, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape5b.render{{\te, f5-!;
		Shape5c.render{{\te, f5-!;
		Shape5d.render{{\te, f5-!;
		Shape5e.render{{\te, f5-!;
		Shape5f.render{{\te, f5-!;
		Shape5g.render{{\te, f5-!;
		Shape5h.render{{\te, f5-!;
		Shape5i.render{{\te, f5-!;
		Shape5j.render{{\te, f5-!;
		Shape5k.render{{\te, f5-!;
		Shape5l.render{{\te, f5-!;
		Shape5m.render{{\te, f5-!;
		Shape5n.render{{\te, f5-!;
		Shape5o.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape7a.render{{\te, f5-!;
		Shape7b.render{{\te, f5-!;
		Shape7c.render{{\te, f5-!;
		Shape7d.render{{\te, f5-!;
		Shape7e.render{{\te, f5-!;
		Shape7f.render{{\te, f5-!;
		Shape7g.render{{\te, f5-!;
		Shape7h.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape6b.render{{\te, f5-!;
	}

}
