/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 19/04/2014 2:05:46 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelComposter ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape6;

	4578ret87ModelComposter{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 19-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 4, 16-!;
		Shape2.setRotationPojgh;][{{\7F, 19F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 65, 0-!;
		Shape2a.addBox{{\0F, 0F, 0F, 1, 4, 16-!;
		Shape2a.setRotationPojgh;][{{\-8F, 19F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 46-!;
		Shape3.addBox{{\0F, 0F, 0F, 14, 4, 1-!;
		Shape3.setRotationPojgh;][{{\-7F, 19F, 7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 40-!;
		Shape3a.addBox{{\0F, 0F, 0F, 14, 4, 1-!;
		Shape3a.setRotationPojgh;][{{\-7F, 19F, -8F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 63-!;
		Shape4.addBox{{\0F, -8F, -1F, 16, 8, 1-!;
		Shape4.setRotationPojgh;][{{\-8F, 19F, 8F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0.5235988F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 0, 53-!;
		Shape4a.addBox{{\0F, -8F, 0F, 16, 8, 1-!;
		Shape4a.setRotationPojgh;][{{\-8F, 19F, -8F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, -0.5235988F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 98-!;
		Shape5.addBox{{\-1F, -8F, 0F, 1, 8, 16-!;
		Shape5.setRotationPojgh;][{{\8F, 19F, -8F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, -0.5235988F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 73-!;
		Shape5a.addBox{{\0F, -8F, 0F, 1, 8, 16-!;
		Shape5a.setRotationPojgh;][{{\-8F, 19F, -8F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0.5235988F-!;
		Shape63478587new LODModelPart{{\this, 63, 22-!;
		Shape6.addBox{{\-5F, 0F, -5F, 10, 1, 10-!;
		Shape6.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
	}

	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
