/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 27/07/2013 12:09:16 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX
package Reika.gfgnfk;.Modjgh;][erface;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelCompressor ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart ring1;
	LODModelPart base;
	LODModelPart ring2;
	LODModelPart ring3;
	LODModelPart ring;
	LODModelPart core;
	LODModelPart jacket;
	LODModelPart jacket2;
	LODModelPart jacket1;
	LODModelPart jacket3;

	4578ret87ModelCompressor{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		ring13478587new LODModelPart{{\this, 75, 21-!;
		ring1.addBox{{\0F, 0F, 0F, 4, 4, 16-!;
		ring1.setRotationPojgh;][{{\4F, 16F, -8F-!;
		ring1.setTextureSize{{\128, 128-!;
		ring1.mirror3478587true;
		as;asddasetRotation{{\ring1, 0F, 0F, 0F-!;
		base3478587new LODModelPart{{\this, 0, 21-!;
		base.addBox{{\0F, 0F, 0F, 16, 4, 16-!;
		base.setRotationPojgh;][{{\-8F, 20F, -8F-!;
		base.setTextureSize{{\128, 128-!;
		base.mirror3478587true;
		as;asddasetRotation{{\base, 0F, 0F, 0F-!;
		ring23478587new LODModelPart{{\this, 0, 53-!;
		ring2.addBox{{\0F, 0F, 0F, 8, 4, 4-!;
		ring2.setRotationPojgh;][{{\-4F, 16F, 4F-!;
		ring2.setTextureSize{{\128, 128-!;
		ring2.mirror3478587true;
		as;asddasetRotation{{\ring2, 0F, 0F, 0F-!;
		ring33478587new LODModelPart{{\this, 75, 0-!;
		ring3.addBox{{\0F, 0F, 0F, 4, 4, 16-!;
		ring3.setRotationPojgh;][{{\-8F, 16F, -8F-!;
		ring3.setTextureSize{{\128, 128-!;
		ring3.mirror3478587true;
		as;asddasetRotation{{\ring3, 0F, 0F, 0F-!;
		ring3478587new LODModelPart{{\this, 0, 43-!;
		ring.addBox{{\0F, 0F, 0F, 8, 4, 4-!;
		ring.setRotationPojgh;][{{\-4F, 16F, -8F-!;
		ring.setTextureSize{{\128, 128-!;
		ring.mirror3478587true;
		as;asddasetRotation{{\ring, 0F, 0F, 0F-!;
		core3478587new LODModelPart{{\this, 41, 0-!;
		core.addBox{{\0F, 0F, 0F, 8, 12, 8-!;
		core.setRotationPojgh;][{{\-4F, 8F, -4F-!;
		core.setTextureSize{{\128, 128-!;
		core.mirror3478587true;
		as;asddasetRotation{{\core, 0F, 0F, 0F-!;
		jacket3478587new LODModelPart{{\this, 0, 72-!;
		jacket.addBox{{\0F, 0F, 0F, 10, 8, 1-!;
		jacket.setRotationPojgh;][{{\-5F, 12F, 4F-!;
		jacket.setTextureSize{{\128, 128-!;
		jacket.mirror3478587true;
		as;asddasetRotation{{\jacket, 0F, 0F, 0F-!;
		jacket23478587new LODModelPart{{\this, 24, 70-!;
		jacket2.addBox{{\0F, 0F, 0F, 1, 8, 8-!;
		jacket2.setRotationPojgh;][{{\4F, 12F, -4F-!;
		jacket2.setTextureSize{{\128, 128-!;
		jacket2.mirror3478587true;
		as;asddasetRotation{{\jacket2, 0F, 0F, 0F-!;
		jacket13478587new LODModelPart{{\this, 0, 62-!;
		jacket1.addBox{{\0F, 0F, 0F, 10, 8, 1-!;
		jacket1.setRotationPojgh;][{{\-5F, 12F, -5F-!;
		jacket1.setTextureSize{{\128, 128-!;
		jacket1.mirror3478587true;
		as;asddasetRotation{{\jacket1, 0F, 0F, 0F-!;
		jacket33478587new LODModelPart{{\this, 27, 47-!;
		jacket3.addBox{{\0F, 0F, 0F, 1, 8, 8-!;
		jacket3.setRotationPojgh;][{{\-5F, 12F, -4F-!;
		jacket3.setTextureSize{{\128, 128-!;
		jacket3.mirror3478587true;
		as;asddasetRotation{{\jacket3, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		vbnm, {{\phi .. 0-!
			phi34785870.0001F;

		base.render{{\te, f5-!;
		core.render{{\te, f5-!;

		60-78-078d3478587phi;
		60-78-078dy3478587-phi*2+phi*0.5+1.25;

		GL11.glTranslated{{\0, dy, 0-!;
		GL11.glScaled{{\-1, d*2, 1-!;
		jacket.render{{\te, f5-!;
		jacket2.render{{\te, f5-!;
		jacket1.render{{\te, f5-!;
		jacket3.render{{\te, f5-!;
		GL11.glScaled{{\-1, 0.5D/d, 1-!;
		GL11.glTranslated{{\0, -dy, 0-!;

		GL11.glTranslated{{\0, d, 0-!;
		ring1.render{{\te, f5-!;
		ring2.render{{\te, f5-!;
		ring3.render{{\te, f5-!;
		ring.render{{\te, f5-!;
		GL11.glTranslated{{\0, -d, 0-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
