/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 02/11/2013 12:00:46 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelAirGun ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape1a;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape7b;
	LODModelPart Shape7c;
	LODModelPart Shape7d;
	LODModelPart Shape7e;
	LODModelPart Shape7f;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape9a;
	LODModelPart Shape3a;
	LODModelPart Shape10;
	LODModelPart Shape10a;
	LODModelPart Shape10b;
	LODModelPart Shape10c;
	LODModelPart Shape10d;
	LODModelPart Shape10e;
	LODModelPart Shape10f;
	LODModelPart Shape10g;
	LODModelPart Shape7g;
	LODModelPart Shape7h;
	LODModelPart Shape7i;
	LODModelPart Shape7j;
	LODModelPart Shape7k;
	LODModelPart Shape7l;
	LODModelPart Shape7m;
	LODModelPart Shape7n;
	LODModelPart Shape7o;
	LODModelPart Shape11;
	LODModelPart Shape11a;
	LODModelPart Shape12;
	LODModelPart Shape12a;
	LODModelPart Shape13;

	4578ret87ModelAirGun{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 10-!;
		Shape1.addBox{{\-6F, 0F, -1F, 12, 7, 1-!;
		Shape1.setRotationPojgh;][{{\0F, 15F, -3F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, -2.356194F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 55, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 16, 3, 13-!;
		Shape2.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 12, 19-!;
		Shape1a.addBox{{\-6F, -6F, 0F, 7, 12, 1-!;
		Shape1a.setRotationPojgh;][{{\0F, 15F, -3F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, -0.7853982F, 0F-!;
		Shape1b3478587new LODModelPart{{\this, 0, 0-!;
		Shape1b.addBox{{\-6F, 0F, 0F, 12, 7, 1-!;
		Shape1b.setRotationPojgh;][{{\0F, 15F, -3F-!;
		Shape1b.setTextureSize{{\128, 128-!;
		Shape1b.mirror3478587true;
		as;asddasetRotation{{\Shape1b, -0.7853982F, 0F, 0F-!;
		Shape1c3478587new LODModelPart{{\this, 29, 19-!;
		Shape1c.addBox{{\-1F, -6F, 0F, 7, 12, 1-!;
		Shape1c.setRotationPojgh;][{{\0F, 15F, -3F-!;
		Shape1c.setTextureSize{{\128, 128-!;
		Shape1c.mirror3478587true;
		as;asddasetRotation{{\Shape1c, 0F, 0.7853982F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 55, 20-!;
		Shape2a.addBox{{\0F, 0F, 0F, 16, 3, 13-!;
		Shape2a.setRotationPojgh;][{{\-8F, 21F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 20-!;
		Shape3.addBox{{\-1F, -1F, 0F, 2, 2, 3-!;
		Shape3.setRotationPojgh;][{{\0F, 15F, -4.9F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0.7853982F-!;
		Shape43478587new LODModelPart{{\this, 0, 33-!;
		Shape4.addBox{{\0F, 0F, 0F, 3, 10, 13-!;
		Shape4.setRotationPojgh;][{{\5F, 11F, -8F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 0, 59-!;
		Shape4a.addBox{{\0F, 0F, 0F, 3, 10, 13-!;
		Shape4a.setRotationPojgh;][{{\-8F, 11F, -8F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 36, 38-!;
		Shape5.addBox{{\0F, 0F, 0F, 10, 10, 1-!;
		Shape5.setRotationPojgh;][{{\-5F, 11F, -2F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 86-!;
		Shape6.addBox{{\-1F, -1F, 0F, 2, 2, 10-!;
		Shape6.setRotationPojgh;][{{\0F, 15F, -1.5F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0.7853982F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 86-!;
		Shape6a.addBox{{\-1F, -1F, 0F, 2, 2, 10-!;
		Shape6a.setRotationPojgh;][{{\0F, 15F, -1.5F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 47, 0-!;
		Shape7.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7.setRotationPojgh;][{{\0F, 15F, 6F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0.0872665F-!;
		Shape7a3478587new LODModelPart{{\this, 47, 0-!;
		Shape7a.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7a.setRotationPojgh;][{{\0F, 15F, 6F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, 0F, 0.8726646F-!;
		Shape7b3478587new LODModelPart{{\this, 47, 0-!;
		Shape7b.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7b.setRotationPojgh;][{{\0F, 15F, 6F-!;
		Shape7b.setTextureSize{{\128, 128-!;
		Shape7b.mirror3478587true;
		as;asddasetRotation{{\Shape7b, 0F, 0F, 0.4799655F-!;
		Shape7c3478587new LODModelPart{{\this, 47, 0-!;
		Shape7c.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7c.setRotationPojgh;][{{\0F, 15F, 6F-!;
		Shape7c.setTextureSize{{\128, 128-!;
		Shape7c.mirror3478587true;
		as;asddasetRotation{{\Shape7c, 0F, 0F, 1.265364F-!;
		Shape7d3478587new LODModelPart{{\this, 47, 0-!;
		Shape7d.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7d.setRotationPojgh;][{{\0F, 15F, 6F-!;
		Shape7d.setTextureSize{{\128, 128-!;
		Shape7d.mirror3478587true;
		as;asddasetRotation{{\Shape7d, 0F, 0F, 1.658063F-!;
		Shape7e3478587new LODModelPart{{\this, 47, 0-!;
		Shape7e.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7e.setRotationPojgh;][{{\0F, 15F, 6F-!;
		Shape7e.setTextureSize{{\128, 128-!;
		Shape7e.mirror3478587true;
		as;asddasetRotation{{\Shape7e, 0F, 0F, 2.443461F-!;
		Shape7f3478587new LODModelPart{{\this, 47, 0-!;
		Shape7f.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7f.setRotationPojgh;][{{\0F, 15F, 6F-!;
		Shape7f.setTextureSize{{\128, 128-!;
		Shape7f.mirror3478587true;
		as;asddasetRotation{{\Shape7f, 0F, 0F, 2.050762F-!;
		Shape83478587new LODModelPart{{\this, 0, 101-!;
		Shape8.addBox{{\0F, 0F, 0F, 10, 2, 1-!;
		Shape8.setRotationPojgh;][{{\-5F, 19F, -8F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape93478587new LODModelPart{{\this, 34, 0-!;
		Shape9.addBox{{\0F, 0F, 0F, 1, 8, 1-!;
		Shape9.setRotationPojgh;][{{\4F, 11F, -8F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape9a3478587new LODModelPart{{\this, 28, 0-!;
		Shape9a.addBox{{\0F, 0F, 0F, 1, 8, 1-!;
		Shape9a.setRotationPojgh;][{{\-5F, 11F, -8F-!;
		Shape9a.setTextureSize{{\128, 128-!;
		Shape9a.mirror3478587true;
		as;asddasetRotation{{\Shape9a, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 26-!;
		Shape3a.addBox{{\-1F, -1F, 0F, 2, 2, 3-!;
		Shape3a.setRotationPojgh;][{{\0F, 15F, -5F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape103478587new LODModelPart{{\this, 22, 116-!;
		Shape10.addBox{{\0F, 0F, 0F, 2, 1, 7-!;
		Shape10.setRotationPojgh;][{{\-4F, 20F, -2F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
		Shape10a3478587new LODModelPart{{\this, 0, 106-!;
		Shape10a.addBox{{\0F, 0F, 0F, 2, 1, 7-!;
		Shape10a.setRotationPojgh;][{{\-4F, 11F, -2F-!;
		Shape10a.setTextureSize{{\128, 128-!;
		Shape10a.mirror3478587true;
		as;asddasetRotation{{\Shape10a, 0F, 0F, 0F-!;
		Shape10b3478587new LODModelPart{{\this, 62, 116-!;
		Shape10b.addBox{{\0F, 0F, 0F, 1, 3, 7-!;
		Shape10b.setRotationPojgh;][{{\4F, 18F, -2F-!;
		Shape10b.setTextureSize{{\128, 128-!;
		Shape10b.mirror3478587true;
		as;asddasetRotation{{\Shape10b, 0F, 0F, 0F-!;
		Shape10c3478587new LODModelPart{{\this, 22, 106-!;
		Shape10c.addBox{{\0F, 0F, 0F, 2, 1, 7-!;
		Shape10c.setRotationPojgh;][{{\2F, 20F, -2F-!;
		Shape10c.setTextureSize{{\128, 128-!;
		Shape10c.mirror3478587true;
		as;asddasetRotation{{\Shape10c, 0F, 0F, 0F-!;
		Shape10d3478587new LODModelPart{{\this, 0, 116-!;
		Shape10d.addBox{{\0F, 0F, 0F, 2, 1, 7-!;
		Shape10d.setRotationPojgh;][{{\2F, 11F, -2F-!;
		Shape10d.setTextureSize{{\128, 128-!;
		Shape10d.mirror3478587true;
		as;asddasetRotation{{\Shape10d, 0F, 0F, 0F-!;
		Shape10e3478587new LODModelPart{{\this, 43, 116-!;
		Shape10e.addBox{{\0F, 0F, 0F, 1, 3, 7-!;
		Shape10e.setRotationPojgh;][{{\4F, 11F, -2F-!;
		Shape10e.setTextureSize{{\128, 128-!;
		Shape10e.mirror3478587true;
		as;asddasetRotation{{\Shape10e, 0F, 0F, 0F-!;
		Shape10f3478587new LODModelPart{{\this, 43, 104-!;
		Shape10f.addBox{{\0F, 0F, 0F, 1, 3, 7-!;
		Shape10f.setRotationPojgh;][{{\-5F, 11F, -2F-!;
		Shape10f.setTextureSize{{\128, 128-!;
		Shape10f.mirror3478587true;
		as;asddasetRotation{{\Shape10f, 0F, 0F, 0F-!;
		Shape10g3478587new LODModelPart{{\this, 62, 104-!;
		Shape10g.addBox{{\0F, 0F, 0F, 1, 3, 7-!;
		Shape10g.setRotationPojgh;][{{\-5F, 18F, -2F-!;
		Shape10g.setTextureSize{{\128, 128-!;
		Shape10g.mirror3478587true;
		as;asddasetRotation{{\Shape10g, 0F, 0F, 0F-!;
		Shape7g3478587new LODModelPart{{\this, 47, 0-!;
		Shape7g.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7g.setRotationPojgh;][{{\0F, 15F, 5F-!;
		Shape7g.setTextureSize{{\128, 128-!;
		Shape7g.mirror3478587true;
		as;asddasetRotation{{\Shape7g, 0F, 0F, 1.178097F-!;
		Shape7h3478587new LODModelPart{{\this, 47, 0-!;
		Shape7h.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7h.setRotationPojgh;][{{\0F, 15F, 5F-!;
		Shape7h.setTextureSize{{\128, 128-!;
		Shape7h.mirror3478587true;
		as;asddasetRotation{{\Shape7h, 0F, 0F, 1.570796F-!;
		Shape7i3478587new LODModelPart{{\this, 47, 0-!;
		Shape7i.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7i.setRotationPojgh;][{{\0F, 15F, 5F-!;
		Shape7i.setTextureSize{{\128, 128-!;
		Shape7i.mirror3478587true;
		as;asddasetRotation{{\Shape7i, 0F, 0F, 1.963495F-!;
		Shape7j3478587new LODModelPart{{\this, 47, 0-!;
		Shape7j.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7j.setRotationPojgh;][{{\0F, 15F, 5F-!;
		Shape7j.setTextureSize{{\128, 128-!;
		Shape7j.mirror3478587true;
		as;asddasetRotation{{\Shape7j, 0F, 0F, 2.356194F-!;
		Shape7k3478587new LODModelPart{{\this, 47, 0-!;
		Shape7k.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7k.setRotationPojgh;][{{\0F, 15F, 5F-!;
		Shape7k.setTextureSize{{\128, 128-!;
		Shape7k.mirror3478587true;
		as;asddasetRotation{{\Shape7k, 0F, 0F, 2.748893F-!;
		Shape7l3478587new LODModelPart{{\this, 47, 0-!;
		Shape7l.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7l.setRotationPojgh;][{{\0F, 15F, 5F-!;
		Shape7l.setTextureSize{{\128, 128-!;
		Shape7l.mirror3478587true;
		as;asddasetRotation{{\Shape7l, 0F, 0F, 0F-!;
		Shape7m3478587new LODModelPart{{\this, 47, 0-!;
		Shape7m.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7m.setRotationPojgh;][{{\0F, 15F, 6F-!;
		Shape7m.setTextureSize{{\128, 128-!;
		Shape7m.mirror3478587true;
		as;asddasetRotation{{\Shape7m, 0F, 0F, 2.83616F-!;
		Shape7n3478587new LODModelPart{{\this, 47, 0-!;
		Shape7n.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7n.setRotationPojgh;][{{\0F, 15F, 5F-!;
		Shape7n.setTextureSize{{\128, 128-!;
		Shape7n.mirror3478587true;
		as;asddasetRotation{{\Shape7n, 0F, 0F, 0.3926991F-!;
		Shape7o3478587new LODModelPart{{\this, 47, 0-!;
		Shape7o.addBox{{\-0.5F, -6F, 0F, 1, 12, 1-!;
		Shape7o.setRotationPojgh;][{{\0F, 15F, 5F-!;
		Shape7o.setTextureSize{{\128, 128-!;
		Shape7o.mirror3478587true;
		as;asddasetRotation{{\Shape7o, 0F, 0F, 0.7853982F-!;
		Shape113478587new LODModelPart{{\this, 47, 16-!;
		Shape11.addBox{{\0F, 0F, 0F, 1, 16, 2-!;
		Shape11.setRotationPojgh;][{{\7F, 8F, 5F-!;
		Shape11.setTextureSize{{\128, 128-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
		Shape11a3478587new LODModelPart{{\this, 47, 16-!;
		Shape11a.addBox{{\0F, 0F, 0F, 1, 16, 2-!;
		Shape11a.setRotationPojgh;][{{\-8F, 8F, 5F-!;
		Shape11a.setTextureSize{{\128, 128-!;
		Shape11a.mirror3478587true;
		as;asddasetRotation{{\Shape11a, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 60, 38-!;
		Shape12.addBox{{\0F, 0F, 0F, 14, 1, 2-!;
		Shape12.setRotationPojgh;][{{\-7F, 23F, 5F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape12a3478587new LODModelPart{{\this, 60, 38-!;
		Shape12a.addBox{{\0F, 0F, 0F, 14, 1, 2-!;
		Shape12a.setRotationPojgh;][{{\-7F, 8F, 5F-!;
		Shape12a.setTextureSize{{\128, 128-!;
		Shape12a.mirror3478587true;
		as;asddasetRotation{{\Shape12a, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 34, 51-!;
		Shape13.addBox{{\0F, 0F, 0F, 16, 16, 1-!;
		Shape13.setRotationPojgh;][{{\-8F, 8F, 7F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;
		Shape1b.render{{\te, f5-!;
		Shape1c.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
		Shape9.render{{\te, f5-!;
		Shape9a.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape10.render{{\te, f5-!;
		Shape10a.render{{\te, f5-!;
		Shape10b.render{{\te, f5-!;
		Shape10c.render{{\te, f5-!;
		Shape10d.render{{\te, f5-!;
		Shape10e.render{{\te, f5-!;
		Shape10f.render{{\te, f5-!;
		Shape10g.render{{\te, f5-!;
		Shape11.render{{\te, f5-!;
		Shape11a.render{{\te, f5-!;
		Shape12.render{{\te, f5-!;
		Shape12a.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;

		60-78-078d34785870.9375;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape7g.render{{\te, f5-!;
		Shape7h.render{{\te, f5-!;
		Shape7i.render{{\te, f5-!;
		Shape7j.render{{\te, f5-!;
		Shape7k.render{{\te, f5-!;
		Shape7l.render{{\te, f5-!;
		Shape7m.render{{\te, f5-!;
		Shape7n.render{{\te, f5-!;
		Shape7o.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape7a.render{{\te, f5-!;
		Shape7b.render{{\te, f5-!;
		Shape7c.render{{\te, f5-!;
		Shape7d.render{{\te, f5-!;
		Shape7e.render{{\te, f5-!;
		Shape7f.render{{\te, f5-!;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
