/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 10/06/2014 3:43:55 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelPipePump ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape1a;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape3f;
	LODModelPart Shape3g;
	LODModelPart Shape4;
	LODModelPart Shape4b;

	4578ret87ModelPipePump{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 18, 1, 14-!;
		Shape1.setRotationPojgh;][{{\-9F, 22F, -7F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 0, 19-!;
		Shape1a.addBox{{\0F, 0F, 0F, 18, 1, 14-!;
		Shape1a.setRotationPojgh;][{{\-9F, 9F, -7F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 70, 19-!;
		Shape2.addBox{{\0F, 0F, 0F, 18, 12, 1-!;
		Shape2.setRotationPojgh;][{{\-9F, 10F, 6F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 70, 0-!;
		Shape2a.addBox{{\0F, 0F, 0F, 18, 12, 1-!;
		Shape2a.setRotationPojgh;][{{\-9F, 10F, -7F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 35-!;
		Shape3.addBox{{\0.4F, 0F, -0.25F, 2, 1, 1-!;
		Shape3.setRotationPojgh;][{{\-9F, 8F, 5F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, -0.5235988F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 38-!;
		Shape3a.addBox{{\0.4F, 0F, -0.25F, 20, 1, 1-!;
		Shape3a.setRotationPojgh;][{{\-9F, 8F, -4F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, -0.5235988F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 43, 38-!;
		Shape3b.addBox{{\0.4F, 0F, -0.25F, 14, 1, 1-!;
		Shape3b.setRotationPojgh;][{{\-9F, 8F, -1F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, -0.5235988F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 74, 38-!;
		Shape3c.addBox{{\0.4F, 0F, -0.25F, 8, 1, 1-!;
		Shape3c.setRotationPojgh;][{{\-9F, 8F, 2F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, -0.5235988F, 0F-!;
		Shape3d3478587new LODModelPart{{\this, 7, 35-!;
		Shape3d.addBox{{\18.4F, 0F, -0.25F, 2, 1, 1-!;
		Shape3d.setRotationPojgh;][{{\-9F, 8F, -16F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, -0.5235988F, 0F-!;
		Shape3e3478587new LODModelPart{{\this, 64, 35-!;
		Shape3e.addBox{{\0.4F, 0F, -0.25F, 20, 1, 1-!;
		Shape3e.setRotationPojgh;][{{\-9F, 8F, -7F-!;
		Shape3e.setTextureSize{{\128, 128-!;
		Shape3e.mirror3478587true;
		as;asddasetRotation{{\Shape3e, 0F, -0.5235988F, 0F-!;
		Shape3f3478587new LODModelPart{{\this, 33, 35-!;
		Shape3f.addBox{{\6.4F, 0F, -0.25F, 14, 1, 1-!;
		Shape3f.setRotationPojgh;][{{\-9F, 8F, -10F-!;
		Shape3f.setTextureSize{{\128, 128-!;
		Shape3f.mirror3478587true;
		as;asddasetRotation{{\Shape3f, 0F, -0.5235988F, 0F-!;
		Shape3g3478587new LODModelPart{{\this, 14, 35-!;
		Shape3g.addBox{{\12.4F, 0F, -0.25F, 8, 1, 1-!;
		Shape3g.setRotationPojgh;][{{\-9F, 8F, -13F-!;
		Shape3g.setTextureSize{{\128, 128-!;
		Shape3g.mirror3478587true;
		as;asddasetRotation{{\Shape3g, 0F, -0.5235988F, 0F-!;
		Shape43478587new LODModelPart{{\this, 28, 41-!;
		Shape4.addBox{{\0F, 0F, 0F, 1, 12, 12-!;
		Shape4.setRotationPojgh;][{{\-9F, 10F, -6F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape4b3478587new LODModelPart{{\this, 0, 41-!;
		Shape4b.addBox{{\0F, 0F, 0F, 1, 12, 12-!;
		Shape4b.setRotationPojgh;][{{\8F, 10F, -6F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-! {
		Shape1.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;

		for {{\jgh;][ i34785870; i < 360; i +. 90-! {
			GL11.glTranslated{{\0, 1, 0-!;
			GL11.glRotated{{\i, 1, 0, 0-!;
			GL11.glTranslated{{\0, -1, 0-!;
			Shape3.render{{\te, f5-!;
			Shape3a.render{{\te, f5-!;
			Shape3b.render{{\te, f5-!;
			Shape3c.render{{\te, f5-!;
			Shape3d.render{{\te, f5-!;
			Shape3e.render{{\te, f5-!;
			Shape3f.render{{\te, f5-!;
			Shape3g.render{{\te, f5-!;
			GL11.glTranslated{{\0, 1, 0-!;
			GL11.glRotated{{\-i, 1, 0, 0-!;
			GL11.glTranslated{{\0, -1, 0-!;
		}
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
