/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 14/07/2013 3:56:41 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelDisplay ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape5;

	4578ret87ModelDisplay{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 65, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 6, 1, 6-!;
		Shape2.setRotationPojgh;][{{\-3F, 22F, -3F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 14, 18-!;
		Shape3.addBox{{\0F, 0F, 0F, 6, 1, 2-!;
		Shape3.setRotationPojgh;][{{\-3F, 10F, -1F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 53-!;
		Shape3a.addBox{{\0F, 0F, 0F, 16, 1, 1-!;
		Shape3a.setRotationPojgh;][{{\-8F, 8F, -0.5F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 0, 32-!;
		Shape3b.addBox{{\0F, 0F, 0F, 12, 1, 2-!;
		Shape3b.setRotationPojgh;][{{\-6F, 9F, -1F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 7, 18-!;
		Shape4.addBox{{\0F, 0F, 0F, 1, 11, 2-!;
		Shape4.setRotationPojgh;][{{\2F, 11F, -1F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 5, 36-!;
		Shape4a.addBox{{\0F, 0F, 0F, 1, 15, 1-!;
		Shape4a.setRotationPojgh;][{{\7F, 8.6F, -0.5F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0.3490659F-!;
		Shape4b3478587new LODModelPart{{\this, 0, 18-!;
		Shape4b.addBox{{\0F, 0F, 0F, 1, 11, 2-!;
		Shape4b.setRotationPojgh;][{{\-3F, 11F, -1F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 0F, 0F, 0F-!;
		Shape4c3478587new LODModelPart{{\this, 0, 36-!;
		Shape4c.addBox{{\0F, 0F, 0F, 1, 15, 1-!;
		Shape4c.setRotationPojgh;][{{\-8F, 9F, -0.5F-!;
		Shape4c.setTextureSize{{\128, 128-!;
		Shape4c.mirror3478587true;
		as;asddasetRotation{{\Shape4c, 0F, 0F, -0.3490659F-!;
		Shape53478587new LODModelPart{{\this, 10, 36-!;
		Shape5.addBox{{\0F, 0F, 0F, 4, 11, 1-!;
		Shape5.setRotationPojgh;][{{\-2F, 11F, -0.5F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;
		Shape4c.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
