/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 11/05/2013 6:19:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelCCTV ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape4a;
	LODModelPart Shape4;
	LODModelPart Shape5a;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;

	4578ret87ModelCCTV{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 28, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 8, 1, 8-!;
		Shape1.setRotationPojgh;][{{\-4F, 23F, -4F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 62, 0-!;
		Shape2.addBox{{\-0.5F, 0F, 0F, 1, 5, 3-!;
		Shape2.setRotationPojgh;][{{\0F, 18F, 0F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 26-!;
		Shape3.addBox{{\-2.5F, -1.5F, -5.5F, 5, 3, 8-!;
		Shape3.setRotationPojgh;][{{\0F, 18F, 1.5F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 13-!;
		Shape3a.addBox{{\-2F, -2F, -5.5F, 4, 4, 8-!;
		Shape3a.setRotationPojgh;][{{\0F, 18F, 1.5F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 5, 0-!;
		Shape4a.addBox{{\-2F, 1F, -6.5F, 4, 1, 1-!;
		Shape4a.setRotationPojgh;][{{\0F, 18F, 1.5F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 5, 0-!;
		Shape4.addBox{{\-2F, -2F, -6.5F, 4, 1, 1-!;
		Shape4.setRotationPojgh;][{{\0F, 18F, 1.5F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 0-!;
		Shape5a.addBox{{\-2.5F, -1.5F, -6.5F, 1, 3, 1-!;
		Shape5a.setRotationPojgh;][{{\0F, 18F, 1.5F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 0-!;
		Shape5.addBox{{\1.5F, -1.5F, -6.5F, 1, 3, 1-!;
		Shape5.setRotationPojgh;][{{\0F, 18F, 1.5F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 39-!;
		Shape6.addBox{{\-1.5F, -1F, -6F, 3, 2, 1-!;
		Shape6.setRotationPojgh;][{{\0F, 18F, 1.5F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 5-!;
		Shape7.addBox{{\-2F, -1.5F, 2F, 4, 3, 1-!;
		Shape7.setRotationPojgh;][{{\0F, 18F, 1.5F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078d34785870.175;
		60-78-078d134785870.0625;
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		GL11.glTranslated{{\0, 0, d1-!;
		GL11.glRotatef{{\phi, 0, 1, 0-!;
		GL11.glTranslated{{\0, 0, -d1-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glTranslated{{\0, 0, d-!;
		GL11.glRotatef{{\theta, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		GL11.glTranslated{{\0, 0, -d-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-theta, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		GL11.glTranslated{{\0, 0, d1-!;
		GL11.glRotatef{{\-phi, 0, 1, 0-!;
		GL11.glTranslated{{\0, 0, -d1-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f6-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
