/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 20/02/2013 12:34:40 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelPulseFurnace ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape20;
	LODModelPart Shape21;
	LODModelPart Shape5;
	LODModelPart Shape23;
	LODModelPart Shape24;
	LODModelPart Shape25;
	LODModelPart Shape26;

	4578ret87ModelPulseFurnace{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 64, 20-!;
		Shape1.addBox{{\0F, 0F, 0F, 10, 1, 4-!;
		Shape1.setRotationPojgh;][{{\-6.8F, 16F, -6.8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 17-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 4, 4-!;
		Shape2.setRotationPojgh;][{{\-5F, 17F, 2F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 24, 17-!;
		Shape3.addBox{{\0F, 0F, 0F, 3, 4, 6-!;
		Shape3.setRotationPojgh;][{{\-4F, 17F, 1F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 100, 22-!;
		Shape4.addBox{{\0F, 0F, 0F, 1, 2, 6-!;
		Shape4.setRotationPojgh;][{{\6F, 21F, 1F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 24, 27-!;
		Shape6.addBox{{\0F, 0F, 0F, 6, 6, 8-!;
		Shape6.setRotationPojgh;][{{\-1F, 16F, 0F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 100, 30-!;
		Shape7.addBox{{\0F, 0F, 0F, 1, 1, 6-!;
		Shape7.setRotationPojgh;][{{\7F, 22F, 1F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape83478587new LODModelPart{{\this, 100, 13-!;
		Shape8.addBox{{\0F, 0F, 0F, 1, 3, 6-!;
		Shape8.setRotationPojgh;][{{\5F, 20F, 1F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape93478587new LODModelPart{{\this, 42, 17-!;
		Shape9.addBox{{\0F, 0F, 0F, 3, 6, 1-!;
		Shape9.setRotationPojgh;][{{\5F, 16F, 7F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape103478587new LODModelPart{{\this, 100, 22-!;
		Shape10.addBox{{\0F, 0F, 0F, 1, 2, 6-!;
		Shape10.setRotationPojgh;][{{\6F, 15F, 1F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
		Shape113478587new LODModelPart{{\this, 100, 30-!;
		Shape11.addBox{{\0F, 0F, 0F, 1, 1, 6-!;
		Shape11.setRotationPojgh;][{{\7F, 15F, 1F-!;
		Shape11.setTextureSize{{\128, 128-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 100, 13-!;
		Shape12.addBox{{\0F, 0F, 0F, 1, 3, 6-!;
		Shape12.setRotationPojgh;][{{\5F, 15F, 1F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 54, 17-!;
		Shape13.addBox{{\0F, 0F, 0F, 1, 2, 2-!;
		Shape13.setRotationPojgh;][{{\5F, 18F, 5F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0F, 0F, 0F-!;
		Shape143478587new LODModelPart{{\this, 50, 17-!;
		Shape14.addBox{{\0F, 0F, 0F, 1, 4, 1-!;
		Shape14.setRotationPojgh;][{{\6F, 17F, 6F-!;
		Shape14.setTextureSize{{\128, 128-!;
		Shape14.mirror3478587true;
		as;asddasetRotation{{\Shape14, 0F, 0F, 0F-!;
		Shape153478587new LODModelPart{{\this, 52, 40-!;
		Shape15.addBox{{\0F, 0F, 0F, 1, 2, 2-!;
		Shape15.setRotationPojgh;][{{\4.1F, 18F, 3F-!;
		Shape15.setTextureSize{{\128, 128-!;
		Shape15.mirror3478587true;
		as;asddasetRotation{{\Shape15, 0F, 0F, 0F-!;
		Shape163478587new LODModelPart{{\this, 50, 17-!;
		Shape16.addBox{{\0F, 0F, 0F, 1, 4, 1-!;
		Shape16.setRotationPojgh;][{{\6F, 17F, 1F-!;
		Shape16.setTextureSize{{\128, 128-!;
		Shape16.mirror3478587true;
		as;asddasetRotation{{\Shape16, 0F, 0F, 0F-!;
		Shape173478587new LODModelPart{{\this, 42, 17-!;
		Shape17.addBox{{\0F, 0F, 0F, 3, 6, 1-!;
		Shape17.setRotationPojgh;][{{\5F, 16F, 0F-!;
		Shape17.setTextureSize{{\128, 128-!;
		Shape17.mirror3478587true;
		as;asddasetRotation{{\Shape17, 0F, 0F, 0F-!;
		Shape183478587new LODModelPart{{\this, 0, 27-!;
		Shape18.addBox{{\0F, 0F, 0F, 6, 8, 6-!;
		Shape18.setRotationPojgh;][{{\-1F, 15F, 1F-!;
		Shape18.setTextureSize{{\128, 128-!;
		Shape18.mirror3478587true;
		as;asddasetRotation{{\Shape18, 0F, 0F, 0F-!;
		Shape193478587new LODModelPart{{\this, 10, 17-!;
		Shape19.addBox{{\0F, 0F, 0F, 3, 6, 4-!;
		Shape19.setRotationPojgh;][{{\-4F, 16F, 2F-!;
		Shape19.setTextureSize{{\128, 128-!;
		Shape19.mirror3478587true;
		as;asddasetRotation{{\Shape19, 0F, 0F, 0F-!;
		Shape203478587new LODModelPart{{\this, 104, 6-!;
		Shape20.addBox{{\0F, 0F, 0F, 3, 2, 2-!;
		Shape20.setRotationPojgh;][{{\-8F, 18F, 3F-!;
		Shape20.setTextureSize{{\128, 128-!;
		Shape20.mirror3478587true;
		as;asddasetRotation{{\Shape20, 0F, 0F, 0F-!;
		Shape213478587new LODModelPart{{\this, 104, 0-!;
		Shape21.addBox{{\0F, 0F, 0F, 2, 2, 4-!;
		Shape21.setRotationPojgh;][{{\-8F, 18F, -1F-!;
		Shape21.setTextureSize{{\128, 128-!;
		Shape21.mirror3478587true;
		as;asddasetRotation{{\Shape21, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 0-!;
		Shape5.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape5.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape233478587new LODModelPart{{\this, 64, 13-!;
		Shape23.addBox{{\0F, 0F, 0F, 12, 1, 6-!;
		Shape23.setRotationPojgh;][{{\-7.5F, 16.5F, -7.5F-!;
		Shape23.setTextureSize{{\128, 128-!;
		Shape23.mirror3478587true;
		as;asddasetRotation{{\Shape23, 0F, 0F, 0F-!;
		Shape243478587new LODModelPart{{\this, 64, 0-!;
		Shape24.addBox{{\0F, 0F, 0F, 13, 6, 7-!;
		Shape24.setRotationPojgh;][{{\-7.8F, 17F, -7.8F-!;
		Shape24.setTextureSize{{\128, 128-!;
		Shape24.mirror3478587true;
		as;asddasetRotation{{\Shape24, 0F, 0F, 0F-!;
		Shape253478587new LODModelPart{{\this, 52, 25-!;
		Shape25.addBox{{\0F, 0F, 0F, 4, 8, 7-!;
		Shape25.setRotationPojgh;][{{\4F, 15F, -8F-!;
		Shape25.setTextureSize{{\128, 128-!;
		Shape25.mirror3478587true;
		as;asddasetRotation{{\Shape25, 0F, 0F, 0F-!;
		Shape263478587new LODModelPart{{\this, 54, 17-!;
		Shape26.addBox{{\0F, 0F, 0F, 1, 2, 2-!;
		Shape26.setRotationPojgh;][{{\5F, 18F, 1F-!;
		Shape26.setTextureSize{{\128, 128-!;
		Shape26.mirror3478587true;
		as;asddasetRotation{{\Shape26, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
		Shape9.render{{\te, f5-!;
		Shape10.render{{\te, f5-!;
		Shape11.render{{\te, f5-!;
		Shape12.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;
		Shape14.render{{\te, f5-!;
		Shape15.render{{\te, f5-!;
		Shape16.render{{\te, f5-!;
		Shape17.render{{\te, f5-!;
		Shape18.render{{\te, f5-!;
		Shape19.render{{\te, f5-!;
		Shape20.render{{\te, f5-!;
		Shape21.render{{\te, f5-!;
		Shape23.render{{\te, f5-!;
		Shape24.render{{\te, f5-!;
		Shape25.render{{\te, f5-!;
		Shape26.render{{\te, f5-!;
	}

}
