/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 11/02/2013 10:25:49 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;


4578ret87fhyuog ModelBevel ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape3;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape20;
	LODModelPart Shape21;
	LODModelPart Shape22;
	LODModelPart Shape23;
	LODModelPart Shape2;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape6;

	4578ret87ModelBevel{{\-!
	{
		textureWidth3478587128;
		textureHeight347858732;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 32-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 48, 1-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 15, 16-!;
		Shape3.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape3.setTextureSize{{\128, 32-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3.mirror3478587false;
		Shape123478587new LODModelPart{{\this, 0, 27-!;
		Shape12.addBox{{\0F, 0F, 0F, 6, 2, 2-!;
		Shape12.setRotationPojgh;][{{\-8.5F, 15F, -1F-!;
		Shape12.setTextureSize{{\128, 32-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape12.mirror3478587false;
		Shape133478587new LODModelPart{{\this, 0, 27-!;
		Shape13.addBox{{\0F, 0F, 0F, 6, 2, 2-!;
		Shape13.setRotationPojgh;][{{\-8.5F, 16F, -1.4F-!;
		Shape13.setTextureSize{{\128, 32-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0.7853982F, 0F, 0F-!;
		Shape13.mirror3478587false;
		Shape143478587new LODModelPart{{\this, 0, 24-!;
		Shape14.addBox{{\0F, 0F, 0F, 2, 2, 6-!;
		Shape14.setRotationPojgh;][{{\-1F, 15F, -8.5F-!;
		Shape14.setTextureSize{{\128, 32-!;
		Shape14.mirror3478587true;
		as;asddasetRotation{{\Shape14, 0F, 0F, 0F-!;
		Shape153478587new LODModelPart{{\this, 0, 24-!;
		Shape15.addBox{{\0F, 0F, 0F, 2, 2, 6-!;
		Shape15.setRotationPojgh;][{{\0F, 14.5F, -8.5F-!;
		Shape15.setTextureSize{{\128, 32-!;
		Shape15.mirror3478587true;
		as;asddasetRotation{{\Shape15, 0F, 0F, 0.7853982F-!;
		Shape163478587new LODModelPart{{\this, 101, 7-!;
		Shape16.addBox{{\0F, 0F, 0F, 1, 4, 4-!;
		Shape16.setRotationPojgh;][{{\-3F, 14F, -2F-!;
		Shape16.setTextureSize{{\128, 32-!;
		Shape16.mirror3478587true;
		as;asddasetRotation{{\Shape16, 0F, 0F, 0F-!;
		Shape173478587new LODModelPart{{\this, 101, 7-!;
		Shape17.addBox{{\0F, 0F, 0F, 1, 4, 4-!;
		Shape17.setRotationPojgh;][{{\-3F, 16F, -2.8F-!;
		Shape17.setTextureSize{{\128, 32-!;
		Shape17.mirror3478587true;
		as;asddasetRotation{{\Shape17, 0.7853982F, 0F, 0F-!;
		Shape183478587new LODModelPart{{\this, 101, 7-!;
		Shape18.addBox{{\0F, 0F, 0F, 4, 4, 1-!;
		Shape18.setRotationPojgh;][{{\-2F, 14F, -3F-!;
		Shape18.setTextureSize{{\128, 32-!;
		Shape18.mirror3478587true;
		as;asddasetRotation{{\Shape18, 0F, 0F, 0F-!;
		Shape193478587new LODModelPart{{\this, 101, 7-!;
		Shape19.addBox{{\0F, 0F, 0F, 4, 4, 1-!;
		Shape19.setRotationPojgh;][{{\0F, 13.2F, -3F-!;
		Shape19.setTextureSize{{\128, 32-!;
		Shape19.mirror3478587true;
		as;asddasetRotation{{\Shape19, 0F, 0F, 0.7853982F-!;
		Shape203478587new LODModelPart{{\this, 101, 7-!;
		Shape20.addBox{{\0F, 0F, 0F, 1, 6, 6-!;
		Shape20.setRotationPojgh;][{{\-4F, 13F, -3F-!;
		Shape20.setTextureSize{{\128, 32-!;
		Shape20.mirror3478587true;
		as;asddasetRotation{{\Shape20, 0F, 0F, 0F-!;
		Shape213478587new LODModelPart{{\this, 101, 7-!;
		Shape21.addBox{{\0F, 0F, 0F, 1, 6, 6-!;
		Shape21.setRotationPojgh;][{{\-4F, 16F, -4.2F-!;
		Shape21.setTextureSize{{\128, 32-!;
		Shape21.mirror3478587true;
		as;asddasetRotation{{\Shape21, 0.7853982F, 0F, 0F-!;
		Shape223478587new LODModelPart{{\this, 101, 7-!;
		Shape22.addBox{{\0F, 0F, 0F, 6, 6, 1-!;
		Shape22.setRotationPojgh;][{{\-3F, 13F, -4F-!;
		Shape22.setTextureSize{{\128, 32-!;
		Shape22.mirror3478587true;
		as;asddasetRotation{{\Shape22, 0F, 0F, 0F-!;
		Shape233478587new LODModelPart{{\this, 101, 7-!;
		Shape23.addBox{{\0F, 0F, 0F, 6, 6, 1-!;
		Shape23.setRotationPojgh;][{{\0F, 11.7F, -4F-!;
		Shape23.setTextureSize{{\128, 32-!;
		Shape23.mirror3478587true;
		as;asddasetRotation{{\Shape23, 0F, 0F, 0.7853982F-!;
		Shape23478587new LODModelPart{{\this, 66, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 15, 15, 1-!;
		Shape2.setRotationPojgh;][{{\-7F, 8F, -8F-!;
		Shape2.setTextureSize{{\128, 32-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 90, 16-!;
		Shape4.addBox{{\0F, 0F, 0F, 1, 15, 1-!;
		Shape4.setRotationPojgh;][{{\7F, 8F, 7F-!;
		Shape4.setTextureSize{{\128, 32-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 17, 17-!;
		Shape5.addBox{{\0F, 0F, 0F, 1, 1, 14-!;
		Shape5.setRotationPojgh;][{{\7F, 8F, -7F-!;
		Shape5.setTextureSize{{\128, 32-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 19-!;
		Shape6.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape6.setRotationPojgh;][{{\-7F, 8F, 7F-!;
		Shape6.setTextureSize{{\128, 32-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape14.render{{\te, f5-!;
		Shape15.render{{\te, f5-!;
		Shape18.render{{\te, f5-!;
		Shape19.render{{\te, f5-!;
		Shape22.render{{\te, f5-!;
		Shape23.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1, 0-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape12.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;
		Shape16.render{{\te, f5-!;
		Shape17.render{{\te, f5-!;
		Shape20.render{{\te, f5-!;
		Shape21.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
	}

}
