/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 30/03/2013 7:51:52 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelCannon ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape2g;
	LODModelPart Shape2h;
	LODModelPart Shape2i;
	LODModelPart Shape2j;
	LODModelPart Shape2k;
	LODModelPart Shape2l;
	LODModelPart Shape2m;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape3f;
	LODModelPart Shape3g;
	LODModelPart Shape3h;
	LODModelPart Shape3i;
	LODModelPart Shape3j;
	LODModelPart Shape3k;
	LODModelPart Shape3l;
	LODModelPart Shape3m;

	4578ret87ModelCannon{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 8, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 16F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 34, 24-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 1, 16-!;
		Shape2.setRotationPojgh;][{{\-8F, 9F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 24-!;
		Shape2a.addBox{{\0F, 0F, 0F, 1, 1, 16-!;
		Shape2a.setRotationPojgh;][{{\7F, 9F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 84, 34-!;
		Shape2b.addBox{{\0F, 0F, 0F, 6, 1, 16-!;
		Shape2b.setRotationPojgh;][{{\-8F, 14F, -8F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 86, 51-!;
		Shape2c.addBox{{\0F, 0F, 0F, 5, 1, 16-!;
		Shape2c.setRotationPojgh;][{{\-8F, 13F, -8F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 88, 68-!;
		Shape2d.addBox{{\0F, 0F, 0F, 4, 1, 16-!;
		Shape2d.setRotationPojgh;][{{\-8F, 12F, -8F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0F, 0F-!;
		Shape2e3478587new LODModelPart{{\this, 90, 85-!;
		Shape2e.addBox{{\0F, 0F, 0F, 3, 1, 16-!;
		Shape2e.setRotationPojgh;][{{\-8F, 11F, -8F-!;
		Shape2e.setTextureSize{{\128, 128-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, 0F, 0F, 0F-!;
		Shape2f3478587new LODModelPart{{\this, 92, 102-!;
		Shape2f.addBox{{\0F, 0F, 0F, 2, 1, 16-!;
		Shape2f.setRotationPojgh;][{{\-8F, 10F, -8F-!;
		Shape2f.setTextureSize{{\128, 128-!;
		Shape2f.mirror3478587true;
		as;asddasetRotation{{\Shape2f, 0F, 0F, 0F-!;
		Shape2g3478587new LODModelPart{{\this, 82, 17-!;
		Shape2g.addBox{{\0F, 0F, 0F, 7, 1, 16-!;
		Shape2g.setRotationPojgh;][{{\-8F, 15F, -8F-!;
		Shape2g.setTextureSize{{\128, 128-!;
		Shape2g.mirror3478587true;
		as;asddasetRotation{{\Shape2g, 0F, 0F, 0F-!;
		Shape2h3478587new LODModelPart{{\this, 64, 0-!;
		Shape2h.addBox{{\0F, 0F, 0F, 7, 1, 16-!;
		Shape2h.setRotationPojgh;][{{\1F, 15F, -8F-!;
		Shape2h.setTextureSize{{\128, 128-!;
		Shape2h.mirror3478587true;
		as;asddasetRotation{{\Shape2h, 0F, 0F, 0F-!;
		Shape2i3478587new LODModelPart{{\this, 0, 109-!;
		Shape2i.addBox{{\0F, 0F, 0F, 6, 1, 16-!;
		Shape2i.setRotationPojgh;][{{\2F, 14F, -8F-!;
		Shape2i.setTextureSize{{\128, 128-!;
		Shape2i.mirror3478587true;
		as;asddasetRotation{{\Shape2i, 0F, 0F, 0F-!;
		Shape2j3478587new LODModelPart{{\this, 0, 92-!;
		Shape2j.addBox{{\0F, 0F, 0F, 5, 1, 16-!;
		Shape2j.setRotationPojgh;][{{\3F, 13F, -8F-!;
		Shape2j.setTextureSize{{\128, 128-!;
		Shape2j.mirror3478587true;
		as;asddasetRotation{{\Shape2j, 0F, 0F, 0F-!;
		Shape2k3478587new LODModelPart{{\this, 0, 75-!;
		Shape2k.addBox{{\0F, 0F, 0F, 4, 1, 16-!;
		Shape2k.setRotationPojgh;][{{\4F, 12F, -8F-!;
		Shape2k.setTextureSize{{\128, 128-!;
		Shape2k.mirror3478587true;
		as;asddasetRotation{{\Shape2k, 0F, 0F, 0F-!;
		Shape2l3478587new LODModelPart{{\this, 0, 58-!;
		Shape2l.addBox{{\0F, 0F, 0F, 3, 1, 16-!;
		Shape2l.setRotationPojgh;][{{\5F, 11F, -8F-!;
		Shape2l.setTextureSize{{\128, 128-!;
		Shape2l.mirror3478587true;
		as;asddasetRotation{{\Shape2l, 0F, 0F, 0F-!;
		Shape2m3478587new LODModelPart{{\this, 0, 41-!;
		Shape2m.addBox{{\0F, 0F, 0F, 2, 1, 16-!;
		Shape2m.setRotationPojgh;][{{\6F, 10F, -8F-!;
		Shape2m.setTextureSize{{\128, 128-!;
		Shape2m.mirror3478587true;
		as;asddasetRotation{{\Shape2m, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 36, 41-!;
		Shape3.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape3.setRotationPojgh;][{{\-7F, 9F, 7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 39, 68-!;
		Shape3a.addBox{{\0F, 0F, 0F, 2, 1, 7-!;
		Shape3a.setRotationPojgh;][{{\-1F, 15F, 1F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 38, 61-!;
		Shape3b.addBox{{\0F, 0F, 0F, 4, 1, 6-!;
		Shape3b.setRotationPojgh;][{{\-2F, 14F, 2F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 38, 55-!;
		Shape3c.addBox{{\0F, 0F, 0F, 6, 1, 5-!;
		Shape3c.setRotationPojgh;][{{\-3F, 13F, 3F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 0F-!;
		Shape3d3478587new LODModelPart{{\this, 36, 50-!;
		Shape3d.addBox{{\0F, 0F, 0F, 8, 1, 4-!;
		Shape3d.setRotationPojgh;][{{\-4F, 12F, 4F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, 0F, 0F-!;
		Shape3e3478587new LODModelPart{{\this, 36, 46-!;
		Shape3e.addBox{{\0F, 0F, 0F, 10, 1, 3-!;
		Shape3e.setRotationPojgh;][{{\-5F, 11F, 5F-!;
		Shape3e.setTextureSize{{\128, 128-!;
		Shape3e.mirror3478587true;
		as;asddasetRotation{{\Shape3e, 0F, 0F, 0F-!;
		Shape3f3478587new LODModelPart{{\this, 36, 43-!;
		Shape3f.addBox{{\0F, 0F, 0F, 12, 1, 2-!;
		Shape3f.setRotationPojgh;][{{\-6F, 10F, 6F-!;
		Shape3f.setTextureSize{{\128, 128-!;
		Shape3f.mirror3478587true;
		as;asddasetRotation{{\Shape3f, 0F, 0F, 0F-!;
		Shape3g3478587new LODModelPart{{\this, 40, 76-!;
		Shape3g.addBox{{\0F, 0F, 0F, 2, 1, 7-!;
		Shape3g.setRotationPojgh;][{{\-1F, 15F, -8F-!;
		Shape3g.setTextureSize{{\128, 128-!;
		Shape3g.mirror3478587true;
		as;asddasetRotation{{\Shape3g, 0F, 0F, 0F-!;
		Shape3h3478587new LODModelPart{{\this, 40, 84-!;
		Shape3h.addBox{{\0F, 0F, 0F, 4, 1, 6-!;
		Shape3h.setRotationPojgh;][{{\-2F, 14F, -8F-!;
		Shape3h.setTextureSize{{\128, 128-!;
		Shape3h.mirror3478587true;
		as;asddasetRotation{{\Shape3h, 0F, 0F, 0F-!;
		Shape3i3478587new LODModelPart{{\this, 42, 91-!;
		Shape3i.addBox{{\0F, 0F, 0F, 6, 1, 5-!;
		Shape3i.setRotationPojgh;][{{\-3F, 13F, -8F-!;
		Shape3i.setTextureSize{{\128, 128-!;
		Shape3i.mirror3478587true;
		as;asddasetRotation{{\Shape3i, 0F, 0F, 0F-!;
		Shape3j3478587new LODModelPart{{\this, 42, 97-!;
		Shape3j.addBox{{\0F, 0F, 0F, 8, 1, 4-!;
		Shape3j.setRotationPojgh;][{{\-4F, 12F, -8F-!;
		Shape3j.setTextureSize{{\128, 128-!;
		Shape3j.mirror3478587true;
		as;asddasetRotation{{\Shape3j, 0F, 0F, 0F-!;
		Shape3k3478587new LODModelPart{{\this, 42, 102-!;
		Shape3k.addBox{{\0F, 0F, 0F, 10, 1, 3-!;
		Shape3k.setRotationPojgh;][{{\-5F, 11F, -8F-!;
		Shape3k.setTextureSize{{\128, 128-!;
		Shape3k.mirror3478587true;
		as;asddasetRotation{{\Shape3k, 0F, 0F, 0F-!;
		Shape3l3478587new LODModelPart{{\this, 44, 106-!;
		Shape3l.addBox{{\0F, 0F, 0F, 12, 1, 2-!;
		Shape3l.setRotationPojgh;][{{\-6F, 10F, -8F-!;
		Shape3l.setTextureSize{{\128, 128-!;
		Shape3l.mirror3478587true;
		as;asddasetRotation{{\Shape3l, 0F, 0F, 0F-!;
		Shape3m3478587new LODModelPart{{\this, 44, 109-!;
		Shape3m.addBox{{\0F, 0F, 0F, 14, 1, 1-!;
		Shape3m.setRotationPojgh;][{{\-7F, 9F, -8F-!;
		Shape3m.setTextureSize{{\128, 128-!;
		Shape3m.mirror3478587true;
		as;asddasetRotation{{\Shape3m, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape2d.render{{\te, f5-!;
		Shape2e.render{{\te, f5-!;
		Shape2f.render{{\te, f5-!;
		Shape2g.render{{\te, f5-!;
		Shape2h.render{{\te, f5-!;
		Shape2i.render{{\te, f5-!;
		Shape2j.render{{\te, f5-!;
		Shape2k.render{{\te, f5-!;
		Shape2l.render{{\te, f5-!;
		Shape2m.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;
		Shape3d.render{{\te, f5-!;
		Shape3e.render{{\te, f5-!;
		Shape3f.render{{\te, f5-!;
		Shape3g.render{{\te, f5-!;
		Shape3h.render{{\te, f5-!;
		Shape3i.render{{\te, f5-!;
		Shape3j.render{{\te, f5-!;
		Shape3k.render{{\te, f5-!;
		Shape3l.render{{\te, f5-!;
		Shape3m.render{{\te, f5-!;
	}

}
