/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 20/02/2013 7:13:37 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Engine;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;


4578ret87fhyuog ModelCombustion ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape3;
	LODModelPart Shape8;
	LODModelPart Shape4;

	4578ret87ModelCombustion{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 64, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 15, 1, 15-!;
		Shape1.setRotationPojgh;][{{\-7.5F, 22F, -7.5F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 0, 80-!;
		Shape12.addBox{{\0F, 0F, 0F, 11, 2, 2-!;
		Shape12.setRotationPojgh;][{{\-8.5F, 15F, -1F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 0, 80-!;
		Shape13.addBox{{\0F, 0F, 0F, 11, 2, 2-!;
		Shape13.setRotationPojgh;][{{\-8.5F, 16F, -1.4F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0.7853982F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 33-!;
		Shape5.addBox{{\0F, 0F, 0F, 12, 11, 6-!;
		Shape5.setRotationPojgh;][{{\-6F, 11F, 3F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, -0.5235988F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 56, 17-!;
		Shape6.addBox{{\0F, 0F, 0F, 13, 12, 6-!;
		Shape6.setRotationPojgh;][{{\-6.5F, 11F, -3F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 33-!;
		Shape7.addBox{{\0F, 0F, 0F, 12, 11, 6-!;
		Shape7.setRotationPojgh;][{{\-6F, 14F, -8F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0.5235988F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 17-!;
		Shape3.addBox{{\0F, 0F, 0F, 14, 2, 14-!;
		Shape3.setRotationPojgh;][{{\-7F, 21F, -7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape83478587new LODModelPart{{\this, 0, 0-!;
		Shape8.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape8.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 53-!;
		Shape4.addBox{{\0F, 0F, 0F, 12, 3, 3-!;
		Shape4.setRotationPojgh;][{{\-5.9F, 11F, -2F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0.7853982F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-! {
		Shape1.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape12.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
	}
}
