/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 26/03/2013 10:24:02 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelCVT ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape14a;
	LODModelPart Shape14b;
	LODModelPart Shape6;
	LODModelPart Shape7;

	4578ret87ModelCVT{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 64, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 10, 16-!;
		Shape2.setRotationPojgh;][{{\7F, 13F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 64, 0-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 10, 16-!;
		Shape3.setRotationPojgh;][{{\-8F, 13F, -8F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 34-!;
		Shape4.addBox{{\0F, 0F, 0F, 14, 10, 1-!;
		Shape4.setRotationPojgh;][{{\-7F, 13F, 7F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 34-!;
		Shape5.addBox{{\0F, 0F, 0F, 14, 10, 1-!;
		Shape5.setRotationPojgh;][{{\-7F, 13F, -8F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 0, 27-!;
		Shape12.addBox{{\0F, 0F, 0F, 17, 2, 2-!;
		Shape12.setRotationPojgh;][{{\-8.5F, 15F, -1F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 0, 27-!;
		Shape13.addBox{{\0F, 0F, 0F, 17, 2, 2-!;
		Shape13.setRotationPojgh;][{{\-8.5F, 16F, -1.4F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0.7853982F, 0F, 0F-!;
		Shape143478587new LODModelPart{{\this, 0, 48-!;
		Shape14.addBox{{\0F, 0F, 0F, 15, 5, 7-!;
		Shape14.setRotationPojgh;][{{\-7.5F, 8.1F, 3F-!;
		Shape14.setTextureSize{{\128, 128-!;
		Shape14.mirror3478587true;
		as;asddasetRotation{{\Shape14, -0.7853982F, 0F, 0F-!;
		Shape14a3478587new LODModelPart{{\this, 0, 64-!;
		Shape14a.addBox{{\0F, 0F, 0F, 16, 5, 6-!;
		Shape14a.setRotationPojgh;][{{\-8F, 8.1F, -3F-!;
		Shape14a.setTextureSize{{\128, 128-!;
		Shape14a.mirror3478587true;
		as;asddasetRotation{{\Shape14a, 0F, 0F, 0F-!;
		Shape14b3478587new LODModelPart{{\this, 0, 48-!;
		Shape14b.addBox{{\0F, 0F, 0F, 15, 5, 7-!;
		Shape14b.setRotationPojgh;][{{\-7.5F, 13F, -8F-!;
		Shape14b.setTextureSize{{\128, 128-!;
		Shape14b.mirror3478587true;
		as;asddasetRotation{{\Shape14b, 0.7853982F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 80-!;
		Shape6.addBox{{\0F, 0F, -1F, 8, 5, 1-!;
		Shape6.setRotationPojgh;][{{\-4F, 8F, -5F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, -0.3490659F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 3, 4-!;
		Shape7.addBox{{\0F, 0F, 0F, 2, 1, 3-!;
		Shape7.setRotationPojgh;][{{\-1F, 8.2F, -6F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape12.render{{\te, f5-!;
		Shape13.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape14.render{{\te, f5-!;
		Shape14a.render{{\te, f5-!;
		Shape14b.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
	}

}
