/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 19/02/2014 7:29:01 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelGrindstone ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape2g;
	LODModelPart Shape2h;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape3a;
	LODModelPart Shape5;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape5a;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape7a;

	4578ret87ModelGrindstone{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 19-!;
		Shape2.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 1.396263F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 19-!;
		Shape2a.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2a.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 19-!;
		Shape2b.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2b.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0.1745329F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 19-!;
		Shape2c.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2c.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0.3490659F-!;
		Shape2d3478587new LODModelPart{{\this, 0, 19-!;
		Shape2d.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2d.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0F, 0.5235988F-!;
		Shape2e3478587new LODModelPart{{\this, 0, 19-!;
		Shape2e.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2e.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2e.setTextureSize{{\128, 128-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, 0F, 0F, 0.6981317F-!;
		Shape2f3478587new LODModelPart{{\this, 0, 19-!;
		Shape2f.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2f.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2f.setTextureSize{{\128, 128-!;
		Shape2f.mirror3478587true;
		as;asddasetRotation{{\Shape2f, 0F, 0F, 0.8726646F-!;
		Shape2g3478587new LODModelPart{{\this, 0, 19-!;
		Shape2g.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2g.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2g.setTextureSize{{\128, 128-!;
		Shape2g.mirror3478587true;
		as;asddasetRotation{{\Shape2g, 0F, 0F, 1.047198F-!;
		Shape2h3478587new LODModelPart{{\this, 0, 19-!;
		Shape2h.addBox{{\-4F, -4F, -2F, 8, 8, 4-!;
		Shape2h.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape2h.setTextureSize{{\128, 128-!;
		Shape2h.mirror3478587true;
		as;asddasetRotation{{\Shape2h, 0F, 0F, 1.22173F-!;
		Shape33478587new LODModelPart{{\this, 66, 0-!;
		Shape3.addBox{{\0F, 0F, 0F, 2, 10, 2-!;
		Shape3.setRotationPojgh;][{{\6F, 13F, 6F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 33-!;
		Shape4.addBox{{\-1F, -1F, 0F, 2, 2, 17-!;
		Shape4.setRotationPojgh;][{{\0F, 15F, -8.5F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0.7853982F-!;
		Shape4a3478587new LODModelPart{{\this, 0, 33-!;
		Shape4a.addBox{{\-1F, -1F, 0F, 2, 2, 17-!;
		Shape4a.setRotationPojgh;][{{\0F, 15F, -8.5F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 66, 0-!;
		Shape3a.addBox{{\0F, 0F, 0F, 2, 10, 2-!;
		Shape3a.setRotationPojgh;][{{\-8F, 13F, 6F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 54-!;
		Shape5.addBox{{\0F, 0F, 0F, 12, 4, 1-!;
		Shape5.setRotationPojgh;][{{\-6F, 13F, 6.5F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 66, 0-!;
		Shape3b.addBox{{\0F, 0F, 0F, 2, 10, 2-!;
		Shape3b.setRotationPojgh;][{{\6F, 13F, -8F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 66, 0-!;
		Shape3c.addBox{{\0F, 0F, 0F, 2, 10, 2-!;
		Shape3c.setRotationPojgh;][{{\-8F, 13F, -8F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 54-!;
		Shape5a.addBox{{\0F, 0F, 0F, 12, 4, 1-!;
		Shape5a.setRotationPojgh;][{{\-6F, 13F, -7.5F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 61-!;
		Shape6.addBox{{\0F, 0F, 0F, 1, 1, 4-!;
		Shape6.setRotationPojgh;][{{\-8F, 22F, -2F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 80-!;
		Shape7.addBox{{\-3F, -3F, 0F, 6, 6, 5-!;
		Shape7.setRotationPojgh;][{{\0F, 15F, -2.5F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0.7853982F-!;
		Shape7a3478587new LODModelPart{{\this, 0, 67-!;
		Shape7a.addBox{{\-3F, -3F, 0F, 6, 6, 6-!;
		Shape7a.setRotationPojgh;][{{\0F, 15F, -3F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;

		60-78-078d34785870.9375;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape2d.render{{\te, f5-!;
		Shape2e.render{{\te, f5-!;
		Shape2f.render{{\te, f5-!;
		Shape2g.render{{\te, f5-!;
		Shape2h.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;

		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape7a.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
