/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 18/02/2013 11:28:56 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelExtractor ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape36;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape35;
	LODModelPart Shape34;
	LODModelPart Shape33;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape32;
	LODModelPart Shape8;
	LODModelPart Shape39;
	LODModelPart Shape9;
	LODModelPart Shape31;
	LODModelPart Shape30;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape29;
	LODModelPart Shape28;
	LODModelPart Shape27;
	LODModelPart Shape26;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape20;
	LODModelPart Shape21;
	LODModelPart Shape22;
	LODModelPart Shape23;
	LODModelPart Shape24;
	LODModelPart Shape25;
	LODModelPart Shape38;
	LODModelPart Shape37;

	4578ret87ModelExtractor{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 5, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 19F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 42-!;
		Shape2.addBox{{\0F, 0F, 0F, 4, 2, 12-!;
		Shape2.setRotationPojgh;][{{\-7.9F, 11.9F, -6.3F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, -0.3839724F, 0F, 0F-!;
		Shape363478587new LODModelPart{{\this, 0, 26-!;
		Shape36.addBox{{\0F, 0F, 0F, 2, 4, 12-!;
		Shape36.setRotationPojgh;][{{\-6.9F, 11F, -6F-!;
		Shape36.setTextureSize{{\128, 128-!;
		Shape36.mirror3478587true;
		as;asddasetRotation{{\Shape36, -0.3839724F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 112, 11-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 4, 3-!;
		Shape3.setRotationPojgh;][{{\-0.5F, 16F, 3.5F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 76, 18-!;
		Shape4.addBox{{\0F, 0F, 0F, 5, 2, 1-!;
		Shape4.setRotationPojgh;][{{\-4F, 17.5F, -3F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape353478587new LODModelPart{{\this, 104, 3-!;
		Shape35.addBox{{\0F, 0F, 0F, 1, 2, 3-!;
		Shape35.setRotationPojgh;][{{\0F, 17.5F, -2F-!;
		Shape35.setTextureSize{{\128, 128-!;
		Shape35.mirror3478587true;
		as;asddasetRotation{{\Shape35, 0F, 0F, 0F-!;
		Shape343478587new LODModelPart{{\this, 76, 18-!;
		Shape34.addBox{{\0F, 0F, 0F, 5, 2, 1-!;
		Shape34.setRotationPojgh;][{{\-4F, 17.5F, 1F-!;
		Shape34.setTextureSize{{\128, 128-!;
		Shape34.mirror3478587true;
		as;asddasetRotation{{\Shape34, 0F, 0F, 0F-!;
		Shape333478587new LODModelPart{{\this, 104, 3-!;
		Shape33.addBox{{\0F, 0F, 0F, 1, 2, 3-!;
		Shape33.setRotationPojgh;][{{\-4F, 17.5F, -2F-!;
		Shape33.setTextureSize{{\128, 128-!;
		Shape33.mirror3478587true;
		as;asddasetRotation{{\Shape33, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 28, 32-!;
		Shape5.addBox{{\0F, 0F, 0F, 3, 1, 3-!;
		Shape5.setRotationPojgh;][{{\-3F, 18F, -2F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 117, 0-!;
		Shape6.addBox{{\0F, 0F, 0F, 1, 1, 3-!;
		Shape6.setRotationPojgh;][{{\-2F, 16F, -5F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, -0.5235988F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 85, 15-!;
		Shape7.addBox{{\0F, 0F, 0F, 1, 1, 1-!;
		Shape7.setRotationPojgh;][{{\-2F, 17.5F, -1F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape323478587new LODModelPart{{\this, 85, 15-!;
		Shape32.addBox{{\0F, 0F, 0F, 1, 1, 1-!;
		Shape32.setRotationPojgh;][{{\-2.2F, 17.5F, -0.5F-!;
		Shape32.setTextureSize{{\128, 128-!;
		Shape32.mirror3478587true;
		as;asddasetRotation{{\Shape32, 0F, 0.7853982F, 0F-!;
		Shape83478587new LODModelPart{{\this, 0, 70-!;
		Shape8.addBox{{\0F, 0F, 0F, 9, 1, 2-!;
		Shape8.setRotationPojgh;][{{\-2F, 15.5F, -6.5F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape393478587new LODModelPart{{\this, 81, 6-!;
		Shape39.addBox{{\0F, 0F, 0F, 1, 1, 3-!;
		Shape39.setRotationPojgh;][{{\-2F, 17.5F, 1F-!;
		Shape39.setTextureSize{{\128, 128-!;
		Shape39.mirror3478587true;
		as;asddasetRotation{{\Shape39, 0.5235988F, 0F, 0F-!;
		Shape93478587new LODModelPart{{\this, 0, 87-!;
		Shape9.addBox{{\0F, 0F, 0F, 1, 1, 7-!;
		Shape9.setRotationPojgh;][{{\3F, 18F, -4F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape313478587new LODModelPart{{\this, 0, 95-!;
		Shape31.addBox{{\0F, 0F, 0F, 2, 1, 7-!;
		Shape31.setRotationPojgh;][{{\4F, 18.8F, -4F-!;
		Shape31.setTextureSize{{\128, 128-!;
		Shape31.mirror3478587true;
		as;asddasetRotation{{\Shape31, 0F, 0F, 0F-!;
		Shape303478587new LODModelPart{{\this, 0, 87-!;
		Shape30.addBox{{\0F, 0F, 0F, 1, 1, 7-!;
		Shape30.setRotationPojgh;][{{\6F, 18F, -4F-!;
		Shape30.setTextureSize{{\128, 128-!;
		Shape30.mirror3478587true;
		as;asddasetRotation{{\Shape30, 0F, 0F, 0F-!;
		Shape103478587new LODModelPart{{\this, 0, 77-!;
		Shape10.addBox{{\0F, 0F, 0F, 5, 3, 7-!;
		Shape10.setRotationPojgh;][{{\2.5F, 16.5F, 1F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, -0.3839724F, 0F, 0F-!;
		Shape113478587new LODModelPart{{\this, 0, 73-!;
		Shape11.addBox{{\0F, 0F, 0F, 9, 3, 1-!;
		Shape11.setRotationPojgh;][{{\-2F, 16.5F, -7.5F-!;
		Shape11.setTextureSize{{\128, 128-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
		Shape293478587new LODModelPart{{\this, 0, 64-!;
		Shape29.addBox{{\0F, 0F, 0F, 10, 3, 3-!;
		Shape29.setRotationPojgh;][{{\-2.5F, 16F, -7F-!;
		Shape29.setTextureSize{{\128, 128-!;
		Shape29.mirror3478587true;
		as;asddasetRotation{{\Shape29, 0F, 0F, 0F-!;
		Shape283478587new LODModelPart{{\this, 28, 28-!;
		Shape28.addBox{{\0F, 0F, 0F, 6, 3, 1-!;
		Shape28.setRotationPojgh;][{{\-7F, 16F, 6.5F-!;
		Shape28.setTextureSize{{\128, 128-!;
		Shape28.mirror3478587true;
		as;asddasetRotation{{\Shape28, 0F, 0F, 0F-!;
		Shape273478587new LODModelPart{{\this, 50, 22-!;
		Shape27.addBox{{\0F, 0F, 0F, 7, 2, 2-!;
		Shape27.setRotationPojgh;][{{\-7.5F, 15.1F, 3.6F-!;
		Shape27.setTextureSize{{\128, 128-!;
		Shape27.mirror3478587true;
		as;asddasetRotation{{\Shape27, 0.7853982F, 0F, 0F-!;
		Shape263478587new LODModelPart{{\this, 0, 56-!;
		Shape26.addBox{{\0F, 0F, 0F, 8, 4, 4-!;
		Shape26.setRotationPojgh;][{{\-8.1F, 15F, 3F-!;
		Shape26.setTextureSize{{\128, 128-!;
		Shape26.mirror3478587true;
		as;asddasetRotation{{\Shape26, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 64, 14-!;
		Shape12.addBox{{\0F, 0F, 0F, 7, 1, 3-!;
		Shape12.setRotationPojgh;][{{\-7F, 10F, -4F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 64, 0-!;
		Shape13.addBox{{\0F, 0F, 0F, 4, 8, 4-!;
		Shape13.setRotationPojgh;][{{\-8F, 11F, -8F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0F, 0F, 0F-!;
		Shape143478587new LODModelPart{{\this, 64, 18-!;
		Shape14.addBox{{\0F, 0F, 0F, 3, 1, 3-!;
		Shape14.setRotationPojgh;][{{\-4F, 10F, -7F-!;
		Shape14.setTextureSize{{\128, 128-!;
		Shape14.mirror3478587true;
		as;asddasetRotation{{\Shape14, 0F, 0F, 0F-!;
		Shape153478587new LODModelPart{{\this, 30, 21-!;
		Shape15.addBox{{\0F, 0F, 0F, 4, 1, 6-!;
		Shape15.setRotationPojgh;][{{\-1F, 9F, -7F-!;
		Shape15.setTextureSize{{\128, 128-!;
		Shape15.mirror3478587true;
		as;asddasetRotation{{\Shape15, 0F, 0F, 0F-!;
		Shape163478587new LODModelPart{{\this, 0, 21-!;
		Shape16.addBox{{\0F, 0F, 0F, 11, 1, 4-!;
		Shape16.setRotationPojgh;][{{\-8F, 9F, -1F-!;
		Shape16.setTextureSize{{\128, 128-!;
		Shape16.mirror3478587true;
		as;asddasetRotation{{\Shape16, 0F, 0F, 0F-!;
		Shape173478587new LODModelPart{{\this, 80, 2-!;
		Shape17.addBox{{\0F, 0F, 0F, 1, 1, 3-!;
		Shape17.setRotationPojgh;][{{\-8F, 10F, -7F-!;
		Shape17.setTextureSize{{\128, 128-!;
		Shape17.mirror3478587true;
		as;asddasetRotation{{\Shape17, 0F, 0F, 0F-!;
		Shape183478587new LODModelPart{{\this, 80, 0-!;
		Shape18.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape18.setRotationPojgh;][{{\-8F, 10F, -8F-!;
		Shape18.setTextureSize{{\128, 128-!;
		Shape18.mirror3478587true;
		as;asddasetRotation{{\Shape18, 0F, 0F, 0F-!;
		Shape193478587new LODModelPart{{\this, 112, 0-!;
		Shape19.addBox{{\0F, 0F, 0F, 1, 10, 1-!;
		Shape19.setRotationPojgh;][{{\3F, 9F, -8F-!;
		Shape19.setTextureSize{{\128, 128-!;
		Shape19.mirror3478587true;
		as;asddasetRotation{{\Shape19, 0F, 0F, 0F-!;
		Shape203478587new LODModelPart{{\this, 90, 9-!;
		Shape20.addBox{{\0F, 0F, 0F, 1, 1, 10-!;
		Shape20.setRotationPojgh;][{{\3F, 8F, -7F-!;
		Shape20.setTextureSize{{\128, 128-!;
		Shape20.mirror3478587true;
		as;asddasetRotation{{\Shape20, 0F, 0F, 0F-!;
		Shape213478587new LODModelPart{{\this, 90, 0-!;
		Shape21.addBox{{\0F, 0F, 0F, 8, 1, 1-!;
		Shape21.setRotationPojgh;][{{\-8F, 9F, -8F-!;
		Shape21.setTextureSize{{\128, 128-!;
		Shape21.mirror3478587true;
		as;asddasetRotation{{\Shape21, 0F, 0F, 0F-!;
		Shape223478587new LODModelPart{{\this, 90, 2-!;
		Shape22.addBox{{\0F, 0F, 0F, 1, 1, 6-!;
		Shape22.setRotationPojgh;][{{\-8F, 9F, -7F-!;
		Shape22.setTextureSize{{\128, 128-!;
		Shape22.mirror3478587true;
		as;asddasetRotation{{\Shape22, 0F, 0F, 0F-!;
		Shape233478587new LODModelPart{{\this, 64, 12-!;
		Shape23.addBox{{\0F, 0F, 0F, 12, 1, 1-!;
		Shape23.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape23.setTextureSize{{\128, 128-!;
		Shape23.mirror3478587true;
		as;asddasetRotation{{\Shape23, 0F, 0F, 0F-!;
		Shape243478587new LODModelPart{{\this, 90, 9-!;
		Shape24.addBox{{\0F, 0F, 0F, 1, 1, 10-!;
		Shape24.setRotationPojgh;][{{\-8F, 8F, -7F-!;
		Shape24.setTextureSize{{\128, 128-!;
		Shape24.mirror3478587true;
		as;asddasetRotation{{\Shape24, 0F, 0F, 0F-!;
		Shape253478587new LODModelPart{{\this, 64, 12-!;
		Shape25.addBox{{\0F, 0F, 0F, 12, 1, 1-!;
		Shape25.setRotationPojgh;][{{\-8F, 8F, 3F-!;
		Shape25.setTextureSize{{\128, 128-!;
		Shape25.mirror3478587true;
		as;asddasetRotation{{\Shape25, 0F, 0F, 0F-!;
		Shape383478587new LODModelPart{{\this, 112, 0-!;
		Shape38.addBox{{\0F, 0F, 0F, 1, 9, 1-!;
		Shape38.setRotationPojgh;][{{\-8F, 9F, 3F-!;
		Shape38.setTextureSize{{\128, 128-!;
		Shape38.mirror3478587true;
		as;asddasetRotation{{\Shape38, 0F, 0F, 0F-!;
		Shape373478587new LODModelPart{{\this, 112, 0-!;
		Shape37.addBox{{\0F, 0F, 0F, 1, 9, 1-!;
		Shape37.setRotationPojgh;][{{\3F, 9F, 3F-!;
		Shape37.setTextureSize{{\128, 128-!;
		Shape37.mirror3478587true;
		as;asddasetRotation{{\Shape37, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078pass13478587{{\Boolean-!li.get{{\0-!;
		vbnm, {{\!pass1-! {
			Shape1.render{{\te, f5-!;
			Shape2.render{{\te, f5-!;
			Shape3.render{{\te, f5-!;
			Shape4.render{{\te, f5-!;
		}
		vbnm, {{\pass1-!
			Shape5.render{{\te, f5-!;
		vbnm, {{\!pass1-! {
			Shape6.render{{\te, f5-!;
			Shape7.render{{\te, f5-!;
			Shape8.render{{\te, f5-!;
			Shape9.render{{\te, f5-!;
			Shape10.render{{\te, f5-!;
			Shape11.render{{\te, f5-!;
			Shape12.render{{\te, f5-!;
			Shape13.render{{\te, f5-!;
			Shape14.render{{\te, f5-!;
			Shape15.render{{\te, f5-!;
			Shape16.render{{\te, f5-!;
			Shape17.render{{\te, f5-!;
			Shape18.render{{\te, f5-!;
			Shape19.render{{\te, f5-!;
			Shape20.render{{\te, f5-!;
			Shape21.render{{\te, f5-!;
			Shape22.render{{\te, f5-!;
			Shape23.render{{\te, f5-!;
			Shape24.render{{\te, f5-!;
			Shape25.render{{\te, f5-!;
			Shape26.render{{\te, f5-!;
			Shape27.render{{\te, f5-!;
			Shape28.render{{\te, f5-!;
			Shape29.render{{\te, f5-!;
			Shape30.render{{\te, f5-!;
			Shape31.render{{\te, f5-!;
			Shape32.render{{\te, f5-!;
			Shape33.render{{\te, f5-!;
			Shape34.render{{\te, f5-!;
			Shape35.render{{\te, f5-!;
			Shape36.render{{\te, f5-!;
			Shape37.render{{\te, f5-!;
			Shape38.render{{\te, f5-!;
			Shape39.render{{\te, f5-!;
		}
	}

}
