/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 13/03/2013 8:20:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelDetector ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape4;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape2p;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape3f;
	LODModelPart Shape3g;
	LODModelPart Shape3h;
	LODModelPart Shape3j;
	LODModelPart Shape2g;
	LODModelPart Shape2h;
	LODModelPart Shape3i;
	LODModelPart Shape3k;
	LODModelPart Shape2i;
	LODModelPart Shape2j;
	LODModelPart Shape2k;
	LODModelPart Shape2l;
	LODModelPart Shape3l;
	LODModelPart Shape3m;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape5;
	LODModelPart Shape6;

	4578ret87ModelDetector{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 64, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 8, 1, 8-!;
		Shape1.setRotationPojgh;][{{\-4F, 22F, -4F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 43-!;
		Shape2.addBox{{\0F, 0F, 0F, 3, 2, 1-!;
		Shape2.setRotationPojgh;][{{\3F, 19F, 5F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 43-!;
		Shape2a.addBox{{\0F, 0F, 0F, 3, 2, 1-!;
		Shape2a.setRotationPojgh;][{{\3F, 19F, -6F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 38-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 2, 2-!;
		Shape3.setRotationPojgh;][{{\-6F, 19F, 3F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 38-!;
		Shape3a.addBox{{\0F, 0F, 0F, 1, 2, 2-!;
		Shape3a.setRotationPojgh;][{{\5F, 19F, 3F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 0, 50-!;
		Shape3b.addBox{{\0F, 0F, 0F, 1, 1, 2-!;
		Shape3b.setRotationPojgh;][{{\-5F, 21F, 2F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 0, 50-!;
		Shape3c.addBox{{\0F, 0F, 0F, 1, 1, 2-!;
		Shape3c.setRotationPojgh;][{{\4F, 21F, 2F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 47-!;
		Shape2b.addBox{{\0F, 0F, 0F, 3, 1, 1-!;
		Shape2b.setRotationPojgh;][{{\2F, 21F, -5F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 27-!;
		Shape2c.addBox{{\0F, 0F, 0F, 6, 2, 1-!;
		Shape2c.setRotationPojgh;][{{\-3F, 19F, -7F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 116, 0-!;
		Shape4.addBox{{\-0.5F, 0F, -0.5F, 1, 8, 1-!;
		Shape4.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, -0.2617994F-!;
		Shape3d3478587new LODModelPart{{\this, 0, 38-!;
		Shape3d.addBox{{\0F, 0F, 0F, 1, 2, 2-!;
		Shape3d.setRotationPojgh;][{{\-6F, 19F, -5F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, 0F, 0F-!;
		Shape3e3478587new LODModelPart{{\this, 0, 38-!;
		Shape3e.addBox{{\0F, 0F, 0F, 1, 2, 2-!;
		Shape3e.setRotationPojgh;][{{\5F, 19F, -5F-!;
		Shape3e.setTextureSize{{\128, 128-!;
		Shape3e.mirror3478587true;
		as;asddasetRotation{{\Shape3e, 0F, 0F, 0F-!;
		Shape2p3478587new LODModelPart{{\this, 0, 43-!;
		Shape2p.addBox{{\0F, 0F, 0F, 3, 2, 1-!;
		Shape2p.setRotationPojgh;][{{\-6F, 19F, -6F-!;
		Shape2p.setTextureSize{{\128, 128-!;
		Shape2p.mirror3478587true;
		as;asddasetRotation{{\Shape2p, 0F, 0F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 0, 43-!;
		Shape2d.addBox{{\0F, 0F, 0F, 3, 2, 1-!;
		Shape2d.setRotationPojgh;][{{\-6F, 19F, 5F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0F, 0F-!;
		Shape2e3478587new LODModelPart{{\this, 0, 47-!;
		Shape2e.addBox{{\0F, 0F, 0F, 3, 1, 1-!;
		Shape2e.setRotationPojgh;][{{\-5F, 21F, -5F-!;
		Shape2e.setTextureSize{{\128, 128-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, 0F, 0F, 0F-!;
		Shape2f3478587new LODModelPart{{\this, 0, 47-!;
		Shape2f.addBox{{\0F, 0F, 0F, 3, 1, 1-!;
		Shape2f.setRotationPojgh;][{{\-5F, 21F, 4F-!;
		Shape2f.setTextureSize{{\128, 128-!;
		Shape2f.mirror3478587true;
		as;asddasetRotation{{\Shape2f, 0F, 0F, 0F-!;
		Shape3f3478587new LODModelPart{{\this, 0, 50-!;
		Shape3f.addBox{{\0F, 0F, 0F, 1, 1, 2-!;
		Shape3f.setRotationPojgh;][{{\-5F, 21F, -4F-!;
		Shape3f.setTextureSize{{\128, 128-!;
		Shape3f.mirror3478587true;
		as;asddasetRotation{{\Shape3f, 0F, 0F, 0F-!;
		Shape3g3478587new LODModelPart{{\this, 0, 30-!;
		Shape3g.addBox{{\0F, 0F, 0F, 1, 2, 6-!;
		Shape3g.setRotationPojgh;][{{\-7F, 19F, -3F-!;
		Shape3g.setTextureSize{{\128, 128-!;
		Shape3g.mirror3478587true;
		as;asddasetRotation{{\Shape3g, 0F, 0F, 0F-!;
		Shape3h3478587new LODModelPart{{\this, 0, 50-!;
		Shape3h.addBox{{\0F, 0F, 0F, 1, 1, 2-!;
		Shape3h.setRotationPojgh;][{{\4F, 21F, -4F-!;
		Shape3h.setTextureSize{{\128, 128-!;
		Shape3h.mirror3478587true;
		as;asddasetRotation{{\Shape3h, 0F, 0F, 0F-!;
		Shape3j3478587new LODModelPart{{\this, 0, 30-!;
		Shape3j.addBox{{\0F, 0F, 0F, 1, 2, 6-!;
		Shape3j.setRotationPojgh;][{{\6F, 19F, -3F-!;
		Shape3j.setTextureSize{{\128, 128-!;
		Shape3j.mirror3478587true;
		as;asddasetRotation{{\Shape3j, 0F, 0F, 0F-!;
		Shape2g3478587new LODModelPart{{\this, 0, 47-!;
		Shape2g.addBox{{\0F, 0F, 0F, 3, 1, 1-!;
		Shape2g.setRotationPojgh;][{{\2F, 21F, 4F-!;
		Shape2g.setTextureSize{{\128, 128-!;
		Shape2g.mirror3478587true;
		as;asddasetRotation{{\Shape2g, 0F, 0F, 0F-!;
		Shape2h3478587new LODModelPart{{\this, 0, 27-!;
		Shape2h.addBox{{\0F, 0F, 0F, 6, 2, 1-!;
		Shape2h.setRotationPojgh;][{{\-3F, 19F, 6F-!;
		Shape2h.setTextureSize{{\128, 128-!;
		Shape2h.mirror3478587true;
		as;asddasetRotation{{\Shape2h, 0F, 0F, 0F-!;
		Shape3i3478587new LODModelPart{{\this, 96, 0-!;
		Shape3i.addBox{{\0F, 0F, 0F, 1, 1, 4-!;
		Shape3i.setRotationPojgh;][{{\-5F, 22F, -2F-!;
		Shape3i.setTextureSize{{\128, 128-!;
		Shape3i.mirror3478587true;
		as;asddasetRotation{{\Shape3i, 0F, 0F, 0F-!;
		Shape3k3478587new LODModelPart{{\this, 96, 0-!;
		Shape3k.addBox{{\0F, 0F, 0F, 1, 1, 4-!;
		Shape3k.setRotationPojgh;][{{\4F, 22F, -2F-!;
		Shape3k.setTextureSize{{\128, 128-!;
		Shape3k.mirror3478587true;
		as;asddasetRotation{{\Shape3k, 0F, 0F, 0F-!;
		Shape2i3478587new LODModelPart{{\this, 106, 0-!;
		Shape2i.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape2i.setRotationPojgh;][{{\-2F, 22F, 4F-!;
		Shape2i.setTextureSize{{\128, 128-!;
		Shape2i.mirror3478587true;
		as;asddasetRotation{{\Shape2i, 0F, 0F, 0F-!;
		Shape2j3478587new LODModelPart{{\this, 106, 0-!;
		Shape2j.addBox{{\0F, 0F, 0F, 4, 1, 1-!;
		Shape2j.setRotationPojgh;][{{\-2F, 22F, -5F-!;
		Shape2j.setTextureSize{{\128, 128-!;
		Shape2j.mirror3478587true;
		as;asddasetRotation{{\Shape2j, 0F, 0F, 0F-!;
		Shape2k3478587new LODModelPart{{\this, 0, 18-!;
		Shape2k.addBox{{\0F, 0F, 0F, 6, 1, 1-!;
		Shape2k.setRotationPojgh;][{{\-3F, 21F, 5F-!;
		Shape2k.setTextureSize{{\128, 128-!;
		Shape2k.mirror3478587true;
		as;asddasetRotation{{\Shape2k, 0F, 0F, 0F-!;
		Shape2l3478587new LODModelPart{{\this, 0, 18-!;
		Shape2l.addBox{{\0F, 0F, 0F, 6, 1, 1-!;
		Shape2l.setRotationPojgh;][{{\-3F, 21F, -6F-!;
		Shape2l.setTextureSize{{\128, 128-!;
		Shape2l.mirror3478587true;
		as;asddasetRotation{{\Shape2l, 0F, 0F, 0F-!;
		Shape3l3478587new LODModelPart{{\this, 0, 20-!;
		Shape3l.addBox{{\0F, 0F, 0F, 1, 1, 6-!;
		Shape3l.setRotationPojgh;][{{\5F, 21F, -3F-!;
		Shape3l.setTextureSize{{\128, 128-!;
		Shape3l.mirror3478587true;
		as;asddasetRotation{{\Shape3l, 0F, 0F, 0F-!;
		Shape3m3478587new LODModelPart{{\this, 0, 20-!;
		Shape3m.addBox{{\0F, 0F, 0F, 1, 1, 6-!;
		Shape3m.setRotationPojgh;][{{\-6F, 21F, -3F-!;
		Shape3m.setTextureSize{{\128, 128-!;
		Shape3m.mirror3478587true;
		as;asddasetRotation{{\Shape3m, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 116, 0-!;
		Shape4a.addBox{{\-0.5F, 0F, -0.5F, 1, 8, 1-!;
		Shape4a.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0.2617994F-!;
		Shape4b3478587new LODModelPart{{\this, 116, 0-!;
		Shape4b.addBox{{\-0.5F, 0F, -0.5F, 1, 8, 1-!;
		Shape4b.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 0.2617994F, 0F, 0F-!;
		Shape4c3478587new LODModelPart{{\this, 116, 0-!;
		Shape4c.addBox{{\-0.5F, 0F, -0.5F, 1, 8, 1-!;
		Shape4c.setRotationPojgh;][{{\0F, 15F, 0F-!;
		Shape4c.setTextureSize{{\128, 128-!;
		Shape4c.mirror3478587true;
		as;asddasetRotation{{\Shape4c, -0.2617994F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 107, 2-!;
		Shape5.addBox{{\-1F, 0F, -1F, 2, 3, 2-!;
		Shape5.setRotationPojgh;][{{\0F, 13F, 0F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 0-!;
		Shape6.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape6.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape3d.render{{\te, f5-!;
		Shape3e.render{{\te, f5-!;
		Shape2p.render{{\te, f5-!;
		Shape2d.render{{\te, f5-!;
		Shape2e.render{{\te, f5-!;
		Shape2f.render{{\te, f5-!;
		Shape3f.render{{\te, f5-!;
		Shape3g.render{{\te, f5-!;
		Shape3h.render{{\te, f5-!;
		Shape3j.render{{\te, f5-!;
		Shape2g.render{{\te, f5-!;
		Shape2h.render{{\te, f5-!;
		Shape3i.render{{\te, f5-!;
		Shape3k.render{{\te, f5-!;
		Shape2i.render{{\te, f5-!;
		Shape2j.render{{\te, f5-!;
		Shape2k.render{{\te, f5-!;
		Shape2l.render{{\te, f5-!;
		Shape3l.render{{\te, f5-!;
		Shape3m.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;
		Shape4c.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
	}

}
