/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 28/12/2013 4:51:42 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelCrystallizer ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;
	LODModelPart Shape5f;
	LODModelPart Shape5g;
	LODModelPart Shape5h;
	LODModelPart Shape5i;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6b;
	LODModelPart Shape6c;
	LODModelPart Shape6d;
	LODModelPart Shape6e;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape8;
	LODModelPart Shape8a;
	LODModelPart Shape9;

	4578ret87ModelCrystallizer{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 65, 0-!;
		Shape2.addBox{{\-1F, -1F, 0F, 2, 2, 4-!;
		Shape2.setRotationPojgh;][{{\0F, 16F, 4.5F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0.7853982F-!;
		Shape2a3478587new LODModelPart{{\this, 65, 0-!;
		Shape2a.addBox{{\-1F, -1F, 0F, 2, 2, 4-!;
		Shape2a.setRotationPojgh;][{{\0F, 16F, 4.5F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 78, 0-!;
		Shape3.addBox{{\-1F, -6F, 0F, 2, 12, 1-!;
		Shape3.setRotationPojgh;][{{\0F, 16F, 6F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 2.356194F-!;
		Shape3a3478587new LODModelPart{{\this, 78, 0-!;
		Shape3a.addBox{{\-1F, -6F, 0F, 2, 12, 1-!;
		Shape3a.setRotationPojgh;][{{\0F, 16F, 6F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 78, 0-!;
		Shape3b.addBox{{\-1F, -6F, 0F, 2, 12, 1-!;
		Shape3b.setRotationPojgh;][{{\0F, 16F, 6F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0.7853982F-!;
		Shape3c3478587new LODModelPart{{\this, 78, 0-!;
		Shape3c.addBox{{\-1F, -6F, 0F, 2, 12, 1-!;
		Shape3c.setRotationPojgh;][{{\0F, 16F, 6F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 1.570796F-!;
		Shape43478587new LODModelPart{{\this, 0, 19-!;
		Shape4.addBox{{\0F, 0F, 0F, 13, 15, 12-!;
		Shape4.setRotationPojgh;][{{\-6.5F, 8.5F, -6F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 85, 0-!;
		Shape5.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5.setRotationPojgh;][{{\5.5F, 21F, -6F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 85, 0-!;
		Shape5a.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5a.setRotationPojgh;][{{\-7.5F, 9F, -6F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape5b3478587new LODModelPart{{\this, 85, 0-!;
		Shape5b.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5b.setRotationPojgh;][{{\-7.5F, 21F, -6F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, 0F, 0F, 0F-!;
		Shape5c3478587new LODModelPart{{\this, 85, 0-!;
		Shape5c.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5c.setRotationPojgh;][{{\5.5F, 15F, -6F-!;
		Shape5c.setTextureSize{{\128, 128-!;
		Shape5c.mirror3478587true;
		as;asddasetRotation{{\Shape5c, 0F, 0F, 0F-!;
		Shape5d3478587new LODModelPart{{\this, 85, 0-!;
		Shape5d.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5d.setRotationPojgh;][{{\5.5F, 18F, -6F-!;
		Shape5d.setTextureSize{{\128, 128-!;
		Shape5d.mirror3478587true;
		as;asddasetRotation{{\Shape5d, 0F, 0F, 0F-!;
		Shape5e3478587new LODModelPart{{\this, 85, 0-!;
		Shape5e.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5e.setRotationPojgh;][{{\5.5F, 9F, -6F-!;
		Shape5e.setTextureSize{{\128, 128-!;
		Shape5e.mirror3478587true;
		as;asddasetRotation{{\Shape5e, 0F, 0F, 0F-!;
		Shape5f3478587new LODModelPart{{\this, 85, 0-!;
		Shape5f.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5f.setRotationPojgh;][{{\5.5F, 12F, -6F-!;
		Shape5f.setTextureSize{{\128, 128-!;
		Shape5f.mirror3478587true;
		as;asddasetRotation{{\Shape5f, 0F, 0F, 0F-!;
		Shape5g3478587new LODModelPart{{\this, 85, 0-!;
		Shape5g.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5g.setRotationPojgh;][{{\-7.5F, 12F, -6F-!;
		Shape5g.setTextureSize{{\128, 128-!;
		Shape5g.mirror3478587true;
		as;asddasetRotation{{\Shape5g, 0F, 0F, 0F-!;
		Shape5h3478587new LODModelPart{{\this, 85, 0-!;
		Shape5h.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5h.setRotationPojgh;][{{\-7.5F, 15F, -6F-!;
		Shape5h.setTextureSize{{\128, 128-!;
		Shape5h.mirror3478587true;
		as;asddasetRotation{{\Shape5h, 0F, 0F, 0F-!;
		Shape5i3478587new LODModelPart{{\this, 85, 0-!;
		Shape5i.addBox{{\0F, 0F, 0F, 2, 1, 11-!;
		Shape5i.setRotationPojgh;][{{\-7.5F, 18F, -6F-!;
		Shape5i.setTextureSize{{\128, 128-!;
		Shape5i.mirror3478587true;
		as;asddasetRotation{{\Shape5i, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 47-!;
		Shape6.addBox{{\0F, 0F, 0F, 1, 1, 11-!;
		Shape6.setRotationPojgh;][{{\-6F, 8F, -6F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 47-!;
		Shape6a.addBox{{\0F, 0F, 0F, 1, 1, 11-!;
		Shape6a.setRotationPojgh;][{{\5F, 8F, -6F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0F-!;
		Shape6b3478587new LODModelPart{{\this, 0, 47-!;
		Shape6b.addBox{{\0F, 0F, 0F, 1, 1, 11-!;
		Shape6b.setRotationPojgh;][{{\3F, 8F, -6F-!;
		Shape6b.setTextureSize{{\128, 128-!;
		Shape6b.mirror3478587true;
		as;asddasetRotation{{\Shape6b, 0F, 0F, 0F-!;
		Shape6c3478587new LODModelPart{{\this, 0, 47-!;
		Shape6c.addBox{{\0F, 0F, 0F, 1, 1, 11-!;
		Shape6c.setRotationPojgh;][{{\1F, 8F, -6F-!;
		Shape6c.setTextureSize{{\128, 128-!;
		Shape6c.mirror3478587true;
		as;asddasetRotation{{\Shape6c, 0F, 0F, 0F-!;
		Shape6d3478587new LODModelPart{{\this, 0, 47-!;
		Shape6d.addBox{{\0F, 0F, 0F, 1, 1, 11-!;
		Shape6d.setRotationPojgh;][{{\-2F, 8F, -6F-!;
		Shape6d.setTextureSize{{\128, 128-!;
		Shape6d.mirror3478587true;
		as;asddasetRotation{{\Shape6d, 0F, 0F, 0F-!;
		Shape6e3478587new LODModelPart{{\this, 0, 47-!;
		Shape6e.addBox{{\0F, 0F, 0F, 1, 1, 11-!;
		Shape6e.setRotationPojgh;][{{\-4F, 8F, -6F-!;
		Shape6e.setTextureSize{{\128, 128-!;
		Shape6e.mirror3478587true;
		as;asddasetRotation{{\Shape6e, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 61-!;
		Shape7.addBox{{\0F, 0F, 0F, 13, 1, 1-!;
		Shape7.setRotationPojgh;][{{\-6.5F, 8.5F, -7F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape7a3478587new LODModelPart{{\this, 0, 64-!;
		Shape7a.addBox{{\0F, 0F, 0F, 13, 1, 1-!;
		Shape7a.setRotationPojgh;][{{\-6.5F, 22.5F, -7F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, 0F, 0F-!;
		Shape83478587new LODModelPart{{\this, 118, 0-!;
		Shape8.addBox{{\0F, 0F, 0F, 1, 13, 1-!;
		Shape8.setRotationPojgh;][{{\5.5F, 9.5F, -7F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape8a3478587new LODModelPart{{\this, 113, 0-!;
		Shape8a.addBox{{\0F, 0F, 0F, 1, 13, 1-!;
		Shape8a.setRotationPojgh;][{{\-6.5F, 9.5F, -7F-!;
		Shape8a.setTextureSize{{\128, 128-!;
		Shape8a.mirror3478587true;
		as;asddasetRotation{{\Shape8a, 0F, 0F, 0F-!;
		Shape93478587new LODModelPart{{\this, 0, 68-!;
		Shape9.addBox{{\0F, 0F, 0F, 10, 12, 1-!;
		Shape9.setRotationPojgh;][{{\-5F, 10F, -7F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;

		60-78-078d34785871;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;

		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape5b.render{{\te, f5-!;
		Shape5c.render{{\te, f5-!;
		Shape5d.render{{\te, f5-!;
		Shape5e.render{{\te, f5-!;
		Shape5f.render{{\te, f5-!;
		Shape5g.render{{\te, f5-!;
		Shape5h.render{{\te, f5-!;
		Shape5i.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape6b.render{{\te, f5-!;
		Shape6c.render{{\te, f5-!;
		Shape6d.render{{\te, f5-!;
		Shape6e.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape7a.render{{\te, f5-!;
		Shape8.render{{\te, f5-!;
		Shape8a.render{{\te, f5-!;
		Shape9.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
