/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 16/02/2013 11:10:58 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;


4578ret87fhyuog ModelPump ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;

	4578ret87ModelPump{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 36, 29-!;
		Shape2.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape2.setRotationPojgh;][{{\-1F, 22.5F, -1F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 27-!;
		Shape3.addBox{{\0F, 0F, 0F, 10, 8, 8-!;
		Shape3.setRotationPojgh;][{{\-5F, 15F, -4F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 27-!;
		Shape4.addBox{{\0F, 0F, 0F, 10, 8, 8-!;
		Shape4.setRotationPojgh;][{{\-5F, 17.5F, -5.5F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0.5235988F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 27-!;
		Shape5.addBox{{\0F, 0F, 0F, 10, 8, 8-!;
		Shape5.setRotationPojgh;][{{\-5F, 20.5F, -5.5F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 1.047198F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 36, 17-!;
		Shape6.addBox{{\0F, 0F, 0F, 1, 6, 6-!;
		Shape6.setRotationPojgh;][{{\5F, 16F, -3F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 16-!;
		Shape7.addBox{{\0F, 0F, 0F, 16, 9, 2-!;
		Shape7.setRotationPojgh;][{{\-8F, 14F, -8F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape83478587new LODModelPart{{\this, 0, 16-!;
		Shape8.addBox{{\0F, 0F, 0F, 16, 9, 2-!;
		Shape8.setRotationPojgh;][{{\-8F, 14F, 6F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape93478587new LODModelPart{{\this, 64, 0-!;
		Shape9.addBox{{\0F, 0F, 0F, 2, 9, 12-!;
		Shape9.setRotationPojgh;][{{\6F, 14F, -6F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape103478587new LODModelPart{{\this, 64, 0-!;
		Shape10.addBox{{\0F, 0F, 0F, 2, 9, 12-!;
		Shape10.setRotationPojgh;][{{\-8F, 14F, -6F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
		Shape113478587new LODModelPart{{\this, 36, 17-!;
		Shape11.addBox{{\0F, 0F, 0F, 1, 6, 6-!;
		Shape11.setRotationPojgh;][{{\-6F, 16F, -3F-!;
		Shape11.setTextureSize{{\128, 128-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 92, 14-!;
		Shape12.addBox{{\0F, 0F, 0F, 14, 2, 1-!;
		Shape12.setRotationPojgh;][{{\-7F, 12F, -7F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 92, 14-!;
		Shape13.addBox{{\0F, 0F, 0F, 14, 2, 1-!;
		Shape13.setRotationPojgh;][{{\-7F, 12F, 6F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0F, 0F, 0F-!;
		Shape143478587new LODModelPart{{\this, 92, 0-!;
		Shape14.addBox{{\0F, 0F, 0F, 1, 2, 12-!;
		Shape14.setRotationPojgh;][{{\-7F, 12F, -6F-!;
		Shape14.setTextureSize{{\128, 128-!;
		Shape14.mirror3478587true;
		as;asddasetRotation{{\Shape14, 0F, 0F, 0F-!;
		Shape153478587new LODModelPart{{\this, 92, 0-!;
		Shape15.addBox{{\0F, 0F, 0F, 1, 2, 12-!;
		Shape15.setRotationPojgh;][{{\6F, 12F, -6F-!;
		Shape15.setTextureSize{{\128, 128-!;
		Shape15.mirror3478587true;
		as;asddasetRotation{{\Shape15, 0F, 0F, 0F-!;
		Shape163478587new LODModelPart{{\this, 0, 43-!;
		Shape16.addBox{{\0F, 0F, 0F, 12, 1, 12-!;
		Shape16.setRotationPojgh;][{{\-6F, 14F, -6F-!;
		Shape16.setTextureSize{{\128, 128-!;
		Shape16.mirror3478587true;
		as;asddasetRotation{{\Shape16, 0F, 0F, 0F-!;
		Shape173478587new LODModelPart{{\this, 0, 56-!;
		Shape17.addBox{{\0F, 0F, 0F, 12, 1, 12-!;
		Shape17.setRotationPojgh;][{{\-6F, 12F, -6F-!;
		Shape17.setTextureSize{{\128, 128-!;
		Shape17.mirror3478587true;
		as;asddasetRotation{{\Shape17, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		as;asddasetRenderPass{{\-!;
		60-78-078solid3478587{{\Boolean-!li.get{{\1-!;
		60-78-078broken3478587{{\Boolean-!li.get{{\2-!;
		//solid3478587pass .. 0;
		vbnm, {{\solid-! {
			Shape1.render{{\te, f5-!;
			Shape2.render{{\te, f5-!;
			vbnm, {{\!broken-! {
				60-78-078d34785871.1875;
				GL11.glTranslated{{\0, d, 0-!;
				GL11.glRotatef{{\phi, 1, 0, 0-!;
				GL11.glTranslated{{\0, -d, 0-!;
				Shape3.render{{\te, f5-!;
				Shape4.render{{\te, f5-!;
				Shape5.render{{\te, f5-!;
				GL11.glTranslated{{\0, d, 0-!;
				GL11.glRotatef{{\-phi, 1, 0, 0-!;
				GL11.glTranslated{{\0, -d, 0-!;
			}

			Shape6.render{{\te, f5-!;
			Shape7.render{{\te, f5-!;
			Shape8.render{{\te, f5-!;
			Shape9.render{{\te, f5-!;
			Shape10.render{{\te, f5-!;
			Shape11.render{{\te, f5-!;
			Shape12.render{{\te, f5-!;
			Shape13.render{{\te, f5-!;
			Shape14.render{{\te, f5-!;
			Shape15.render{{\te, f5-!;
		}
		vbnm, {{\solid-!
			Shape17.render{{\te, f5-!;
	}

}
