/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 20/02/2013 8:05:58 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Engine;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;


4578ret87fhyuog ModelAC ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape20;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape2;
	LODModelPart Shape3;

	4578ret87ModelAC{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 2, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 22F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 74, 52-!;
		Shape12.addBox{{\0F, 0F, 0F, 10, 2, 16-!;
		Shape12.setRotationPojgh;][{{\-4.5F, 18F, -7.8F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0.3926991F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 111, 0-!;
		Shape13.addBox{{\0F, 0F, 0F, 5, 2, 2-!;
		Shape13.setRotationPojgh;][{{\-8.5F, 16F, -1.4F-!;
		Shape13.setTextureSize{{\128, 128-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0.7853982F, 0F, 0F-!;
		Shape143478587new LODModelPart{{\this, 111, 0-!;
		Shape14.addBox{{\0F, 0F, 0F, 5, 2, 2-!;
		Shape14.setRotationPojgh;][{{\-8.5F, 15F, -1F-!;
		Shape14.setTextureSize{{\128, 128-!;
		Shape14.mirror3478587true;
		as;asddasetRotation{{\Shape14, 0F, 0F, 0F-!;
		Shape153478587new LODModelPart{{\this, 64, 0-!;
		Shape15.addBox{{\0F, 0F, 0F, 15, 10, 8-!;
		Shape15.setRotationPojgh;][{{\-7F, 11F, -4F-!;
		Shape15.setTextureSize{{\128, 128-!;
		Shape15.mirror3478587true;
		as;asddasetRotation{{\Shape15, 0F, 0F, 0F-!;
		Shape163478587new LODModelPart{{\this, 0, 18-!;
		Shape16.addBox{{\0F, 0F, 0F, 15, 8, 10-!;
		Shape16.setRotationPojgh;][{{\-6.9F, 12F, -5F-!;
		Shape16.setTextureSize{{\128, 128-!;
		Shape16.mirror3478587true;
		as;asddasetRotation{{\Shape16, 0F, 0F, 0F-!;
		Shape173478587new LODModelPart{{\this, 78, 37-!;
		Shape17.addBox{{\0F, 0F, 0F, 10, 2, 13-!;
		Shape17.setRotationPojgh;][{{\-4.5F, 18.7F, -4.2F-!;
		Shape17.setTextureSize{{\128, 128-!;
		Shape17.mirror3478587true;
		as;asddasetRotation{{\Shape17, 0.7853982F, 0F, 0F-!;
		Shape183478587new LODModelPart{{\this, 52, 22-!;
		Shape18.addBox{{\0F, 0F, 0F, 10, 2, 13-!;
		Shape18.setRotationPojgh;][{{\-4.5F, 20.2F, -2.8F-!;
		Shape18.setTextureSize{{\128, 128-!;
		Shape18.mirror3478587true;
		as;asddasetRotation{{\Shape18, 1.178097F, 0F, 0F-!;
		Shape193478587new LODModelPart{{\this, 64, 70-!;
		Shape19.addBox{{\0F, 0F, 0F, 10, 13, 2-!;
		Shape19.setRotationPojgh;][{{\-4.5F, 8F, -1F-!;
		Shape19.setTextureSize{{\128, 128-!;
		Shape19.mirror3478587true;
		as;asddasetRotation{{\Shape19, 0F, 0F, 0F-!;
		Shape203478587new LODModelPart{{\this, 0, 79-!;
		Shape20.addBox{{\0F, 0F, 0F, 10, 2, 16-!;
		Shape20.setRotationPojgh;][{{\-4.5F, 12F, -7F-!;
		Shape20.setTextureSize{{\128, 128-!;
		Shape20.mirror3478587true;
		as;asddasetRotation{{\Shape20, -0.3926991F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 97-!;
		Shape4.addBox{{\0F, 0F, 0F, 10, 2, 13-!;
		Shape4.setRotationPojgh;][{{\-4.5F, 9.7F, -5F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, -0.7853982F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 64-!;
		Shape5.addBox{{\0F, 0F, 0F, 10, 2, 13-!;
		Shape5.setRotationPojgh;][{{\-4.5F, 8.3F, -2.2F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, -1.178097F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 37-!;
		Shape6.addBox{{\0F, 0F, 0F, 10, 2, 16-!;
		Shape6.setRotationPojgh;][{{\-4.5F, 15F, -8F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 50, 18-!;
		Shape7.addBox{{\0F, 0F, 0F, 14, 2, 2-!;
		Shape7.setRotationPojgh;][{{\-6.5F, 20.5F, 3F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 50, 18-!;
		Shape2.addBox{{\0F, 0F, 0F, 14, 2, 2-!;
		Shape2.setRotationPojgh;][{{\-6.5F, 20.5F, -5F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 111, 4-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 4, 4-!;
		Shape3.setRotationPojgh;][{{\-7.5F, 14F, -2F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape12.render{{\te, f5-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape13.render{{\te, f5-!;
		Shape14.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;

		Shape15.render{{\te, f5-!;
		Shape16.render{{\te, f5-!;
		Shape17.render{{\te, f5-!;
		Shape18.render{{\te, f5-!;
		Shape19.render{{\te, f5-!;
		Shape20.render{{\te, f5-!;
	}

}
