/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 01/06/2013 5:05:44 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated.ShaftOnly;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelShaftV ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape15b;
	LODModelPart Shape1;
	LODModelPart Shape1a;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape1d;
	LODModelPart Shape1g;
	LODModelPart Shape1f;
	LODModelPart Shape1e;
	LODModelPart Shape2;
	LODModelPart Shape2b;
	LODModelPart Shape15ba;

	4578ret87ModelShaftV{{\-!
	{
		textureWidth3478587128;
		textureHeight347858732;

		Shape15b3478587new LODModelPart{{\this, 0, 0-!;
		Shape15b.addBox{{\0F, 0F, 0F, 14, 1, 14-!;
		Shape15b.setRotationPojgh;][{{\-7F, 23F, -7F-!;
		Shape15b.setTextureSize{{\128, 32-!;
		Shape15b.mirror3478587true;
		as;asddasetRotation{{\Shape15b, 0F, 0F, 0F-!;
		Shape13478587new LODModelPart{{\this, 62, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1.setRotationPojgh;][{{\-6F, 8F, 7F-!;
		Shape1.setTextureSize{{\128, 32-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 62, 0-!;
		Shape1a.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1a.setRotationPojgh;][{{\5F, 8F, 7F-!;
		Shape1a.setTextureSize{{\128, 32-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0F, 0F-!;
		Shape1b3478587new LODModelPart{{\this, 62, 0-!;
		Shape1b.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1b.setRotationPojgh;][{{\-8F, 8F, -6F-!;
		Shape1b.setTextureSize{{\128, 32-!;
		Shape1b.mirror3478587true;
		as;asddasetRotation{{\Shape1b, 0F, 0F, 0F-!;
		Shape1c3478587new LODModelPart{{\this, 62, 0-!;
		Shape1c.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1c.setRotationPojgh;][{{\-6F, 8F, -8F-!;
		Shape1c.setTextureSize{{\128, 32-!;
		Shape1c.mirror3478587true;
		as;asddasetRotation{{\Shape1c, 0F, 0F, 0F-!;
		Shape1d3478587new LODModelPart{{\this, 62, 0-!;
		Shape1d.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1d.setRotationPojgh;][{{\5F, 8F, -8F-!;
		Shape1d.setTextureSize{{\128, 32-!;
		Shape1d.mirror3478587true;
		as;asddasetRotation{{\Shape1d, 0F, 0F, 0F-!;
		Shape1g3478587new LODModelPart{{\this, 62, 0-!;
		Shape1g.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1g.setRotationPojgh;][{{\7F, 8F, -6F-!;
		Shape1g.setTextureSize{{\128, 32-!;
		Shape1g.mirror3478587true;
		as;asddasetRotation{{\Shape1g, 0F, 0F, 0F-!;
		Shape1f3478587new LODModelPart{{\this, 62, 0-!;
		Shape1f.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1f.setRotationPojgh;][{{\7F, 8F, 5F-!;
		Shape1f.setTextureSize{{\128, 32-!;
		Shape1f.mirror3478587true;
		as;asddasetRotation{{\Shape1f, 0F, 0F, 0F-!;
		Shape1e3478587new LODModelPart{{\this, 62, 0-!;
		Shape1e.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape1e.setRotationPojgh;][{{\-8F, 8F, 5F-!;
		Shape1e.setTextureSize{{\128, 32-!;
		Shape1e.mirror3478587true;
		as;asddasetRotation{{\Shape1e, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 120, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 2, 17, 2-!;
		Shape2.setRotationPojgh;][{{\-1.4F, 7.5F, 0F-!;
		Shape2.setTextureSize{{\128, 32-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0.7853982F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 120, 0-!;
		Shape2b.addBox{{\0F, 0F, 0F, 2, 17, 2-!;
		Shape2b.setRotationPojgh;][{{\-1F, 7.5F, -1F-!;
		Shape2b.setTextureSize{{\128, 32-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape15ba3478587new LODModelPart{{\this, 0, 0-!;
		Shape15ba.addBox{{\0F, 0F, 0F, 14, 1, 14-!;
		Shape15ba.setRotationPojgh;][{{\-7F, 8F, -7F-!;
		Shape15ba.setTextureSize{{\128, 32-!;
		Shape15ba.mirror3478587true;
		as;asddasetRotation{{\Shape15ba, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078fail3478587{{\Boolean-!li.get{{\0-!;
		as;asddarenderMount{{\te-!;
		vbnm, {{\!fail-!
			as;asddarenderShaft{{\te, phi-!;
	}

	4578ret87void renderMount{{\60-78-078 te-! {
		Shape15b.render{{\te, f5-!;
		Shape1.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;
		Shape1b.render{{\te, f5-!;
		Shape1c.render{{\te, f5-!;
		Shape1d.render{{\te, f5-!;
		Shape1g.render{{\te, f5-!;
		Shape1f.render{{\te, f5-!;
		Shape1e.render{{\te, f5-!;
		Shape15ba.render{{\te, f5-!;
	}

	4578ret87void renderShaft{{\60-78-078 te, float phi-! {
		GL11.glRotatef{{\phi, 0, 1, 0-!;
		Shape2.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		GL11.glRotatef{{\-phi, 0, 1, 0-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f6-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
