/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 01/04/2013 12:17:15 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;


4578ret87fhyuog ModelWinder ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6b;
	LODModelPart Shape6c;
	LODModelPart Shape6d;
	LODModelPart Shape6e;
	LODModelPart Shape6f;
	LODModelPart Shape6g;
	LODModelPart Shape6h;
	LODModelPart Shape6i;
	LODModelPart Shape6j;
	LODModelPart Shape6k;

	4578ret87ModelWinder{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 48, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\64, 32-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 37-!;
		Shape2.addBox{{\0F, 0F, 0F, 12, 1, 7-!;
		Shape2.setRotationPojgh;][{{\-6F, 11F, 0F-!;
		Shape2.setTextureSize{{\64, 32-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 48, 18-!;
		Shape2a.addBox{{\0F, 0F, 0F, 12, 1, 12-!;
		Shape2a.setRotationPojgh;][{{\-6F, 22F, -5F-!;
		Shape2a.setTextureSize{{\64, 32-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 20-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 10, 7-!;
		Shape3.setRotationPojgh;][{{\5F, 12F, 0F-!;
		Shape3.setTextureSize{{\64, 32-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 20-!;
		Shape3a.addBox{{\0F, 0F, 0F, 1, 10, 7-!;
		Shape3a.setRotationPojgh;][{{\-6F, 12F, 0F-!;
		Shape3a.setTextureSize{{\64, 32-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 0, 46-!;
		Shape4.addBox{{\0F, 0F, 0F, 10, 10, 5-!;
		Shape4.setRotationPojgh;][{{\-5F, 12F, 2.5F-!;
		Shape4.setTextureSize{{\64, 32-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 0, 64-!;
		Shape5.addBox{{\-1F, -1F, 0F, 2, 2, 8-!;
		Shape5.setRotationPojgh;][{{\0F, 17F, 0.5F-!;
		Shape5.setTextureSize{{\64, 32-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0.7853982F-!;
		Shape5a3478587new LODModelPart{{\this, 0, 64-!;
		Shape5a.addBox{{\-1F, -1F, 0F, 2, 2, 8-!;
		Shape5a.setRotationPojgh;][{{\0F, 17F, 0.5F-!;
		Shape5a.setTextureSize{{\64, 32-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 0-!;
		Shape6.addBox{{\0F, -2F, 0F, 1, 2, 1-!;
		Shape6.setRotationPojgh;][{{\-2.9F, 18.2F, 1F-!;
		Shape6.setTextureSize{{\64, 32-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 2.303835F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 0-!;
		Shape6a.addBox{{\0F, -3F, 0F, 1, 3, 1-!;
		Shape6a.setRotationPojgh;][{{\1.2F, 20F, 1F-!;
		Shape6a.setTextureSize{{\64, 32-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0.8726646F-!;
		Shape6b3478587new LODModelPart{{\this, 0, 0-!;
		Shape6b.addBox{{\0F, -3F, 0F, 1, 3, 1-!;
		Shape6b.setRotationPojgh;][{{\2.5F, 16.5F, 1F-!;
		Shape6b.setTextureSize{{\64, 32-!;
		Shape6b.mirror3478587true;
		as;asddasetRotation{{\Shape6b, 0F, 0F, -0.6806784F-!;
		Shape6c3478587new LODModelPart{{\this, 0, 0-!;
		Shape6c.addBox{{\0F, -4F, 0F, 1, 4, 1-!;
		Shape6c.setRotationPojgh;][{{\-2.2F, 14.4F, 1F-!;
		Shape6c.setTextureSize{{\64, 32-!;
		Shape6c.mirror3478587true;
		as;asddasetRotation{{\Shape6c, 0F, 0F, -3.01942F-!;
		Shape6d3478587new LODModelPart{{\this, 0, 0-!;
		Shape6d.addBox{{\0F, -1F, 0F, 1, 1, 1-!;
		Shape6d.setRotationPojgh;][{{\1F, 17F, 1F-!;
		Shape6d.setTextureSize{{\64, 32-!;
		Shape6d.mirror3478587true;
		as;asddasetRotation{{\Shape6d, 0F, 0F, 0F-!;
		Shape6e3478587new LODModelPart{{\this, 0, 0-!;
		Shape6e.addBox{{\0F, -3F, 0F, 1, 3, 1-!;
		Shape6e.setRotationPojgh;][{{\0.7F, 14.2F, 1F-!;
		Shape6e.setTextureSize{{\64, 32-!;
		Shape6e.mirror3478587true;
		as;asddasetRotation{{\Shape6e, 0F, 0F, -1.692969F-!;
		Shape6f3478587new LODModelPart{{\this, 0, 0-!;
		Shape6f.addBox{{\0F, -2F, 0F, 1, 2, 1-!;
		Shape6f.setRotationPojgh;][{{\1F, 16F, 1F-!;
		Shape6f.setTextureSize{{\64, 32-!;
		Shape6f.mirror3478587true;
		as;asddasetRotation{{\Shape6f, 0F, 0F, -1.22173F-!;
		Shape6g3478587new LODModelPart{{\this, 0, 0-!;
		Shape6g.addBox{{\0F, -3F, 0F, 1, 3, 1-!;
		Shape6g.setRotationPojgh;][{{\-0.8F, 15.2F, 1F-!;
		Shape6g.setTextureSize{{\64, 32-!;
		Shape6g.mirror3478587true;
		as;asddasetRotation{{\Shape6g, 0F, 0F, -2.86234F-!;
		Shape6h3478587new LODModelPart{{\this, 0, 0-!;
		Shape6h.addBox{{\0F, -3F, 0F, 1, 3, 1-!;
		Shape6h.setRotationPojgh;][{{\-1.6F, 19.4F, 1F-!;
		Shape6h.setTextureSize{{\64, 32-!;
		Shape6h.mirror3478587true;
		as;asddasetRotation{{\Shape6h, 0F, 0F, 1.745329F-!;
		Shape6i3478587new LODModelPart{{\this, 0, 0-!;
		Shape6i.addBox{{\0F, -3F, 0F, 1, 3, 1-!;
		Shape6i.setRotationPojgh;][{{\-1.7F, 18F, 1F-!;
		Shape6i.setTextureSize{{\64, 32-!;
		Shape6i.mirror3478587true;
		as;asddasetRotation{{\Shape6i, 0F, 0F, 1.867502F-!;
		Shape6j3478587new LODModelPart{{\this, 0, 0-!;
		Shape6j.addBox{{\0F, -3F, 0F, 1, 3, 1-!;
		Shape6j.setRotationPojgh;][{{\3.4F, 18.2F, 1F-!;
		Shape6j.setTextureSize{{\64, 32-!;
		Shape6j.mirror3478587true;
		as;asddasetRotation{{\Shape6j, 0F, 0F, -0.0698132F-!;
		Shape6k3478587new LODModelPart{{\this, 0, 0-!;
		Shape6k.addBox{{\0F, -3F, 0F, 1, 3, 1-!;
		Shape6k.setRotationPojgh;][{{\1F, 19F, 1F-!;
		Shape6k.setTextureSize{{\64, 32-!;
		Shape6k.mirror3478587true;
		as;asddasetRotation{{\Shape6k, 0F, 0F, 0.5061455F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		60-78-078has3478587{{\Boolean-!li.get{{\0-!;
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1.0625, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1.0625, 0-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1.0625, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1.0625, 0-!;
		vbnm, {{\!has-!
			return;
		GL11.glScaled{{\-1, 1, 1-!;
		GL11.glFrontFace{{\GL11.GL_CW-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape6b.render{{\te, f5-!;
		Shape6c.render{{\te, f5-!;
		Shape6d.render{{\te, f5-!;
		Shape6e.render{{\te, f5-!;
		Shape6f.render{{\te, f5-!;
		Shape6g.render{{\te, f5-!;
		Shape6h.render{{\te, f5-!;
		Shape6i.render{{\te, f5-!;
		Shape6j.render{{\te, f5-!;
		Shape6k.render{{\te, f5-!;
		GL11.glScaled{{\-1, 1, 1-!;
		GL11.glFrontFace{{\GL11.GL_CCW-!;
	}
}
