/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 01/09/2013 5:41:06 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelEMP ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape6;

	4578ret87ModelEMP{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 114, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 2, 7, 2-!;
		Shape2.setRotationPojgh;][{{\-1F, 16F, -1F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 40-!;
		Shape3.addBox{{\0F, -7F, 0F, 4, 7, 1-!;
		Shape3.setRotationPojgh;][{{\2F, 23F, -1F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, -1.047198F, 3.141593F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 30-!;
		Shape3a.addBox{{\0F, -7F, 0F, 4, 7, 1-!;
		Shape3a.setRotationPojgh;][{{\-1F, 23F, -2F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, -1.047198F, -1.570796F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 0, 50-!;
		Shape3b.addBox{{\0F, -7F, 0F, 4, 7, 1-!;
		Shape3b.setRotationPojgh;][{{\-2F, 23F, 1F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, -1.047198F, 0F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 0, 20-!;
		Shape3c.addBox{{\0F, -7F, 0F, 4, 7, 1-!;
		Shape3c.setRotationPojgh;][{{\1F, 23F, 2F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, -1.047198F, 1.570796F, 0F-!;
		Shape43478587new LODModelPart{{\this, 12, 50-!;
		Shape4.addBox{{\-1F, -7F, -1F, 2, 7, 1-!;
		Shape4.setRotationPojgh;][{{\-1F, 23F, 1F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 1.047198F, 2.356194F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 12, 20-!;
		Shape4a.addBox{{\-1F, -7F, -1F, 2, 7, 1-!;
		Shape4a.setRotationPojgh;][{{\1F, 23F, 1F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 1.047198F, -2.356194F, 0F-!;
		Shape4b3478587new LODModelPart{{\this, 12, 40-!;
		Shape4b.addBox{{\-1F, -7F, -1F, 2, 7, 1-!;
		Shape4b.setRotationPojgh;][{{\-1F, 23F, -1F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 1.047198F, 0.7853982F, 0F-!;
		Shape4c3478587new LODModelPart{{\this, 12, 30-!;
		Shape4c.addBox{{\-1F, -7F, -1F, 2, 7, 1-!;
		Shape4c.setRotationPojgh;][{{\1F, 23F, -1F-!;
		Shape4c.setTextureSize{{\128, 128-!;
		Shape4c.mirror3478587true;
		as;asddasetRotation{{\Shape4c, 1.047198F, -0.7853982F, 0F-!;
		Shape53478587new LODModelPart{{\this, 114, 20-!;
		Shape5.addBox{{\0F, 0F, 0F, 3, 1, 3-!;
		Shape5.setRotationPojgh;][{{\-1.5F, 21F, -1.5F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 114, 10-!;
		Shape5a.addBox{{\0F, 0F, 0F, 3, 1, 3-!;
		Shape5a.setRotationPojgh;][{{\-1.5F, 17F, -1.5F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape5b3478587new LODModelPart{{\this, 114, 15-!;
		Shape5b.addBox{{\0F, 0F, 0F, 3, 1, 3-!;
		Shape5b.setRotationPojgh;][{{\-1.5F, 19F, -1.5F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 65, 0-!;
		Shape6.addBox{{\0F, 0F, 0F, 12, 1, 12-!;
		Shape6.setRotationPojgh;][{{\-6F, 22.5F, -6F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3c.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;
		Shape4c.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape5b.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
