/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 13/09/2014 8:00:45 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelDryingBed ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape1a;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape4d;
	LODModelPart Shape4e;
	LODModelPart Shape4f;
	LODModelPart Shape4g;
	LODModelPart Shape4h;
	LODModelPart Shape4i;
	LODModelPart Shape4k;
	LODModelPart Shape4j;
	LODModelPart Shape4m;
	LODModelPart Shape4n;
	LODModelPart Shape4o;
	LODModelPart Shape4p;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6b;
	LODModelPart Shape6c;
	LODModelPart Shape6d;
	LODModelPart Shape6e;
	LODModelPart Shape6f;
	LODModelPart Shape6g;
	LODModelPart Shape6h;
	LODModelPart Shape6i;
	LODModelPart Shape6j;
	LODModelPart Shape6k;

	4578ret87ModelDryingBed{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 61-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 2, 1-!;
		Shape1.setRotationPojgh;][{{\-8F, 8F, 7F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 0, 56-!;
		Shape1a.addBox{{\0F, 0F, 0F, 16, 2, 1-!;
		Shape1a.setRotationPojgh;][{{\-8F, 8F, -8F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 22-!;
		Shape2.addBox{{\0F, 0F, 0F, 16, 2, 2-!;
		Shape2.setRotationPojgh;][{{\-8F, 10F, 6F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 65-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 2, 14-!;
		Shape3.setRotationPojgh;][{{\7F, 8F, -7F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 0-!;
		Shape3a.addBox{{\0F, 0F, 0F, 1, 2, 14-!;
		Shape3a.setRotationPojgh;][{{\-8F, 8F, -7F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 27-!;
		Shape2a.addBox{{\0F, 0F, 0F, 16, 2, 2-!;
		Shape2a.setRotationPojgh;][{{\-8F, 10F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 44-!;
		Shape2b.addBox{{\0F, 0F, 0F, 16, 2, 1-!;
		Shape2b.setRotationPojgh;][{{\-8F, 10F, 3F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 19, 33-!;
		Shape4.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4.setRotationPojgh;][{{\6F, 10F, 4F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 9, 33-!;
		Shape4a.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4a.setRotationPojgh;][{{\1F, 10F, 4F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		Shape4b3478587new LODModelPart{{\this, 0, 33-!;
		Shape4b.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4b.setRotationPojgh;][{{\-8F, 10F, 4F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 0F, 0F, 0F-!;
		Shape4c3478587new LODModelPart{{\this, 9, 33-!;
		Shape4c.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4c.setRotationPojgh;][{{\-3F, 10F, 4F-!;
		Shape4c.setTextureSize{{\128, 128-!;
		Shape4c.mirror3478587true;
		as;asddasetRotation{{\Shape4c, 0F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 38-!;
		Shape2c.addBox{{\0F, 0F, -1.5F, 14, 1, 4-!;
		Shape2c.setRotationPojgh;][{{\-7F, 10.5F, 3F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 0, 17-!;
		Shape2d.addBox{{\0F, 0F, 0F, 16, 2, 2-!;
		Shape2d.setRotationPojgh;][{{\-8F, 10F, -1F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0F, 0F-!;
		Shape4d3478587new LODModelPart{{\this, 0, 33-!;
		Shape4d.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4d.setRotationPojgh;][{{\-8F, 10F, -6F-!;
		Shape4d.setTextureSize{{\128, 128-!;
		Shape4d.mirror3478587true;
		as;asddasetRotation{{\Shape4d, 0F, 0F, 0F-!;
		Shape4e3478587new LODModelPart{{\this, 0, 33-!;
		Shape4e.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4e.setRotationPojgh;][{{\-8F, 10F, -3F-!;
		Shape4e.setTextureSize{{\128, 128-!;
		Shape4e.mirror3478587true;
		as;asddasetRotation{{\Shape4e, 0F, 0F, 0F-!;
		Shape4f3478587new LODModelPart{{\this, 0, 33-!;
		Shape4f.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4f.setRotationPojgh;][{{\-8F, 10F, 1F-!;
		Shape4f.setTextureSize{{\128, 128-!;
		Shape4f.mirror3478587true;
		as;asddasetRotation{{\Shape4f, 0F, 0F, 0F-!;
		Shape4g3478587new LODModelPart{{\this, 19, 33-!;
		Shape4g.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4g.setRotationPojgh;][{{\6F, 10F, -6F-!;
		Shape4g.setTextureSize{{\128, 128-!;
		Shape4g.mirror3478587true;
		as;asddasetRotation{{\Shape4g, 0F, 0F, 0F-!;
		Shape4h3478587new LODModelPart{{\this, 19, 33-!;
		Shape4h.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4h.setRotationPojgh;][{{\6F, 10F, -3F-!;
		Shape4h.setTextureSize{{\128, 128-!;
		Shape4h.mirror3478587true;
		as;asddasetRotation{{\Shape4h, 0F, 0F, 0F-!;
		Shape4i3478587new LODModelPart{{\this, 19, 33-!;
		Shape4i.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4i.setRotationPojgh;][{{\6F, 10F, 1F-!;
		Shape4i.setTextureSize{{\128, 128-!;
		Shape4i.mirror3478587true;
		as;asddasetRotation{{\Shape4i, 0F, 0F, 0F-!;
		Shape4k3478587new LODModelPart{{\this, 9, 33-!;
		Shape4k.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4k.setRotationPojgh;][{{\-3F, 10F, -6F-!;
		Shape4k.setTextureSize{{\128, 128-!;
		Shape4k.mirror3478587true;
		as;asddasetRotation{{\Shape4k, 0F, 0F, 0F-!;
		Shape4j3478587new LODModelPart{{\this, 9, 33-!;
		Shape4j.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4j.setRotationPojgh;][{{\-3F, 10F, -3F-!;
		Shape4j.setTextureSize{{\128, 128-!;
		Shape4j.mirror3478587true;
		as;asddasetRotation{{\Shape4j, 0F, 0F, 0F-!;
		Shape4m3478587new LODModelPart{{\this, 9, 33-!;
		Shape4m.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4m.setRotationPojgh;][{{\-3F, 10F, 1F-!;
		Shape4m.setTextureSize{{\128, 128-!;
		Shape4m.mirror3478587true;
		as;asddasetRotation{{\Shape4m, 0F, 0F, 0F-!;
		Shape4n3478587new LODModelPart{{\this, 9, 33-!;
		Shape4n.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4n.setRotationPojgh;][{{\1F, 10F, -6F-!;
		Shape4n.setTextureSize{{\128, 128-!;
		Shape4n.mirror3478587true;
		as;asddasetRotation{{\Shape4n, 0F, 0F, 0F-!;
		Shape4o3478587new LODModelPart{{\this, 9, 33-!;
		Shape4o.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4o.setRotationPojgh;][{{\1F, 10F, -3F-!;
		Shape4o.setTextureSize{{\128, 128-!;
		Shape4o.mirror3478587true;
		as;asddasetRotation{{\Shape4o, 0F, 0F, 0F-!;
		Shape4p3478587new LODModelPart{{\this, 9, 33-!;
		Shape4p.addBox{{\0F, 0F, 0F, 2, 2, 2-!;
		Shape4p.setRotationPojgh;][{{\1F, 10F, 1F-!;
		Shape4p.setTextureSize{{\128, 128-!;
		Shape4p.mirror3478587true;
		as;asddasetRotation{{\Shape4p, 0F, 0F, 0F-!;
		Shape2e3478587new LODModelPart{{\this, 0, 44-!;
		Shape2e.addBox{{\0F, 0F, 0F, 16, 2, 1-!;
		Shape2e.setRotationPojgh;][{{\-8F, 10F, -4F-!;
		Shape2e.setTextureSize{{\128, 128-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, 0F, 0F, 0F-!;
		Shape2f3478587new LODModelPart{{\this, 0, 38-!;
		Shape2f.addBox{{\0F, 0F, -1.5F, 14, 1, 4-!;
		Shape2f.setRotationPojgh;][{{\-7F, 10.5F, -4F-!;
		Shape2f.setTextureSize{{\128, 128-!;
		Shape2f.mirror3478587true;
		as;asddasetRotation{{\Shape2f, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 37, 0-!;
		Shape5.addBox{{\0F, 0F, 0F, 16, 8, 16-!;
		Shape5.setRotationPojgh;][{{\-8F, 12F, -8F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 49-!;
		Shape6.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6.setRotationPojgh;][{{\6F, 20F, -8F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6a3478587new LODModelPart{{\this, 0, 49-!;
		Shape6a.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6a.setRotationPojgh;][{{\-8F, 20F, 6F-!;
		Shape6a.setTextureSize{{\128, 128-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0F-!;
		Shape6b3478587new LODModelPart{{\this, 0, 49-!;
		Shape6b.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6b.setRotationPojgh;][{{\6F, 20F, 6F-!;
		Shape6b.setTextureSize{{\128, 128-!;
		Shape6b.mirror3478587true;
		as;asddasetRotation{{\Shape6b, 0F, 0F, 0F-!;
		Shape6c3478587new LODModelPart{{\this, 0, 49-!;
		Shape6c.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6c.setRotationPojgh;][{{\2F, 20F, -8F-!;
		Shape6c.setTextureSize{{\128, 128-!;
		Shape6c.mirror3478587true;
		as;asddasetRotation{{\Shape6c, 0F, 0F, 0F-!;
		Shape6d3478587new LODModelPart{{\this, 0, 49-!;
		Shape6d.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6d.setRotationPojgh;][{{\-8F, 20F, -8F-!;
		Shape6d.setTextureSize{{\128, 128-!;
		Shape6d.mirror3478587true;
		as;asddasetRotation{{\Shape6d, 0F, 0F, 0F-!;
		Shape6e3478587new LODModelPart{{\this, 0, 49-!;
		Shape6e.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6e.setRotationPojgh;][{{\6F, 20F, -4F-!;
		Shape6e.setTextureSize{{\128, 128-!;
		Shape6e.mirror3478587true;
		as;asddasetRotation{{\Shape6e, 0F, 0F, 0F-!;
		Shape6f3478587new LODModelPart{{\this, 0, 49-!;
		Shape6f.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6f.setRotationPojgh;][{{\6F, 20F, 2F-!;
		Shape6f.setTextureSize{{\128, 128-!;
		Shape6f.mirror3478587true;
		as;asddasetRotation{{\Shape6f, 0F, 0F, 0F-!;
		Shape6g3478587new LODModelPart{{\this, 0, 49-!;
		Shape6g.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6g.setRotationPojgh;][{{\-4F, 20F, -8F-!;
		Shape6g.setTextureSize{{\128, 128-!;
		Shape6g.mirror3478587true;
		as;asddasetRotation{{\Shape6g, 0F, 0F, 0F-!;
		Shape6h3478587new LODModelPart{{\this, 0, 49-!;
		Shape6h.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6h.setRotationPojgh;][{{\-4F, 20F, 6F-!;
		Shape6h.setTextureSize{{\128, 128-!;
		Shape6h.mirror3478587true;
		as;asddasetRotation{{\Shape6h, 0F, 0F, 0F-!;
		Shape6i3478587new LODModelPart{{\this, 0, 49-!;
		Shape6i.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6i.setRotationPojgh;][{{\2F, 20F, 6F-!;
		Shape6i.setTextureSize{{\128, 128-!;
		Shape6i.mirror3478587true;
		as;asddasetRotation{{\Shape6i, 0F, 0F, 0F-!;
		Shape6j3478587new LODModelPart{{\this, 0, 49-!;
		Shape6j.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6j.setRotationPojgh;][{{\-8F, 20F, -4F-!;
		Shape6j.setTextureSize{{\128, 128-!;
		Shape6j.mirror3478587true;
		as;asddasetRotation{{\Shape6j, 0F, 0F, 0F-!;
		Shape6k3478587new LODModelPart{{\this, 0, 49-!;
		Shape6k.addBox{{\0F, 0F, 0F, 2, 4, 2-!;
		Shape6k.setRotationPojgh;][{{\-8F, 20F, 2F-!;
		Shape6k.setTextureSize{{\128, 128-!;
		Shape6k.mirror3478587true;
		as;asddasetRotation{{\Shape6k, 0F, 0F, 0F-!;
	}

	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;
		Shape4c.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape2d.render{{\te, f5-!;
		Shape4d.render{{\te, f5-!;
		Shape4e.render{{\te, f5-!;
		Shape4f.render{{\te, f5-!;
		Shape4g.render{{\te, f5-!;
		Shape4h.render{{\te, f5-!;
		Shape4i.render{{\te, f5-!;
		Shape4k.render{{\te, f5-!;
		Shape4j.render{{\te, f5-!;
		Shape4m.render{{\te, f5-!;
		Shape4n.render{{\te, f5-!;
		Shape4o.render{{\te, f5-!;
		Shape4p.render{{\te, f5-!;
		Shape2e.render{{\te, f5-!;
		Shape2f.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape6b.render{{\te, f5-!;
		Shape6c.render{{\te, f5-!;
		Shape6d.render{{\te, f5-!;
		Shape6e.render{{\te, f5-!;
		Shape6f.render{{\te, f5-!;
		Shape6g.render{{\te, f5-!;
		Shape6h.render{{\te, f5-!;
		Shape6i.render{{\te, f5-!;
		Shape6j.render{{\te, f5-!;
		Shape6k.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
