/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 14-03-2013 10:11:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated.ShaftOnly;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelCross ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape13;
	LODModelPart Shape12;
	LODModelPart Shape14;
	LODModelPart Shape14a;
	LODModelPart Shape14b;
	LODModelPart Shape14c;
	LODModelPart Shape14b1;
	LODModelPart Shape14b2;
	LODModelPart Shape14b3;
	LODModelPart Shape14b4;
	LODModelPart Shape14b5;
	LODModelPart Shape14b6;
	LODModelPart Shape14b7;
	LODModelPart Shape14b8;
	LODModelPart Shape14b9;
	LODModelPart Shape14b10;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6b;

	4578ret87ModelCross{{\-!
	{
		textureWidth3478587128;
		textureHeight347858732;

		Shape13478587new LODModelPart{{\this, 0, 0-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 32-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 64, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 1, 12, 16-!;
		Shape2.setRotationPojgh;][{{\7F, 11F, -8F-!;
		Shape2.setTextureSize{{\128, 32-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 64, 0-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 12, 16-!;
		Shape3.setRotationPojgh;][{{\-8F, 11F, -8F-!;
		Shape3.setTextureSize{{\128, 32-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 98, 15-!;
		Shape4.addBox{{\0F, 0F, 0F, 14, 12, 1-!;
		Shape4.setRotationPojgh;][{{\-7F, 11F, 7F-!;
		Shape4.setTextureSize{{\128, 32-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, 0F, 0F-!;
		Shape53478587new LODModelPart{{\this, 98, 15-!;
		Shape5.addBox{{\0F, 0F, 0F, 14, 12, 1-!;
		Shape5.setRotationPojgh;][{{\-7F, 11F, -8F-!;
		Shape5.setTextureSize{{\128, 32-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape133478587new LODModelPart{{\this, 0, 27-!;
		Shape13.addBox{{\0F, -1F, -1F, 17, 2, 2-!;
		Shape13.setRotationPojgh;][{{\-8.5F, 16F, 0F-!;
		Shape13.setTextureSize{{\128, 32-!;
		Shape13.mirror3478587true;
		as;asddasetRotation{{\Shape13, 0.7853982F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 0, 27-!;
		Shape12.addBox{{\0F, -1F, -1F, 17, 2, 2-!;
		Shape12.setRotationPojgh;][{{\-8.5F, 16F, 0F-!;
		Shape12.setTextureSize{{\128, 32-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
		Shape143478587new LODModelPart{{\this, 100, 0-!;
		Shape14.addBox{{\-1F, -1F, 0F, 2, 2, 5-!;
		Shape14.setRotationPojgh;][{{\0F, 16F, -8.5F-!;
		Shape14.setTextureSize{{\128, 32-!;
		Shape14.mirror3478587true;
		as;asddasetRotation{{\Shape14, 0F, 0F, 0.7853982F-!;
		Shape14a3478587new LODModelPart{{\this, 100, 0-!;
		Shape14a.addBox{{\-1F, -1F, 0F, 2, 2, 5-!;
		Shape14a.setRotationPojgh;][{{\0F, 16F, 3.5F-!;
		Shape14a.setTextureSize{{\128, 32-!;
		Shape14a.mirror3478587true;
		as;asddasetRotation{{\Shape14a, 0F, 0F, 0.7853982F-!;
		Shape14b3478587new LODModelPart{{\this, 100, 0-!;
		Shape14b.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape14b.setRotationPojgh;][{{\0F, 20F, -4F-!;
		Shape14b.setTextureSize{{\128, 32-!;
		Shape14b.mirror3478587true;
		as;asddasetRotation{{\Shape14b, 0F, 0F, 1.178097F-!;
		Shape14c3478587new LODModelPart{{\this, 100, 0-!;
		Shape14c.addBox{{\-1F, -1F, 0F, 2, 2, 5-!;
		Shape14c.setRotationPojgh;][{{\0F, 16F, -8.5F-!;
		Shape14c.setTextureSize{{\128, 32-!;
		Shape14c.mirror3478587true;
		as;asddasetRotation{{\Shape14c, 0F, 0F, 0F-!;
		Shape14b13478587new LODModelPart{{\this, 100, 0-!;
		Shape14b1.addBox{{\-1F, -1F, 0F, 2, 2, 7-!;
		Shape14b1.setRotationPojgh;][{{\0F, 20F, -3.5F-!;
		Shape14b1.setTextureSize{{\128, 32-!;
		Shape14b1.mirror3478587true;
		as;asddasetRotation{{\Shape14b1, 0F, 0F, 0.7853982F-!;
		Shape14b23478587new LODModelPart{{\this, 100, 0-!;
		Shape14b2.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape14b2.setRotationPojgh;][{{\0F, 20F, -4F-!;
		Shape14b2.setTextureSize{{\128, 32-!;
		Shape14b2.mirror3478587true;
		as;asddasetRotation{{\Shape14b2, 0F, 0F, 0.3926991F-!;
		Shape14b33478587new LODModelPart{{\this, 100, 0-!;
		Shape14b3.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape14b3.setRotationPojgh;][{{\0F, 16F, -4F-!;
		Shape14b3.setTextureSize{{\128, 32-!;
		Shape14b3.mirror3478587true;
		as;asddasetRotation{{\Shape14b3, 0F, 0F, 0F-!;
		Shape14b43478587new LODModelPart{{\this, 100, 0-!;
		Shape14b4.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape14b4.setRotationPojgh;][{{\0F, 16F, -4F-!;
		Shape14b4.setTextureSize{{\128, 32-!;
		Shape14b4.mirror3478587true;
		as;asddasetRotation{{\Shape14b4, 0F, 0F, 0.7853982F-!;
		Shape14b53478587new LODModelPart{{\this, 100, 0-!;
		Shape14b5.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape14b5.setRotationPojgh;][{{\0F, 16F, 3F-!;
		Shape14b5.setTextureSize{{\128, 32-!;
		Shape14b5.mirror3478587true;
		as;asddasetRotation{{\Shape14b5, 0F, 0F, 0F-!;
		Shape14b63478587new LODModelPart{{\this, 100, 0-!;
		Shape14b6.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape14b6.setRotationPojgh;][{{\0F, 16F, 3F-!;
		Shape14b6.setTextureSize{{\128, 32-!;
		Shape14b6.mirror3478587true;
		as;asddasetRotation{{\Shape14b6, 0F, 0F, 0.7853982F-!;
		Shape14b73478587new LODModelPart{{\this, 100, 0-!;
		Shape14b7.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape14b7.setRotationPojgh;][{{\0F, 20F, 3F-!;
		Shape14b7.setTextureSize{{\128, 32-!;
		Shape14b7.mirror3478587true;
		as;asddasetRotation{{\Shape14b7, 0F, 0F, 1.178097F-!;
		Shape14b83478587new LODModelPart{{\this, 100, 0-!;
		Shape14b8.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape14b8.setRotationPojgh;][{{\0F, 20F, 3F-!;
		Shape14b8.setTextureSize{{\128, 32-!;
		Shape14b8.mirror3478587true;
		as;asddasetRotation{{\Shape14b8, 0F, 0F, 0.3926991F-!;
		Shape14b93478587new LODModelPart{{\this, 100, 0-!;
		Shape14b9.addBox{{\-1F, -1F, 0F, 2, 2, 5-!;
		Shape14b9.setRotationPojgh;][{{\0F, 16F, 3.5F-!;
		Shape14b9.setTextureSize{{\128, 32-!;
		Shape14b9.mirror3478587true;
		as;asddasetRotation{{\Shape14b9, 0F, 0F, 0F-!;
		Shape14b103478587new LODModelPart{{\this, 100, 0-!;
		Shape14b10.addBox{{\-1F, -1F, 0F, 2, 2, 7-!;
		Shape14b10.setRotationPojgh;][{{\0F, 20F, -3.5F-!;
		Shape14b10.setTextureSize{{\128, 32-!;
		Shape14b10.mirror3478587true;
		as;asddasetRotation{{\Shape14b10, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 66, 0-!;
		Shape6.addBox{{\0F, 0F, 0F, 4, 9, 1-!;
		Shape6.setRotationPojgh;][{{\-2F, 14F, 5F-!;
		Shape6.setTextureSize{{\128, 32-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape6a3478587new LODModelPart{{\this, 66, 0-!;
		Shape6a.addBox{{\0F, 0F, 0F, 4, 5, 1-!;
		Shape6a.setRotationPojgh;][{{\-2F, 18F, -0.5F-!;
		Shape6a.setTextureSize{{\128, 32-!;
		Shape6a.mirror3478587true;
		as;asddasetRotation{{\Shape6a, 0F, 0F, 0F-!;
		Shape6b3478587new LODModelPart{{\this, 66, 0-!;
		Shape6b.addBox{{\0F, 0F, 0F, 4, 9, 1-!;
		Shape6b.setRotationPojgh;][{{\-2F, 14F, -6F-!;
		Shape6b.setTextureSize{{\128, 32-!;
		Shape6b.mirror3478587true;
		as;asddasetRotation{{\Shape6b, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float phi2-! //using "theta" param as phi2
	{
		Shape1.render{{\te, f5-!;
		Shape2.render{{\te, f5-!;
		Shape3.render{{\te, f5-!;
		Shape4.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape6a.render{{\te, f5-!;
		Shape6b.render{{\te, f5-!;

		60-78-078d34785870.25;
		GL11.glTranslated{{\0, 1+d, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1-d, 0-!;
		Shape14b.render{{\te, f5-!;
		Shape14b1.render{{\te, f5-!;
		Shape14b10.render{{\te, f5-!;
		Shape14b2.render{{\te, f5-!;
		Shape14b7.render{{\te, f5-!;
		Shape14b8.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1+d, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1-d, 0-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape14.render{{\te, f5-!;
		Shape14c.render{{\te, f5-!;
		Shape14a.render{{\te, f5-!;
		Shape14b9.render{{\te, f5-!;
		Shape14b5.render{{\te, f5-!;
		Shape14b6.render{{\te, f5-!;
		Shape14b3.render{{\te, f5-!;
		Shape14b4.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -1, 0-!;

		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\phi2, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
		Shape13.render{{\te, f5-!;
		Shape12.render{{\te, f5-!;
		GL11.glTranslated{{\0, 1, 0-!;
		GL11.glRotatef{{\-phi2, 1, 0, 0-!;
		GL11.glTranslated{{\0, -1, 0-!;
	}

}
