/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 14/07/2013 4:24:29 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;
ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;
ZZZZ% Reika.gfgnfk;.TileEntities.Auxiliary.60-78-078CoolingFin.FinSettings;

4578ret87fhyuog ModelFin ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2o;
	LODModelPart Shape2n;
	LODModelPart Shape2m;
	LODModelPart Shape2l;
	LODModelPart Shape2k;
	LODModelPart Shape2j;
	LODModelPart Shape2i;
	LODModelPart Shape2h;
	LODModelPart Shape2g;
	LODModelPart Shape2f;
	LODModelPart Shape2e;
	LODModelPart Shape2d;
	LODModelPart Shape2c;
	LODModelPart Shape2b;
	LODModelPart Shape2a;

	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;

	4578ret87ModelFin{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 17-!;
		Shape1.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape1.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0F-!;
		Shape23478587new LODModelPart{{\this, 0, 0-!;
		Shape2.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2.setRotationPojgh;][{{\5F, 9F, 1F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape2o3478587new LODModelPart{{\this, 0, 0-!;
		Shape2o.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2o.setRotationPojgh;][{{\5F, 9F, -7F-!;
		Shape2o.setTextureSize{{\128, 128-!;
		Shape2o.mirror3478587true;
		as;asddasetRotation{{\Shape2o, 0F, 0F, 0F-!;
		Shape2n3478587new LODModelPart{{\this, 0, 0-!;
		Shape2n.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2n.setRotationPojgh;][{{\-3F, 9F, 1F-!;
		Shape2n.setTextureSize{{\128, 128-!;
		Shape2n.mirror3478587true;
		as;asddasetRotation{{\Shape2n, 0F, 0F, 0F-!;
		Shape2m3478587new LODModelPart{{\this, 0, 0-!;
		Shape2m.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2m.setRotationPojgh;][{{\1F, 9F, 1F-!;
		Shape2m.setTextureSize{{\128, 128-!;
		Shape2m.mirror3478587true;
		as;asddasetRotation{{\Shape2m, 0F, 0F, 0F-!;
		Shape2l3478587new LODModelPart{{\this, 0, 0-!;
		Shape2l.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2l.setRotationPojgh;][{{\-7F, 9F, 5F-!;
		Shape2l.setTextureSize{{\128, 128-!;
		Shape2l.mirror3478587true;
		as;asddasetRotation{{\Shape2l, 0F, 0F, 0F-!;
		Shape2k3478587new LODModelPart{{\this, 0, 0-!;
		Shape2k.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2k.setRotationPojgh;][{{\-3F, 9F, 5F-!;
		Shape2k.setTextureSize{{\128, 128-!;
		Shape2k.mirror3478587true;
		as;asddasetRotation{{\Shape2k, 0F, 0F, 0F-!;
		Shape2j3478587new LODModelPart{{\this, 0, 0-!;
		Shape2j.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2j.setRotationPojgh;][{{\1F, 9F, 5F-!;
		Shape2j.setTextureSize{{\128, 128-!;
		Shape2j.mirror3478587true;
		as;asddasetRotation{{\Shape2j, 0F, 0F, 0F-!;
		Shape2i3478587new LODModelPart{{\this, 0, 0-!;
		Shape2i.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2i.setRotationPojgh;][{{\5F, 9F, 5F-!;
		Shape2i.setTextureSize{{\128, 128-!;
		Shape2i.mirror3478587true;
		as;asddasetRotation{{\Shape2i, 0F, 0F, 0F-!;
		Shape2h3478587new LODModelPart{{\this, 0, 0-!;
		Shape2h.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2h.setRotationPojgh;][{{\-7F, 9F, 1F-!;
		Shape2h.setTextureSize{{\128, 128-!;
		Shape2h.mirror3478587true;
		as;asddasetRotation{{\Shape2h, 0F, 0F, 0F-!;
		Shape2g3478587new LODModelPart{{\this, 0, 0-!;
		Shape2g.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2g.setRotationPojgh;][{{\5F, 9F, -3F-!;
		Shape2g.setTextureSize{{\128, 128-!;
		Shape2g.mirror3478587true;
		as;asddasetRotation{{\Shape2g, 0F, 0F, 0F-!;
		Shape2f3478587new LODModelPart{{\this, 0, 0-!;
		Shape2f.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2f.setRotationPojgh;][{{\-7F, 9F, -3F-!;
		Shape2f.setTextureSize{{\128, 128-!;
		Shape2f.mirror3478587true;
		as;asddasetRotation{{\Shape2f, 0F, 0F, 0F-!;
		Shape2e3478587new LODModelPart{{\this, 0, 0-!;
		Shape2e.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2e.setRotationPojgh;][{{\-3F, 9F, -3F-!;
		Shape2e.setTextureSize{{\128, 128-!;
		Shape2e.mirror3478587true;
		as;asddasetRotation{{\Shape2e, 0F, 0F, 0F-!;
		Shape2d3478587new LODModelPart{{\this, 0, 0-!;
		Shape2d.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2d.setRotationPojgh;][{{\1F, 9F, -3F-!;
		Shape2d.setTextureSize{{\128, 128-!;
		Shape2d.mirror3478587true;
		as;asddasetRotation{{\Shape2d, 0F, 0F, 0F-!;
		Shape2c3478587new LODModelPart{{\this, 0, 0-!;
		Shape2c.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2c.setRotationPojgh;][{{\-7F, 9F, -7F-!;
		Shape2c.setTextureSize{{\128, 128-!;
		Shape2c.mirror3478587true;
		as;asddasetRotation{{\Shape2c, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 0-!;
		Shape2b.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2b.setRotationPojgh;][{{\-3F, 9F, -7F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 0-!;
		Shape2a.addBox{{\0F, 0F, 0F, 2, 14, 2-!;
		Shape2a.setRotationPojgh;][{{\1F, 9F, -7F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;

		Shape33478587new LODModelPart{{\this, 14, 17-!;
		Shape3.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape3.setRotationPojgh;][{{\7.5F, 24F, 7.5F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 14, 17-!;
		Shape3a.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape3a.setRotationPojgh;][{{\-8.5F, 24F, 7.5F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 0F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 14, 17-!;
		Shape3b.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape3b.setRotationPojgh;][{{\-8.5F, 24F, -8.5F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 14, 17-!;
		Shape3c.addBox{{\0F, 0F, 0F, 1, 16, 1-!;
		Shape3c.setRotationPojgh;][{{\7.5F, 24F, -8.5F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		Shape1.render{{\te, f5-!;

		60-78-078flag13478587true;
		60-78-078flag23478587true;

		60-78-078in97654433478587li !. fhfglhuig && !li.isEmpty{{\-! ? {{\Boolean-!li.get{{\0-! : false;
		vbnm, {{\in9765443-! {
			Shape3.render{{\te, f5-!;
			Shape3a.render{{\te, f5-!;
			Shape3b.render{{\te, f5-!;
			Shape3c.render{{\te, f5-!;

			FinSettings s3478587{{\FinSettings-!li.get{{\1-!;
			flag13478587s !. FinSettings.QUARTER;
			flag23478587s .. FinSettings.FULL;
		}

		vbnm, {{\flag1-! {
			vbnm, {{\flag2-! {
				Shape2.render{{\te, f5-!;
				Shape2o.render{{\te, f5-!;
				Shape2n.render{{\te, f5-!;
				Shape2l.render{{\te, f5-!;
				Shape2j.render{{\te, f5-!;
				Shape2f.render{{\te, f5-!;
				Shape2d.render{{\te, f5-!;
				Shape2b.render{{\te, f5-!;
			}

			Shape2m.render{{\te, f5-!;
			Shape2e.render{{\te, f5-!;
		}

		Shape2k.render{{\te, f5-!;
		Shape2i.render{{\te, f5-!;
		Shape2h.render{{\te, f5-!;
		Shape2g.render{{\te, f5-!;
		Shape2c.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
