/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2016
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 23/12/2013 7:07:49 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.gfgnfk;.Models.Animated;

ZZZZ% java.util.ArrayList;

ZZZZ% net.minecraft.60-78-078.60-78-078;

ZZZZ% org.lwjgl.opengl.GL11;

ZZZZ% Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
ZZZZ% Reika.gfgnfk;.Base.RotaryModelBase;

4578ret87fhyuog ModelHydraulicPump ,.[]\., RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape1a;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape4d;
	LODModelPart Shape4e;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape6;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape1d;
	LODModelPart Shape1e;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape3f;
	LODModelPart Shape3g;
	LODModelPart Shape1f;
	LODModelPart Shape1g;
	LODModelPart Shape8;
	LODModelPart Shape8a;
	LODModelPart Shape9;
	LODModelPart Shape9a;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape11a;
	LODModelPart Shape11b;
	LODModelPart Shape11c;
	LODModelPart Shape11d;
	LODModelPart Shape12;

	4578ret87ModelHydraulicPump{{\-!
	{
		textureWidth3478587128;
		textureHeight3478587128;

		Shape13478587new LODModelPart{{\this, 0, 62-!;
		Shape1.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape1.setRotationPojgh;][{{\0F, 15F, -6F-!;
		Shape1.setTextureSize{{\128, 128-!;
		Shape1.mirror3478587true;
		as;asddasetRotation{{\Shape1, 0F, 0F, 0.7853982F-!;
		Shape23478587new LODModelPart{{\this, 0, 69-!;
		Shape2.addBox{{\0F, 0F, 0F, 16, 2, 2-!;
		Shape2.setRotationPojgh;][{{\-8F, 21F, -8F-!;
		Shape2.setTextureSize{{\128, 128-!;
		Shape2.mirror3478587true;
		as;asddasetRotation{{\Shape2, 0F, 0F, 0F-!;
		Shape33478587new LODModelPart{{\this, 0, 32-!;
		Shape3.addBox{{\-2.5F, 0F, -2.5F, 5, 5, 5-!;
		Shape3.setRotationPojgh;][{{\-3F, 16F, 0F-!;
		Shape3.setTextureSize{{\128, 128-!;
		Shape3.mirror3478587true;
		as;asddasetRotation{{\Shape3, 0F, 0.3926991F, 0F-!;
		Shape1a3478587new LODModelPart{{\this, 0, 18-!;
		Shape1a.addBox{{\-1F, -1F, 0F, 2, 2, 3-!;
		Shape1a.setRotationPojgh;][{{\0F, 15F, -8.5F-!;
		Shape1a.setTextureSize{{\128, 128-!;
		Shape1a.mirror3478587true;
		as;asddasetRotation{{\Shape1a, 0F, 0F, 0F-!;
		Shape3a3478587new LODModelPart{{\this, 0, 32-!;
		Shape3a.addBox{{\-2.5F, 0F, -2.5F, 5, 5, 5-!;
		Shape3a.setRotationPojgh;][{{\-3F, 16F, 0F-!;
		Shape3a.setTextureSize{{\128, 128-!;
		Shape3a.mirror3478587true;
		as;asddasetRotation{{\Shape3a, 0F, 1.178097F, 0F-!;
		Shape3b3478587new LODModelPart{{\this, 0, 99-!;
		Shape3b.addBox{{\-1F, 0F, -1F, 2, 1, 2-!;
		Shape3b.setRotationPojgh;][{{\-3F, 15.5F, 0F-!;
		Shape3b.setTextureSize{{\128, 128-!;
		Shape3b.mirror3478587true;
		as;asddasetRotation{{\Shape3b, 0F, 0.7853982F, 0F-!;
		Shape3c3478587new LODModelPart{{\this, 0, 32-!;
		Shape3c.addBox{{\-2.5F, 0F, -2.5F, 5, 5, 5-!;
		Shape3c.setRotationPojgh;][{{\3F, 16F, 0F-!;
		Shape3c.setTextureSize{{\128, 128-!;
		Shape3c.mirror3478587true;
		as;asddasetRotation{{\Shape3c, 0F, 0F, 0F-!;
		Shape43478587new LODModelPart{{\this, 66, 12-!;
		Shape4.addBox{{\-1F, 0F, -3F, 1, 6, 3-!;
		Shape4.setRotationPojgh;][{{\-7.5F, 15F, 2F-!;
		Shape4.setTextureSize{{\128, 128-!;
		Shape4.mirror3478587true;
		as;asddasetRotation{{\Shape4, 0F, -2.356194F, 0F-!;
		Shape4a3478587new LODModelPart{{\this, 66, 0-!;
		Shape4a.addBox{{\0F, 0F, 0F, 1, 6, 4-!;
		Shape4a.setRotationPojgh;][{{\-7.5F, 15F, -2F-!;
		Shape4a.setTextureSize{{\128, 128-!;
		Shape4a.mirror3478587true;
		as;asddasetRotation{{\Shape4a, 0F, 0F, 0F-!;
		Shape4b3478587new LODModelPart{{\this, 66, 12-!;
		Shape4b.addBox{{\-1F, 0F, 0F, 1, 6, 3-!;
		Shape4b.setRotationPojgh;][{{\-7.5F, 15F, -2F-!;
		Shape4b.setTextureSize{{\128, 128-!;
		Shape4b.mirror3478587true;
		as;asddasetRotation{{\Shape4b, 0F, 2.356194F, 0F-!;
		Shape4c3478587new LODModelPart{{\this, 80, 0-!;
		Shape4c.addBox{{\0F, 0F, 0F, 1, 6, 4-!;
		Shape4c.setRotationPojgh;][{{\6.5F, 15F, -2F-!;
		Shape4c.setTextureSize{{\128, 128-!;
		Shape4c.mirror3478587true;
		as;asddasetRotation{{\Shape4c, 0F, 0F, 0F-!;
		Shape4d3478587new LODModelPart{{\this, 80, 12-!;
		Shape4d.addBox{{\0F, 0F, 0F, 1, 6, 3-!;
		Shape4d.setRotationPojgh;][{{\7.5F, 15F, -2F-!;
		Shape4d.setTextureSize{{\128, 128-!;
		Shape4d.mirror3478587true;
		as;asddasetRotation{{\Shape4d, 0F, -2.356194F, 0F-!;
		Shape4e3478587new LODModelPart{{\this, 80, 12-!;
		Shape4e.addBox{{\0F, 0F, -3F, 1, 6, 3-!;
		Shape4e.setRotationPojgh;][{{\7.5F, 15F, 2F-!;
		Shape4e.setTextureSize{{\128, 128-!;
		Shape4e.mirror3478587true;
		as;asddasetRotation{{\Shape4e, 0F, 2.356194F, 0F-!;
		Shape53478587new LODModelPart{{\this, 10, 43-!;
		Shape5.addBox{{\0F, 0F, 0F, 3, 6, 1-!;
		Shape5.setRotationPojgh;][{{\2.3F, 15F, 3.1F-!;
		Shape5.setTextureSize{{\128, 128-!;
		Shape5.mirror3478587true;
		as;asddasetRotation{{\Shape5, 0F, 0F, 0F-!;
		Shape5a3478587new LODModelPart{{\this, 20, 43-!;
		Shape5a.addBox{{\0F, 0F, 0F, 3, 6, 1-!;
		Shape5a.setRotationPojgh;][{{\-5.3F, 15F, 3.1F-!;
		Shape5a.setTextureSize{{\128, 128-!;
		Shape5a.mirror3478587true;
		as;asddasetRotation{{\Shape5a, 0F, 0F, 0F-!;
		Shape63478587new LODModelPart{{\this, 0, 51-!;
		Shape6.addBox{{\0F, 0F, 0F, 8, 8, 1-!;
		Shape6.setRotationPojgh;][{{\-4F, 13F, -5F-!;
		Shape6.setTextureSize{{\128, 128-!;
		Shape6.mirror3478587true;
		as;asddasetRotation{{\Shape6, 0F, 0F, 0F-!;
		Shape1b3478587new LODModelPart{{\this, 0, 18-!;
		Shape1b.addBox{{\-1F, -1F, 0F, 2, 2, 3-!;
		Shape1b.setRotationPojgh;][{{\0F, 15F, -8.5F-!;
		Shape1b.setTextureSize{{\128, 128-!;
		Shape1b.mirror3478587true;
		as;asddasetRotation{{\Shape1b, 0F, 0F, 0.7853982F-!;
		Shape1c3478587new LODModelPart{{\this, 11, 62-!;
		Shape1c.addBox{{\-0.5F, -0.5F, 0F, 1, 1, 1-!;
		Shape1c.setRotationPojgh;][{{\0F, 20F, -6.5F-!;
		Shape1c.setTextureSize{{\128, 128-!;
		Shape1c.mirror3478587true;
		as;asddasetRotation{{\Shape1c, 0F, 0F, 0.3926991F-!;
		Shape2a3478587new LODModelPart{{\this, 0, 0-!;
		Shape2a.addBox{{\0F, 0F, 0F, 16, 1, 16-!;
		Shape2a.setRotationPojgh;][{{\-8F, 23F, -8F-!;
		Shape2a.setTextureSize{{\128, 128-!;
		Shape2a.mirror3478587true;
		as;asddasetRotation{{\Shape2a, 0F, 0F, 0F-!;
		Shape2b3478587new LODModelPart{{\this, 0, 75-!;
		Shape2b.addBox{{\0F, 0F, 0F, 16, 2, 13-!;
		Shape2b.setRotationPojgh;][{{\-8F, 21F, -5F-!;
		Shape2b.setTextureSize{{\128, 128-!;
		Shape2b.mirror3478587true;
		as;asddasetRotation{{\Shape2b, 0F, 0F, 0F-!;
		Shape73478587new LODModelPart{{\this, 0, 95-!;
		Shape7.addBox{{\0F, 0F, 0F, 4, 2, 1-!;
		Shape7.setRotationPojgh;][{{\4F, 21F, -6F-!;
		Shape7.setTextureSize{{\128, 128-!;
		Shape7.mirror3478587true;
		as;asddasetRotation{{\Shape7, 0F, 0F, 0F-!;
		Shape7a3478587new LODModelPart{{\this, 0, 91-!;
		Shape7a.addBox{{\0F, 0F, 0F, 4, 2, 1-!;
		Shape7a.setRotationPojgh;][{{\-8F, 21F, -6F-!;
		Shape7a.setTextureSize{{\128, 128-!;
		Shape7a.mirror3478587true;
		as;asddasetRotation{{\Shape7a, 0F, 0F, 0F-!;
		Shape1d3478587new LODModelPart{{\this, 0, 62-!;
		Shape1d.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape1d.setRotationPojgh;][{{\0F, 15F, -6F-!;
		Shape1d.setTextureSize{{\128, 128-!;
		Shape1d.mirror3478587true;
		as;asddasetRotation{{\Shape1d, 0F, 0F, 0F-!;
		Shape1e3478587new LODModelPart{{\this, 0, 62-!;
		Shape1e.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape1e.setRotationPojgh;][{{\0F, 20F, -6F-!;
		Shape1e.setTextureSize{{\128, 128-!;
		Shape1e.mirror3478587true;
		as;asddasetRotation{{\Shape1e, 0F, 0F, 0.3926991F-!;
		Shape5b3478587new LODModelPart{{\this, 0, 43-!;
		Shape5b.addBox{{\0F, 0F, 0F, 3, 6, 1-!;
		Shape5b.setRotationPojgh;][{{\2.3F, 15F, -4.1F-!;
		Shape5b.setTextureSize{{\128, 128-!;
		Shape5b.mirror3478587true;
		as;asddasetRotation{{\Shape5b, 0F, 0F, 0F-!;
		Shape5c3478587new LODModelPart{{\this, 29, 43-!;
		Shape5c.addBox{{\0F, 0F, 0F, 3, 6, 1-!;
		Shape5c.setRotationPojgh;][{{\-5.3F, 15F, -4.1F-!;
		Shape5c.setTextureSize{{\128, 128-!;
		Shape5c.mirror3478587true;
		as;asddasetRotation{{\Shape5c, 0F, 0F, 0F-!;
		Shape5d3478587new LODModelPart{{\this, 0, 43-!;
		Shape5d.addBox{{\0F, 0F, 0F, 3, 6, 1-!;
		Shape5d.setRotationPojgh;][{{\-5.3F, 15F, 3.1F-!;
		Shape5d.setTextureSize{{\128, 128-!;
		Shape5d.mirror3478587true;
		as;asddasetRotation{{\Shape5d, 0F, 0F, 0F-!;
		Shape3d3478587new LODModelPart{{\this, 0, 32-!;
		Shape3d.addBox{{\-2.5F, 0F, -2.5F, 5, 5, 5-!;
		Shape3d.setRotationPojgh;][{{\3F, 16F, 0F-!;
		Shape3d.setTextureSize{{\128, 128-!;
		Shape3d.mirror3478587true;
		as;asddasetRotation{{\Shape3d, 0F, 0.7853982F, 0F-!;
		Shape3e3478587new LODModelPart{{\this, 0, 99-!;
		Shape3e.addBox{{\-1F, 0F, -1F, 2, 1, 2-!;
		Shape3e.setRotationPojgh;][{{\3F, 15.5F, 0F-!;
		Shape3e.setTextureSize{{\128, 128-!;
		Shape3e.mirror3478587true;
		as;asddasetRotation{{\Shape3e, 0F, 0.7853982F, 0F-!;
		Shape3f3478587new LODModelPart{{\this, 0, 99-!;
		Shape3f.addBox{{\-1F, 0F, -1F, 2, 1, 2-!;
		Shape3f.setRotationPojgh;][{{\3F, 15.5F, 0F-!;
		Shape3f.setTextureSize{{\128, 128-!;
		Shape3f.mirror3478587true;
		as;asddasetRotation{{\Shape3f, 0F, 0F, 0F-!;
		Shape3g3478587new LODModelPart{{\this, 0, 99-!;
		Shape3g.addBox{{\-1F, 0F, -1F, 2, 1, 2-!;
		Shape3g.setRotationPojgh;][{{\-3F, 15.5F, 0F-!;
		Shape3g.setTextureSize{{\128, 128-!;
		Shape3g.mirror3478587true;
		as;asddasetRotation{{\Shape3g, 0F, 0F, 0F-!;
		Shape1f3478587new LODModelPart{{\this, 0, 62-!;
		Shape1f.addBox{{\-2F, -2F, 0F, 4, 4, 1-!;
		Shape1f.setRotationPojgh;][{{\0F, 20F, -6F-!;
		Shape1f.setTextureSize{{\128, 128-!;
		Shape1f.mirror3478587true;
		as;asddasetRotation{{\Shape1f, 0F, 0F, 1.178097F-!;
		Shape1g3478587new LODModelPart{{\this, 11, 62-!;
		Shape1g.addBox{{\-0.5F, -0.5F, 0F, 1, 1, 1-!;
		Shape1g.setRotationPojgh;][{{\0F, 20F, -6.5F-!;
		Shape1g.setTextureSize{{\128, 128-!;
		Shape1g.mirror3478587true;
		as;asddasetRotation{{\Shape1g, 0F, 0F, 1.178097F-!;
		Shape83478587new LODModelPart{{\this, 0, 114-!;
		Shape8.addBox{{\-3F, -3F, 0F, 6, 4, 1-!;
		Shape8.setRotationPojgh;][{{\0F, 15F, 4F-!;
		Shape8.setTextureSize{{\128, 128-!;
		Shape8.mirror3478587true;
		as;asddasetRotation{{\Shape8, 0F, 0F, 0F-!;
		Shape8a3478587new LODModelPart{{\this, 0, 103-!;
		Shape8a.addBox{{\-3F, -3F, 0F, 6, 9, 1-!;
		Shape8a.setRotationPojgh;][{{\0F, 15F, 7F-!;
		Shape8a.setTextureSize{{\128, 128-!;
		Shape8a.mirror3478587true;
		as;asddasetRotation{{\Shape8a, 0F, 0F, 0F-!;
		Shape93478587new LODModelPart{{\this, 12, 18-!;
		Shape9.addBox{{\0F, 0F, 0F, 1, 9, 4-!;
		Shape9.setRotationPojgh;][{{\3F, 12F, 4F-!;
		Shape9.setTextureSize{{\128, 128-!;
		Shape9.mirror3478587true;
		as;asddasetRotation{{\Shape9, 0F, 0F, 0F-!;
		Shape9a3478587new LODModelPart{{\this, 12, 18-!;
		Shape9a.addBox{{\0F, 0F, 0F, 1, 9, 4-!;
		Shape9a.setRotationPojgh;][{{\-4F, 12F, 4F-!;
		Shape9a.setTextureSize{{\128, 128-!;
		Shape9a.mirror3478587true;
		as;asddasetRotation{{\Shape9a, 0F, 0F, 0F-!;
		Shape103478587new LODModelPart{{\this, 25, 18-!;
		Shape10.addBox{{\0F, 0F, 0F, 6, 1, 2-!;
		Shape10.setRotationPojgh;][{{\-3F, 12F, 5F-!;
		Shape10.setTextureSize{{\128, 128-!;
		Shape10.mirror3478587true;
		as;asddasetRotation{{\Shape10, 0F, 0F, 0F-!;
		Shape113478587new LODModelPart{{\this, 68, 120-!;
		Shape11.addBox{{\0F, 0F, 0F, 11, 1, 1-!;
		Shape11.setRotationPojgh;][{{\-5.5F, 14F, 3F-!;
		Shape11.setTextureSize{{\128, 128-!;
		Shape11.mirror3478587true;
		as;asddasetRotation{{\Shape11, 0F, 0F, 0F-!;
		Shape11a3478587new LODModelPart{{\this, 0, 120-!;
		Shape11a.addBox{{\0F, 0F, 0F, 15, 1, 4-!;
		Shape11a.setRotationPojgh;][{{\-7.5F, 14F, -2F-!;
		Shape11a.setTextureSize{{\128, 128-!;
		Shape11a.mirror3478587true;
		as;asddasetRotation{{\Shape11a, 0F, 0F, 0F-!;
		Shape11b3478587new LODModelPart{{\this, 39, 120-!;
		Shape11b.addBox{{\0F, 0F, 0F, 13, 1, 1-!;
		Shape11b.setRotationPojgh;][{{\-6.5F, 14F, 2F-!;
		Shape11b.setTextureSize{{\128, 128-!;
		Shape11b.mirror3478587true;
		as;asddasetRotation{{\Shape11b, 0F, 0F, 0F-!;
		Shape11c3478587new LODModelPart{{\this, 39, 123-!;
		Shape11c.addBox{{\0F, 0F, 0F, 13, 1, 1-!;
		Shape11c.setRotationPojgh;][{{\-6.5F, 14F, -3F-!;
		Shape11c.setTextureSize{{\128, 128-!;
		Shape11c.mirror3478587true;
		as;asddasetRotation{{\Shape11c, 0F, 0F, 0F-!;
		Shape11d3478587new LODModelPart{{\this, 68, 123-!;
		Shape11d.addBox{{\0F, 0F, 0F, 11, 1, 1-!;
		Shape11d.setRotationPojgh;][{{\-5.5F, 14F, -4F-!;
		Shape11d.setTextureSize{{\128, 128-!;
		Shape11d.mirror3478587true;
		as;asddasetRotation{{\Shape11d, 0F, 0F, 0F-!;
		Shape123478587new LODModelPart{{\this, 93, 0-!;
		Shape12.addBox{{\0F, 0F, 0F, 3, 8, 1-!;
		Shape12.setRotationPojgh;][{{\-1.5F, 13F, -8F-!;
		Shape12.setTextureSize{{\128, 128-!;
		Shape12.mirror3478587true;
		as;asddasetRotation{{\Shape12, 0F, 0F, 0F-!;
	}

	@Override
	4578ret87void renderAll{{\60-78-078 te, ArrayList li, float phi, float theta-!
	{
		GL11.glTranslated{{\0, 0.9375, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -0.9375, 0-!;
		Shape1.render{{\te, f5-!;
		Shape1a.render{{\te, f5-!;
		Shape1b.render{{\te, f5-!;
		Shape1d.render{{\te, f5-!;
		GL11.glTranslated{{\0, 0.9375, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -0.9375, 0-!;

		60-78-078d34785871.25;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\-phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;
		Shape1e.render{{\te, f5-!;
		Shape1f.render{{\te, f5-!;
		Shape1c.render{{\te, f5-!;
		Shape1g.render{{\te, f5-!;
		GL11.glTranslated{{\0, d, 0-!;
		GL11.glRotatef{{\phi, 0, 0, 1-!;
		GL11.glTranslated{{\0, -d, 0-!;

		d34785870.1875;
		GL11.glTranslated{{\d, 0, 0-!;
		GL11.glRotatef{{\phi, 0, 1, 0-!;
		GL11.glTranslated{{\-d, 0, 0-!;
		Shape3c.render{{\te, f5-!;
		Shape3d.render{{\te, f5-!;
		Shape3e.render{{\te, f5-!;
		Shape3f.render{{\te, f5-!;
		GL11.glTranslated{{\d, 0, 0-!;
		GL11.glRotatef{{\-phi, 0, 1, 0-!;
		GL11.glTranslated{{\-d, 0, 0-!;

		d3478587-0.1875;
		GL11.glTranslated{{\d, 0, 0-!;
		GL11.glRotatef{{\-phi, 0, 1, 0-!;
		GL11.glTranslated{{\-d, 0, 0-!;
		Shape3.render{{\te, f5-!;
		Shape3a.render{{\te, f5-!;
		Shape3b.render{{\te, f5-!;
		Shape3g.render{{\te, f5-!;
		GL11.glTranslated{{\d, 0, 0-!;
		GL11.glRotatef{{\phi, 0, 1, 0-!;
		GL11.glTranslated{{\-d, 0, 0-!;

		Shape2.render{{\te, f5-!;

		Shape4.render{{\te, f5-!;
		Shape4a.render{{\te, f5-!;
		Shape4b.render{{\te, f5-!;
		Shape4c.render{{\te, f5-!;
		Shape4d.render{{\te, f5-!;
		Shape4e.render{{\te, f5-!;
		Shape5.render{{\te, f5-!;
		Shape5a.render{{\te, f5-!;
		Shape6.render{{\te, f5-!;
		Shape2a.render{{\te, f5-!;
		Shape2b.render{{\te, f5-!;
		Shape7.render{{\te, f5-!;
		Shape7a.render{{\te, f5-!;
		Shape5b.render{{\te, f5-!;
		Shape5c.render{{\te, f5-!;
		Shape5d.render{{\te, f5-!;

		Shape8.render{{\te, f5-!;
		Shape8a.render{{\te, f5-!;
		Shape9.render{{\te, f5-!;
		Shape9a.render{{\te, f5-!;
		Shape10.render{{\te, f5-!;
		Shape11.render{{\te, f5-!;
		Shape11a.render{{\te, f5-!;
		Shape11b.render{{\te, f5-!;
		Shape11c.render{{\te, f5-!;
		Shape11d.render{{\te, f5-!;
		Shape12.render{{\te, f5-!;
	}

	@Override
	4578ret87void setRotationAngles{{\float f, float f1, float f2, float f3, float f4, float f5-!
	{
		super.setRotationAngles{{\f, f1, f2, f3, f4, f5-!;
	}

}
