/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 20/02/2013 4:55:10 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models.Engine;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

import org.lwjgl.opengl.GL11;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;


public class ModelSteam extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape2;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape20;
	LODModelPart Shape11;
	LODModelPart Shape10;
	LODModelPart Shape9;
	LODModelPart Shape8;
	LODModelPart Shape7;
	LODModelPart Shape6;
	LODModelPart Shape5;
	LODModelPart Shape4;
	LODModelPart Shape21;
	LODModelPart Shape22;
	LODModelPart Shape23;
	LODModelPart Shape3;

	public ModelSteam()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape1.setRotationPoint(-8F, 23F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape12 = new LODModelPart(this, 98, 0);
		Shape12.addBox(0F, 0F, 0F, 1, 8, 8);
		Shape12.setRotationPoint(-6.1F, 13.8F, -5.1F);
		Shape12.setTextureSize(128, 128);
		Shape12.mirror = true;
		this.setRotation(Shape12, 0.3926991F, 0F, 0F);
		Shape13 = new LODModelPart(this, 98, 0);
		Shape13.addBox(0F, 0F, 0F, 1, 8, 8);
		Shape13.setRotationPoint(-6F, 16F, -5.5F);
		Shape13.setTextureSize(128, 128);
		Shape13.mirror = true;
		this.setRotation(Shape13, 0.7853982F, 0F, 0F);
		Shape14 = new LODModelPart(this, 0, 27);
		Shape14.addBox(0F, 0F, 0F, 5, 2, 2);
		Shape14.setRotationPoint(-8.5F, 15F, -1F);
		Shape14.setTextureSize(128, 128);
		Shape14.mirror = true;
		this.setRotation(Shape14, 0F, 0F, 0F);
		Shape15 = new LODModelPart(this, 0, 27);
		Shape15.addBox(0F, 0F, 0F, 5, 2, 2);
		Shape15.setRotationPoint(-8.5F, 16F, -1.4F);
		Shape15.setTextureSize(128, 128);
		Shape15.mirror = true;
		this.setRotation(Shape15, 0.7853982F, 0F, 0F);
		Shape16 = new LODModelPart(this, 98, 0);
		Shape16.addBox(0F, 0F, 0F, 1, 8, 8);
		Shape16.setRotationPoint(-6F, 10.8F, -2.2F);
		Shape16.setTextureSize(128, 128);
		Shape16.mirror = true;
		this.setRotation(Shape16, -0.3926991F, 0F, 0F);
		Shape17 = new LODModelPart(this, 98, 0);
		Shape17.addBox(0F, 0F, 0F, 1, 8, 8);
		Shape17.setRotationPoint(-5.9F, 12F, -4F);
		Shape17.setTextureSize(128, 128);
		Shape17.mirror = true;
		this.setRotation(Shape17, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 98, 16);
		Shape2.addBox(0F, -1.5F, -1.5F, 1, 3, 3);
		Shape2.setRotationPoint(-6F, 20.5F, -5.5F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0.7853982F, 0F, 0F);
		Shape18 = new LODModelPart(this, 0, 32);
		Shape18.addBox(0F, -0.5F, -0.5F, 3, 1, 1);
		Shape18.setRotationPoint(-5F, 20.5F, 5.5F);
		Shape18.setTextureSize(128, 128);
		Shape18.mirror = true;
		this.setRotation(Shape18, 0.7853982F, 0F, 0F);
		Shape19 = new LODModelPart(this, 98, 16);
		Shape19.addBox(0F, -1.5F, -1.5F, 1, 3, 3);
		Shape19.setRotationPoint(-6F, 20.5F, 5.5F);
		Shape19.setTextureSize(128, 128);
		Shape19.mirror = true;
		this.setRotation(Shape19, 0F, 0F, 0F);
		Shape20 = new LODModelPart(this, 98, 16);
		Shape20.addBox(0F, -1.5F, -1.5F, 1, 3, 3);
		Shape20.setRotationPoint(-6F, 20.5F, 5.5F);
		Shape20.setTextureSize(128, 128);
		Shape20.mirror = true;
		this.setRotation(Shape20, 0.7853982F, 0F, 0F);
		Shape11 = new LODModelPart(this, 98, 16);
		Shape11.addBox(0F, -1.5F, -1.5F, 1, 3, 3);
		Shape11.setRotationPoint(-6F, 20.5F, -5.5F);
		Shape11.setTextureSize(128, 128);
		Shape11.mirror = true;
		this.setRotation(Shape11, 0F, 0F, 0F);
		Shape10 = new LODModelPart(this, 48, 17);
		Shape10.addBox(0F, 0F, 0F, 1, 4, 4);
		Shape10.setRotationPoint(-2F, 20.5F, 1F);
		Shape10.setTextureSize(128, 128);
		Shape10.mirror = true;
		this.setRotation(Shape10, 0.7853982F, 0F, 0F);
		Shape9 = new LODModelPart(this, 64, 0);
		Shape9.addBox(0F, 0F, 0F, 9, 6, 8);
		Shape9.setRotationPoint(-3F, 17F, -4F);
		Shape9.setTextureSize(128, 128);
		Shape9.mirror = true;
		this.setRotation(Shape9, 0F, 0F, 0F);
		Shape8 = new LODModelPart(this, 28, 17);
		Shape8.addBox(0F, 0F, 0F, 1, 1, 2);
		Shape8.setRotationPoint(-4F, 14.5F, -1F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		this.setRotation(Shape8, 0F, 0F, 0F);
		Shape7 = new LODModelPart(this, 0, 32);
		Shape7.addBox(0F, -0.5F, -0.5F, 7, 1, 1);
		Shape7.setRotationPoint(-5F, 20.5F, -5.5F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0.7853982F, 0F, 0F);
		Shape6 = new LODModelPart(this, 0, 32);
		Shape6.addBox(0F, -0.5F, -0.5F, 7, 1, 1);
		Shape6.setRotationPoint(-5F, 20.5F, -5.5F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 48, 17);
		Shape5.addBox(0F, 0F, 0F, 1, 4, 4);
		Shape5.setRotationPoint(2F, 20.5F, -6.7F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0.7853982F, 0F, 0F);
		Shape4 = new LODModelPart(this, 0, 32);
		Shape4.addBox(0F, -0.5F, -0.5F, 3, 1, 1);
		Shape4.setRotationPoint(-5F, 20.5F, 5.5F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape21 = new LODModelPart(this, 34, 17);
		Shape21.addBox(0F, 0F, 0F, 1, 4, 4);
		Shape21.setRotationPoint(7F, 17F, -2F);
		Shape21.setTextureSize(128, 128);
		Shape21.mirror = true;
		this.setRotation(Shape21, 0F, 0F, 0F);
		Shape22 = new LODModelPart(this, 0, 17);
		Shape22.addBox(0F, 0F, 0F, 3, 1, 5);
		Shape22.setRotationPoint(-4F, 15.5F, -2.5F);
		Shape22.setTextureSize(128, 128);
		Shape22.mirror = true;
		this.setRotation(Shape22, 0F, 0F, 0F);
		Shape23 = new LODModelPart(this, 16, 17);
		Shape23.addBox(0F, 0F, 0F, 2, 1, 4);
		Shape23.setRotationPoint(-4F, 15F, -2F);
		Shape23.setTextureSize(128, 128);
		Shape23.mirror = true;
		this.setRotation(Shape23, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 64, 14);
		Shape3.addBox(0F, 0F, 0F, 11, 7, 6);
		Shape3.setRotationPoint(-4F, 16F, -3F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);
		Shape3.render(te, f5);
		Shape5.render(te, f5);
		Shape8.render(te, f5);
		Shape9.render(te, f5);
		Shape10.render(te, f5);

		GL11.glTranslated(0, 1, 0);
		GL11.glRotatef(phi, 1, 0, 0);
		GL11.glTranslated(0, -1, 0);
		Shape12.render(te, f5);
		Shape13.render(te, f5);
		Shape14.render(te, f5);
		Shape15.render(te, f5);
		Shape16.render(te, f5);
		Shape17.render(te, f5);
		GL11.glTranslated(0, 1, 0);
		GL11.glRotatef(-phi, 1, 0, 0);
		GL11.glTranslated(0, -1, 0);

		double d = 1.28125;
		double d1 = 0.34375;
		double d2 = -0.3125;
		GL11.glTranslated(d2, d, d1);
		GL11.glRotatef(-phi*1.5F, 1, 0, 0);
		Shape4.setRotationPoint(0, 0, 0);
		Shape18.setRotationPoint(0, 0, 0);
		Shape19.setRotationPoint(-1F, 0, 0);
		Shape20.setRotationPoint(-1F, 0, 0);
		Shape4.render(te, f5);
		Shape18.render(te, f5);
		Shape19.render(te, f5);
		Shape20.render(te, f5);
		GL11.glRotatef(phi*1.5F, 1, 0, 0);
		GL11.glTranslated(-d2, -d, -d1);

		d = 1.28125;
		d1 = -0.34375;
		d2 = -0.3125;
		GL11.glTranslated(d2, d, d1);
		GL11.glRotatef(-phi*1.5F, 1, 0, 0);
		Shape2.setRotationPoint(-1F, 0, 0);
		Shape11.setRotationPoint(-1F, 0, 0);
		Shape6.setRotationPoint(0, 0, 0);
		Shape7.setRotationPoint(0, 0, 0);
		Shape2.render(te, f5);
		Shape11.render(te, f5);
		Shape6.render(te, f5);
		Shape7.render(te, f5);
		GL11.glRotatef(phi*1.5F, 1, 0, 0);
		GL11.glTranslated(-d2, -d, -d1);

		Shape21.render(te, f5);
		Shape22.render(te, f5);
		Shape23.render(te, f5);
	}

}
