/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2013
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 28/12/2013 4:51:42 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models.Animated;

import java.util.ArrayList;

import net.minecraft.client.model.ModelRenderer;

import org.lwjgl.opengl.GL11;

import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelCrystallizer extends RotaryModelBase
{
	//fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape2a;
	ModelRenderer Shape3;
	ModelRenderer Shape3a;
	ModelRenderer Shape3b;
	ModelRenderer Shape3c;
	ModelRenderer Shape4;
	ModelRenderer Shape5;
	ModelRenderer Shape5a;
	ModelRenderer Shape5b;
	ModelRenderer Shape5c;
	ModelRenderer Shape5d;
	ModelRenderer Shape5e;
	ModelRenderer Shape5f;
	ModelRenderer Shape5g;
	ModelRenderer Shape5h;
	ModelRenderer Shape5i;
	ModelRenderer Shape6;
	ModelRenderer Shape6a;
	ModelRenderer Shape6b;
	ModelRenderer Shape6c;
	ModelRenderer Shape6d;
	ModelRenderer Shape6e;
	ModelRenderer Shape7;
	ModelRenderer Shape7a;
	ModelRenderer Shape8;
	ModelRenderer Shape8a;
	ModelRenderer Shape9;

	public ModelCrystallizer()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new ModelRenderer(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape1.setRotationPoint(-8F, 23F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 65, 0);
		Shape2.addBox(-1F, -1F, 0F, 2, 2, 4);
		Shape2.setRotationPoint(0F, 16F, 4.5F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0.7853982F);
		Shape2a = new ModelRenderer(this, 65, 0);
		Shape2a.addBox(-1F, -1F, 0F, 2, 2, 4);
		Shape2a.setRotationPoint(0F, 16F, 4.5F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 78, 0);
		Shape3.addBox(-1F, -6F, 0F, 2, 12, 1);
		Shape3.setRotationPoint(0F, 16F, 6F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 2.356194F);
		Shape3a = new ModelRenderer(this, 78, 0);
		Shape3a.addBox(-1F, -6F, 0F, 2, 12, 1);
		Shape3a.setRotationPoint(0F, 16F, 6F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape3b = new ModelRenderer(this, 78, 0);
		Shape3b.addBox(-1F, -6F, 0F, 2, 12, 1);
		Shape3b.setRotationPoint(0F, 16F, 6F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0F, 0.7853982F);
		Shape3c = new ModelRenderer(this, 78, 0);
		Shape3c.addBox(-1F, -6F, 0F, 2, 12, 1);
		Shape3c.setRotationPoint(0F, 16F, 6F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0F, 1.570796F);
		Shape4 = new ModelRenderer(this, 0, 19);
		Shape4.addBox(0F, 0F, 0F, 13, 15, 12);
		Shape4.setRotationPoint(-6.5F, 8.5F, -6F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape5 = new ModelRenderer(this, 85, 0);
		Shape5.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5.setRotationPoint(5.5F, 21F, -6F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape5a = new ModelRenderer(this, 85, 0);
		Shape5a.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5a.setRotationPoint(-7.5F, 9F, -6F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 0F, 0F, 0F);
		Shape5b = new ModelRenderer(this, 85, 0);
		Shape5b.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5b.setRotationPoint(-7.5F, 21F, -6F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0F, 0F);
		Shape5c = new ModelRenderer(this, 85, 0);
		Shape5c.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5c.setRotationPoint(5.5F, 15F, -6F);
		Shape5c.setTextureSize(128, 128);
		Shape5c.mirror = true;
		this.setRotation(Shape5c, 0F, 0F, 0F);
		Shape5d = new ModelRenderer(this, 85, 0);
		Shape5d.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5d.setRotationPoint(5.5F, 18F, -6F);
		Shape5d.setTextureSize(128, 128);
		Shape5d.mirror = true;
		this.setRotation(Shape5d, 0F, 0F, 0F);
		Shape5e = new ModelRenderer(this, 85, 0);
		Shape5e.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5e.setRotationPoint(5.5F, 9F, -6F);
		Shape5e.setTextureSize(128, 128);
		Shape5e.mirror = true;
		this.setRotation(Shape5e, 0F, 0F, 0F);
		Shape5f = new ModelRenderer(this, 85, 0);
		Shape5f.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5f.setRotationPoint(5.5F, 12F, -6F);
		Shape5f.setTextureSize(128, 128);
		Shape5f.mirror = true;
		this.setRotation(Shape5f, 0F, 0F, 0F);
		Shape5g = new ModelRenderer(this, 85, 0);
		Shape5g.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5g.setRotationPoint(-7.5F, 12F, -6F);
		Shape5g.setTextureSize(128, 128);
		Shape5g.mirror = true;
		this.setRotation(Shape5g, 0F, 0F, 0F);
		Shape5h = new ModelRenderer(this, 85, 0);
		Shape5h.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5h.setRotationPoint(-7.5F, 15F, -6F);
		Shape5h.setTextureSize(128, 128);
		Shape5h.mirror = true;
		this.setRotation(Shape5h, 0F, 0F, 0F);
		Shape5i = new ModelRenderer(this, 85, 0);
		Shape5i.addBox(0F, 0F, 0F, 2, 1, 11);
		Shape5i.setRotationPoint(-7.5F, 18F, -6F);
		Shape5i.setTextureSize(128, 128);
		Shape5i.mirror = true;
		this.setRotation(Shape5i, 0F, 0F, 0F);
		Shape6 = new ModelRenderer(this, 0, 47);
		Shape6.addBox(0F, 0F, 0F, 1, 1, 11);
		Shape6.setRotationPoint(-6F, 8F, -6F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape6a = new ModelRenderer(this, 0, 47);
		Shape6a.addBox(0F, 0F, 0F, 1, 1, 11);
		Shape6a.setRotationPoint(5F, 8F, -6F);
		Shape6a.setTextureSize(128, 128);
		Shape6a.mirror = true;
		this.setRotation(Shape6a, 0F, 0F, 0F);
		Shape6b = new ModelRenderer(this, 0, 47);
		Shape6b.addBox(0F, 0F, 0F, 1, 1, 11);
		Shape6b.setRotationPoint(3F, 8F, -6F);
		Shape6b.setTextureSize(128, 128);
		Shape6b.mirror = true;
		this.setRotation(Shape6b, 0F, 0F, 0F);
		Shape6c = new ModelRenderer(this, 0, 47);
		Shape6c.addBox(0F, 0F, 0F, 1, 1, 11);
		Shape6c.setRotationPoint(1F, 8F, -6F);
		Shape6c.setTextureSize(128, 128);
		Shape6c.mirror = true;
		this.setRotation(Shape6c, 0F, 0F, 0F);
		Shape6d = new ModelRenderer(this, 0, 47);
		Shape6d.addBox(0F, 0F, 0F, 1, 1, 11);
		Shape6d.setRotationPoint(-2F, 8F, -6F);
		Shape6d.setTextureSize(128, 128);
		Shape6d.mirror = true;
		this.setRotation(Shape6d, 0F, 0F, 0F);
		Shape6e = new ModelRenderer(this, 0, 47);
		Shape6e.addBox(0F, 0F, 0F, 1, 1, 11);
		Shape6e.setRotationPoint(-4F, 8F, -6F);
		Shape6e.setTextureSize(128, 128);
		Shape6e.mirror = true;
		this.setRotation(Shape6e, 0F, 0F, 0F);
		Shape7 = new ModelRenderer(this, 0, 61);
		Shape7.addBox(0F, 0F, 0F, 13, 1, 1);
		Shape7.setRotationPoint(-6.5F, 8.5F, -7F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, 0F, 0F);
		Shape7a = new ModelRenderer(this, 0, 64);
		Shape7a.addBox(0F, 0F, 0F, 13, 1, 1);
		Shape7a.setRotationPoint(-6.5F, 22.5F, -7F);
		Shape7a.setTextureSize(128, 128);
		Shape7a.mirror = true;
		this.setRotation(Shape7a, 0F, 0F, 0F);
		Shape8 = new ModelRenderer(this, 118, 0);
		Shape8.addBox(0F, 0F, 0F, 1, 13, 1);
		Shape8.setRotationPoint(5.5F, 9.5F, -7F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		this.setRotation(Shape8, 0F, 0F, 0F);
		Shape8a = new ModelRenderer(this, 113, 0);
		Shape8a.addBox(0F, 0F, 0F, 1, 13, 1);
		Shape8a.setRotationPoint(-6.5F, 9.5F, -7F);
		Shape8a.setTextureSize(128, 128);
		Shape8a.mirror = true;
		this.setRotation(Shape8a, 0F, 0F, 0F);
		Shape9 = new ModelRenderer(this, 0, 68);
		Shape9.addBox(0F, 0F, 0F, 10, 12, 1);
		Shape9.setRotationPoint(-5F, 10F, -7F);
		Shape9.setTextureSize(128, 128);
		Shape9.mirror = true;
		this.setRotation(Shape9, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(ArrayList li, float phi, float theta)
	{
		Shape1.render(f5);

		double d = 1;
		GL11.glTranslated(0, d, 0);
		GL11.glRotatef(phi, 0, 0, 1);
		GL11.glTranslated(0, -d, 0);
		Shape2.render(f5);
		Shape2a.render(f5);
		Shape3.render(f5);
		Shape3a.render(f5);
		Shape3b.render(f5);
		Shape3c.render(f5);
		GL11.glTranslated(0, d, 0);
		GL11.glRotatef(-phi, 0, 0, 1);
		GL11.glTranslated(0, -d, 0);

		Shape4.render(f5);
		Shape5.render(f5);
		Shape5a.render(f5);
		Shape5b.render(f5);
		Shape5c.render(f5);
		Shape5d.render(f5);
		Shape5e.render(f5);
		Shape5f.render(f5);
		Shape5g.render(f5);
		Shape5h.render(f5);
		Shape5i.render(f5);
		Shape6.render(f5);
		Shape6a.render(f5);
		Shape6b.render(f5);
		Shape6c.render(f5);
		Shape6d.render(f5);
		Shape6e.render(f5);
		Shape7.render(f5);
		Shape7a.render(f5);
		Shape8.render(f5);
		Shape8a.render(f5);
		Shape9.render(f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
