/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 03/03/2013 3:04:35 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models.Animated;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

import org.lwjgl.opengl.GL11;


public class ModelPileDriver extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape9;
	LODModelPart Shape9a;
	LODModelPart Shape9b;
	LODModelPart Shape9c;
	LODModelPart Shape9d;
	LODModelPart Shape9e;
	LODModelPart Shape9f;
	LODModelPart Shape9g;
	LODModelPart Shape10;
	LODModelPart Shape1o;
	LODModelPart Shape1a;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape1d;
	LODModelPart Shape1e;
	LODModelPart Shape1f;
	LODModelPart Shape1g;
	LODModelPart Shape9h;
	LODModelPart Shape10af;
	LODModelPart Shape10z;
	LODModelPart Shape10y;
	LODModelPart Shape10x;
	LODModelPart Shape10w;
	LODModelPart Shape10v;
	LODModelPart Shape10u;
	LODModelPart Shape10t;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape6;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape7;
	LODModelPart Shape7a;

	public ModelPileDriver()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 27, 0);
		Shape1.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1.setRotationPoint(-1F, 16F, 0F);
		Shape1.setTextureSize(64, 32);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0.1745329F, 0F, 0F);
		Shape9 = new LODModelPart(this, 0, 0);
		Shape9.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9.setRotationPoint(-2F, 16F, 0F);
		Shape9.setTextureSize(64, 32);
		Shape9.mirror = true;
		this.setRotation(Shape9, 0.1745329F, 0F, 0F);
		Shape9a = new LODModelPart(this, 0, 0);
		Shape9a.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9a.setRotationPoint(-2F, 16F, 0F);
		Shape9a.setTextureSize(64, 32);
		Shape9a.mirror = true;
		this.setRotation(Shape9a, 0.3490659F, 0F, 0F);
		Shape9b = new LODModelPart(this, 0, 0);
		Shape9b.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9b.setRotationPoint(-2F, 16F, 0F);
		Shape9b.setTextureSize(64, 32);
		Shape9b.mirror = true;
		this.setRotation(Shape9b, 0.6981317F, 0F, 0F);
		Shape9c = new LODModelPart(this, 0, 0);
		Shape9c.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9c.setRotationPoint(-2F, 16F, 0F);
		Shape9c.setTextureSize(64, 32);
		Shape9c.mirror = true;
		this.setRotation(Shape9c, 1.047198F, 0F, 0F);
		Shape9d = new LODModelPart(this, 0, 0);
		Shape9d.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9d.setRotationPoint(-2F, 16F, 0F);
		Shape9d.setTextureSize(64, 32);
		Shape9d.mirror = true;
		this.setRotation(Shape9d, 0.8726646F, 0F, 0F);
		Shape9e = new LODModelPart(this, 0, 0);
		Shape9e.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9e.setRotationPoint(-2F, 16F, 0F);
		Shape9e.setTextureSize(64, 32);
		Shape9e.mirror = true;
		this.setRotation(Shape9e, 0.5235988F, 0F, 0F);
		Shape9f = new LODModelPart(this, 0, 0);
		Shape9f.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9f.setRotationPoint(-2F, 16F, 0F);
		Shape9f.setTextureSize(64, 32);
		Shape9f.mirror = true;
		this.setRotation(Shape9f, 1.22173F, 0F, 0F);
		Shape9g = new LODModelPart(this, 0, 0);
		Shape9g.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9g.setRotationPoint(-2F, 16F, 0F);
		Shape9g.setTextureSize(64, 32);
		Shape9g.mirror = true;
		this.setRotation(Shape9g, 1.396263F, 0F, 0F);
		Shape10 = new LODModelPart(this, 0, 0);
		Shape10.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10.setRotationPoint(1F, 16F, 0F);
		Shape10.setTextureSize(64, 32);
		Shape10.mirror = true;
		this.setRotation(Shape10, 0.1745329F, 0F, 0F);
		Shape1o = new LODModelPart(this, 27, 0);
		Shape1o.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1o.setRotationPoint(-1F, 16F, 0F);
		Shape1o.setTextureSize(64, 32);
		Shape1o.mirror = true;
		this.setRotation(Shape1o, 1.22173F, 0F, 0F);
		Shape1a = new LODModelPart(this, 27, 0);
		Shape1a.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1a.setRotationPoint(-1F, 16F, 0F);
		Shape1a.setTextureSize(64, 32);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, 0.6981317F, 0F, 0F);
		Shape1b = new LODModelPart(this, 27, 0);
		Shape1b.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1b.setRotationPoint(-1F, 16F, 0F);
		Shape1b.setTextureSize(64, 32);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0.8726646F, 0F, 0F);
		Shape1c = new LODModelPart(this, 27, 0);
		Shape1c.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1c.setRotationPoint(-1F, 16F, 0F);
		Shape1c.setTextureSize(64, 32);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, 0.5235988F, 0F, 0F);
		Shape1d = new LODModelPart(this, 27, 0);
		Shape1d.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1d.setRotationPoint(-1F, 16F, 0F);
		Shape1d.setTextureSize(64, 32);
		Shape1d.mirror = true;
		this.setRotation(Shape1d, 0.3490659F, 0F, 0F);
		Shape1e = new LODModelPart(this, 27, 0);
		Shape1e.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1e.setRotationPoint(-1F, 16F, 0F);
		Shape1e.setTextureSize(64, 32);
		Shape1e.mirror = true;
		this.setRotation(Shape1e, 1.047198F, 0F, 0F);
		Shape1f = new LODModelPart(this, 27, 0);
		Shape1f.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1f.setRotationPoint(-1F, 16F, 0F);
		Shape1f.setTextureSize(64, 32);
		Shape1f.mirror = true;
		this.setRotation(Shape1f, 0F, 0F, 0F);
		Shape1g = new LODModelPart(this, 27, 0);
		Shape1g.addBox(0F, -5F, -5F, 2, 10, 10);
		Shape1g.setRotationPoint(-1F, 16F, 0F);
		Shape1g.setTextureSize(64, 32);
		Shape1g.mirror = true;
		this.setRotation(Shape1g, 1.396263F, 0F, 0F);
		Shape9h = new LODModelPart(this, 0, 0);
		Shape9h.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape9h.setRotationPoint(-2F, 16F, 0F);
		Shape9h.setTextureSize(64, 32);
		Shape9h.mirror = true;
		this.setRotation(Shape9h, 0F, 0F, 0F);
		Shape10af = new LODModelPart(this, 0, 0);
		Shape10af.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10af.setRotationPoint(1F, 16F, 0F);
		Shape10af.setTextureSize(64, 32);
		Shape10af.mirror = true;
		this.setRotation(Shape10af, 1.396263F, 0F, 0F);
		Shape10z = new LODModelPart(this, 0, 0);
		Shape10z.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10z.setRotationPoint(1F, 16F, 0F);
		Shape10z.setTextureSize(64, 32);
		Shape10z.mirror = true;
		this.setRotation(Shape10z, 0.8726646F, 0F, 0F);
		Shape10y = new LODModelPart(this, 0, 0);
		Shape10y.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10y.setRotationPoint(1F, 16F, 0F);
		Shape10y.setTextureSize(64, 32);
		Shape10y.mirror = true;
		this.setRotation(Shape10y, 1.047198F, 0F, 0F);
		Shape10x = new LODModelPart(this, 0, 0);
		Shape10x.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10x.setRotationPoint(1F, 16F, 0F);
		Shape10x.setTextureSize(64, 32);
		Shape10x.mirror = true;
		this.setRotation(Shape10x, 0.6981317F, 0F, 0F);
		Shape10w = new LODModelPart(this, 0, 0);
		Shape10w.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10w.setRotationPoint(1F, 16F, 0F);
		Shape10w.setTextureSize(64, 32);
		Shape10w.mirror = true;
		this.setRotation(Shape10w, 0.3490659F, 0F, 0F);
		Shape10v = new LODModelPart(this, 0, 0);
		Shape10v.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10v.setRotationPoint(1F, 16F, 0F);
		Shape10v.setTextureSize(64, 32);
		Shape10v.mirror = true;
		this.setRotation(Shape10v, 0.5235988F, 0F, 0F);
		Shape10u = new LODModelPart(this, 0, 0);
		Shape10u.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10u.setRotationPoint(1F, 16F, 0F);
		Shape10u.setTextureSize(64, 32);
		Shape10u.mirror = true;
		this.setRotation(Shape10u, 1.22173F, 0F, 0F);
		Shape10t = new LODModelPart(this, 0, 0);
		Shape10t.addBox(0F, -6F, -6F, 1, 12, 12);
		Shape10t.setRotationPoint(1F, 16F, 0F);
		Shape10t.setTextureSize(64, 32);
		Shape10t.mirror = true;
		this.setRotation(Shape10t, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 0, 25);
		Shape2.addBox(0F, -1F, -1F, 17, 2, 2);
		Shape2.setRotationPoint(-8.5F, 16F, 0F);
		Shape2.setTextureSize(64, 32);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0.7853982F, 0F, 0F);
		Shape2a = new LODModelPart(this, 0, 25);
		Shape2a.addBox(0F, -1F, -1F, 17, 2, 2);
		Shape2a.setRotationPoint(-8.5F, 16F, 0F);
		Shape2a.setTextureSize(64, 32);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 51, 0);
		Shape3.addBox(0F, 0F, 0F, 1, 16, 16);
		Shape3.setRotationPoint(-8F, 8F, -8F);
		Shape3.setTextureSize(64, 32);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape3a = new LODModelPart(this, 51, 0);
		Shape3a.addBox(0F, 0F, 0F, 1, 16, 16);
		Shape3a.setRotationPoint(7F, 8F, -8F);
		Shape3a.setTextureSize(64, 32);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 0, 30);
		Shape4.addBox(0F, 0F, 0F, 14, 3, 1);
		Shape4.setRotationPoint(-7F, 21F, -8F);
		Shape4.setTextureSize(64, 32);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape4a = new LODModelPart(this, 0, 30);
		Shape4a.addBox(0F, 0F, 0F, 14, 3, 1);
		Shape4a.setRotationPoint(-7F, 8F, -8F);
		Shape4a.setTextureSize(64, 32);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape4b = new LODModelPart(this, 0, 30);
		Shape4b.addBox(0F, 0F, 0F, 14, 3, 1);
		Shape4b.setRotationPoint(-7F, 21F, 7F);
		Shape4b.setTextureSize(64, 32);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0F, 0F, 0F);
		Shape4c = new LODModelPart(this, 0, 30);
		Shape4c.addBox(0F, 0F, 0F, 14, 3, 1);
		Shape4c.setRotationPoint(-7F, 8F, 7F);
		Shape4c.setTextureSize(64, 32);
		Shape4c.mirror = true;
		this.setRotation(Shape4c, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 100, 0);
		Shape5.addBox(0F, 0F, -0.5F, 2, 8, 1);
		Shape5.setRotationPoint(-1F, 16.4F, 8F);
		Shape5.setTextureSize(64, 32);
		Shape5.mirror = true;
		this.setRotation(Shape5, -2.687807F, 0F, 0F);
		Shape5a = new LODModelPart(this, 100, 0);
		Shape5a.addBox(0F, 0F, -0.5F, 2, 8, 1);
		Shape5a.setRotationPoint(-1F, 16.4F, -8F);
		Shape5a.setTextureSize(64, 32);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 2.687807F, 0F, 0F);
		Shape6 = new LODModelPart(this, 0, 34);
		Shape6.addBox(0F, 0F, -0.5F, 2, 4, 13);
		Shape6.setRotationPoint(-1F, 21F, -6F);
		Shape6.setTextureSize(64, 32);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape5b = new LODModelPart(this, 106, 0);
		Shape5b.addBox(0F, 0F, -0.5F, 2, 7, 1);
		Shape5b.setRotationPoint(-1F, 16F, 8F);
		Shape5b.setTextureSize(64, 32);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, -0.296706F, 0F, 0F);
		Shape5c = new LODModelPart(this, 106, 0);
		Shape5c.addBox(0F, 0F, -0.5F, 2, 7, 1);
		Shape5c.setRotationPoint(-1F, 16F, -8F);
		Shape5c.setTextureSize(64, 32);
		Shape5c.mirror = true;
		this.setRotation(Shape5c, 0.296706F, 0F, 0F);
		Shape7 = new LODModelPart(this, 86, 0);
		Shape7.addBox(0F, 0F, 0F, 2, 1, 5);
		Shape7.setRotationPoint(-1F, 9F, 0.2F);
		Shape7.setTextureSize(64, 32);
		Shape7.mirror = true;
		this.setRotation(Shape7, -2.94088F, 0F, 0F);
		Shape7a = new LODModelPart(this, 86, 0);
		Shape7a.addBox(0F, 0F, 0F, 2, 1, 5);
		Shape7a.setRotationPoint(-1F, 8F, 0F);
		Shape7a.setTextureSize(64, 32);
		Shape7a.mirror = true;
		this.setRotation(Shape7a, -0.2181662F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		boolean on = (Boolean)li.get(0);
		if (!on)
			Shape1.render(te, f5);
		float f1 = 2.5F;
		GL11.glTranslated(0, 1, 0);
		GL11.glRotatef(phi/f1, 1, 0, 0);
		GL11.glTranslated(0, -1, 0);
		Shape9.render(te, f5);
		Shape9a.render(te, f5);
		Shape9b.render(te, f5);
		Shape9c.render(te, f5);
		Shape9d.render(te, f5);
		Shape9e.render(te, f5);
		Shape9f.render(te, f5);
		Shape9g.render(te, f5);
		Shape10.render(te, f5);
		GL11.glTranslated(0, 1, 0);
		GL11.glRotatef(-phi/f1, 1, 0, 0);
		GL11.glTranslated(0, -1, 0);
		if (!on) {
			Shape1o.render(te, f5);
			Shape1a.render(te, f5);
			Shape1b.render(te, f5);
			Shape1c.render(te, f5);
			Shape1d.render(te, f5);
			Shape1e.render(te, f5);
			Shape1f.render(te, f5);
			Shape1g.render(te, f5);
		}
		GL11.glTranslated(0, 1, 0);
		GL11.glRotatef(phi/f1, 1, 0, 0);
		GL11.glTranslated(0, -1, 0);
		Shape9h.render(te, f5);
		Shape10af.render(te, f5);
		Shape10z.render(te, f5);
		Shape10y.render(te, f5);
		Shape10x.render(te, f5);
		Shape10w.render(te, f5);
		Shape10v.render(te, f5);
		Shape10u.render(te, f5);
		Shape10t.render(te, f5);
		GL11.glTranslated(0, 1, 0);
		GL11.glRotatef(-phi/f1, 1, 0, 0);
		GL11.glTranslated(0, -1, 0);
		GL11.glTranslated(0, 1, 0);
		GL11.glRotatef(phi, 1, 0, 0);
		GL11.glTranslated(0, -1, 0);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		GL11.glTranslated(0, 1, 0);
		GL11.glRotatef(-phi, 1, 0, 0);
		GL11.glTranslated(0, -1, 0);
		Shape3.render(te, f5);
		Shape3a.render(te, f5);
		Shape4.render(te, f5);
		Shape4a.render(te, f5);
		Shape4b.render(te, f5);
		Shape4c.render(te, f5);
		if (on) {
			Shape5.render(te, f5);
			Shape5a.render(te, f5);
			Shape6.render(te, f5);
			Shape5b.render(te, f5);
			Shape5c.render(te, f5);
			Shape7.render(te, f5);
			Shape7a.render(te, f5);
		}
	}
}