/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 21/02/2014 5:25:40 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models.Animated;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

import org.lwjgl.opengl.GL11;

public class ModelDefoliator extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape4e;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape4d;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6c;

	public ModelDefoliator()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape1.setRotationPoint(-8F, 23F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 0, 33);
		Shape3.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape3.setRotationPoint(0F, 18F, 0F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 1.308997F, 0F);
		Shape4 = new LODModelPart(this, 0, 45);
		Shape4.addBox(-3F, 0F, -3F, 6, 1, 6);
		Shape4.setRotationPoint(0F, 17F, 0F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 1.308997F, 0F);
		Shape5 = new LODModelPart(this, 0, 54);
		Shape5.addBox(-1.5F, 0F, -1.5F, 3, 1, 3);
		Shape5.setRotationPoint(0F, 16F, 0F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 1.308997F, 0F);
		Shape2 = new LODModelPart(this, 0, 19);
		Shape2.addBox(-5F, 0F, -5F, 10, 3, 10);
		Shape2.setRotationPoint(0F, 20F, 0F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 1.308997F, 0F);
		Shape2a = new LODModelPart(this, 0, 19);
		Shape2a.addBox(-5F, 0F, -5F, 10, 3, 10);
		Shape2a.setRotationPoint(0F, 20F, 0F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape2b = new LODModelPart(this, 0, 19);
		Shape2b.addBox(-5F, 0F, -5F, 10, 3, 10);
		Shape2b.setRotationPoint(0F, 20F, 0F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0.2617994F, 0F);
		Shape2c = new LODModelPart(this, 0, 19);
		Shape2c.addBox(-5F, 0F, -5F, 10, 3, 10);
		Shape2c.setRotationPoint(0F, 20F, 0F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0.5235988F, 0F);
		Shape2d = new LODModelPart(this, 0, 19);
		Shape2d.addBox(-5F, 0F, -5F, 10, 3, 10);
		Shape2d.setRotationPoint(0F, 20F, 0F);
		Shape2d.setTextureSize(128, 128);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 0.7853982F, 0F);
		Shape2e = new LODModelPart(this, 0, 19);
		Shape2e.addBox(-5F, 0F, -5F, 10, 3, 10);
		Shape2e.setRotationPoint(0F, 20F, 0F);
		Shape2e.setTextureSize(128, 128);
		Shape2e.mirror = true;
		this.setRotation(Shape2e, 0F, 1.047198F, 0F);
		Shape3a = new LODModelPart(this, 0, 33);
		Shape3a.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape3a.setRotationPoint(0F, 18F, 0F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape3b = new LODModelPart(this, 0, 33);
		Shape3b.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape3b.setRotationPoint(0F, 18F, 0F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0.2617994F, 0F);
		Shape3c = new LODModelPart(this, 0, 33);
		Shape3c.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape3c.setRotationPoint(0F, 18F, 0F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0.5235988F, 0F);
		Shape3d = new LODModelPart(this, 0, 33);
		Shape3d.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape3d.setRotationPoint(0F, 18F, 0F);
		Shape3d.setTextureSize(128, 128);
		Shape3d.mirror = true;
		this.setRotation(Shape3d, 0F, 0.7853982F, 0F);
		Shape3e = new LODModelPart(this, 0, 33);
		Shape3e.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape3e.setRotationPoint(0F, 18F, 0F);
		Shape3e.setTextureSize(128, 128);
		Shape3e.mirror = true;
		this.setRotation(Shape3e, 0F, 1.047198F, 0F);
		Shape4e = new LODModelPart(this, 0, 45);
		Shape4e.addBox(-3F, 0F, -3F, 6, 1, 6);
		Shape4e.setRotationPoint(0F, 17F, 0F);
		Shape4e.setTextureSize(128, 128);
		Shape4e.mirror = true;
		this.setRotation(Shape4e, 0F, 0F, 0F);
		Shape4a = new LODModelPart(this, 0, 45);
		Shape4a.addBox(-3F, 0F, -3F, 6, 1, 6);
		Shape4a.setRotationPoint(0F, 17F, 0F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0.2617994F, 0F);
		Shape4b = new LODModelPart(this, 0, 45);
		Shape4b.addBox(-3F, 0F, -3F, 6, 1, 6);
		Shape4b.setRotationPoint(0F, 17F, 0F);
		Shape4b.setTextureSize(128, 128);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0F, 0.5235988F, 0F);
		Shape4c = new LODModelPart(this, 0, 45);
		Shape4c.addBox(-3F, 0F, -3F, 6, 1, 6);
		Shape4c.setRotationPoint(0F, 17F, 0F);
		Shape4c.setTextureSize(128, 128);
		Shape4c.mirror = true;
		this.setRotation(Shape4c, 0F, 0.7853982F, 0F);
		Shape4d = new LODModelPart(this, 0, 45);
		Shape4d.addBox(-3F, 0F, -3F, 6, 1, 6);
		Shape4d.setRotationPoint(0F, 17F, 0F);
		Shape4d.setTextureSize(128, 128);
		Shape4d.mirror = true;
		this.setRotation(Shape4d, 0F, 1.047198F, 0F);
		Shape5a = new LODModelPart(this, 0, 54);
		Shape5a.addBox(-1.5F, 0F, -1.5F, 3, 1, 3);
		Shape5a.setRotationPoint(0F, 16F, 0F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 0F, 0F, 0F);
		Shape5b = new LODModelPart(this, 0, 54);
		Shape5b.addBox(-1.5F, 0F, -1.5F, 3, 1, 3);
		Shape5b.setRotationPoint(0F, 16F, 0F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0.2617994F, 0F);
		Shape5c = new LODModelPart(this, 0, 54);
		Shape5c.addBox(-1.5F, 0F, -1.5F, 3, 1, 3);
		Shape5c.setRotationPoint(0F, 16F, 0F);
		Shape5c.setTextureSize(128, 128);
		Shape5c.mirror = true;
		this.setRotation(Shape5c, 0F, 0.5235988F, 0F);
		Shape5d = new LODModelPart(this, 0, 54);
		Shape5d.addBox(-1.5F, 0F, -1.5F, 3, 1, 3);
		Shape5d.setRotationPoint(0F, 16F, 0F);
		Shape5d.setTextureSize(128, 128);
		Shape5d.mirror = true;
		this.setRotation(Shape5d, 0F, 0.7853982F, 0F);
		Shape5e = new LODModelPart(this, 0, 54);
		Shape5e.addBox(-1.5F, 0F, -1.5F, 3, 1, 3);
		Shape5e.setRotationPoint(0F, 16F, 0F);
		Shape5e.setTextureSize(128, 128);
		Shape5e.mirror = true;
		this.setRotation(Shape5e, 0F, 1.047198F, 0F);
		Shape6 = new LODModelPart(this, 65, 0);
		Shape6.addBox(1F, -7F, -1F, 2, 4, 2);
		Shape6.setRotationPoint(0F, 20F, 0F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, -2.094395F*0, 0.7853982F);
		Shape6a = new LODModelPart(this, 65, 0);
		Shape6a.addBox(1F, -8F, -1F, 2, 4, 2);
		Shape6a.setRotationPoint(0F, 20F, 0F);
		Shape6a.setTextureSize(128, 128);
		Shape6a.mirror = true;
		this.setRotation(Shape6a, 0F, -1.047198F*0, 1.22173F);
		Shape6c = new LODModelPart(this, 65, 7);
		Shape6c.addBox(0.5F, -6F, -0.5F, 1, 3, 1);
		Shape6c.setRotationPoint(0F, 20F, 0F);
		Shape6c.setTextureSize(128, 128);
		Shape6c.mirror = true;
		this.setRotation(Shape6c, 0F, -0.7853982F*0, 0.3926991F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);

		GL11.glRotatef(phi, 0, 1, 0);
		Shape3.render(te, f5);
		Shape4.render(te, f5);
		Shape5.render(te, f5);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape2b.render(te, f5);
		Shape2c.render(te, f5);
		Shape2d.render(te, f5);
		Shape2e.render(te, f5);
		Shape3a.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c.render(te, f5);
		Shape3d.render(te, f5);
		Shape3e.render(te, f5);
		Shape4e.render(te, f5);
		Shape4a.render(te, f5);
		Shape4b.render(te, f5);
		Shape4c.render(te, f5);
		Shape4d.render(te, f5);
		Shape5a.render(te, f5);
		Shape5b.render(te, f5);
		Shape5c.render(te, f5);
		Shape5d.render(te, f5);
		Shape5e.render(te, f5);

		for (int i = 0; i < 3; i++) {
			GL11.glRotatef(120*i, 0, 1, 0);
			Shape6.render(te, f5);
			GL11.glRotatef(60, 0, 1, 0);
			Shape6a.render(te, f5);
			GL11.glRotatef(-60, 0, 1, 0);
			GL11.glRotatef(-120*i, 0, 1, 0);
		}

		for (int i = 0; i < 4; i++) {
			GL11.glRotatef(45+90*i, 0, 1, 0);
			Shape6c.render(te, f5);
			GL11.glRotatef(-45-90*i, 0, 1, 0);
		}

		GL11.glRotatef(-phi, 0, 1, 0);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}