/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 19/02/2014 7:29:01 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models.Animated;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

import org.lwjgl.opengl.GL11;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelGrindstone extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape2g;
	LODModelPart Shape2h;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape3a;
	LODModelPart Shape5;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape5a;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape7a;

	public ModelGrindstone()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape1.setRotationPoint(-8F, 23F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 0, 19);
		Shape2.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2.setRotationPoint(0F, 15F, 0F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 1.396263F);
		Shape2a = new LODModelPart(this, 0, 19);
		Shape2a.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2a.setRotationPoint(0F, 15F, 0F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape2b = new LODModelPart(this, 0, 19);
		Shape2b.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2b.setRotationPoint(0F, 15F, 0F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0.1745329F);
		Shape2c = new LODModelPart(this, 0, 19);
		Shape2c.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2c.setRotationPoint(0F, 15F, 0F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0F, 0.3490659F);
		Shape2d = new LODModelPart(this, 0, 19);
		Shape2d.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2d.setRotationPoint(0F, 15F, 0F);
		Shape2d.setTextureSize(128, 128);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 0F, 0.5235988F);
		Shape2e = new LODModelPart(this, 0, 19);
		Shape2e.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2e.setRotationPoint(0F, 15F, 0F);
		Shape2e.setTextureSize(128, 128);
		Shape2e.mirror = true;
		this.setRotation(Shape2e, 0F, 0F, 0.6981317F);
		Shape2f = new LODModelPart(this, 0, 19);
		Shape2f.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2f.setRotationPoint(0F, 15F, 0F);
		Shape2f.setTextureSize(128, 128);
		Shape2f.mirror = true;
		this.setRotation(Shape2f, 0F, 0F, 0.8726646F);
		Shape2g = new LODModelPart(this, 0, 19);
		Shape2g.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2g.setRotationPoint(0F, 15F, 0F);
		Shape2g.setTextureSize(128, 128);
		Shape2g.mirror = true;
		this.setRotation(Shape2g, 0F, 0F, 1.047198F);
		Shape2h = new LODModelPart(this, 0, 19);
		Shape2h.addBox(-4F, -4F, -2F, 8, 8, 4);
		Shape2h.setRotationPoint(0F, 15F, 0F);
		Shape2h.setTextureSize(128, 128);
		Shape2h.mirror = true;
		this.setRotation(Shape2h, 0F, 0F, 1.22173F);
		Shape3 = new LODModelPart(this, 66, 0);
		Shape3.addBox(0F, 0F, 0F, 2, 10, 2);
		Shape3.setRotationPoint(6F, 13F, 6F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 0, 33);
		Shape4.addBox(-1F, -1F, 0F, 2, 2, 17);
		Shape4.setRotationPoint(0F, 15F, -8.5F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0.7853982F);
		Shape4a = new LODModelPart(this, 0, 33);
		Shape4a.addBox(-1F, -1F, 0F, 2, 2, 17);
		Shape4a.setRotationPoint(0F, 15F, -8.5F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape3a = new LODModelPart(this, 66, 0);
		Shape3a.addBox(0F, 0F, 0F, 2, 10, 2);
		Shape3a.setRotationPoint(-8F, 13F, 6F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 0, 54);
		Shape5.addBox(0F, 0F, 0F, 12, 4, 1);
		Shape5.setRotationPoint(-6F, 13F, 6.5F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape3b = new LODModelPart(this, 66, 0);
		Shape3b.addBox(0F, 0F, 0F, 2, 10, 2);
		Shape3b.setRotationPoint(6F, 13F, -8F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0F, 0F);
		Shape3c = new LODModelPart(this, 66, 0);
		Shape3c.addBox(0F, 0F, 0F, 2, 10, 2);
		Shape3c.setRotationPoint(-8F, 13F, -8F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0F, 0F);
		Shape5a = new LODModelPart(this, 0, 54);
		Shape5a.addBox(0F, 0F, 0F, 12, 4, 1);
		Shape5a.setRotationPoint(-6F, 13F, -7.5F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 0, 61);
		Shape6.addBox(0F, 0F, 0F, 1, 1, 4);
		Shape6.setRotationPoint(-8F, 22F, -2F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape7 = new LODModelPart(this, 0, 80);
		Shape7.addBox(-3F, -3F, 0F, 6, 6, 5);
		Shape7.setRotationPoint(0F, 15F, -2.5F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, 0F, 0.7853982F);
		Shape7a = new LODModelPart(this, 0, 67);
		Shape7a.addBox(-3F, -3F, 0F, 6, 6, 6);
		Shape7a.setRotationPoint(0F, 15F, -3F);
		Shape7a.setTextureSize(128, 128);
		Shape7a.mirror = true;
		this.setRotation(Shape7a, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);

		double d = 0.9375;
		GL11.glTranslated(0, d, 0);
		GL11.glRotatef(phi, 0, 0, 1);
		GL11.glTranslated(0, -d, 0);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape2b.render(te, f5);
		Shape2c.render(te, f5);
		Shape2d.render(te, f5);
		Shape2e.render(te, f5);
		Shape2f.render(te, f5);
		Shape2g.render(te, f5);
		Shape2h.render(te, f5);
		Shape4.render(te, f5);
		Shape4a.render(te, f5);
		GL11.glTranslated(0, d, 0);
		GL11.glRotatef(-phi, 0, 0, 1);
		GL11.glTranslated(0, -d, 0);

		Shape3.render(te, f5);
		Shape3a.render(te, f5);
		Shape5.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c.render(te, f5);
		Shape5a.render(te, f5);
		Shape6.render(te, f5);
		Shape7.render(te, f5);
		Shape7a.render(te, f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
