/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 20/02/2013 1:48:42 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models.Animated;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

import org.lwjgl.opengl.GL11;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;


public class ModelCompactor extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape3;
	LODModelPart Shape20;
	LODModelPart Shape21;
	LODModelPart Shape22;
	LODModelPart Shape23;
	LODModelPart Shape24;
	LODModelPart Shape25;
	LODModelPart Shape4;

	public ModelCompactor()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape1.setRotationPoint(-8F, 23F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 100, 12);
		Shape2.addBox(0F, 0F, 0F, 5, 3, 1);
		Shape2.setRotationPoint(-2.5F, 14.5F, -4F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 0, 88);
		Shape5.addBox(0F, 0F, 0F, 4, 1, 2);
		Shape5.setRotationPoint(-2F, 18F, -1F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 100, 16);
		Shape6.addBox(0F, 0F, 0F, 4, 2, 1);
		Shape6.setRotationPoint(-2F, 15F, -3F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape7 = new LODModelPart(this, 0, 84);
		Shape7.addBox(0F, 0F, 0F, 5, 1, 3);
		Shape7.setRotationPoint(-2.5F, 19F, -1.5F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, 0F, 0F);
		Shape8 = new LODModelPart(this, 100, 0);
		Shape8.addBox(0F, 0F, 0F, 8, 6, 1);
		Shape8.setRotationPoint(-4F, 13F, -6F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		this.setRotation(Shape8, 0F, 0F, 0F);
		Shape9 = new LODModelPart(this, 100, 16);
		Shape9.addBox(0F, 0F, 0F, 5, 2, 1);
		Shape9.setRotationPoint(-3F, 15F, 2F);
		Shape9.setTextureSize(128, 128);
		Shape9.mirror = true;
		this.setRotation(Shape9, 0F, 0F, 0F);
		Shape10 = new LODModelPart(this, 100, 7);
		Shape10.addBox(0F, 0F, 0F, 6, 4, 1);
		Shape10.setRotationPoint(-3F, 14F, -5F);
		Shape10.setTextureSize(128, 128);
		Shape10.mirror = true;
		this.setRotation(Shape10, 0F, 0F, 0F);
		Shape11 = new LODModelPart(this, 100, 12);
		Shape11.addBox(0F, 0F, 0F, 6, 3, 1);
		Shape11.setRotationPoint(-3.5F, 14.5F, 3F);
		Shape11.setTextureSize(128, 128);
		Shape11.mirror = true;
		this.setRotation(Shape11, 0F, 0F, 0F);
		Shape12 = new LODModelPart(this, 100, 7);
		Shape12.addBox(0F, 0F, 0F, 6, 4, 1);
		Shape12.setRotationPoint(-3F, 14F, 4F);
		Shape12.setTextureSize(128, 128);
		Shape12.mirror = true;
		this.setRotation(Shape12, 0F, 0F, 0F);
		Shape13 = new LODModelPart(this, 100, 0);
		Shape13.addBox(0F, 0F, 0F, 8, 6, 1);
		Shape13.setRotationPoint(-4F, 13F, 5F);
		Shape13.setTextureSize(128, 128);
		Shape13.mirror = true;
		this.setRotation(Shape13, 0F, 0F, 0F);
		Shape14 = new LODModelPart(this, 0, 72);
		Shape14.addBox(0F, 0F, 0F, 8, 1, 6);
		Shape14.setRotationPoint(-4F, 21F, -3F);
		Shape14.setTextureSize(128, 128);
		Shape14.mirror = true;
		this.setRotation(Shape14, 0F, 0F, 0F);
		Shape15 = new LODModelPart(this, 0, 88);
		Shape15.addBox(0F, 0F, 0F, 4, 1, 2);
		Shape15.setRotationPoint(-2F, 13F, -1F);
		Shape15.setTextureSize(128, 128);
		Shape15.mirror = true;
		this.setRotation(Shape15, 0F, 0F, 0F);
		Shape16 = new LODModelPart(this, 0, 79);
		Shape16.addBox(0F, 0F, 0F, 6, 1, 4);
		Shape16.setRotationPoint(-3F, 20F, -2F);
		Shape16.setTextureSize(128, 128);
		Shape16.mirror = true;
		this.setRotation(Shape16, 0F, 0F, 0F);
		Shape17 = new LODModelPart(this, 0, 84);
		Shape17.addBox(0F, 0F, 0F, 5, 1, 3);
		Shape17.setRotationPoint(-2.5F, 12F, -1.5F);
		Shape17.setTextureSize(128, 128);
		Shape17.mirror = true;
		this.setRotation(Shape17, 0F, 0F, 0F);
		Shape18 = new LODModelPart(this, 0, 79);
		Shape18.addBox(0F, 0F, 0F, 6, 1, 4);
		Shape18.setRotationPoint(-3F, 11F, -2F);
		Shape18.setTextureSize(128, 128);
		Shape18.mirror = true;
		this.setRotation(Shape18, 0F, 0F, 0F);
		Shape19 = new LODModelPart(this, 0, 72);
		Shape19.addBox(0F, 0F, 0F, 8, 1, 6);
		Shape19.setRotationPoint(-4F, 10F, -3F);
		Shape19.setTextureSize(128, 128);
		Shape19.mirror = true;
		this.setRotation(Shape19, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 0, 46);
		Shape3.addBox(0F, 0F, 0F, 10, 12, 1);
		Shape3.setRotationPoint(-5F, 11F, 7F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape20 = new LODModelPart(this, 0, 18);
		Shape20.addBox(0F, 0F, 0F, 12, 1, 14);
		Shape20.setRotationPoint(-6F, 22F, -7F);
		Shape20.setTextureSize(128, 128);
		Shape20.mirror = true;
		this.setRotation(Shape20, 0F, 0F, 0F);
		Shape21 = new LODModelPart(this, 0, 59);
		Shape21.addBox(0F, 0F, 0F, 11, 1, 12);
		Shape21.setRotationPoint(-5.5F, 8F, -6F);
		Shape21.setTextureSize(128, 128);
		Shape21.mirror = true;
		this.setRotation(Shape21, 0F, 0F, 0F);
		Shape22 = new LODModelPart(this, 0, 46);
		Shape22.addBox(0F, 0F, 0F, 10, 12, 1);
		Shape22.setRotationPoint(-5F, 11F, -8F);
		Shape22.setTextureSize(128, 128);
		Shape22.mirror = true;
		this.setRotation(Shape22, 0F, 0F, 0F);
		Shape23 = new LODModelPart(this, 0, 33);
		Shape23.addBox(0F, 0F, 0F, 12, 12, 1);
		Shape23.setRotationPoint(-6F, 10F, -7F);
		Shape23.setTextureSize(128, 128);
		Shape23.mirror = true;
		this.setRotation(Shape23, 0F, 0F, 0F);
		Shape24 = new LODModelPart(this, 0, 33);
		Shape24.addBox(0F, 0F, 0F, 12, 12, 1);
		Shape24.setRotationPoint(-6F, 10F, 6F);
		Shape24.setTextureSize(128, 128);
		Shape24.mirror = true;
		this.setRotation(Shape24, 0F, 0F, 0F);
		Shape25 = new LODModelPart(this, 0, 18);
		Shape25.addBox(0F, 0F, 0F, 12, 1, 14);
		Shape25.setRotationPoint(-6F, 9F, -7F);
		Shape25.setTextureSize(128, 128);
		Shape25.mirror = true;
		this.setRotation(Shape25, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 64, 0);
		Shape4.addBox(0F, 0F, 0F, 2, 15, 16);
		Shape4.setRotationPoint(-8F, 8F, -8F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);
		Shape3.render(te, f5);
		Shape4.render(te, f5);
		double d = phi/3D-0.36;
		GL11.glTranslated(0, 0, d);
		GL11.glScalef(1, 1, phi);
		Shape2.render(te, f5);
		Shape6.render(te, f5);
		Shape8.render(te, f5);
		Shape10.render(te, f5);
		GL11.glScalef(1, 1, 1F/phi);
		GL11.glTranslated(0, 0, -d);

		GL11.glTranslated(0, 0, -d);
		GL11.glScalef(1, 1, phi);
		Shape9.render(te, f5);
		Shape11.render(te, f5);
		Shape12.render(te, f5);
		Shape13.render(te, f5);
		GL11.glScalef(1, 1, 1F/phi);
		GL11.glTranslated(0, 0, d);

		d = 1.38;

		GL11.glTranslated(0, d, 0);
		GL11.glScalef(1, phi, 1);
		GL11.glTranslated(0, -d, 0);
		Shape5.render(te, f5);
		Shape7.render(te, f5);
		Shape14.render(te, f5);
		Shape16.render(te, f5);
		GL11.glTranslated(0, d, 0);
		GL11.glScalef(1, 1F/phi, 1);
		GL11.glTranslated(0, -d, 0);

		d = 0.62;
		GL11.glTranslated(0, d, 0);
		GL11.glScalef(1, phi, 1);
		GL11.glTranslated(0, -d, 0);
		Shape15.render(te, f5);
		Shape17.render(te, f5);
		Shape18.render(te, f5);
		Shape19.render(te, f5);
		GL11.glTranslated(0, d, 0);
		GL11.glScalef(1, 1F/phi, 1);
		GL11.glTranslated(0, -d, 0);

		Shape20.render(te, f5);
		Shape21.render(te, f5);
		Shape22.render(te, f5);
		Shape23.render(te, f5);
		Shape24.render(te, f5);
		Shape25.render(te, f5);
	}

}
