/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 12/07/2014 5:48:37 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models.Animated;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

import org.lwjgl.opengl.GL11;

public class ModelCentrifuge extends RotaryModelBase
{
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape2g;
	LODModelPart Shape2h;
	LODModelPart Shape2i;
	LODModelPart Shape2j;
	LODModelPart Shape2k;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape3a;
	LODModelPart Shape3c;
	LODModelPart Shape3b;
	LODModelPart Shape3c2;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape3f;
	LODModelPart Shape3g;
	LODModelPart Shape3h;
	LODModelPart Shape3i;
	LODModelPart Shape3j;
	LODModelPart Shape4c;
	LODModelPart Shape4d;
	LODModelPart Shape4e;

	public ModelCentrifuge()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape1.setRotationPoint(-8F, 23F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 0, 19);
		Shape2.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2.setRotationPoint(0F, 18F, 0F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, -2.617994F, 0F);
		Shape2a = new LODModelPart(this, 0, 19);
		Shape2a.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2a.setRotationPoint(0F, 18F, 0F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape2b = new LODModelPart(this, 0, 19);
		Shape2b.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2b.setRotationPoint(0F, 18F, 0F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0.5235988F, 0F);
		Shape2c = new LODModelPart(this, 0, 19);
		Shape2c.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2c.setRotationPoint(0F, 18F, 0F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 1.047198F, 0F);
		Shape2d = new LODModelPart(this, 0, 19);
		Shape2d.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2d.setRotationPoint(0F, 18F, 0F);
		Shape2d.setTextureSize(128, 128);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 1.570796F, 0F);
		Shape2e = new LODModelPart(this, 0, 19);
		Shape2e.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2e.setRotationPoint(0F, 18F, 0F);
		Shape2e.setTextureSize(128, 128);
		Shape2e.mirror = true;
		this.setRotation(Shape2e, 0F, 2.094395F, 0F);
		Shape2f = new LODModelPart(this, 0, 19);
		Shape2f.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2f.setRotationPoint(0F, 18F, 0F);
		Shape2f.setTextureSize(128, 128);
		Shape2f.mirror = true;
		this.setRotation(Shape2f, 0F, 2.617994F, 0F);
		Shape2g = new LODModelPart(this, 0, 19);
		Shape2g.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2g.setRotationPoint(0F, 18F, 0F);
		Shape2g.setTextureSize(128, 128);
		Shape2g.mirror = true;
		this.setRotation(Shape2g, 0F, 3.141593F, 0F);
		Shape2h = new LODModelPart(this, 0, 19);
		Shape2h.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2h.setRotationPoint(0F, 18F, 0F);
		Shape2h.setTextureSize(128, 128);
		Shape2h.mirror = true;
		this.setRotation(Shape2h, 0F, -0.5235988F, 0F);
		Shape2i = new LODModelPart(this, 0, 19);
		Shape2i.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2i.setRotationPoint(0F, 18F, 0F);
		Shape2i.setTextureSize(128, 128);
		Shape2i.mirror = true;
		this.setRotation(Shape2i, 0F, -1.047198F, 0F);
		Shape2j = new LODModelPart(this, 0, 19);
		Shape2j.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2j.setRotationPoint(0F, 18F, 0F);
		Shape2j.setTextureSize(128, 128);
		Shape2j.mirror = true;
		this.setRotation(Shape2j, 0F, -1.570796F, 0F);
		Shape2k = new LODModelPart(this, 0, 19);
		Shape2k.addBox(-2F, 0F, 6.5F, 4, 5, 1);
		Shape2k.setRotationPoint(0F, 18F, 0F);
		Shape2k.setTextureSize(128, 128);
		Shape2k.mirror = true;
		this.setRotation(Shape2k, 0F, -2.094395F, 0F);
		Shape3 = new LODModelPart(this, 65, 0);
		Shape3.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3.setRotationPoint(0F, 23F, 0F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0.6108652F, -2.617994F, 0F);
		Shape4 = new LODModelPart(this, 0, 44);
		Shape4.addBox(-7F, 0F, -3F, 14, 1, 6);
		Shape4.setRotationPoint(0F, 22F, 0F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 2.094395F, 0F);
		Shape4a = new LODModelPart(this, 0, 54);
		Shape4a.addBox(-7F, 0F, -3F, 14, 1, 6);
		Shape4a.setRotationPoint(0F, 18F, 0F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 2.094395F, 0F);
		Shape4b = new LODModelPart(this, 0, 35);
		Shape4b.addBox(-7F, 0F, -3F, 14, 1, 6);
		Shape4b.setRotationPoint(0F, 22F, 0F);
		Shape4b.setTextureSize(128, 128);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0F, 1.047198F, 0F);
		Shape3a = new LODModelPart(this, 65, 0);
		Shape3a.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3a.setRotationPoint(0F, 23F, 0F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0.6108652F, 0F, 0F);
		Shape3c = new LODModelPart(this, 65, 0);
		Shape3c.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3c.setRotationPoint(0F, 23F, 0F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0.6108652F, 0.5235988F, 0F);
		Shape3b = new LODModelPart(this, 65, 0);
		Shape3b.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3b.setRotationPoint(0F, 23F, 0F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0.6108652F, 1.047198F, 0F);
		Shape3c2 = new LODModelPart(this, 65, 0);
		Shape3c2.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3c2.setRotationPoint(0F, 23F, 0F);
		Shape3c2.setTextureSize(128, 128);
		Shape3c2.mirror = true;
		this.setRotation(Shape3c2, 0.6108652F, 1.570796F, 0F);
		Shape3d = new LODModelPart(this, 65, 0);
		Shape3d.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3d.setRotationPoint(0F, 23F, 0F);
		Shape3d.setTextureSize(128, 128);
		Shape3d.mirror = true;
		this.setRotation(Shape3d, 0.6108652F, 2.094395F, 0F);
		Shape3e = new LODModelPart(this, 65, 0);
		Shape3e.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3e.setRotationPoint(0F, 23F, 0F);
		Shape3e.setTextureSize(128, 128);
		Shape3e.mirror = true;
		this.setRotation(Shape3e, 0.6108652F, 2.617994F, 0F);
		Shape3f = new LODModelPart(this, 65, 0);
		Shape3f.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3f.setRotationPoint(0F, 23F, 0F);
		Shape3f.setTextureSize(128, 128);
		Shape3f.mirror = true;
		this.setRotation(Shape3f, 0.6108652F, 3.141593F, 0F);
		Shape3g = new LODModelPart(this, 65, 0);
		Shape3g.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3g.setRotationPoint(0F, 23F, 0F);
		Shape3g.setTextureSize(128, 128);
		Shape3g.mirror = true;
		this.setRotation(Shape3g, 0.6108652F, -0.5235988F, 0F);
		Shape3h = new LODModelPart(this, 65, 0);
		Shape3h.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3h.setRotationPoint(0F, 23F, 0F);
		Shape3h.setTextureSize(128, 128);
		Shape3h.mirror = true;
		this.setRotation(Shape3h, 0.6108652F, -1.047198F, 0F);
		Shape3i = new LODModelPart(this, 65, 0);
		Shape3i.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3i.setRotationPoint(0F, 23F, 0F);
		Shape3i.setTextureSize(128, 128);
		Shape3i.mirror = true;
		this.setRotation(Shape3i, 0.6108652F, -1.570796F, 0F);
		Shape3j = new LODModelPart(this, 65, 0);
		Shape3j.addBox(-2F, 0F, 0F, 4, 1, 8);
		Shape3j.setRotationPoint(0F, 23F, 0F);
		Shape3j.setTextureSize(128, 128);
		Shape3j.mirror = true;
		this.setRotation(Shape3j, 0.6108652F, -2.094395F, 0F);
		Shape4c = new LODModelPart(this, 0, 26);
		Shape4c.addBox(-7F, 0F, -3F, 14, 1, 6);
		Shape4c.setRotationPoint(0F, 22F, 0F);
		Shape4c.setTextureSize(128, 128);
		Shape4c.mirror = true;
		this.setRotation(Shape4c, 0F, 0F, 0F);
		Shape4d = new LODModelPart(this, 0, 54);
		Shape4d.addBox(-7F, 0F, -3F, 14, 1, 6);
		Shape4d.setRotationPoint(0F, 18F, 0F);
		Shape4d.setTextureSize(128, 128);
		Shape4d.mirror = true;
		this.setRotation(Shape4d, 0F, 0F, 0F);
		Shape4e = new LODModelPart(this, 0, 54);
		Shape4e.addBox(-7F, 0F, -3F, 14, 1, 6);
		Shape4e.setRotationPoint(0F, 18F, 0F);
		Shape4e.setTextureSize(128, 128);
		Shape4e.mirror = true;
		this.setRotation(Shape4e, 0F, 1.047198F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);

		GL11.glRotatef(phi, 0, 1, 0);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape2b.render(te, f5);
		Shape2c.render(te, f5);
		Shape2d.render(te, f5);
		Shape2e.render(te, f5);
		Shape2f.render(te, f5);
		Shape2g.render(te, f5);
		Shape2h.render(te, f5);
		Shape2i.render(te, f5);
		Shape2j.render(te, f5);
		Shape2k.render(te, f5);
		Shape3.render(te, f5);
		Shape4.render(te, f5);
		Shape4a.render(te, f5);
		Shape4b.render(te, f5);
		Shape3a.render(te, f5);
		Shape3c.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c2.render(te, f5);
		Shape3d.render(te, f5);
		Shape3e.render(te, f5);
		Shape3f.render(te, f5);
		Shape3g.render(te, f5);
		Shape3h.render(te, f5);
		Shape3i.render(te, f5);
		Shape3j.render(te, f5);
		Shape4c.render(te, f5);
		Shape4d.render(te, f5);
		Shape4e.render(te, f5);
		GL11.glRotatef(-phi, 0, 1, 0);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}