/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 30/10/2013 9:28:26 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.ModInterface;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

public class ModelGenerator extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape1a;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape4a;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6b;
	LODModelPart Shape6c;
	LODModelPart Shape6d;
	LODModelPart Shape6e;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape7b;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape9a;
	LODModelPart Shape9b;
	LODModelPart Shape9c;

	public ModelGenerator()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 42);
		Shape1.addBox(-3F, -3F, 0F, 6, 6, 9);
		Shape1.setRotationPoint(0F, 17F, -7.5F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 1.178097F);
		Shape2 = new LODModelPart(this, 0, 22);
		Shape2.addBox(-4F, -4F, 0F, 8, 8, 6);
		Shape2.setRotationPoint(0F, 17F, 2F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 1.178097F);
		Shape1a = new LODModelPart(this, 0, 42);
		Shape1a.addBox(-3F, -3F, 0F, 6, 6, 9);
		Shape1a.setRotationPoint(0F, 17F, -7.5F);
		Shape1a.setTextureSize(128, 128);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, 0F, 0F, 0F);
		Shape2a = new LODModelPart(this, 0, 22);
		Shape2a.addBox(-4F, -4F, 0F, 8, 8, 6);
		Shape2a.setRotationPoint(0F, 17F, 2F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 0, 0);
		Shape3.addBox(-2.5F, -2.5F, 0F, 5, 5, 1);
		Shape3.setRotationPoint(0F, 17F, 1F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0.7853982F);
		Shape3a = new LODModelPart(this, 0, 0);
		Shape3a.addBox(-2.5F, -2.5F, 0F, 5, 5, 1);
		Shape3a.setRotationPoint(0F, 17F, 1F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 1.178097F);
		Shape2b = new LODModelPart(this, 0, 22);
		Shape2b.addBox(-4F, -4F, 0F, 8, 8, 6);
		Shape2b.setRotationPoint(0F, 17F, 2F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0.7853982F);
		Shape2c = new LODModelPart(this, 0, 22);
		Shape2c.addBox(-4F, -4F, 0F, 8, 8, 6);
		Shape2c.setRotationPoint(0F, 17F, 2F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0F, 0.3926991F);
		Shape1b = new LODModelPart(this, 0, 42);
		Shape1b.addBox(-3F, -3F, 0F, 6, 6, 9);
		Shape1b.setRotationPoint(0F, 17F, -7.5F);
		Shape1b.setTextureSize(128, 128);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0F, 0F, 0.7853982F);
		Shape1c = new LODModelPart(this, 0, 42);
		Shape1c.addBox(-3F, -3F, 0F, 6, 6, 9);
		Shape1c.setRotationPoint(0F, 17F, -7.5F);
		Shape1c.setTextureSize(128, 128);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, 0F, 0F, 0.3926991F);
		Shape3b = new LODModelPart(this, 0, 0);
		Shape3b.addBox(-2.5F, -2.5F, 0F, 5, 5, 1);
		Shape3b.setRotationPoint(0F, 17F, 1F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0F, 0F);
		Shape3c = new LODModelPart(this, 0, 0);
		Shape3c.addBox(-2.5F, -2.5F, 0F, 5, 5, 1);
		Shape3c.setRotationPoint(0F, 17F, 1F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0F, 0.3926991F);
		Shape4 = new LODModelPart(this, 0, 78);
		Shape4.addBox(-2F, 0F, 0F, 4, 1, 9);
		Shape4.setRotationPoint(0F, 12F, -7.5F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 0, 12);
		Shape5.addBox(-4F, 0F, 0F, 8, 1, 6);
		Shape5.setRotationPoint(0F, 8F, 1.5F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape4a = new LODModelPart(this, 0, 117);
		Shape4a.addBox(-3F, 0F, 0F, 6, 1, 9);
		Shape4a.setRotationPoint(0F, 13F, -7.5F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape5a = new LODModelPart(this, 0, 58);
		Shape5a.addBox(-5F, 0F, 0F, 10, 4, 7);
		Shape5a.setRotationPoint(0F, 8.5F, 0.9F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 0F, 0F, 0F);
		Shape5b = new LODModelPart(this, 0, 70);
		Shape5b.addBox(-4F, 0F, 0F, 8, 1, 6);
		Shape5b.setRotationPoint(0F, 12F, 1.8F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 0, 89);
		Shape6.addBox(0F, 0F, 0F, 1, 1, 8);
		Shape6.setRotationPoint(-1.5F, 9F, -5.5F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape6a = new LODModelPart(this, 15, 99);
		Shape6a.addBox(0F, 0F, 0F, 1, 2, 1);
		Shape6a.setRotationPoint(-1.5F, 9F, -6.5F);
		Shape6a.setTextureSize(128, 128);
		Shape6a.mirror = true;
		this.setRotation(Shape6a, 0F, 0F, 0F);
		Shape6b = new LODModelPart(this, 15, 99);
		Shape6b.addBox(0F, 0F, 0F, 1, 2, 1);
		Shape6b.setRotationPoint(0.5F, 9F, -6.5F);
		Shape6b.setTextureSize(128, 128);
		Shape6b.mirror = true;
		this.setRotation(Shape6b, 0F, 0F, 0F);
		Shape6c = new LODModelPart(this, 0, 99);
		Shape6c.addBox(0F, 0F, 0F, 1, 1, 6);
		Shape6c.setRotationPoint(-1.5F, 11F, -6.5F);
		Shape6c.setTextureSize(128, 128);
		Shape6c.mirror = true;
		this.setRotation(Shape6c, 0F, 0F, 0F);
		Shape6d = new LODModelPart(this, 0, 89);
		Shape6d.addBox(0F, 0F, 0F, 1, 1, 8);
		Shape6d.setRotationPoint(0.5F, 9F, -5.5F);
		Shape6d.setTextureSize(128, 128);
		Shape6d.mirror = true;
		this.setRotation(Shape6d, 0F, 0F, 0F);
		Shape6e = new LODModelPart(this, 0, 99);
		Shape6e.addBox(0F, 0F, 0F, 1, 1, 6);
		Shape6e.setRotationPoint(0.5F, 11F, -6.5F);
		Shape6e.setTextureSize(128, 128);
		Shape6e.mirror = true;
		this.setRotation(Shape6e, 0F, 0F, 0F);
		Shape7 = new LODModelPart(this, 0, 113);
		Shape7.addBox(0F, 0F, 0F, 1, 2, 1);
		Shape7.setRotationPoint(-1.5F, 13F, -8F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, 0F, 0F);
		Shape7a = new LODModelPart(this, 0, 107);
		Shape7a.addBox(-2F, -2F, 0F, 4, 4, 1);
		Shape7a.setRotationPoint(0F, 17F, -8F);
		Shape7a.setTextureSize(128, 128);
		Shape7a.mirror = true;
		this.setRotation(Shape7a, 0F, 0F, 0F);
		Shape7b = new LODModelPart(this, 0, 113);
		Shape7b.addBox(0F, 0F, 0F, 1, 2, 1);
		Shape7b.setRotationPoint(0.5F, 13F, -8F);
		Shape7b.setTextureSize(128, 128);
		Shape7b.mirror = true;
		this.setRotation(Shape7b, 0F, 0F, 0F);
		Shape8 = new LODModelPart(this, 36, 0);
		Shape8.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape8.setRotationPoint(-8F, 23F, -8F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		this.setRotation(Shape8, 0F, 0F, 0F);
		Shape9 = new LODModelPart(this, 101, 0);
		Shape9.addBox(-1F, 0F, 0F, 2, 8, 3);
		Shape9.setRotationPoint(0F, 17F, -7F);
		Shape9.setTextureSize(128, 128);
		Shape9.mirror = true;
		this.setRotation(Shape9, 0F, 0F, -0.6108652F);
		Shape9a = new LODModelPart(this, 101, 0);
		Shape9a.addBox(-1F, 0F, 0F, 2, 8, 3);
		Shape9a.setRotationPoint(0F, 17F, 4F);
		Shape9a.setTextureSize(128, 128);
		Shape9a.mirror = true;
		this.setRotation(Shape9a, 0F, 0F, -0.6108652F);
		Shape9b = new LODModelPart(this, 101, 0);
		Shape9b.addBox(-1F, 0F, 0F, 2, 8, 3);
		Shape9b.setRotationPoint(0F, 17F, -7F);
		Shape9b.setTextureSize(128, 128);
		Shape9b.mirror = true;
		this.setRotation(Shape9b, 0F, 0F, 0.6108652F);
		Shape9c = new LODModelPart(this, 101, 0);
		Shape9c.addBox(-1F, 0F, 0F, 2, 8, 3);
		Shape9c.setRotationPoint(0F, 17F, 4F);
		Shape9c.setTextureSize(128, 128);
		Shape9c.mirror = true;
		this.setRotation(Shape9c, 0F, 0F, 0.6108652F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);
		Shape2.render(te, f5);
		Shape1a.render(te, f5);
		Shape2a.render(te, f5);
		Shape3.render(te, f5);
		Shape3a.render(te, f5);
		Shape2b.render(te, f5);
		Shape2c.render(te, f5);
		Shape1b.render(te, f5);
		Shape1c.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c.render(te, f5);
		Shape4.render(te, f5);
		Shape5.render(te, f5);
		Shape4a.render(te, f5);
		Shape5a.render(te, f5);
		Shape5b.render(te, f5);
		Shape6.render(te, f5);
		Shape6a.render(te, f5);
		Shape6b.render(te, f5);
		Shape6c.render(te, f5);
		Shape6d.render(te, f5);
		Shape6e.render(te, f5);
		Shape7.render(te, f5);
		Shape7a.render(te, f5);
		Shape7b.render(te, f5);
		Shape8.render(te, f5);
		Shape9.render(te, f5);
		Shape9a.render(te, f5);
		Shape9b.render(te, f5);
		Shape9c.render(te, f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}