/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 13/03/2013 8:20:22 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

public class ModelDetector extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape4;
	LODModelPart Shape3d;
	LODModelPart Shape3e;
	LODModelPart Shape2p;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape3f;
	LODModelPart Shape3g;
	LODModelPart Shape3h;
	LODModelPart Shape3j;
	LODModelPart Shape2g;
	LODModelPart Shape2h;
	LODModelPart Shape3i;
	LODModelPart Shape3k;
	LODModelPart Shape2i;
	LODModelPart Shape2j;
	LODModelPart Shape2k;
	LODModelPart Shape2l;
	LODModelPart Shape3l;
	LODModelPart Shape3m;
	LODModelPart Shape4a;
	LODModelPart Shape4b;
	LODModelPart Shape4c;
	LODModelPart Shape5;
	LODModelPart Shape6;

	public ModelDetector()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 64, 0);
		Shape1.addBox(0F, 0F, 0F, 8, 1, 8);
		Shape1.setRotationPoint(-4F, 22F, -4F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 0, 43);
		Shape2.addBox(0F, 0F, 0F, 3, 2, 1);
		Shape2.setRotationPoint(3F, 19F, 5F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape2a = new LODModelPart(this, 0, 43);
		Shape2a.addBox(0F, 0F, 0F, 3, 2, 1);
		Shape2a.setRotationPoint(3F, 19F, -6F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 0, 38);
		Shape3.addBox(0F, 0F, 0F, 1, 2, 2);
		Shape3.setRotationPoint(-6F, 19F, 3F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape3a = new LODModelPart(this, 0, 38);
		Shape3a.addBox(0F, 0F, 0F, 1, 2, 2);
		Shape3a.setRotationPoint(5F, 19F, 3F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape3b = new LODModelPart(this, 0, 50);
		Shape3b.addBox(0F, 0F, 0F, 1, 1, 2);
		Shape3b.setRotationPoint(-5F, 21F, 2F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0F, 0F);
		Shape3c = new LODModelPart(this, 0, 50);
		Shape3c.addBox(0F, 0F, 0F, 1, 1, 2);
		Shape3c.setRotationPoint(4F, 21F, 2F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0F, 0F);
		Shape2b = new LODModelPart(this, 0, 47);
		Shape2b.addBox(0F, 0F, 0F, 3, 1, 1);
		Shape2b.setRotationPoint(2F, 21F, -5F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0F);
		Shape2c = new LODModelPart(this, 0, 27);
		Shape2c.addBox(0F, 0F, 0F, 6, 2, 1);
		Shape2c.setRotationPoint(-3F, 19F, -7F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 116, 0);
		Shape4.addBox(-0.5F, 0F, -0.5F, 1, 8, 1);
		Shape4.setRotationPoint(0F, 15F, 0F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, -0.2617994F);
		Shape3d = new LODModelPart(this, 0, 38);
		Shape3d.addBox(0F, 0F, 0F, 1, 2, 2);
		Shape3d.setRotationPoint(-6F, 19F, -5F);
		Shape3d.setTextureSize(128, 128);
		Shape3d.mirror = true;
		this.setRotation(Shape3d, 0F, 0F, 0F);
		Shape3e = new LODModelPart(this, 0, 38);
		Shape3e.addBox(0F, 0F, 0F, 1, 2, 2);
		Shape3e.setRotationPoint(5F, 19F, -5F);
		Shape3e.setTextureSize(128, 128);
		Shape3e.mirror = true;
		this.setRotation(Shape3e, 0F, 0F, 0F);
		Shape2p = new LODModelPart(this, 0, 43);
		Shape2p.addBox(0F, 0F, 0F, 3, 2, 1);
		Shape2p.setRotationPoint(-6F, 19F, -6F);
		Shape2p.setTextureSize(128, 128);
		Shape2p.mirror = true;
		this.setRotation(Shape2p, 0F, 0F, 0F);
		Shape2d = new LODModelPart(this, 0, 43);
		Shape2d.addBox(0F, 0F, 0F, 3, 2, 1);
		Shape2d.setRotationPoint(-6F, 19F, 5F);
		Shape2d.setTextureSize(128, 128);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 0F, 0F);
		Shape2e = new LODModelPart(this, 0, 47);
		Shape2e.addBox(0F, 0F, 0F, 3, 1, 1);
		Shape2e.setRotationPoint(-5F, 21F, -5F);
		Shape2e.setTextureSize(128, 128);
		Shape2e.mirror = true;
		this.setRotation(Shape2e, 0F, 0F, 0F);
		Shape2f = new LODModelPart(this, 0, 47);
		Shape2f.addBox(0F, 0F, 0F, 3, 1, 1);
		Shape2f.setRotationPoint(-5F, 21F, 4F);
		Shape2f.setTextureSize(128, 128);
		Shape2f.mirror = true;
		this.setRotation(Shape2f, 0F, 0F, 0F);
		Shape3f = new LODModelPart(this, 0, 50);
		Shape3f.addBox(0F, 0F, 0F, 1, 1, 2);
		Shape3f.setRotationPoint(-5F, 21F, -4F);
		Shape3f.setTextureSize(128, 128);
		Shape3f.mirror = true;
		this.setRotation(Shape3f, 0F, 0F, 0F);
		Shape3g = new LODModelPart(this, 0, 30);
		Shape3g.addBox(0F, 0F, 0F, 1, 2, 6);
		Shape3g.setRotationPoint(-7F, 19F, -3F);
		Shape3g.setTextureSize(128, 128);
		Shape3g.mirror = true;
		this.setRotation(Shape3g, 0F, 0F, 0F);
		Shape3h = new LODModelPart(this, 0, 50);
		Shape3h.addBox(0F, 0F, 0F, 1, 1, 2);
		Shape3h.setRotationPoint(4F, 21F, -4F);
		Shape3h.setTextureSize(128, 128);
		Shape3h.mirror = true;
		this.setRotation(Shape3h, 0F, 0F, 0F);
		Shape3j = new LODModelPart(this, 0, 30);
		Shape3j.addBox(0F, 0F, 0F, 1, 2, 6);
		Shape3j.setRotationPoint(6F, 19F, -3F);
		Shape3j.setTextureSize(128, 128);
		Shape3j.mirror = true;
		this.setRotation(Shape3j, 0F, 0F, 0F);
		Shape2g = new LODModelPart(this, 0, 47);
		Shape2g.addBox(0F, 0F, 0F, 3, 1, 1);
		Shape2g.setRotationPoint(2F, 21F, 4F);
		Shape2g.setTextureSize(128, 128);
		Shape2g.mirror = true;
		this.setRotation(Shape2g, 0F, 0F, 0F);
		Shape2h = new LODModelPart(this, 0, 27);
		Shape2h.addBox(0F, 0F, 0F, 6, 2, 1);
		Shape2h.setRotationPoint(-3F, 19F, 6F);
		Shape2h.setTextureSize(128, 128);
		Shape2h.mirror = true;
		this.setRotation(Shape2h, 0F, 0F, 0F);
		Shape3i = new LODModelPart(this, 96, 0);
		Shape3i.addBox(0F, 0F, 0F, 1, 1, 4);
		Shape3i.setRotationPoint(-5F, 22F, -2F);
		Shape3i.setTextureSize(128, 128);
		Shape3i.mirror = true;
		this.setRotation(Shape3i, 0F, 0F, 0F);
		Shape3k = new LODModelPart(this, 96, 0);
		Shape3k.addBox(0F, 0F, 0F, 1, 1, 4);
		Shape3k.setRotationPoint(4F, 22F, -2F);
		Shape3k.setTextureSize(128, 128);
		Shape3k.mirror = true;
		this.setRotation(Shape3k, 0F, 0F, 0F);
		Shape2i = new LODModelPart(this, 106, 0);
		Shape2i.addBox(0F, 0F, 0F, 4, 1, 1);
		Shape2i.setRotationPoint(-2F, 22F, 4F);
		Shape2i.setTextureSize(128, 128);
		Shape2i.mirror = true;
		this.setRotation(Shape2i, 0F, 0F, 0F);
		Shape2j = new LODModelPart(this, 106, 0);
		Shape2j.addBox(0F, 0F, 0F, 4, 1, 1);
		Shape2j.setRotationPoint(-2F, 22F, -5F);
		Shape2j.setTextureSize(128, 128);
		Shape2j.mirror = true;
		this.setRotation(Shape2j, 0F, 0F, 0F);
		Shape2k = new LODModelPart(this, 0, 18);
		Shape2k.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape2k.setRotationPoint(-3F, 21F, 5F);
		Shape2k.setTextureSize(128, 128);
		Shape2k.mirror = true;
		this.setRotation(Shape2k, 0F, 0F, 0F);
		Shape2l = new LODModelPart(this, 0, 18);
		Shape2l.addBox(0F, 0F, 0F, 6, 1, 1);
		Shape2l.setRotationPoint(-3F, 21F, -6F);
		Shape2l.setTextureSize(128, 128);
		Shape2l.mirror = true;
		this.setRotation(Shape2l, 0F, 0F, 0F);
		Shape3l = new LODModelPart(this, 0, 20);
		Shape3l.addBox(0F, 0F, 0F, 1, 1, 6);
		Shape3l.setRotationPoint(5F, 21F, -3F);
		Shape3l.setTextureSize(128, 128);
		Shape3l.mirror = true;
		this.setRotation(Shape3l, 0F, 0F, 0F);
		Shape3m = new LODModelPart(this, 0, 20);
		Shape3m.addBox(0F, 0F, 0F, 1, 1, 6);
		Shape3m.setRotationPoint(-6F, 21F, -3F);
		Shape3m.setTextureSize(128, 128);
		Shape3m.mirror = true;
		this.setRotation(Shape3m, 0F, 0F, 0F);
		Shape4a = new LODModelPart(this, 116, 0);
		Shape4a.addBox(-0.5F, 0F, -0.5F, 1, 8, 1);
		Shape4a.setRotationPoint(0F, 15F, 0F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0.2617994F);
		Shape4b = new LODModelPart(this, 116, 0);
		Shape4b.addBox(-0.5F, 0F, -0.5F, 1, 8, 1);
		Shape4b.setRotationPoint(0F, 15F, 0F);
		Shape4b.setTextureSize(128, 128);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0.2617994F, 0F, 0F);
		Shape4c = new LODModelPart(this, 116, 0);
		Shape4c.addBox(-0.5F, 0F, -0.5F, 1, 8, 1);
		Shape4c.setRotationPoint(0F, 15F, 0F);
		Shape4c.setTextureSize(128, 128);
		Shape4c.mirror = true;
		this.setRotation(Shape4c, -0.2617994F, 0F, 0F);
		Shape5 = new LODModelPart(this, 107, 2);
		Shape5.addBox(-1F, 0F, -1F, 2, 3, 2);
		Shape5.setRotationPoint(0F, 13F, 0F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 0, 0);
		Shape6.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape6.setRotationPoint(-8F, 23F, -8F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape3.render(te, f5);
		Shape3a.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c.render(te, f5);
		Shape2b.render(te, f5);
		Shape2c.render(te, f5);
		Shape4.render(te, f5);
		Shape3d.render(te, f5);
		Shape3e.render(te, f5);
		Shape2p.render(te, f5);
		Shape2d.render(te, f5);
		Shape2e.render(te, f5);
		Shape2f.render(te, f5);
		Shape3f.render(te, f5);
		Shape3g.render(te, f5);
		Shape3h.render(te, f5);
		Shape3j.render(te, f5);
		Shape2g.render(te, f5);
		Shape2h.render(te, f5);
		Shape3i.render(te, f5);
		Shape3k.render(te, f5);
		Shape2i.render(te, f5);
		Shape2j.render(te, f5);
		Shape2k.render(te, f5);
		Shape2l.render(te, f5);
		Shape3l.render(te, f5);
		Shape3m.render(te, f5);
		Shape4a.render(te, f5);
		Shape4b.render(te, f5);
		Shape4c.render(te, f5);
		Shape5.render(te, f5);
		Shape6.render(te, f5);
	}

}