/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 18/02/2013 11:28:56 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

public class ModelExtractor extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape36;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape35;
	LODModelPart Shape34;
	LODModelPart Shape33;
	LODModelPart Shape5;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape32;
	LODModelPart Shape8;
	LODModelPart Shape39;
	LODModelPart Shape9;
	LODModelPart Shape31;
	LODModelPart Shape30;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape29;
	LODModelPart Shape28;
	LODModelPart Shape27;
	LODModelPart Shape26;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape20;
	LODModelPart Shape21;
	LODModelPart Shape22;
	LODModelPart Shape23;
	LODModelPart Shape24;
	LODModelPart Shape25;
	LODModelPart Shape38;
	LODModelPart Shape37;

	public ModelExtractor()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 5, 16);
		Shape1.setRotationPoint(-8F, 19F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 0, 42);
		Shape2.addBox(0F, 0F, 0F, 4, 2, 12);
		Shape2.setRotationPoint(-7.9F, 11.9F, -6.3F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, -0.3839724F, 0F, 0F);
		Shape36 = new LODModelPart(this, 0, 26);
		Shape36.addBox(0F, 0F, 0F, 2, 4, 12);
		Shape36.setRotationPoint(-6.9F, 11F, -6F);
		Shape36.setTextureSize(128, 128);
		Shape36.mirror = true;
		this.setRotation(Shape36, -0.3839724F, 0F, 0F);
		Shape3 = new LODModelPart(this, 112, 11);
		Shape3.addBox(0F, 0F, 0F, 1, 4, 3);
		Shape3.setRotationPoint(-0.5F, 16F, 3.5F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 76, 18);
		Shape4.addBox(0F, 0F, 0F, 5, 2, 1);
		Shape4.setRotationPoint(-4F, 17.5F, -3F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape35 = new LODModelPart(this, 104, 3);
		Shape35.addBox(0F, 0F, 0F, 1, 2, 3);
		Shape35.setRotationPoint(0F, 17.5F, -2F);
		Shape35.setTextureSize(128, 128);
		Shape35.mirror = true;
		this.setRotation(Shape35, 0F, 0F, 0F);
		Shape34 = new LODModelPart(this, 76, 18);
		Shape34.addBox(0F, 0F, 0F, 5, 2, 1);
		Shape34.setRotationPoint(-4F, 17.5F, 1F);
		Shape34.setTextureSize(128, 128);
		Shape34.mirror = true;
		this.setRotation(Shape34, 0F, 0F, 0F);
		Shape33 = new LODModelPart(this, 104, 3);
		Shape33.addBox(0F, 0F, 0F, 1, 2, 3);
		Shape33.setRotationPoint(-4F, 17.5F, -2F);
		Shape33.setTextureSize(128, 128);
		Shape33.mirror = true;
		this.setRotation(Shape33, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 28, 32);
		Shape5.addBox(0F, 0F, 0F, 3, 1, 3);
		Shape5.setRotationPoint(-3F, 18F, -2F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 117, 0);
		Shape6.addBox(0F, 0F, 0F, 1, 1, 3);
		Shape6.setRotationPoint(-2F, 16F, -5F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, -0.5235988F, 0F, 0F);
		Shape7 = new LODModelPart(this, 85, 15);
		Shape7.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape7.setRotationPoint(-2F, 17.5F, -1F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, 0F, 0F);
		Shape32 = new LODModelPart(this, 85, 15);
		Shape32.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape32.setRotationPoint(-2.2F, 17.5F, -0.5F);
		Shape32.setTextureSize(128, 128);
		Shape32.mirror = true;
		this.setRotation(Shape32, 0F, 0.7853982F, 0F);
		Shape8 = new LODModelPart(this, 0, 70);
		Shape8.addBox(0F, 0F, 0F, 9, 1, 2);
		Shape8.setRotationPoint(-2F, 15.5F, -6.5F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		this.setRotation(Shape8, 0F, 0F, 0F);
		Shape39 = new LODModelPart(this, 81, 6);
		Shape39.addBox(0F, 0F, 0F, 1, 1, 3);
		Shape39.setRotationPoint(-2F, 17.5F, 1F);
		Shape39.setTextureSize(128, 128);
		Shape39.mirror = true;
		this.setRotation(Shape39, 0.5235988F, 0F, 0F);
		Shape9 = new LODModelPart(this, 0, 87);
		Shape9.addBox(0F, 0F, 0F, 1, 1, 7);
		Shape9.setRotationPoint(3F, 18F, -4F);
		Shape9.setTextureSize(128, 128);
		Shape9.mirror = true;
		this.setRotation(Shape9, 0F, 0F, 0F);
		Shape31 = new LODModelPart(this, 0, 95);
		Shape31.addBox(0F, 0F, 0F, 2, 1, 7);
		Shape31.setRotationPoint(4F, 18.8F, -4F);
		Shape31.setTextureSize(128, 128);
		Shape31.mirror = true;
		this.setRotation(Shape31, 0F, 0F, 0F);
		Shape30 = new LODModelPart(this, 0, 87);
		Shape30.addBox(0F, 0F, 0F, 1, 1, 7);
		Shape30.setRotationPoint(6F, 18F, -4F);
		Shape30.setTextureSize(128, 128);
		Shape30.mirror = true;
		this.setRotation(Shape30, 0F, 0F, 0F);
		Shape10 = new LODModelPart(this, 0, 77);
		Shape10.addBox(0F, 0F, 0F, 5, 3, 7);
		Shape10.setRotationPoint(2.5F, 16.5F, 1F);
		Shape10.setTextureSize(128, 128);
		Shape10.mirror = true;
		this.setRotation(Shape10, -0.3839724F, 0F, 0F);
		Shape11 = new LODModelPart(this, 0, 73);
		Shape11.addBox(0F, 0F, 0F, 9, 3, 1);
		Shape11.setRotationPoint(-2F, 16.5F, -7.5F);
		Shape11.setTextureSize(128, 128);
		Shape11.mirror = true;
		this.setRotation(Shape11, 0F, 0F, 0F);
		Shape29 = new LODModelPart(this, 0, 64);
		Shape29.addBox(0F, 0F, 0F, 10, 3, 3);
		Shape29.setRotationPoint(-2.5F, 16F, -7F);
		Shape29.setTextureSize(128, 128);
		Shape29.mirror = true;
		this.setRotation(Shape29, 0F, 0F, 0F);
		Shape28 = new LODModelPart(this, 28, 28);
		Shape28.addBox(0F, 0F, 0F, 6, 3, 1);
		Shape28.setRotationPoint(-7F, 16F, 6.5F);
		Shape28.setTextureSize(128, 128);
		Shape28.mirror = true;
		this.setRotation(Shape28, 0F, 0F, 0F);
		Shape27 = new LODModelPart(this, 50, 22);
		Shape27.addBox(0F, 0F, 0F, 7, 2, 2);
		Shape27.setRotationPoint(-7.5F, 15.1F, 3.6F);
		Shape27.setTextureSize(128, 128);
		Shape27.mirror = true;
		this.setRotation(Shape27, 0.7853982F, 0F, 0F);
		Shape26 = new LODModelPart(this, 0, 56);
		Shape26.addBox(0F, 0F, 0F, 8, 4, 4);
		Shape26.setRotationPoint(-8.1F, 15F, 3F);
		Shape26.setTextureSize(128, 128);
		Shape26.mirror = true;
		this.setRotation(Shape26, 0F, 0F, 0F);
		Shape12 = new LODModelPart(this, 64, 14);
		Shape12.addBox(0F, 0F, 0F, 7, 1, 3);
		Shape12.setRotationPoint(-7F, 10F, -4F);
		Shape12.setTextureSize(128, 128);
		Shape12.mirror = true;
		this.setRotation(Shape12, 0F, 0F, 0F);
		Shape13 = new LODModelPart(this, 64, 0);
		Shape13.addBox(0F, 0F, 0F, 4, 8, 4);
		Shape13.setRotationPoint(-8F, 11F, -8F);
		Shape13.setTextureSize(128, 128);
		Shape13.mirror = true;
		this.setRotation(Shape13, 0F, 0F, 0F);
		Shape14 = new LODModelPart(this, 64, 18);
		Shape14.addBox(0F, 0F, 0F, 3, 1, 3);
		Shape14.setRotationPoint(-4F, 10F, -7F);
		Shape14.setTextureSize(128, 128);
		Shape14.mirror = true;
		this.setRotation(Shape14, 0F, 0F, 0F);
		Shape15 = new LODModelPart(this, 30, 21);
		Shape15.addBox(0F, 0F, 0F, 4, 1, 6);
		Shape15.setRotationPoint(-1F, 9F, -7F);
		Shape15.setTextureSize(128, 128);
		Shape15.mirror = true;
		this.setRotation(Shape15, 0F, 0F, 0F);
		Shape16 = new LODModelPart(this, 0, 21);
		Shape16.addBox(0F, 0F, 0F, 11, 1, 4);
		Shape16.setRotationPoint(-8F, 9F, -1F);
		Shape16.setTextureSize(128, 128);
		Shape16.mirror = true;
		this.setRotation(Shape16, 0F, 0F, 0F);
		Shape17 = new LODModelPart(this, 80, 2);
		Shape17.addBox(0F, 0F, 0F, 1, 1, 3);
		Shape17.setRotationPoint(-8F, 10F, -7F);
		Shape17.setTextureSize(128, 128);
		Shape17.mirror = true;
		this.setRotation(Shape17, 0F, 0F, 0F);
		Shape18 = new LODModelPart(this, 80, 0);
		Shape18.addBox(0F, 0F, 0F, 4, 1, 1);
		Shape18.setRotationPoint(-8F, 10F, -8F);
		Shape18.setTextureSize(128, 128);
		Shape18.mirror = true;
		this.setRotation(Shape18, 0F, 0F, 0F);
		Shape19 = new LODModelPart(this, 112, 0);
		Shape19.addBox(0F, 0F, 0F, 1, 10, 1);
		Shape19.setRotationPoint(3F, 9F, -8F);
		Shape19.setTextureSize(128, 128);
		Shape19.mirror = true;
		this.setRotation(Shape19, 0F, 0F, 0F);
		Shape20 = new LODModelPart(this, 90, 9);
		Shape20.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape20.setRotationPoint(3F, 8F, -7F);
		Shape20.setTextureSize(128, 128);
		Shape20.mirror = true;
		this.setRotation(Shape20, 0F, 0F, 0F);
		Shape21 = new LODModelPart(this, 90, 0);
		Shape21.addBox(0F, 0F, 0F, 8, 1, 1);
		Shape21.setRotationPoint(-8F, 9F, -8F);
		Shape21.setTextureSize(128, 128);
		Shape21.mirror = true;
		this.setRotation(Shape21, 0F, 0F, 0F);
		Shape22 = new LODModelPart(this, 90, 2);
		Shape22.addBox(0F, 0F, 0F, 1, 1, 6);
		Shape22.setRotationPoint(-8F, 9F, -7F);
		Shape22.setTextureSize(128, 128);
		Shape22.mirror = true;
		this.setRotation(Shape22, 0F, 0F, 0F);
		Shape23 = new LODModelPart(this, 64, 12);
		Shape23.addBox(0F, 0F, 0F, 12, 1, 1);
		Shape23.setRotationPoint(-8F, 8F, -8F);
		Shape23.setTextureSize(128, 128);
		Shape23.mirror = true;
		this.setRotation(Shape23, 0F, 0F, 0F);
		Shape24 = new LODModelPart(this, 90, 9);
		Shape24.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape24.setRotationPoint(-8F, 8F, -7F);
		Shape24.setTextureSize(128, 128);
		Shape24.mirror = true;
		this.setRotation(Shape24, 0F, 0F, 0F);
		Shape25 = new LODModelPart(this, 64, 12);
		Shape25.addBox(0F, 0F, 0F, 12, 1, 1);
		Shape25.setRotationPoint(-8F, 8F, 3F);
		Shape25.setTextureSize(128, 128);
		Shape25.mirror = true;
		this.setRotation(Shape25, 0F, 0F, 0F);
		Shape38 = new LODModelPart(this, 112, 0);
		Shape38.addBox(0F, 0F, 0F, 1, 9, 1);
		Shape38.setRotationPoint(-8F, 9F, 3F);
		Shape38.setTextureSize(128, 128);
		Shape38.mirror = true;
		this.setRotation(Shape38, 0F, 0F, 0F);
		Shape37 = new LODModelPart(this, 112, 0);
		Shape37.addBox(0F, 0F, 0F, 1, 9, 1);
		Shape37.setRotationPoint(3F, 9F, 3F);
		Shape37.setTextureSize(128, 128);
		Shape37.mirror = true;
		this.setRotation(Shape37, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		boolean pass1 = (Boolean)li.get(0);
		if (!pass1) {
			Shape1.render(te, f5);
			Shape2.render(te, f5);
			Shape3.render(te, f5);
			Shape4.render(te, f5);
		}
		if (pass1)
			Shape5.render(te, f5);
		if (!pass1) {
			Shape6.render(te, f5);
			Shape7.render(te, f5);
			Shape8.render(te, f5);
			Shape9.render(te, f5);
			Shape10.render(te, f5);
			Shape11.render(te, f5);
			Shape12.render(te, f5);
			Shape13.render(te, f5);
			Shape14.render(te, f5);
			Shape15.render(te, f5);
			Shape16.render(te, f5);
			Shape17.render(te, f5);
			Shape18.render(te, f5);
			Shape19.render(te, f5);
			Shape20.render(te, f5);
			Shape21.render(te, f5);
			Shape22.render(te, f5);
			Shape23.render(te, f5);
			Shape24.render(te, f5);
			Shape25.render(te, f5);
			Shape26.render(te, f5);
			Shape27.render(te, f5);
			Shape28.render(te, f5);
			Shape29.render(te, f5);
			Shape30.render(te, f5);
			Shape31.render(te, f5);
			Shape32.render(te, f5);
			Shape33.render(te, f5);
			Shape34.render(te, f5);
			Shape35.render(te, f5);
			Shape36.render(te, f5);
			Shape37.render(te, f5);
			Shape38.render(te, f5);
			Shape39.render(te, f5);
		}
	}

}