/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 20/02/2013 12:34:40 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;
import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelPulseFurnace extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape4;
	LODModelPart Shape6;
	LODModelPart Shape7;
	LODModelPart Shape8;
	LODModelPart Shape9;
	LODModelPart Shape10;
	LODModelPart Shape11;
	LODModelPart Shape12;
	LODModelPart Shape13;
	LODModelPart Shape14;
	LODModelPart Shape15;
	LODModelPart Shape16;
	LODModelPart Shape17;
	LODModelPart Shape18;
	LODModelPart Shape19;
	LODModelPart Shape20;
	LODModelPart Shape21;
	LODModelPart Shape5;
	LODModelPart Shape23;
	LODModelPart Shape24;
	LODModelPart Shape25;
	LODModelPart Shape26;

	public ModelPulseFurnace()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 64, 20);
		Shape1.addBox(0F, 0F, 0F, 10, 1, 4);
		Shape1.setRotationPoint(-6.8F, 16F, -6.8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 0, 17);
		Shape2.addBox(0F, 0F, 0F, 1, 4, 4);
		Shape2.setRotationPoint(-5F, 17F, 2F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 24, 17);
		Shape3.addBox(0F, 0F, 0F, 3, 4, 6);
		Shape3.setRotationPoint(-4F, 17F, 1F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 100, 22);
		Shape4.addBox(0F, 0F, 0F, 1, 2, 6);
		Shape4.setRotationPoint(6F, 21F, 1F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 24, 27);
		Shape6.addBox(0F, 0F, 0F, 6, 6, 8);
		Shape6.setRotationPoint(-1F, 16F, 0F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape7 = new LODModelPart(this, 100, 30);
		Shape7.addBox(0F, 0F, 0F, 1, 1, 6);
		Shape7.setRotationPoint(7F, 22F, 1F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, 0F, 0F);
		Shape8 = new LODModelPart(this, 100, 13);
		Shape8.addBox(0F, 0F, 0F, 1, 3, 6);
		Shape8.setRotationPoint(5F, 20F, 1F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		this.setRotation(Shape8, 0F, 0F, 0F);
		Shape9 = new LODModelPart(this, 42, 17);
		Shape9.addBox(0F, 0F, 0F, 3, 6, 1);
		Shape9.setRotationPoint(5F, 16F, 7F);
		Shape9.setTextureSize(128, 128);
		Shape9.mirror = true;
		this.setRotation(Shape9, 0F, 0F, 0F);
		Shape10 = new LODModelPart(this, 100, 22);
		Shape10.addBox(0F, 0F, 0F, 1, 2, 6);
		Shape10.setRotationPoint(6F, 15F, 1F);
		Shape10.setTextureSize(128, 128);
		Shape10.mirror = true;
		this.setRotation(Shape10, 0F, 0F, 0F);
		Shape11 = new LODModelPart(this, 100, 30);
		Shape11.addBox(0F, 0F, 0F, 1, 1, 6);
		Shape11.setRotationPoint(7F, 15F, 1F);
		Shape11.setTextureSize(128, 128);
		Shape11.mirror = true;
		this.setRotation(Shape11, 0F, 0F, 0F);
		Shape12 = new LODModelPart(this, 100, 13);
		Shape12.addBox(0F, 0F, 0F, 1, 3, 6);
		Shape12.setRotationPoint(5F, 15F, 1F);
		Shape12.setTextureSize(128, 128);
		Shape12.mirror = true;
		this.setRotation(Shape12, 0F, 0F, 0F);
		Shape13 = new LODModelPart(this, 54, 17);
		Shape13.addBox(0F, 0F, 0F, 1, 2, 2);
		Shape13.setRotationPoint(5F, 18F, 5F);
		Shape13.setTextureSize(128, 128);
		Shape13.mirror = true;
		this.setRotation(Shape13, 0F, 0F, 0F);
		Shape14 = new LODModelPart(this, 50, 17);
		Shape14.addBox(0F, 0F, 0F, 1, 4, 1);
		Shape14.setRotationPoint(6F, 17F, 6F);
		Shape14.setTextureSize(128, 128);
		Shape14.mirror = true;
		this.setRotation(Shape14, 0F, 0F, 0F);
		Shape15 = new LODModelPart(this, 52, 40);
		Shape15.addBox(0F, 0F, 0F, 1, 2, 2);
		Shape15.setRotationPoint(4.1F, 18F, 3F);
		Shape15.setTextureSize(128, 128);
		Shape15.mirror = true;
		this.setRotation(Shape15, 0F, 0F, 0F);
		Shape16 = new LODModelPart(this, 50, 17);
		Shape16.addBox(0F, 0F, 0F, 1, 4, 1);
		Shape16.setRotationPoint(6F, 17F, 1F);
		Shape16.setTextureSize(128, 128);
		Shape16.mirror = true;
		this.setRotation(Shape16, 0F, 0F, 0F);
		Shape17 = new LODModelPart(this, 42, 17);
		Shape17.addBox(0F, 0F, 0F, 3, 6, 1);
		Shape17.setRotationPoint(5F, 16F, 0F);
		Shape17.setTextureSize(128, 128);
		Shape17.mirror = true;
		this.setRotation(Shape17, 0F, 0F, 0F);
		Shape18 = new LODModelPart(this, 0, 27);
		Shape18.addBox(0F, 0F, 0F, 6, 8, 6);
		Shape18.setRotationPoint(-1F, 15F, 1F);
		Shape18.setTextureSize(128, 128);
		Shape18.mirror = true;
		this.setRotation(Shape18, 0F, 0F, 0F);
		Shape19 = new LODModelPart(this, 10, 17);
		Shape19.addBox(0F, 0F, 0F, 3, 6, 4);
		Shape19.setRotationPoint(-4F, 16F, 2F);
		Shape19.setTextureSize(128, 128);
		Shape19.mirror = true;
		this.setRotation(Shape19, 0F, 0F, 0F);
		Shape20 = new LODModelPart(this, 104, 6);
		Shape20.addBox(0F, 0F, 0F, 3, 2, 2);
		Shape20.setRotationPoint(-8F, 18F, 3F);
		Shape20.setTextureSize(128, 128);
		Shape20.mirror = true;
		this.setRotation(Shape20, 0F, 0F, 0F);
		Shape21 = new LODModelPart(this, 104, 0);
		Shape21.addBox(0F, 0F, 0F, 2, 2, 4);
		Shape21.setRotationPoint(-8F, 18F, -1F);
		Shape21.setTextureSize(128, 128);
		Shape21.mirror = true;
		this.setRotation(Shape21, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 0, 0);
		Shape5.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape5.setRotationPoint(-8F, 23F, -8F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape23 = new LODModelPart(this, 64, 13);
		Shape23.addBox(0F, 0F, 0F, 12, 1, 6);
		Shape23.setRotationPoint(-7.5F, 16.5F, -7.5F);
		Shape23.setTextureSize(128, 128);
		Shape23.mirror = true;
		this.setRotation(Shape23, 0F, 0F, 0F);
		Shape24 = new LODModelPart(this, 64, 0);
		Shape24.addBox(0F, 0F, 0F, 13, 6, 7);
		Shape24.setRotationPoint(-7.8F, 17F, -7.8F);
		Shape24.setTextureSize(128, 128);
		Shape24.mirror = true;
		this.setRotation(Shape24, 0F, 0F, 0F);
		Shape25 = new LODModelPart(this, 52, 25);
		Shape25.addBox(0F, 0F, 0F, 4, 8, 7);
		Shape25.setRotationPoint(4F, 15F, -8F);
		Shape25.setTextureSize(128, 128);
		Shape25.mirror = true;
		this.setRotation(Shape25, 0F, 0F, 0F);
		Shape26 = new LODModelPart(this, 54, 17);
		Shape26.addBox(0F, 0F, 0F, 1, 2, 2);
		Shape26.setRotationPoint(5F, 18F, 1F);
		Shape26.setTextureSize(128, 128);
		Shape26.mirror = true;
		this.setRotation(Shape26, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);
		Shape2.render(te, f5);
		Shape3.render(te, f5);
		Shape4.render(te, f5);
		Shape5.render(te, f5);
		Shape6.render(te, f5);
		Shape7.render(te, f5);
		Shape8.render(te, f5);
		Shape9.render(te, f5);
		Shape10.render(te, f5);
		Shape11.render(te, f5);
		Shape12.render(te, f5);
		Shape13.render(te, f5);
		Shape14.render(te, f5);
		Shape15.render(te, f5);
		Shape16.render(te, f5);
		Shape17.render(te, f5);
		Shape18.render(te, f5);
		Shape19.render(te, f5);
		Shape20.render(te, f5);
		Shape21.render(te, f5);
		Shape23.render(te, f5);
		Shape24.render(te, f5);
		Shape25.render(te, f5);
		Shape26.render(te, f5);
	}

}
