/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2013
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 30/05/2013 7:20:24 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import java.util.List;

import net.minecraft.client.model.ModelRenderer;

import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelLandmine extends RotaryModelBase
{
	//fields
	ModelRenderer Shape2;
	ModelRenderer Shape2a;
	ModelRenderer Shape2b;
	ModelRenderer Shape2c;
	ModelRenderer Shape2d;
	ModelRenderer Shape2e;
	ModelRenderer Shape2f;
	ModelRenderer Shape2g;
	ModelRenderer Shape2i;
	ModelRenderer Shape21;
	ModelRenderer Shape22;
	ModelRenderer Shape23;

	public ModelLandmine()
	{
		textureWidth = 64;
		textureHeight = 64;

		Shape2 = new ModelRenderer(this, 0, 0);
		Shape2.addBox(-5F, 0F, -5F, 10, 4, 10);
		Shape2.setRotationPoint(0F, 20F, 0F);
		Shape2.setTextureSize(64, 64);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 1.178097F, 0F);
		Shape2a = new ModelRenderer(this, 0, 0);
		Shape2a.addBox(-5F, 0F, -5F, 10, 4, 10);
		Shape2a.setRotationPoint(0F, 20F, 0F);
		Shape2a.setTextureSize(64, 64);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0.3926991F, 0F);
		Shape2b = new ModelRenderer(this, 0, 31);
		Shape2b.addBox(-2F, 0F, -2F, 4, 1, 4);
		Shape2b.setRotationPoint(0F, 17F, 0F);
		Shape2b.setTextureSize(64, 64);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0F);
		Shape2c = new ModelRenderer(this, 0, 0);
		Shape2c.addBox(-5F, 0F, -5F, 10, 4, 10);
		Shape2c.setRotationPoint(0F, 20F, 0F);
		Shape2c.setTextureSize(64, 64);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0.7853982F, 0F);
		Shape2d = new ModelRenderer(this, 0, 0);
		Shape2d.addBox(-5F, 0F, -5F, 10, 4, 10);
		Shape2d.setRotationPoint(0F, 20F, 0F);
		Shape2d.setTextureSize(64, 64);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 0F, 0F);
		Shape2e = new ModelRenderer(this, 0, 15);
		Shape2e.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape2e.setRotationPoint(0F, 18F, 0F);
		Shape2e.setTextureSize(64, 64);
		Shape2e.mirror = true;
		this.setRotation(Shape2e, 0F, 0F, 0F);
		Shape2f = new ModelRenderer(this, 0, 15);
		Shape2f.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape2f.setRotationPoint(0F, 18F, 0F);
		Shape2f.setTextureSize(64, 64);
		Shape2f.mirror = true;
		this.setRotation(Shape2f, 0F, 0.3926991F, 0F);
		Shape2g = new ModelRenderer(this, 0, 15);
		Shape2g.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape2g.setRotationPoint(0F, 18F, 0F);
		Shape2g.setTextureSize(64, 64);
		Shape2g.mirror = true;
		this.setRotation(Shape2g, 0F, 0.7853982F, 0F);
		Shape2i = new ModelRenderer(this, 0, 15);
		Shape2i.addBox(-4F, 0F, -4F, 8, 2, 8);
		Shape2i.setRotationPoint(0F, 18F, 0F);
		Shape2i.setTextureSize(64, 64);
		Shape2i.mirror = true;
		this.setRotation(Shape2i, 0F, 1.178097F, 0F);
		Shape21 = new ModelRenderer(this, 0, 31);
		Shape21.addBox(-2F, 0F, -2F, 4, 1, 4);
		Shape21.setRotationPoint(0F, 17F, 0F);
		Shape21.setTextureSize(64, 64);
		Shape21.mirror = true;
		this.setRotation(Shape21, 0F, 1.178097F, 0F);
		Shape22 = new ModelRenderer(this, 0, 31);
		Shape22.addBox(-2F, 0F, -2F, 4, 1, 4);
		Shape22.setRotationPoint(0F, 17F, 0F);
		Shape22.setTextureSize(64, 64);
		Shape22.mirror = true;
		this.setRotation(Shape22, 0F, 0.7853982F, 0F);
		Shape23 = new ModelRenderer(this, 0, 31);
		Shape23.addBox(-2F, 0F, -2F, 4, 1, 4);
		Shape23.setRotationPoint(0F, 17F, 0F);
		Shape23.setTextureSize(64, 64);
		Shape23.mirror = true;
		this.setRotation(Shape23, 0F, 0.3926991F, 0F);
	}

	@Override
	public void renderAll(List li, float phi)
	{
		Shape2.render(f5);
		Shape2a.render(f5);
		Shape2b.render(f5);
		Shape2c.render(f5);
		Shape2d.render(f5);
		Shape2e.render(f5);
		Shape2f.render(f5);
		Shape2g.render(f5);
		Shape2i.render(f5);
		Shape21.render(f5);
		Shape22.render(f5);
		Shape23.render(f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}
