/*******************************************************************************
 * @author Reika
 * 
 * Copyright 2013
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 13/05/2013 11:58:50 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import java.util.List;

import net.minecraft.client.model.ModelRenderer;

import org.lwjgl.opengl.GL11;

import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelHydro extends RotaryModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape1a;
    ModelRenderer Shape2;
    ModelRenderer Shape2a;
    ModelRenderer Shape2b;
    ModelRenderer Shape2c;
    ModelRenderer Shape3;
    ModelRenderer Shape3d;

  public ModelHydro()
  {
    textureWidth = 128;
    textureHeight = 128;

      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, -1F, -1F, 17, 2, 2);
      Shape1.setRotationPoint(-8.5F, 16F, 0F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      this.setRotation(Shape1, 0.7853982F, 0F, 0F);
      Shape1a = new ModelRenderer(this, 0, 0);
      Shape1a.addBox(0F, -1F, -1F, 17, 2, 2);
      Shape1a.setRotationPoint(-8.5F, 16F, 0F);
      Shape1a.setTextureSize(128, 128);
      Shape1a.mirror = true;
      this.setRotation(Shape1a, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 0, 34);
      Shape2.addBox(0F, -0.5F, -16F, 14, 1, 32);
      Shape2.setRotationPoint(-7F, 16F, 0F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      this.setRotation(Shape2, 1.570796F, 0F, 0F);
      Shape2a = new ModelRenderer(this, 0, 34);
      Shape2a.addBox(0F, -0.5F, -16F, 14, 1, 32);
      Shape2a.setRotationPoint(-7F, 16F, 0F);
      Shape2a.setTextureSize(128, 128);
      Shape2a.mirror = true;
      this.setRotation(Shape2a, 2.356194F, 0F, 0F);
      Shape2b = new ModelRenderer(this, 0, 34);
      Shape2b.addBox(0F, -0.5F, -16F, 14, 1, 32);
      Shape2b.setRotationPoint(-7F, 16F, 0F);
      Shape2b.setTextureSize(128, 128);
      Shape2b.mirror = true;
      this.setRotation(Shape2b, 0.7853982F, 0F, 0F);
      Shape2c = new ModelRenderer(this, 0, 34);
      Shape2c.addBox(0F, -0.5F, -16F, 14, 1, 32);
      Shape2c.setRotationPoint(-7F, 16F, 0F);
      Shape2c.setTextureSize(128, 128);
      Shape2c.mirror = true;
      this.setRotation(Shape2c, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 75, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 16, 16);
      Shape3.setRotationPoint(-8F, 8F, -8F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      this.setRotation(Shape3, 0F, 0F, 0F);
      Shape3d = new ModelRenderer(this, 40, 0);
      Shape3d.addBox(0F, 0F, 0F, 1, 16, 16);
      Shape3d.setRotationPoint(7F, 8F, -8F);
      Shape3d.setTextureSize(128, 128);
      Shape3d.mirror = true;
      this.setRotation(Shape3d, 0F, 0F, 0F);
  }

  @Override
public void renderAll(List li, float phi)
  {
      GL11.glTranslated(0, 1, 0);
      GL11.glRotatef(phi, 1, 0, 0);
      GL11.glTranslated(0, -1, 0);
    Shape1.render(f5);
    Shape1a.render(f5);
    Shape2.render(f5);
    Shape2a.render(f5);
    Shape2b.render(f5);
    Shape2c.render(f5);
    GL11.glTranslated(0, 1, 0);
    GL11.glRotatef(-phi, 1, 0, 0);
    GL11.glTranslated(0, -1, 0);

    Shape3.render(f5);
    Shape3d.render(f5);
  }

  @Override
public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5);
  }

}
