/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 26/02/2013 11:50:47 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

public class ModelFraction extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape3b;
	LODModelPart Shape3c;
	LODModelPart Shape4;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape6;
	LODModelPart Shape6a;
	LODModelPart Shape6b;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape6c;
	LODModelPart Shape6d;
	LODModelPart Shape5d;
	LODModelPart Shape6e;
	LODModelPart Shape5e;
	LODModelPart Shape5f;
	LODModelPart Shape6f;
	LODModelPart Shape5g;
	LODModelPart Shape6g;
	LODModelPart Shape7;

	public ModelFraction()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 64, 14);
		Shape1.addBox(0F, 0F, 0F, 8, 14, 12);
		Shape1.setRotationPoint(-4F, 9F, -6F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 0, 18);
		Shape2.addBox(0F, 0F, 0F, 12, 14, 8);
		Shape2.setRotationPoint(-6F, 9F, -4F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 0, 41);
		Shape3.addBox(0F, 0F, 0F, 3, 14, 3);
		Shape3.setRotationPoint(1.7F, 9F, 3.8F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0.7853982F, 0F);
		Shape3a = new LODModelPart(this, 0, 41);
		Shape3a.addBox(0F, 0F, 0F, 3, 14, 3);
		Shape3a.setRotationPoint(1.7F, 9F, -3.8F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0.7853982F, 0F);
		Shape3b = new LODModelPart(this, 0, 41);
		Shape3b.addBox(0F, 0F, 0F, 3, 14, 3);
		Shape3b.setRotationPoint(-5.9F, 9F, 3.8F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0.7853982F, 0F);
		Shape3c = new LODModelPart(this, 0, 41);
		Shape3c.addBox(0F, 0F, 0F, 3, 14, 3);
		Shape3c.setRotationPoint(-5.9F, 9F, -3.8F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0.7853982F, 0F);
		Shape4 = new LODModelPart(this, 64, 0);
		Shape4.addBox(0F, 0F, 0F, 13, 1, 13);
		Shape4.setRotationPoint(-6.5F, 8F, -6.5F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 0, 76);
		Shape5.addBox(0F, 0F, 0F, 16, 2, 2);
		Shape5.setRotationPoint(-8F, 10F, -8F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape5a = new LODModelPart(this, 0, 76);
		Shape5a.addBox(0F, 0F, 0F, 16, 2, 2);
		Shape5a.setRotationPoint(-8F, 10F, 6F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 0F, 0F, 0F);
		Shape6 = new LODModelPart(this, 2, 61);
		Shape6.addBox(0F, 0F, 0F, 2, 2, 12);
		Shape6.setRotationPoint(6F, 10F, -6F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape6a = new LODModelPart(this, 2, 61);
		Shape6a.addBox(0F, 0F, 0F, 2, 2, 12);
		Shape6a.setRotationPoint(-8F, 18F, -6F);
		Shape6a.setTextureSize(128, 128);
		Shape6a.mirror = true;
		this.setRotation(Shape6a, 0F, 0F, 0F);
		Shape6b = new LODModelPart(this, 14, 46);
		Shape6b.addBox(0F, 0F, 0F, 2, 1, 12);
		Shape6b.setRotationPoint(6F, 22F, -6F);
		Shape6b.setTextureSize(128, 128);
		Shape6b.mirror = true;
		this.setRotation(Shape6b, 0F, 0F, 0F);
		Shape5b = new LODModelPart(this, 12, 41);
		Shape5b.addBox(0F, 0F, 0F, 16, 1, 2);
		Shape5b.setRotationPoint(-8F, 22F, 6F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0F, 0F);
		Shape5c = new LODModelPart(this, 12, 41);
		Shape5c.addBox(0F, 0F, 0F, 16, 1, 2);
		Shape5c.setRotationPoint(-8F, 22F, -8F);
		Shape5c.setTextureSize(128, 128);
		Shape5c.mirror = true;
		this.setRotation(Shape5c, 0F, 0F, 0F);
		Shape6c = new LODModelPart(this, 2, 61);
		Shape6c.addBox(0F, 0F, 0F, 2, 2, 12);
		Shape6c.setRotationPoint(-8F, 10F, -6F);
		Shape6c.setTextureSize(128, 128);
		Shape6c.mirror = true;
		this.setRotation(Shape6c, 0F, 0F, 0F);
		Shape6d = new LODModelPart(this, 14, 46);
		Shape6d.addBox(0F, 0F, 0F, 2, 1, 12);
		Shape6d.setRotationPoint(-8F, 22F, -6F);
		Shape6d.setTextureSize(128, 128);
		Shape6d.mirror = true;
		this.setRotation(Shape6d, 0F, 0F, 0F);
		Shape5d = new LODModelPart(this, 0, 76);
		Shape5d.addBox(0F, 0F, 0F, 16, 2, 2);
		Shape5d.setRotationPoint(-8F, 18F, -8F);
		Shape5d.setTextureSize(128, 128);
		Shape5d.mirror = true;
		this.setRotation(Shape5d, 0F, 0F, 0F);
		Shape6e = new LODModelPart(this, 2, 61);
		Shape6e.addBox(0F, 0F, 1F, 2, 2, 12);
		Shape6e.setRotationPoint(6F, 18F, -7F);
		Shape6e.setTextureSize(128, 128);
		Shape6e.mirror = true;
		this.setRotation(Shape6e, 0F, 0F, 0F);
		Shape5e = new LODModelPart(this, 0, 76);
		Shape5e.addBox(0F, 0F, 0F, 16, 2, 2);
		Shape5e.setRotationPoint(-8F, 18F, 6F);
		Shape5e.setTextureSize(128, 128);
		Shape5e.mirror = true;
		this.setRotation(Shape5e, 0F, 0F, 0F);
		Shape5f = new LODModelPart(this, 0, 76);
		Shape5f.addBox(0F, 0F, 0F, 16, 2, 2);
		Shape5f.setRotationPoint(-8F, 14F, 6F);
		Shape5f.setTextureSize(128, 128);
		Shape5f.mirror = true;
		this.setRotation(Shape5f, 0F, 0F, 0F);
		Shape6f = new LODModelPart(this, 2, 61);
		Shape6f.addBox(0F, 0F, 0F, 2, 2, 12);
		Shape6f.setRotationPoint(6F, 14F, -6F);
		Shape6f.setTextureSize(128, 128);
		Shape6f.mirror = true;
		this.setRotation(Shape6f, 0F, 0F, 0F);
		Shape5g = new LODModelPart(this, 0, 76);
		Shape5g.addBox(0F, 0F, 0F, 16, 2, 2);
		Shape5g.setRotationPoint(-8F, 14F, -8F);
		Shape5g.setTextureSize(128, 128);
		Shape5g.mirror = true;
		this.setRotation(Shape5g, 0F, 0F, 0F);
		Shape6g = new LODModelPart(this, 2, 61);
		Shape6g.addBox(0F, 0F, 0F, 2, 2, 12);
		Shape6g.setRotationPoint(-8F, 14F, -6F);
		Shape6g.setTextureSize(128, 128);
		Shape6g.mirror = true;
		this.setRotation(Shape6g, 0F, 0F, 0F);
		Shape7 = new LODModelPart(this, 0, 0);
		Shape7.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape7.setRotationPoint(-8F, 23F, -8F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);
		Shape2.render(te, f5);
		Shape3.render(te, f5);
		Shape3a.render(te, f5);
		Shape3b.render(te, f5);
		Shape3c.render(te, f5);
		Shape4.render(te, f5);
		Shape5.render(te, f5);
		Shape5a.render(te, f5);
		Shape6.render(te, f5);
		Shape6a.render(te, f5);
		Shape6b.render(te, f5);
		Shape5b.render(te, f5);
		Shape5c.render(te, f5);
		Shape6c.render(te, f5);
		Shape6d.render(te, f5);
		Shape5d.render(te, f5);
		Shape6e.render(te, f5);
		Shape5e.render(te, f5);
		Shape5f.render(te, f5);
		Shape6f.render(te, f5);
		Shape5g.render(te, f5);
		Shape6g.render(te, f5);
		Shape7.render(te, f5);
	}

}