/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 23/05/2013 1:49:47 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

public class ModelDomeEmitter extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape1a;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape2b;
	LODModelPart Shape2c;
	LODModelPart Shape2d;
	LODModelPart Shape2e;
	LODModelPart Shape2f;
	LODModelPart Shape2g;
	LODModelPart Shape2h;
	LODModelPart Shape2i;
	LODModelPart Shape2j;
	LODModelPart Shape2k;
	LODModelPart Shape2l;
	LODModelPart Shape2m;
	LODModelPart Shape2n;
	LODModelPart Shape2o;
	LODModelPart Shape2p;
	LODModelPart Shape2q;
	LODModelPart Shape2r;
	LODModelPart Shape2s;
	LODModelPart Shape1b;
	LODModelPart Shape1c;
	LODModelPart Shape3;
	LODModelPart Shape4;

	public ModelDomeEmitter()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 0);
		Shape1.addBox(0F, 0F, 0F, 16, 3, 16);
		Shape1.setRotationPoint(-8F, 21F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape1a = new LODModelPart(this, 0, 21);
		Shape1a.addBox(0F, 0F, 0F, 8, 1, 8);
		Shape1a.setRotationPoint(-4F, 18F, -4F);
		Shape1a.setTextureSize(128, 128);
		Shape1a.mirror = true;
		this.setRotation(Shape1a, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 105, 0);
		Shape2.addBox(0F, 0F, 0F, 1, 2, 6);
		Shape2.setRotationPoint(-7F, 18F, -3F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape2a = new LODModelPart(this, 65, 0);
		Shape2a.addBox(0F, 0F, 0F, 1, 12, 2);
		Shape2a.setRotationPoint(-3F, 8F, -1F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape2b = new LODModelPart(this, 72, 0);
		Shape2b.addBox(0F, 0F, 0F, 1, 9, 3);
		Shape2b.setRotationPoint(-4F, 11F, -1.5F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0F);
		Shape2c = new LODModelPart(this, 81, 0);
		Shape2c.addBox(0F, 0F, 0F, 1, 6, 4);
		Shape2c.setRotationPoint(-5F, 14F, -2F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0F, 0F);
		Shape2d = new LODModelPart(this, 92, 0);
		Shape2d.addBox(0F, 0F, 0F, 1, 4, 5);
		Shape2d.setRotationPoint(-6F, 16F, -2.5F);
		Shape2d.setTextureSize(128, 128);
		Shape2d.mirror = true;
		this.setRotation(Shape2d, 0F, 0F, 0F);
		Shape2e = new LODModelPart(this, 105, 18);
		Shape2e.addBox(0F, 0F, 0F, 6, 2, 1);
		Shape2e.setRotationPoint(-3F, 18F, -7F);
		Shape2e.setTextureSize(128, 128);
		Shape2e.mirror = true;
		this.setRotation(Shape2e, 0F, 0F, 0F);
		Shape2f = new LODModelPart(this, 72, 13);
		Shape2f.addBox(0F, 0F, 0F, 1, 9, 3);
		Shape2f.setRotationPoint(3F, 11F, -1.5F);
		Shape2f.setTextureSize(128, 128);
		Shape2f.mirror = true;
		this.setRotation(Shape2f, 0F, 0F, 0F);
		Shape2g = new LODModelPart(this, 81, 11);
		Shape2g.addBox(0F, 0F, 0F, 1, 6, 4);
		Shape2g.setRotationPoint(4F, 14F, -2F);
		Shape2g.setTextureSize(128, 128);
		Shape2g.mirror = true;
		this.setRotation(Shape2g, 0F, 0F, 0F);
		Shape2h = new LODModelPart(this, 92, 10);
		Shape2h.addBox(0F, 0F, 0F, 1, 4, 5);
		Shape2h.setRotationPoint(5F, 16F, -2.5F);
		Shape2h.setTextureSize(128, 128);
		Shape2h.mirror = true;
		this.setRotation(Shape2h, 0F, 0F, 0F);
		Shape2i = new LODModelPart(this, 105, 9);
		Shape2i.addBox(0F, 0F, 0F, 1, 2, 6);
		Shape2i.setRotationPoint(6F, 18F, -3F);
		Shape2i.setTextureSize(128, 128);
		Shape2i.mirror = true;
		this.setRotation(Shape2i, 0F, 0F, 0F);
		Shape2j = new LODModelPart(this, 65, 15);
		Shape2j.addBox(0F, 0F, 0F, 1, 12, 2);
		Shape2j.setRotationPoint(2F, 8F, -1F);
		Shape2j.setTextureSize(128, 128);
		Shape2j.mirror = true;
		this.setRotation(Shape2j, 0F, 0F, 0F);
		Shape2k = new LODModelPart(this, 65, 30);
		Shape2k.addBox(0F, 0F, 0F, 2, 12, 1);
		Shape2k.setRotationPoint(-1F, 8F, -3F);
		Shape2k.setTextureSize(128, 128);
		Shape2k.mirror = true;
		this.setRotation(Shape2k, 0F, 0F, 0F);
		Shape2l = new LODModelPart(this, 72, 26);
		Shape2l.addBox(0F, 0F, 0F, 3, 9, 1);
		Shape2l.setRotationPoint(-1.5F, 11F, -4F);
		Shape2l.setTextureSize(128, 128);
		Shape2l.mirror = true;
		this.setRotation(Shape2l, 0F, 0F, 0F);
		Shape2m = new LODModelPart(this, 81, 22);
		Shape2m.addBox(0F, 0F, 0F, 4, 6, 1);
		Shape2m.setRotationPoint(-2F, 14F, -5F);
		Shape2m.setTextureSize(128, 128);
		Shape2m.mirror = true;
		this.setRotation(Shape2m, 0F, 0F, 0F);
		Shape2n = new LODModelPart(this, 92, 20);
		Shape2n.addBox(0F, 0F, 0F, 5, 4, 1);
		Shape2n.setRotationPoint(-2.5F, 16F, -6F);
		Shape2n.setTextureSize(128, 128);
		Shape2n.mirror = true;
		this.setRotation(Shape2n, 0F, 0F, 0F);
		Shape2o = new LODModelPart(this, 65, 44);
		Shape2o.addBox(0F, 0F, 0F, 2, 12, 1);
		Shape2o.setRotationPoint(-1F, 8F, 2F);
		Shape2o.setTextureSize(128, 128);
		Shape2o.mirror = true;
		this.setRotation(Shape2o, 0F, 0F, 0F);
		Shape2p = new LODModelPart(this, 72, 37);
		Shape2p.addBox(0F, 0F, 0F, 3, 9, 1);
		Shape2p.setRotationPoint(-1.5F, 11F, 3F);
		Shape2p.setTextureSize(128, 128);
		Shape2p.mirror = true;
		this.setRotation(Shape2p, 0F, 0F, 0F);
		Shape2q = new LODModelPart(this, 81, 30);
		Shape2q.addBox(0F, 0F, 0F, 4, 6, 1);
		Shape2q.setRotationPoint(-2F, 14F, 4F);
		Shape2q.setTextureSize(128, 128);
		Shape2q.mirror = true;
		this.setRotation(Shape2q, 0F, 0F, 0F);
		Shape2r = new LODModelPart(this, 92, 26);
		Shape2r.addBox(0F, 0F, 0F, 5, 4, 1);
		Shape2r.setRotationPoint(-2.5F, 16F, 5F);
		Shape2r.setTextureSize(128, 128);
		Shape2r.mirror = true;
		this.setRotation(Shape2r, 0F, 0F, 0F);
		Shape2s = new LODModelPart(this, 105, 22);
		Shape2s.addBox(0F, 0F, 0F, 6, 2, 1);
		Shape2s.setRotationPoint(-3F, 18F, 6F);
		Shape2s.setTextureSize(128, 128);
		Shape2s.mirror = true;
		this.setRotation(Shape2s, 0F, 0F, 0F);
		Shape1b = new LODModelPart(this, 0, 45);
		Shape1b.addBox(0F, 0F, 0F, 14, 1, 14);
		Shape1b.setRotationPoint(-7F, 20F, -7F);
		Shape1b.setTextureSize(128, 128);
		Shape1b.mirror = true;
		this.setRotation(Shape1b, 0F, 0F, 0F);
		Shape1c = new LODModelPart(this, 0, 31);
		Shape1c.addBox(0F, 0F, 0F, 12, 1, 12);
		Shape1c.setRotationPoint(-6F, 19F, -6F);
		Shape1c.setTextureSize(128, 128);
		Shape1c.mirror = true;
		this.setRotation(Shape1c, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 110, 26);
		Shape3.addBox(0F, 0F, 0F, 2, 4, 2);
		Shape3.setRotationPoint(-1F, 14F, -1F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape4 = new LODModelPart(this, 105, 26);
		Shape4.addBox(0F, 0F, 0F, 1, 5, 1);
		Shape4.setRotationPoint(-0.5F, 9F, -0.5F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		Shape1.render(te, f5);
		Shape1a.render(te, f5);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape2b.render(te, f5);
		Shape2c.render(te, f5);
		Shape2d.render(te, f5);
		Shape2e.render(te, f5);
		Shape2f.render(te, f5);
		Shape2g.render(te, f5);
		Shape2h.render(te, f5);
		Shape2i.render(te, f5);
		Shape2j.render(te, f5);
		Shape2k.render(te, f5);
		Shape2l.render(te, f5);
		Shape2m.render(te, f5);
		Shape2n.render(te, f5);
		Shape2o.render(te, f5);
		Shape2p.render(te, f5);
		Shape2q.render(te, f5);
		Shape2r.render(te, f5);
		Shape2s.render(te, f5);
		Shape1b.render(te, f5);
		Shape1c.render(te, f5);
		Shape3.render(te, f5);
		Shape4.render(te, f5);
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f6)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5);
	}

}