/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2013
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 20/02/2013 8:05:58 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import java.util.List;

import net.minecraft.client.model.ModelRenderer;

import org.lwjgl.opengl.GL11;

import Reika.RotaryCraft.Base.RotaryModelBase;


public class ModelAC extends RotaryModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
    ModelRenderer Shape16;
    ModelRenderer Shape17;
    ModelRenderer Shape18;
    ModelRenderer Shape19;
    ModelRenderer Shape20;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
  
  public ModelAC()
  {
    textureWidth = 128;
    textureHeight = 128;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 16, 2, 16);
      Shape1.setRotationPoint(-8F, 22F, -8F);
      Shape1.setTextureSize(128, 128);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape12 = new ModelRenderer(this, 74, 52);
      Shape12.addBox(0F, 0F, 0F, 10, 2, 16);
      Shape12.setRotationPoint(-4.5F, 18F, -7.8F);
      Shape12.setTextureSize(128, 128);
      Shape12.mirror = true;
      setRotation(Shape12, 0.3926991F, 0F, 0F);
      Shape13 = new ModelRenderer(this, 111, 0);
      Shape13.addBox(0F, 0F, 0F, 5, 2, 2);
      Shape13.setRotationPoint(-8.5F, 16F, -1.4F);
      Shape13.setTextureSize(128, 128);
      Shape13.mirror = true;
      setRotation(Shape13, 0.7853982F, 0F, 0F);
      Shape14 = new ModelRenderer(this, 111, 0);
      Shape14.addBox(0F, 0F, 0F, 5, 2, 2);
      Shape14.setRotationPoint(-8.5F, 15F, -1F);
      Shape14.setTextureSize(128, 128);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 64, 0);
      Shape15.addBox(0F, 0F, 0F, 15, 10, 8);
      Shape15.setRotationPoint(-7F, 11F, -4F);
      Shape15.setTextureSize(128, 128);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
      Shape16 = new ModelRenderer(this, 0, 18);
      Shape16.addBox(0F, 0F, 0F, 15, 8, 10);
      Shape16.setRotationPoint(-6.9F, 12F, -5F);
      Shape16.setTextureSize(128, 128);
      Shape16.mirror = true;
      setRotation(Shape16, 0F, 0F, 0F);
      Shape17 = new ModelRenderer(this, 78, 37);
      Shape17.addBox(0F, 0F, 0F, 11, 2, 13);
      Shape17.setRotationPoint(-5.5F, 18.7F, -4.2F);
      Shape17.setTextureSize(128, 128);
      Shape17.mirror = true;
      setRotation(Shape17, 0.7853982F, 0F, 0F);
      Shape18 = new ModelRenderer(this, 52, 22);
      Shape18.addBox(0F, 0F, 0F, 10, 2, 13);
      Shape18.setRotationPoint(-4.5F, 20.2F, -2.8F);
      Shape18.setTextureSize(128, 128);
      Shape18.mirror = true;
      setRotation(Shape18, 1.178097F, 0F, 0F);
      Shape19 = new ModelRenderer(this, 64, 70);
      Shape19.addBox(0F, 0F, 0F, 10, 13, 2);
      Shape19.setRotationPoint(-4.5F, 8F, -1F);
      Shape19.setTextureSize(128, 128);
      Shape19.mirror = true;
      setRotation(Shape19, 0F, 0F, 0F);
      Shape20 = new ModelRenderer(this, 0, 79);
      Shape20.addBox(0F, 0F, 0F, 10, 2, 16);
      Shape20.setRotationPoint(-4.5F, 12F, -7F);
      Shape20.setTextureSize(128, 128);
      Shape20.mirror = true;
      setRotation(Shape20, -0.3926991F, 0F, 0F);
      Shape4 = new ModelRenderer(this, 0, 97);
      Shape4.addBox(0F, 0F, 0F, 10, 2, 13);
      Shape4.setRotationPoint(-4.5F, 9.7F, -5F);
      Shape4.setTextureSize(128, 128);
      Shape4.mirror = true;
      setRotation(Shape4, -0.7853982F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 0, 64);
      Shape5.addBox(0F, 0F, 0F, 10, 2, 13);
      Shape5.setRotationPoint(-4.5F, 8.3F, -2.2F);
      Shape5.setTextureSize(128, 128);
      Shape5.mirror = true;
      setRotation(Shape5, -1.178097F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 0, 37);
      Shape6.addBox(0F, 0F, 0F, 10, 2, 16);
      Shape6.setRotationPoint(-4.5F, 15F, -8F);
      Shape6.setTextureSize(128, 128);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 50, 18);
      Shape7.addBox(0F, 0F, 0F, 14, 2, 2);
      Shape7.setRotationPoint(-6.5F, 20.5F, 3F);
      Shape7.setTextureSize(128, 128);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 50, 18);
      Shape2.addBox(0F, 0F, 0F, 14, 2, 2);
      Shape2.setRotationPoint(-6.5F, 20.5F, -5F);
      Shape2.setTextureSize(128, 128);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 111, 4);
      Shape3.addBox(0F, 0F, 0F, 1, 4, 4);
      Shape3.setRotationPoint(-7.5F, 14F, -2F);
      Shape3.setTextureSize(128, 128);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
  }
  
  public void renderAll(List li, float phi)
  {
      this.Shape1.render(f5);
      this.Shape2.render(f5);
      this.Shape3.render(f5);
      this.Shape4.render(f5);
      this.Shape5.render(f5);
      this.Shape6.render(f5);
      this.Shape7.render(f5);
      this.Shape12.render(f5);
      
      GL11.glTranslated(0, 1, 0);
      GL11.glRotatef(phi, 1, 0, 0);
      GL11.glTranslated(0, -1, 0);
      this.Shape13.render(f5);
      this.Shape14.render(f5);
      GL11.glTranslated(0, 1, 0);
      GL11.glRotatef(-phi, 1, 0, 0);
      GL11.glTranslated(0, -1, 0);
      
      this.Shape15.render(f5);
      this.Shape16.render(f5);
      this.Shape17.render(f5);
      this.Shape18.render(f5);
      this.Shape19.render(f5);
      this.Shape20.render(f5);
  }

}
