/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2013
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 11/02/2013 9:54:57 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import java.util.List;

import net.minecraft.client.model.ModelRenderer;

import org.lwjgl.opengl.GL11;

import Reika.RotaryCraft.Base.RotaryModelBase;


public class ModelClutch extends RotaryModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
    ModelRenderer Shape12;
    ModelRenderer Shape13;
    ModelRenderer Shape14;
    ModelRenderer Shape15;
  
  public ModelClutch()
  {
    textureWidth = 128;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
      Shape1.setRotationPoint(-8F, 23F, -8F);
      Shape1.setTextureSize(128, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 64, 0);
      Shape2.addBox(0F, 0F, 0F, 1, 12, 16);
      Shape2.setRotationPoint(7F, 11F, -8F);
      Shape2.setTextureSize(128, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape2.mirror = false;
      Shape3 = new ModelRenderer(this, 64, 0);
      Shape3.addBox(0F, 0F, 0F, 1, 12, 16);
      Shape3.setRotationPoint(-8F, 11F, -8F);
      Shape3.setTextureSize(128, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0F);
      Shape3.mirror = false;
      Shape4 = new ModelRenderer(this, 0, 17);
      Shape4.addBox(0F, 0F, 0F, 14, 6, 1);
      Shape4.setRotationPoint(-7F, 17F, 7F);
      Shape4.setTextureSize(128, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape4.mirror = false;
      Shape5 = new ModelRenderer(this, 0, 17);
      Shape5.addBox(0F, 0F, 0F, 14, 6, 1);
      Shape5.setRotationPoint(-7F, 17F, -8F);
      Shape5.setTextureSize(128, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape5.mirror = false;
      Shape6 = new ModelRenderer(this, 30, 17);
      Shape6.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape6.setRotationPoint(6F, 14F, 7F);
      Shape6.setTextureSize(128, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape6.mirror = false;
      Shape7 = new ModelRenderer(this, 30, 17);
      Shape7.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape7.setRotationPoint(6F, 14F, -8F);
      Shape7.setTextureSize(128, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape7.mirror = false;
      Shape8 = new ModelRenderer(this, 30, 17);
      Shape8.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape8.setRotationPoint(-7F, 14F, 7F);
      Shape8.setTextureSize(128, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape8.mirror = false;
      Shape9 = new ModelRenderer(this, 30, 17);
      Shape9.addBox(0F, 0F, 0F, 1, 3, 1);
      Shape9.setRotationPoint(-7F, 14F, -8F);
      Shape9.setTextureSize(128, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0F, 0F);
      Shape9.mirror = false;
      Shape10 = new ModelRenderer(this, 42, 17);
      Shape10.addBox(0F, 0F, 0F, 1, 3, 10);
      Shape10.setRotationPoint(7F, 8F, -5F);
      Shape10.setTextureSize(128, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, 0F, 0F);
      Shape10.mirror = false;
      Shape11 = new ModelRenderer(this, 42, 17);
      Shape11.addBox(0F, 0F, 0F, 1, 3, 10);
      Shape11.setRotationPoint(-8F, 8F, -5F);
      Shape11.setTextureSize(128, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
      Shape11.mirror = false;
      Shape12 = new ModelRenderer(this, 0, 27);
      Shape12.addBox(0F, 0F, 0F, 17, 2, 2);
      Shape12.setRotationPoint(-8.5F, 15F, -1F);
      Shape12.setTextureSize(128, 32);
      Shape12.mirror = true;
      setRotation(Shape12, 0F, 0F, 0F);
      Shape12.mirror = false;
      Shape13 = new ModelRenderer(this, 0, 27);
      Shape13.addBox(0F, 0F, 0F, 17, 2, 2);
      Shape13.setRotationPoint(-8.5F, 16F, -1.4F);
      Shape13.setTextureSize(128, 32);
      Shape13.mirror = true;
      setRotation(Shape13, 0.7853982F, 0F, 0F);
      Shape13.mirror = false;
      Shape14 = new ModelRenderer(this, 104, 0);
      Shape14.addBox(0F, 0F, 0F, 6, 6, 6);
      Shape14.setRotationPoint(-3F, 13F, -3F);
      Shape14.setTextureSize(128, 32);
      Shape14.mirror = true;
      setRotation(Shape14, 0F, 0F, 0F);
      Shape15 = new ModelRenderer(this, 95, 0);
      Shape15.addBox(0F, 0F, 0F, 8, 4, 8);
      Shape15.setRotationPoint(-4F, 19F, -4F);
      Shape15.setTextureSize(128, 32);
      Shape15.mirror = true;
      setRotation(Shape15, 0F, 0F, 0F);
  }
  
  public void renderAll(List li, float phi)
  {
      this.Shape1.render(f5);
      this.Shape2.render(f5);
      this.Shape3.render(f5);
      this.Shape4.render(f5);
      this.Shape5.render(f5);
      this.Shape6.render(f5);
      this.Shape7.render(f5);
      this.Shape8.render(f5);
      this.Shape9.render(f5);
      this.Shape10.render(f5);
      this.Shape11.render(f5);
      GL11.glTranslated(0, 1, 0);
      GL11.glRotatef(phi, 1, 0, 0);
      GL11.glTranslated(0, -1, 0);
      this.Shape12.render(f5);
      this.Shape13.render(f5);
      GL11.glTranslated(0, 1, 0);
      GL11.glRotatef(-phi, 1, 0, 0);
      GL11.glTranslated(0, -1, 0);
      this.Shape14.render(f5);
      this.Shape15.render(f5);
  }

}
