/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2013
 * 
 * All rights reserved.
 * 
 * Distribution of the software in any form is only allowed
 * with explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 03/03/2013 1:10:56 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import java.util.List;

import net.minecraft.client.model.ModelRenderer;
import Reika.RotaryCraft.Base.RotaryModelBase;

public class ModelVacuum extends RotaryModelBase
{
	//fields
	ModelRenderer Shape1;
	ModelRenderer Shape2;
	ModelRenderer Shape2a;
	ModelRenderer Shape2b;
	ModelRenderer Shape2c;
	ModelRenderer Shape3;
	ModelRenderer Shape3a;
	ModelRenderer Shape3b;
	ModelRenderer Shape3c;
	ModelRenderer Shape4;
	ModelRenderer Shape4a;
	ModelRenderer Shape4b;
	ModelRenderer Shape4c;
	ModelRenderer Shape5;
	ModelRenderer Shape5a;
	ModelRenderer Shape5b;
	ModelRenderer Shape5d;
	ModelRenderer Shape5e;
	ModelRenderer Shape5f;
	ModelRenderer Shape5g;
	ModelRenderer Shape6;
	ModelRenderer Shape6a;
	ModelRenderer Shape6b;
	ModelRenderer Shape6c;
	ModelRenderer Shape6d;
	ModelRenderer Shape6e;
	ModelRenderer Shape6f;
	ModelRenderer Shape6g;
	ModelRenderer Shape6h;
	ModelRenderer Shape6i;
	ModelRenderer Shape6j;
	ModelRenderer Shape6k;
	ModelRenderer Shape6l;
	ModelRenderer Shape6m;
	ModelRenderer Shape6n;
	ModelRenderer Shape6o;
	ModelRenderer Shape6p;

	public ModelVacuum()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new ModelRenderer(this, 36, 0);
		Shape1.addBox(0F, 0F, 0F, 12, 12, 12);
		Shape1.setRotationPoint(-6F, 10F, -6F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new ModelRenderer(this, 0, 0);
		Shape2.addBox(0F, 0F, 0F, 2, 2, 16);
		Shape2.setRotationPoint(-8F, 22F, -8F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape2a = new ModelRenderer(this, 0, 0);
		Shape2a.addBox(0F, 0F, 0F, 2, 2, 16);
		Shape2a.setRotationPoint(-8F, 8F, -8F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape2b = new ModelRenderer(this, 0, 0);
		Shape2b.addBox(0F, 0F, 0F, 2, 2, 16);
		Shape2b.setRotationPoint(6F, 8F, -8F);
		Shape2b.setTextureSize(128, 128);
		Shape2b.mirror = true;
		this.setRotation(Shape2b, 0F, 0F, 0F);
		Shape2c = new ModelRenderer(this, 0, 0);
		Shape2c.addBox(0F, 0F, 0F, 2, 2, 16);
		Shape2c.setRotationPoint(6F, 22F, -8F);
		Shape2c.setTextureSize(128, 128);
		Shape2c.mirror = true;
		this.setRotation(Shape2c, 0F, 0F, 0F);
		Shape3 = new ModelRenderer(this, 84, 0);
		Shape3.addBox(0F, 0F, 0F, 12, 2, 2);
		Shape3.setRotationPoint(-6F, 22F, 6F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape3a = new ModelRenderer(this, 84, 0);
		Shape3a.addBox(0F, 0F, 0F, 12, 2, 2);
		Shape3a.setRotationPoint(-6F, 8F, 6F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape3b = new ModelRenderer(this, 84, 0);
		Shape3b.addBox(0F, 0F, 0F, 12, 2, 2);
		Shape3b.setRotationPoint(-6F, 22F, -8F);
		Shape3b.setTextureSize(128, 128);
		Shape3b.mirror = true;
		this.setRotation(Shape3b, 0F, 0F, 0F);
		Shape3c = new ModelRenderer(this, 84, 0);
		Shape3c.addBox(0F, 0F, 0F, 12, 2, 2);
		Shape3c.setRotationPoint(-6F, 8F, -8F);
		Shape3c.setTextureSize(128, 128);
		Shape3c.mirror = true;
		this.setRotation(Shape3c, 0F, 0F, 0F);
		Shape4 = new ModelRenderer(this, 0, 45);
		Shape4.addBox(0F, 0F, 0F, 2, 12, 2);
		Shape4.setRotationPoint(-8F, 10F, 6F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
		Shape4a = new ModelRenderer(this, 0, 45);
		Shape4a.addBox(0F, 0F, 0F, 2, 12, 2);
		Shape4a.setRotationPoint(6F, 10F, 6F);
		Shape4a.setTextureSize(128, 128);
		Shape4a.mirror = true;
		this.setRotation(Shape4a, 0F, 0F, 0F);
		Shape4b = new ModelRenderer(this, 0, 45);
		Shape4b.addBox(0F, 0F, 0F, 2, 12, 2);
		Shape4b.setRotationPoint(6F, 10F, -8F);
		Shape4b.setTextureSize(128, 128);
		Shape4b.mirror = true;
		this.setRotation(Shape4b, 0F, 0F, 0F);
		Shape4c = new ModelRenderer(this, 0, 45);
		Shape4c.addBox(0F, 0F, 0F, 2, 12, 2);
		Shape4c.setRotationPoint(-8F, 10F, -8F);
		Shape4c.setTextureSize(128, 128);
		Shape4c.mirror = true;
		this.setRotation(Shape4c, 0F, 0F, 0F);
		Shape5 = new ModelRenderer(this, 0, 29);
		Shape5.addBox(0F, 0F, 0F, 12, 1, 1);
		Shape5.setRotationPoint(-6F, 22F, 5F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape5a = new ModelRenderer(this, 0, 18);
		Shape5a.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape5a.setRotationPoint(5F, 22F, -5F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, 0F, 0F, 0F);
		Shape5b = new ModelRenderer(this, 0, 29);
		Shape5b.addBox(0F, 0F, 0F, 12, 1, 1);
		Shape5b.setRotationPoint(-6F, 22F, -6F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0F, 0F);
		Shape5d = new ModelRenderer(this, 0, 18);
		Shape5d.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape5d.setRotationPoint(-6F, 9F, -5F);
		Shape5d.setTextureSize(128, 128);
		Shape5d.mirror = true;
		this.setRotation(Shape5d, 0F, 0F, 0F);
		Shape5e = new ModelRenderer(this, 0, 29);
		Shape5e.addBox(0F, 0F, 0F, 12, 1, 1);
		Shape5e.setRotationPoint(-6F, 9F, 5F);
		Shape5e.setTextureSize(128, 128);
		Shape5e.mirror = true;
		this.setRotation(Shape5e, 0F, 0F, 0F);
		Shape5f = new ModelRenderer(this, 0, 29);
		Shape5f.addBox(0F, 0F, 0F, 12, 1, 1);
		Shape5f.setRotationPoint(-6F, 9F, -6F);
		Shape5f.setTextureSize(128, 128);
		Shape5f.mirror = true;
		this.setRotation(Shape5f, 0F, 0F, 0F);
		Shape5g = new ModelRenderer(this, 0, 18);
		Shape5g.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape5g.setRotationPoint(5F, 9F, -5F);
		Shape5g.setTextureSize(128, 128);
		Shape5g.mirror = true;
		this.setRotation(Shape5g, 0F, 0F, 0F);
		Shape6 = new ModelRenderer(this, 0, 32);
		Shape6.addBox(0F, 0F, 0F, 10, 1, 1);
		Shape6.setRotationPoint(-5F, 21F, -7F);
		Shape6.setTextureSize(128, 128);
		Shape6.mirror = true;
		this.setRotation(Shape6, 0F, 0F, 0F);
		Shape6a = new ModelRenderer(this, 27, 18);
		Shape6a.addBox(0F, 0F, 0F, 1, 12, 1);
		Shape6a.setRotationPoint(5F, 10F, 6F);
		Shape6a.setTextureSize(128, 128);
		Shape6a.mirror = true;
		this.setRotation(Shape6a, 0F, 0F, 0F);
		Shape6b = new ModelRenderer(this, 27, 18);
		Shape6b.addBox(0F, 0F, 0F, 1, 12, 1);
		Shape6b.setRotationPoint(-6F, 10F, 6F);
		Shape6b.setTextureSize(128, 128);
		Shape6b.mirror = true;
		this.setRotation(Shape6b, 0F, 0F, 0F);
		Shape6c = new ModelRenderer(this, 0, 32);
		Shape6c.addBox(0F, 0F, 0F, 10, 1, 1);
		Shape6c.setRotationPoint(-5F, 10F, 6F);
		Shape6c.setTextureSize(128, 128);
		Shape6c.mirror = true;
		this.setRotation(Shape6c, 0F, 0F, 0F);
		Shape6d = new ModelRenderer(this, 27, 18);
		Shape6d.addBox(0F, 0F, 0F, 1, 12, 1);
		Shape6d.setRotationPoint(-6F, 10F, -7F);
		Shape6d.setTextureSize(128, 128);
		Shape6d.mirror = true;
		this.setRotation(Shape6d, 0F, 0F, 0F);
		Shape6e = new ModelRenderer(this, 0, 32);
		Shape6e.addBox(0F, 0F, 0F, 10, 1, 1);
		Shape6e.setRotationPoint(-5F, 21F, 6F);
		Shape6e.setTextureSize(128, 128);
		Shape6e.mirror = true;
		this.setRotation(Shape6e, 0F, 0F, 0F);
		Shape6f = new ModelRenderer(this, 0, 32);
		Shape6f.addBox(0F, 0F, 0F, 10, 1, 1);
		Shape6f.setRotationPoint(-5F, 10F, -7F);
		Shape6f.setTextureSize(128, 128);
		Shape6f.mirror = true;
		this.setRotation(Shape6f, 0F, 0F, 0F);
		Shape6g = new ModelRenderer(this, 27, 18);
		Shape6g.addBox(0F, 0F, 0F, 1, 12, 1);
		Shape6g.setRotationPoint(-7F, 10F, 5F);
		Shape6g.setTextureSize(128, 128);
		Shape6g.mirror = true;
		this.setRotation(Shape6g, 0F, 0F, 0F);
		Shape6h = new ModelRenderer(this, 27, 18);
		Shape6h.addBox(0F, 0F, 0F, 1, 12, 1);
		Shape6h.setRotationPoint(5F, 10F, -7F);
		Shape6h.setTextureSize(128, 128);
		Shape6h.mirror = true;
		this.setRotation(Shape6h, 0F, 0F, 0F);
		Shape6i = new ModelRenderer(this, 0, 34);
		Shape6i.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape6i.setRotationPoint(6F, 21F, -5F);
		Shape6i.setTextureSize(128, 128);
		Shape6i.mirror = true;
		this.setRotation(Shape6i, 0F, 0F, 0F);
		Shape6j = new ModelRenderer(this, 27, 18);
		Shape6j.addBox(0F, 0F, 0F, 1, 12, 1);
		Shape6j.setRotationPoint(-7F, 10F, -6F);
		Shape6j.setTextureSize(128, 128);
		Shape6j.mirror = true;
		this.setRotation(Shape6j, 0F, 0F, 0F);
		Shape6k = new ModelRenderer(this, 0, 34);
		Shape6k.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape6k.setRotationPoint(-7F, 10F, -5F);
		Shape6k.setTextureSize(128, 128);
		Shape6k.mirror = true;
		this.setRotation(Shape6k, 0F, 0F, 0F);
		Shape6l = new ModelRenderer(this, 0, 34);
		Shape6l.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape6l.setRotationPoint(6F, 10F, -5F);
		Shape6l.setTextureSize(128, 128);
		Shape6l.mirror = true;
		this.setRotation(Shape6l, 0F, 0F, 0F);
		Shape6m = new ModelRenderer(this, 27, 18);
		Shape6m.addBox(0F, 0F, 0F, 1, 12, 1);
		Shape6m.setRotationPoint(6F, 10F, -6F);
		Shape6m.setTextureSize(128, 128);
		Shape6m.mirror = true;
		this.setRotation(Shape6m, 0F, 0F, 0F);
		Shape6n = new ModelRenderer(this, 0, 18);
		Shape6n.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape6n.setRotationPoint(-6F, 22F, -5F);
		Shape6n.setTextureSize(128, 128);
		Shape6n.mirror = true;
		this.setRotation(Shape6n, 0F, 0F, 0F);
		Shape6o = new ModelRenderer(this, 27, 18);
		Shape6o.addBox(0F, 0F, 0F, 1, 12, 1);
		Shape6o.setRotationPoint(6F, 10F, 5F);
		Shape6o.setTextureSize(128, 128);
		Shape6o.mirror = true;
		this.setRotation(Shape6o, 0F, 0F, 0F);
		Shape6p = new ModelRenderer(this, 0, 34);
		Shape6p.addBox(0F, 0F, 0F, 1, 1, 10);
		Shape6p.setRotationPoint(-7F, 21F, -5F);
		Shape6p.setTextureSize(128, 128);
		Shape6p.mirror = true;
		this.setRotation(Shape6p, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(List li, float phi)
	{
		Shape1.render(f5);
		Shape2.render(f5);
		Shape2a.render(f5);
		Shape2b.render(f5);
		Shape2c.render(f5);
		Shape3.render(f5);
		Shape3a.render(f5);
		Shape3b.render(f5);
		Shape3c.render(f5);
		Shape4.render(f5);
		Shape4a.render(f5);
		Shape4b.render(f5);
		Shape4c.render(f5);
		Shape5.render(f5);
		Shape5a.render(f5);
		Shape5b.render(f5);
		Shape5d.render(f5);
		Shape5e.render(f5);
		Shape5f.render(f5);
		Shape5g.render(f5);
		Shape6.render(f5);
		Shape6a.render(f5);
		Shape6b.render(f5);
		Shape6c.render(f5);
		Shape6d.render(f5);
		Shape6e.render(f5);
		Shape6f.render(f5);
		Shape6g.render(f5);
		Shape6h.render(f5);
		Shape6i.render(f5);
		Shape6j.render(f5);
		Shape6k.render(f5);
		Shape6l.render(f5);
		Shape6m.render(f5);
		Shape6n.render(f5);
		Shape6o.render(f5);
		Shape6p.render(f5);
	}
}
