/*******************************************************************************
 * @author Reika Kalseki
 * 
 * Copyright 2014
 * 
 * All rights reserved.
 * Distribution of the software in any form is only allowed with
 * explicit, prior permission from the owner.
 ******************************************************************************/
// Date: 17/03/2013 12:30:05 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package Reika.RotaryCraft.Models;

import Reika.DragonAPI.Instantiable.Rendering.LODModelPart;
import Reika.RotaryCraft.Base.RotaryModelBase;

import java.util.ArrayList;

import net.minecraft.tileentity.TileEntity;

public class ModelBreeder extends RotaryModelBase
{
	//fields
	LODModelPart Shape1;
	LODModelPart Shape2;
	LODModelPart Shape2a;
	LODModelPart Shape3;
	LODModelPart Shape3a;
	LODModelPart Shape5;
	LODModelPart Shape5a;
	LODModelPart Shape5b;
	LODModelPart Shape5c;
	LODModelPart Shape5d;
	LODModelPart Shape5e;
	LODModelPart Shape5f;
	LODModelPart Shape5g;
	LODModelPart Shape5h;
	LODModelPart Shape5i;
	LODModelPart Shape6a;
	LODModelPart Shape6b;
	LODModelPart Shape6c;
	LODModelPart Shape6d;
	LODModelPart Shape6e;
	LODModelPart Shape7;
	LODModelPart Shape7a;
	LODModelPart Shape7b;
	LODModelPart Shape8;
	LODModelPart Shape8a;
	LODModelPart Shape8b;
	LODModelPart Shape8c;
	LODModelPart Shape4;

	public ModelBreeder()
	{
		textureWidth = 128;
		textureHeight = 128;

		Shape1 = new LODModelPart(this, 0, 41);
		Shape1.addBox(0F, 0F, 0F, 16, 1, 16);
		Shape1.setRotationPoint(-8F, 23F, -8F);
		Shape1.setTextureSize(128, 128);
		Shape1.mirror = true;
		this.setRotation(Shape1, 0F, 0F, 0F);
		Shape2 = new LODModelPart(this, 31, 0);
		Shape2.addBox(0F, 0F, 0F, 1, 7, 16);
		Shape2.setRotationPoint(-8F, 16F, -8F);
		Shape2.setTextureSize(128, 128);
		Shape2.mirror = true;
		this.setRotation(Shape2, 0F, 0F, 0F);
		Shape2a = new LODModelPart(this, 31, 0);
		Shape2a.addBox(0F, 0F, 0F, 1, 7, 16);
		Shape2a.setRotationPoint(7F, 16F, -8F);
		Shape2a.setTextureSize(128, 128);
		Shape2a.mirror = true;
		this.setRotation(Shape2a, 0F, 0F, 0F);
		Shape3 = new LODModelPart(this, 0, 18);
		Shape3.addBox(0F, 0F, 0F, 14, 7, 1);
		Shape3.setRotationPoint(-7F, 16F, 7F);
		Shape3.setTextureSize(128, 128);
		Shape3.mirror = true;
		this.setRotation(Shape3, 0F, 0F, 0F);
		Shape3a = new LODModelPart(this, 0, 18);
		Shape3a.addBox(0F, 0F, 0F, 14, 7, 1);
		Shape3a.setRotationPoint(-7F, 16F, -8F);
		Shape3a.setTextureSize(128, 128);
		Shape3a.mirror = true;
		this.setRotation(Shape3a, 0F, 0F, 0F);
		Shape5 = new LODModelPart(this, 0, 0);
		Shape5.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape5.setRotationPoint(4F, 17F, 0F);
		Shape5.setTextureSize(128, 128);
		Shape5.mirror = true;
		this.setRotation(Shape5, 0F, 0F, 0F);
		Shape5a = new LODModelPart(this, 0, 0);
		Shape5a.addBox(0F, 0F, 0F, 3, 1, 3);
		Shape5a.setRotationPoint(-7F, 17F, 2F);
		Shape5a.setTextureSize(128, 128);
		Shape5a.mirror = true;
		this.setRotation(Shape5a, -0.1570796F, 0F, 0F);
		Shape5b = new LODModelPart(this, 0, 0);
		Shape5b.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape5b.setRotationPoint(-3F, 17F, -1F);
		Shape5b.setTextureSize(128, 128);
		Shape5b.mirror = true;
		this.setRotation(Shape5b, 0F, 0F, 0F);
		Shape5c = new LODModelPart(this, 0, 0);
		Shape5c.addBox(0F, 0F, 0F, 3, 1, 3);
		Shape5c.setRotationPoint(-1F, 17F, -6F);
		Shape5c.setTextureSize(128, 128);
		Shape5c.mirror = true;
		this.setRotation(Shape5c, 0F, 0.1396263F, 0.1570796F);
		Shape5d = new LODModelPart(this, 0, 0);
		Shape5d.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape5d.setRotationPoint(0F, 17F, 5F);
		Shape5d.setTextureSize(128, 128);
		Shape5d.mirror = true;
		this.setRotation(Shape5d, -0.2617994F, 0F, 0.1745329F);
		Shape5e = new LODModelPart(this, 0, 0);
		Shape5e.addBox(0F, 0F, 0F, 1, 2, 1);
		Shape5e.setRotationPoint(5F, 17F, -4F);
		Shape5e.setTextureSize(128, 128);
		Shape5e.mirror = true;
		this.setRotation(Shape5e, -0.1489348F, -0.4363323F, -0.296706F);
		Shape5f = new LODModelPart(this, 0, 0);
		Shape5f.addBox(0F, 0F, 0F, 2, 2, 2);
		Shape5f.setRotationPoint(4F, 17F, 5F);
		Shape5f.setTextureSize(128, 128);
		Shape5f.mirror = true;
		this.setRotation(Shape5f, 0F, 1.204277F, 0.3141593F);
		Shape5g = new LODModelPart(this, 0, 0);
		Shape5g.addBox(0F, 0F, 0F, 2, 2, 2);
		Shape5g.setRotationPoint(-5F, 17F, -5F);
		Shape5g.setTextureSize(128, 128);
		Shape5g.mirror = true;
		this.setRotation(Shape5g, -0.2268928F, -0.2792527F, -0.1570796F);
		Shape5h = new LODModelPart(this, 0, 0);
		Shape5h.addBox(0F, 0F, 0F, 1, 1, 1);
		Shape5h.setRotationPoint(-7F, 17F, -2F);
		Shape5h.setTextureSize(128, 128);
		Shape5h.mirror = true;
		this.setRotation(Shape5h, 0F, 0F, 0F);
		Shape5i = new LODModelPart(this, 0, 0);
		Shape5i.addBox(0F, 0F, 0F, 2, 1, 2);
		Shape5i.setRotationPoint(-1F, 17F, 0F);
		Shape5i.setTextureSize(128, 128);
		Shape5i.mirror = true;
		this.setRotation(Shape5i, 0F, 0.3141593F, 0F);
		Shape6a = new LODModelPart(this, 0, 4);
		Shape6a.addBox(0F, 0F, 0F, 3, 1, 1);
		Shape6a.setRotationPoint(-4F, 17F, 5F);
		Shape6a.setTextureSize(128, 128);
		Shape6a.mirror = true;
		this.setRotation(Shape6a, 0F, 0.3839724F, 0.1570796F);
		Shape6b = new LODModelPart(this, 0, 4);
		Shape6b.addBox(0F, 0F, 0F, 4, 1, 1);
		Shape6b.setRotationPoint(3F, 17F, -3F);
		Shape6b.setTextureSize(128, 128);
		Shape6b.mirror = true;
		this.setRotation(Shape6b, 0F, 1.169371F, 0.1919862F);
		Shape6c = new LODModelPart(this, 0, 4);
		Shape6c.addBox(0F, 0F, 0F, 9, 1, 1);
		Shape6c.setRotationPoint(-2F, 17.2F, 4F);
		Shape6c.setTextureSize(128, 128);
		Shape6c.mirror = true;
		this.setRotation(Shape6c, 0F, 1.745329F, 0F);
		Shape6d = new LODModelPart(this, 0, 4);
		Shape6d.addBox(0F, 0F, 0F, 7, 1, 1);
		Shape6d.setRotationPoint(-2F, 17F, 1F);
		Shape6d.setTextureSize(128, 128);
		Shape6d.mirror = true;
		this.setRotation(Shape6d, 0F, -0.6108652F, 0F);
		Shape6e = new LODModelPart(this, 0, 4);
		Shape6e.addBox(0F, 0F, 0F, 11, 2, 1);
		Shape6e.setRotationPoint(-5F, 17F, -2F);
		Shape6e.setTextureSize(128, 128);
		Shape6e.mirror = true;
		this.setRotation(Shape6e, 0.122173F, 0F, 0.0349066F);
		Shape7 = new LODModelPart(this, 0, 6);
		Shape7.addBox(0F, 0F, 0F, 3, 1, 4);
		Shape7.setRotationPoint(-4F, 17.5F, -7F);
		Shape7.setTextureSize(128, 128);
		Shape7.mirror = true;
		this.setRotation(Shape7, 0F, -0.2617994F, 0F);
		Shape7a = new LODModelPart(this, 0, 6);
		Shape7a.addBox(0F, 0F, 0F, 3, 1, 4);
		Shape7a.setRotationPoint(-2F, 17.5F, 1F);
		Shape7a.setTextureSize(128, 128);
		Shape7a.mirror = true;
		this.setRotation(Shape7a, 0F, -1.343904F, 0F);
		Shape7b = new LODModelPart(this, 0, 6);
		Shape7b.addBox(0F, 0F, 0F, 3, 1, 4);
		Shape7b.setRotationPoint(0F, 17.5F, 0F);
		Shape7b.setTextureSize(128, 128);
		Shape7b.mirror = true;
		this.setRotation(Shape7b, 0F, 0.4886922F, 0F);
		Shape8 = new LODModelPart(this, 0, 11);
		Shape8.addBox(0F, 0F, 0F, 1, 2, 3);
		Shape8.setRotationPoint(5F, 16.5F, 1F);
		Shape8.setTextureSize(128, 128);
		Shape8.mirror = true;
		this.setRotation(Shape8, -0.0872665F, -0.7853982F, 0.3316126F);
		Shape8a = new LODModelPart(this, 0, 11);
		Shape8a.addBox(0F, 0F, 0F, 1, 2, 3);
		Shape8a.setRotationPoint(1F, 16.5F, -4F);
		Shape8a.setTextureSize(128, 128);
		Shape8a.mirror = true;
		this.setRotation(Shape8a, -0.0349066F, -1.099557F, -0.2792527F);
		Shape8b = new LODModelPart(this, 0, 11);
		Shape8b.addBox(0F, 0F, 0F, 1, 2, 3);
		Shape8b.setRotationPoint(-5F, 16.8F, 6F);
		Shape8b.setTextureSize(128, 128);
		Shape8b.mirror = true;
		this.setRotation(Shape8b, 0F, 1.43117F, 0F);
		Shape8c = new LODModelPart(this, 0, 11);
		Shape8c.addBox(0F, 0F, 0F, 1, 2, 3);
		Shape8c.setRotationPoint(-6F, 16.5F, -2F);
		Shape8c.setTextureSize(128, 128);
		Shape8c.mirror = true;
		this.setRotation(Shape8c, 0F, 0.3490659F, -0.2094395F);
		Shape4 = new LODModelPart(this, 0, 26);
		Shape4.addBox(0F, 0F, 0F, 14, 1, 14);
		Shape4.setRotationPoint(-7F, 18F, -7F);
		Shape4.setTextureSize(128, 128);
		Shape4.mirror = true;
		this.setRotation(Shape4, 0F, 0F, 0F);
	}

	@Override
	public void renderAll(TileEntity te, ArrayList li, float phi, float theta)
	{
		boolean wheat = (Boolean)li.get(0);
		boolean carrots = (Boolean)li.get(1);
		boolean meat = (Boolean)li.get(2);
		boolean fish = (Boolean)li.get(3);
		boolean greens = (Boolean)li.get(4);
		Shape1.render(te, f5);
		Shape2.render(te, f5);
		Shape2a.render(te, f5);
		Shape3.render(te, f5);
		Shape3a.render(te, f5);
		if (carrots) {
			Shape5.render(te, f5);
			Shape5a.render(te, f5);
			Shape5b.render(te, f5);
			Shape5c	.render(te, f5);
			Shape5d.render(te, f5);
			Shape5e.render(te, f5);
			Shape5f.render(te, f5);
			Shape5g.render(te, f5);
			Shape5h.render(te, f5);
			Shape5i.render(te, f5);
		}
		if (greens) {
			Shape6a.render(te, f5);
			Shape6b.render(te, f5);
			Shape6c.render(te, f5);
			Shape6d.render(te, f5);
			Shape6e.render(te, f5);
		}
		if (meat) {
			Shape7.render(te, f5);
			Shape7a.render(te, f5);
			Shape7b.render(te, f5);
		}
		if (fish) {
			Shape8.render(te, f5);
			Shape8a.render(te, f5);
			Shape8b.render(te, f5);
			Shape8c.render(te, f5);
		}
		if (wheat)
			Shape4.render(te, f5);
	}
}